### ISSUE TITLE
$queryRaw doesn't work with single quotes

### ISSUE THREAD

**Issue by bardiaheshmati** [prisma/prisma#10051]
### Discussed in https://github.com/prisma/prisma/discussions/9991

<div type='discussions-op-text'>

<sup>Originally posted by **bardiaheshmati** October 28, 2021</sup>
i have a query that goes 

```sql
select count(id), status,  "createdAt"::date from "ProjectLog" where "projectId" = (select id from "Project" where slug = ${id}) and "createdAt" > current_date - interval '${interval} day' group by "createdAt"::date, status;
```
i've also tried user `Prisma.sql` to pass the value inside the quotes but it keeps throwing error that it expected 1 argument but fount 2.

i did not have this issue with prisma `2.20.1`
this issue is only happening on version `3.3.0`

```shell
Query: select count(id) as count, status,  "createdAt"::date from "ProjectLog" where "projectId" = (select id from "Project" where slug = $1) and "createdAt" >  current_date - interval '$2 day' and key notnull group by "createdAt"::date, status
Param: ["main","30"]
PrismaClientKnownRequestError:
Invalid `prisma.queryRaw()` invocation:


  Your raw query had an incorrect number of parameters. Expected: `1`, actual: `2`.
  code: 'P1016',
  clientVersion: '3.3.0',
  meta: { expected: 1, actual: 2 }
}
```
any suggestions ?
i'm not sure if this is a bug.
</div>

**Comment by janpio** [comment]
Seems discussion is still ongoing: https://github.com/prisma/prisma/discussions/9991#discussioncomment-1577970

**Comment by jschuur** [comment]
@janpio I've got the same problem. A quick way to replicate this is

```
prisma.$queryRaw`SELECT (CURRENT_TIMESTAMP - interval '${7} day')`
```

The SQL that I expected this to generate is 

```
SELECT (CURRENT_TIMESTAMP - interval '7 day')
```

...but it seems to leave in the question mark placeholder:

```
>  Prisma.sql`SELECT (CURRENT_TIMESTAMP - interval '${7} day')`
{
  text: "SELECT (CURRENT_TIMESTAMP - interval '$1 day')",
  sql: "SELECT (CURRENT_TIMESTAMP - interval '? day')",
  values: [ 7 ]
}
```

...and then error out:

```
Uncaught PrismaClientKnownRequestError:
Invalid `prisma.queryRaw()` invocation:

  Your raw query had an incorrect number of parameters. Expected: `0`, actual: `1`.
    at cb (/Users/jschuur/Code/streamers.dev/node_modules/@prisma/client/runtime/index.js:38688:17)
    at async REPL2:1:24 {
  code: 'P1016',
  clientVersion: '3.7.0',
  meta: { expected: 0, actual: 1 }
```

This is in Prisma 3.7.0, and since it's already an issue in `Prisma.sql`, the database may not matter, but I'm using postgresql as the datasource provider.

I 'solved' this by using `$queryRawUnsafe` without tagged template literals. That's OK in my situation, since I'm not dealing with outside user input, but this still seems like a bug.

**Comment by janpio** [comment]
Thanks, with this information we can take a deeper look @jschuur 👍

**Comment by pantharshit00** [comment]
We will automatically convert template tag variable prepared statement variable to prevent SQL injection. Just curious why you would want to use `${7}` instead of directly encoding it if it is not coming from a dynamic source. If it is coming from a dynamic source, you can pass full `7 day` in the string and doing it like that will also prevent injection attacks.

**Comment by jschuur** [comment]
> Just curious why you would want to use `${7}` instead of directly encoding it if it is not coming from a dynamic source.

@pantharshit00 that was a simplified example to quickly reproduce the issue with template variables (possibly within single quotes and in PostgreSQL). My actual code where I ran into the issue is ([full source](https://github.com/jschuur/streamers.dev/blob/main/lib/stats.js#L254)):

```
  const streamsByDay = await prisma.$queryRaw(`
    SELECT
        DATE("startedAt") AS "timeStamp", count(*) AS count
    FROM "Stream"
    WHERE
        DATE("startedAt") > CURRENT_DATE - INTERVAL '${STATS_RECENT_STREAMS_DAYS} day'
    GROUP BY
        DATE("startedAt")
    ORDER BY
        "timeStamp" ASC`);
```

Side note: I'm using a queryRaw here in the first place, because in Prisma, I can't seem to group by the converted date from a DateTime field ([feature request](https://github.com/prisma/prisma/issues/6653)).

**Comment by matthewmueller** [comment]
@jschuur just curious, did you try:


```ts
  const streamsByDay = await prisma.$queryRaw`
    SELECT
        DATE("startedAt") AS "timeStamp", count(*) AS count
    FROM "Stream"
    WHERE
        DATE("startedAt") > CURRENT_DATE - INTERVAL ${STATS_RECENT_STREAMS_DAYS}
    GROUP BY
        DATE("startedAt")
    ORDER BY
        "timeStamp" ASC`;
```

? 

In general, there's lots of restrictions for what can be prepared and what can't. This is mostly likely a restriction from the database. I wrote some more details in [this comment](https://github.com/prisma/prisma/issues/12456#issuecomment-1097033496)

**Comment by Weakky** [comment]
Hey folks,

@jschuur I can confirm this is a SQL prepared statement limitation. Your query parameter is interpreted as a text because it is inside single quotes. I see two ways_ you could make this work (without using `$queryRawUnsafe`):

1. Either with the solution suggested above. Pass `${"7 day"}` as query parameter
2. Use concatenation operators if you really wish to make `"day"` static. eg 👇
   ```ts
   await prisma.$queryRaw`SELECT CURRENT_TIMESTAMP - (${7} || ' day')::INTERVAL`
   ```

With that, I'm gonna close the issue as there's nothing we can do about it.

Thanks for reporting! 🙏
