### ISSUE TITLE
Postgres - 63 chars limit for index name

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma#10094]
### Discussed in https://github.com/prisma/prisma/discussions/10089

<div type='discussions-op-text'>

<sup>Originally posted by **proutek** November  3, 2021</sup>
Hello,

I'm using prisma 3.3.0.

Is there a way to specify name of underlying index in implicit many to many relation. In postgres the index name is cut (63 chars max) but prisma tries to alter name  back to _unique when running migrate dev which leads to error. I know that I can use shorter name for table name but it will complicate migration for us.

![image](https://user-images.githubusercontent.com/21219132/140154604-485e202f-8048-4b6d-9f50-5647c56eb594.png)

</div>

**Comment by janpio** [comment]
More information: https://github.com/prisma/prisma/discussions/10089#discussioncomment-1584876

**Comment by proutek** [comment]
Migration is trying to alter index name from

_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_uniq 
to
_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_unique 

but it fails stating that _BlankArticleVariantToBlankArticleVariantAttributeValue_AB_uniq already exists. 

Probably because postgres cuts name by 2 chars in this case and the name already exists.

![image](https://user-images.githubusercontent.com/21219132/140993994-18aa55b9-af8b-4baa-a315-4de08572e450.png)
