### ISSUE TITLE
Decide on the default referential actions in a single place

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#10213]
Right now we define referential actions two times if they're not explicitly defined in the data model, first here:

https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/core/src/transform/ast_to_dml/db/walkers/relation.rs#L360-L395

Then we do not use these functions in the validations:

[thttps://github.com/prisma/prisma-engine](https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/core/src/transform/ast_to_dml/lift.rs#L70-L71)

And, again, in the dml part we have another set of defaults:

https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/connectors/dml/src/field.rs#L398-L416

Now if any of these change without the other, there might be quite interesting bugs happening in the future. The correct thing would be to just not use `Option<ReferentialAction>` in the dml. All the engines need some action defined, so it doesn't really need to be optional.

There are some caveats for this. First is how we use dml to render the datamodel string back to the file. We should somehow mark in the data structures so we know to not render a value. This decision needs a lot of data, so at least we could write the default values to the dml and just not render them. The second one is how dml structs hold a `RelationInfo` on both sides of the relation, and it is not the same structure. Should we have the actions in the back relation side too and if so should they be the same in there too? In the case of many to many relations, we don't really define any referential actions, should we just have `NoAction` in these?

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
