### ISSUE TITLE
Unable to use Prisma in new Next JS middleware

### ISSUE THREAD

**Issue by dbismut** [prisma/prisma#10251]
### Bug description

I'm trying to use prisma in the new [Next JS middleware feature](https://nextjs.org/docs/middleware). Unfortunately, it seems like it's importing `PrismaClient` from `index-browser.ts`

### How to reproduce

Here's how the middleware would look like:

```ts
import { NextRequest, NextResponse } from 'next/server'
import prisma from 'server/db/prisma'

export async function middleware(req: NextRequest) {
  const API_KEY = req.nextUrl.searchParams.get('API_KEY')
  if (!API_KEY) return new Response('API_KEY param missing', { status: 401 })

  const referer = req.headers.get('referer')!
  const user = await prisma.user.findUnique({ where: { apiKey: API_KEY } })
  if(!user)  return new Response('API_KEY invalid', { status: 401 })

  return NextResponse.next()
}
```

Unfortunately I'm getting the following error:

```
Error: PrismaClient is unable to be run in the browser.
```

I understand the error, although here I'm using `prisma` inside the middleware, which to my understanding is running in the server, so I'm not sure what the error is.

### Expected behavior

I would expect `PrismaClient` to run in Next JS middleware.

### Prisma information

Not relevant for that use case I think.

### Environment & setup

- OS: Mac OS 12
- Database: PostgreSQL
- Node.js version: 14.8.1

### Prisma Version

```
prisma                  : 3.4.2
@prisma/client          : 3.4.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by pantharshit00** [comment]
Hello,

Since next.js middleware is in preview, looks like there is a bug where next is trying to resolve the browser version of the module for the middleware. In order to fix this, add the following to your webpack config:

```ts
module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.resolve.alias['@prisma/client$'] = require.resolve('@prisma/client')
    return config
  },
}
```

This will force next's build system to resolve the actual client instead of the dummy browser typings that we ship.


Also, please note that you can only use Prisma in NextJS middlewares via DataProxy(https://www.prisma.io/docs/concepts/components/prisma-data-platform#prisma-data-proxy). Next JS middlewares doesn't support the whole Node JS runtime so it is impossible to open actual stateful database connections from them. You can read about their runtime here: https://nextjs.org/docs/api-reference/edge-runtime. Basically they support all the API supported by cloudflare workers. So in order to use Prisma here, you will need to use the dataproxy which can manage database connections for you remotely. This talk on this subject from Vercel conf might help you here: https://youtu.be/gJoa5VRF0jY?t=1535

**Comment by dbismut** [comment]
Crystal clear, thanks a lot for your help!
