### ISSUE TITLE
Validating index length prefixes

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#10288]
MySQL holds special rules about the size of the length prefix. These rules are different on text and bytes columns, and we should maybe catch them in datamodel validation before erroring out in the database.

This should follow up the work on redefining native type and connector specific validations.

Related bug reports:
- https://github.com/prisma/prisma/issues/10405
- https://github.com/prisma/prisma/issues/12693

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
