### ISSUE TITLE
Data Proxy Client stopped working in Vercel Edge Functions / Next 12.0.4

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#10305]
New problem with Vercel Edge and the Data Proxy Client on next 12.0.4 and up

```
    A server error has occurred
    
    EDGE_FUNCTION_INVOCATION_FAILED
```

- They now disable the usage of `eval` by doing an analysis of its usage
- They say that they tree-shake this out instead, whenever it's possible
	- If not, they just error - they don't care for runtime logic.
- We need this to have a a single build that works on Workers & Node.js
- We `eval('require...')` Node.js deps to hide them away from bundlers
	- eg. `fetch` is used on Workers, but eval('require("http")') in Node

https://prisma-company.slack.com/archives/C016KUHB1R6/p1637100669072700

We need:
- To have a pass on the evals that are bundled
- Have a new import like `@prisma/client/edge`
- That would add another runtime build

**Comment by Jolg42** [comment]
Note that next version is currently `"next": "12.0.10"`
https://github.com/prisma/e2e-tests/blob/dev/workers/vercel-edge-functions/package.json#L12

And tests are passing.

See merged Renovate PRs
https://github.com/prisma/e2e-tests/pull/2366
https://github.com/prisma/e2e-tests/pull/2375
https://github.com/prisma/e2e-tests/pull/2380

The last failing one was `12.0.5`
https://github.com/prisma/e2e-tests/pull/2357

So it works with a version between `12.0.5` and `12.0.9` or since `12.0.9` (unsure since renovate only tried to update .9, might be that it was working with a version in between)

**Comment by Jolg42** [comment]
Using recent versions of Next with Vercel Edge Functions fails with 
```
./node_modules/@prisma/client/runtime/proxy.js

Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware
```
The last working version is 12.0.10 from Feb 01, 2022
https://github.com/prisma/ecosystem-tests/pull/2612#issuecomment-1097623916

**Comment by millsp** [comment]
Note for users finding this:

We have released some changes a few minutes ago in [prisma@3.15.0](https://github.com/prisma/prisma/releases). tl;dr;
* Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
* `import { PrismaClient } from '@prisma/client/edge'` for a Vercel Edge Function compatible Prisma Client
* Please be aware that `.env` aren't bundled into the generated Prisma Client any longer ([see docs](https://www.prisma.io/docs/concepts/data-platform/data-proxy#edge-runtimes))
* You can also remove any package location aliasing from your build scripts
* Warnings around `eval` are now also fixed
