### ISSUE TITLE
Support fulltext indexes on SQL Server

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#10387]
Do we need a syntax for `catalog`?

**Comment by janpio** [comment]
Seems there is no demand.

**Comment by cahilfoley** [comment]
I would absolutely love to have this feature added for SQL Server support - I'm not sure where we are supposed to express our desire for feature support like this to be extended to MSSQL, otherwise I would have done so.

I work across multiple project teams that would benefit greatly from this, would greatly reduce the number of raw queries and workaround for the database schema we have to maintain.
