### ISSUE TITLE
Validate the native types of scalar fields in `@relation`'s `fields` and `references` arguments

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10390]
We used to validate this naively by equality comparison until https://github.com/prisma/prisma-engines/pull/2433

The validation was removed for two main reasons:

- It was underspecified and not tested
- It had known false positives: https://github.com/prisma/prisma/issues/5289

Most of the time, slight differences in the types should be ok. To be correct, we need a more subtle approach.

When we reintroduce this validation, we should do so by researching on each connector which combinations are valid, and reflecting that as faithfully as possible in the validation. This will probably end up being a lot of code and a lot of work, so we could try addressing this case by case, validating for mismatches that actually happen to users.

## Examples

Without prior research:

- A `String @db.VARCHAR(200)` referencing a `String @db.VARCHAR(100)` on MySQL should be fine
- A `String @db.Text` referencing a `String @db.Uuid` on postgres is probably an error

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
