### ISSUE TITLE
Improve the error when SQLite database file is locked

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#10403]
We had a test that attempted concurrent writes to SQLite. Since quaint [maps SQLite’s `DatabaseBusy` error to  `SocketTimeout`](https://github.com/prisma/quaint/blob/05eb0acc841eeb88569d1538c35b66b5e4f83266/src/connector/sqlite/error.rs#L142-L157), and there’s no case for the `(ErrorKind::SocketTimeout, ConnectionInfo::Sqlite { .. })` pair in `user_facing_errors::quaint::render_quaint_error`, the error looked like this:

```
      Error occurred during query execution:
    ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })

      161 |         throw new PrismaClientRustPanicError(message, this.client._clientVersion)
      162 |       } else if (e instanceof PrismaClientUnknownRequestError) {
    > 163 |         throw new PrismaClientUnknownRequestError(message, this.client._clientVersion)
          |               ^
```

It would be nice to have some user-facing error with the correct message here (e.g., “The database file is locked”).

---

The updated source code link is: https://github.com/prisma/prisma-engines/blob/b567896ae76a9c991a5aca05b09b97c7628357cd/quaint/src/connector/sqlite/error.rs#L87-L96.

**Comment by devuxer** [comment]
I upgraded from v3 to v4 but started encountering this error constantly, even on localhost,, so I downgraded right back to v3, and the errors stopped.

Not a very satisfying solution, but [these issues](https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+Timed+out+during+query+execution%22),, have been around for months and hardly anyone seems bothered, so I doubt they'll be fixed anytime soon.

Probably time to just ditch SQLite. I chose it because it's more than capable of handling the small load of my web app, but it's an uphill battle using something that hardly anyone else is using (particularly in production). I guess SQLite's sweet spot is phone apps, not web apps.

**Comment by mweel1** [comment]
@devuxer I know but for prototyping it's nice not have to spin up a database.

**Comment by robert-king** [comment]
when my application starts up, two of my services onModuleInit methods write to the database (transactions, different tables). I get an error almost everytime. very strange. I would expect one write could wait for the other. Do I need to recompile my sqlite to support concurrency / thred-safety, or is this some limitation with prisma and sqlite? hope prisma can document a solution for this soon :)

**Comment by samspycher** [comment]
Two inputs on this:

- **Mitigation**: enabling WAL mode will probably alleviate this issue for most people. You can do this as a one-off or on startup with a [script](https://github.com/simonw/til/blob/main/sqlite/enabling-wal-mode.md) prior to starting the app, with a [raw query](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access), or you can implement the [feature](https://github.com/WillBooster/shared/issues/116)
- **Resolution**: Totally not an expert, but besides throwing a clearer error (enable WAL if not enabled) it may make sense to take advantage of the [callback](http://www.sqlite.org/c3ref/busy_handler.html) and the [busy timeout](http://www.sqlite.org/c3ref/busy_timeout.html) for tuning the handling at some level between prisma and the DB, since theres seems to be no backoff/retry at all.

**Comment by devuxer** [comment]
> Two inputs on this:
> 
> * **Mitigation**: enabling WAL mode will probably alleviate this issue for most people. You can do this as a one-off or on startup with a [script](https://github.com/simonw/til/blob/main/sqlite/enabling-wal-mode.md) prior to starting the app, with a [raw query](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access), or you can implement the [feature](https://github.com/WillBooster/shared/issues/116)
> * **Resolution**: Totally not an expert, but besides throwing a clearer error (enable WAL if not enabled) it may make sense to take advantage of the [callback](http://www.sqlite.org/c3ref/busy_handler.html) and the [busy timeout](http://www.sqlite.org/c3ref/busy_timeout.html) for tuning the handling at some level between prisma and the DB, since there seems to be no backoff/retry at all.

@samspycher, Thank you! Just tried this out, and so far, it's working for me!

The only question I have is, why do I only need to do this starting with Prisma 4???

Quick guide for anyone else wanting to try this:

- SQLite has a property called `journal_mode` that determines how transactions are handled (see [Pragma statements support by SQLite](https://www.sqlite.org/pragma.html#pragma_journal_mode)).
- `journal_mode` can be one of these values: `DELETE` (the default), `TRUNCATE`, `PERSIST`, `MEMORY`, `WAL`, `OFF`.
- WAL stands for "Write Ahead  Log" and works differently than the usual method (rollback journal).
- Details and pros and cons of WAL mode can be found [here](https://www.sqlite.org/wal.html).
- To set the `journal_mode` to `WAL` for all databases within a SQLite file, execute this SQL in a script or query runner: `PRAGMA journal_mode=WAL;`.
- IMPORTANT: the `WAL` journaling mode is persistent; after being set it stays in effect across multiple database connections and after closing and reopening the database.

**Comment by reustle** [comment]
Thank you @devuxer ! I outlined a way to do this within a migration here https://github.com/prisma/prisma/issues/3303#issuecomment-2140917491
