### ISSUE TITLE
Implement Mysql Fulltext Querying Capabilities

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#10415]
With schema level support almost done (see https://github.com/prisma/prisma/issues/9412), we can start working on implementing Client API support. 

## Suggested solution

It should have the [same Full-Text Search API](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search).

**Comment by Jolg42** [comment]
Reopening, adding a test like the one we did for PostgreSQL here in prisma/prisma would be great https://github.com/prisma/prisma/tree/main/packages/client/src/__tests__/integration/happy/full-text-search

**Comment by garrensmith** [comment]
Using full text search with mysql would go something like this. Create a model and add a full text index for the fields that you would like to search:

```prisma

model Blog {
  id Int @unique
  content String
  title String
  @@fulltext([content])
  @@fulltext([content, title])  
}

```

Adding the index `@@fulltext([content])` that means that we can now do a search on the content field:

```
const result = await prisma.blogs.findMany({
  where: {
    content: {
      search: 'cat',
    },
  },
})
```

And with the `@@fulltext([content, title])` means we can do searches like this:

```
const result = await prisma.blogs.findMany({
  where: {
    content: {
      search: 'cat',
    },
    title: {
      search: 'food'
    }
  },
})
```

However if we try and do a search on title alone, this will fail with an error:

```
const result = await prisma.blogs.findMany({
  where: {
    title: {
      search: 'cat',
    },
  },
})

```
Because no index has been defined for it. The error will say `Cannot find a fulltext index to use for the search` and the message code is `P2030`.

Internally, we are using the [`Boolean text searches`](https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html) from MySql. This means that we can use the `+` and `-` query operators. So by default if we have two words we are searching `search: "cat dog"` that would be treated as an `OR` operation. But we could also do `"cat -dog"` which means find all text which contains cat and not dog.

**Comment by janpio** [comment]
We have tests now, and docs are being created 👍
