### ISSUE TITLE
Crash on unhandled permission error for schema.prisma in migration engine

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10553]
Command: `prisma migrate dev first init`
Version: `3.5.0`
Binary Version: `78a5df6def6943431f4c022e1428dbc3e833cf8e`
Report: https://prisma-errors.netlify.app/report/13592 
OS: `x64 win32 10.0.19043`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\cli\src/main.rs:80:60] error opening datamodel file: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (<...>\node_modules\prisma\build\index.js:100836:25)
    at ChildProcess.<anonymous> (C:\Users\21655\Desktop\REACT\Web\server\node_modules\prisma\build\index.js:100845:15)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[migration-engine\cli\src/main.rs:80:60] error opening datamodel file: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
