### ISSUE TITLE
[PSL] Validate length of model and field names

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#10685]
Databases specify a maximum length for identifiers. If this is exceeded, errors are produced or they get silently truncated (Postgres). 

For index and constraint names we already validate these, but not for model and fieldnames. 

Note: we would need an upgrade path for Postgres since just adding a validation would make a datamodel that previously migrated (even though it then truncated)  invalid upon parsing.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
