### ISSUE TITLE
How to import ESM version of @prisma/client/runtime?

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#10775]
I see that my app is bundling `@prisma/client/runtime/index.js`. I also see that there is an `esm` directory there with an ESM version of index.mjs. I would like to use the ESM version, but I'm unclear on how to do this.

The `package.json` contains: 
```
  "main": "index.js",
```
But it has no exports section, so I'm not sure how normal module bundling could know that the esm version exists. Should @prisma/client/runtime's package.json contain an [exports section as recommended](https://nodejs.org/api/packages.html#dual-commonjses-module-packages) in the node docs?

E.g.
```
{
  "main": "./index.js",
  "exports": {
    "import": "./esm/index.mjs",
    "require": "./index.js"
  }
}
```

_Originally posted by @revmischa in https://github.com/prisma/prisma/issues/10724#issuecomment-997374000_

**Comment by millsp** [comment]
Hey @revmischa, this was solely used for the purposed of doing tree-shaking internally and was never intended to be imported or used externally. I was invalid ESM, because it still included things like `__dirname`, or `eval('require')`. We now do tree-shaking differently across the monorepo thanks to typescript paths, so this has been removed.
