### ISSUE TITLE
When using `@ignore` for some fields, there is no `create` method in the model

### ISSUE THREAD

**Issue by rostamiani** [prisma/prisma#11283]
### Bug description

When using `@ignore` for some fields, there is no `create` method in the model. I'm ignoring just two fields but the rest should be available.

### How to reproduce

Define this model:
```prisma
model User {
  id        Int       @id @default(autoincrement())
  email     String    @unique
  password  String
  createdAt DateTime  @default(now()) @ignore
  updatedAt DateTime  @updatedAt @ignore
  remarks   String?
}
```
Then generate it. Then you cannot create a user using this code:
```ts
await this.prismaService.user.create({ data: newUser });
```
Because of this error:
```bash
Property 'create' does not exist on type 'UserDelegate<RejectOnNotFound | RejectPerOperation | undefined>'.ts(2339)
```

### Expected behavior

The `create` method should be there!

### Environment & setup

- OS: Ubuntu 21.10
- Database: PostgreSQL
- Node.js version: 16.13.1

### Prisma Version

```
3.8.1
```

**Comment by matthewmueller** [comment]
That's odd. If you remove the @ignore and re-generate does create show up?

**Comment by rostamiani** [comment]
@matthewmueller 
Yes

**Comment by maple5233** [comment]
same issues, too

**Comment by janpio** [comment]
I can reproduce:

```prisma
model Foo {
  id  Int    @id @default(autoincrement())
  foo String
  bar String?
}
```

```ts
    await prisma.foo.create({
        data: {
            foo: "lala",
        }
    });
```

Works fine. 

As soon as I add `@ignore` on `foo` the `create` is underlined red.
(Note that I needed to reload the TS server after `generate` to make this visible)

**Comment by AndrewSouthpaw** [comment]
This is a pretty serious problem, as it prevents people from removing columns safely by ignoring them first in the client. See related discussion [here](https://github.com/prisma/prisma/discussions/13922#discussioncomment-3451893).

Without something like `@ignore` for fields, there's currently no way AFAICT to delete columns without causing some downtime.

**Comment by janpio** [comment]
Please open a feature request for what you need if there is none for it yet, otherwise link to it. This is really just a bug issue about unexpected behavior when using `@ignore` how it was currently designed.

**Comment by AndrewSouthpaw** [comment]
Maybe I'm not understanding how `@ignore` was designed to be used. `@ignore` would in theory achieve this desired outcome [according to the docs](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#remarks-16), so it doesn't feel like a feature is missing?

It seems like the bug goes away when the field is marked optional, FWIW.

```
// no `create`
model Test {
  id  Int    @id @default(autoincrement())
  foo String @ignore
}

// has `create`
model Test {
  id  Int    @id @default(autoincrement())
  foo String? @ignore
}
```

**Comment by janpio** [comment]
That then explain what is happening: Without providing a value to a non optional field, a modle can not be created in the database - hence a required field being marked with `@ignore` removes the `create` method in the Client API.

We probably should confirm this internally, and if true and intentional, add this to the documentation.

@AndrewSouthpaw That we have this discussion in a bug issue (that is potentially just a misunderstanding, not a real bug - or missing documentation) shows that this is not the right place to get the behavior you want or need. If it turns out that the feature indeed does already do what you want, we can still close the feature request. (And if not, figure out why it is like that or if it can be adapted etc)

**Comment by AndrewSouthpaw** [comment]
Yeah, once I realized making it optional fixed the issue, it was a "ok, I guess that makes sense" moment, I can see how it wouldn't work with the Prisma machinery. I think it's reasonable to assume `String @ignore` would've worked fine as well, so a note in the docs would definitely fix the issue.

I opened a PR with some propose changes, to try to make things easier for you all. 😄 

I've tested it out locally, and using `@ignore` on an optional field does give us what we need for zero-downtime migrations to delete a column. In the same way that Rails has `self.ignored_columns`, and you need to set that before deleting the column to avoid downtime, Prisma would achieve this with `@ignore`.

Orthogonal but related to this issue, I think it'd make sense to create a little guide on safely deleting columns, since it's an easy mistake to make. What do you think about me contributing a new section next to [here](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations#renaming-a-field), maybe something like "Deleting columns" perhaps?

**Comment by maxh** [comment]
FYI there is now a rule `forbid-required-ignored-field` in prisma-lint to prevent confusion here:

https://github.com/loop-payments/prisma-lint/blob/main/src/rules/forbid-required-ignored-field.ts
