### ISSUE TITLE
Output information when migration creates a remove/add because of a probably renamed field

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11296]
We could detect with quite high probability when a field got renamed (= everything about the column is the same besides the name, model, position in columns, type, attributes, usage in relation etc) and then output an information in the CLI that we by drop remove and add columns, but that they can edit the SQL to change that.

We could also already generate the required SQL and output it in the migration file as commented statement to just replace the existing one.

Related: https://github.com/prisma/prisma/issues/7790

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
