### ISSUE TITLE
Query Engine logs different Prisma Client query than I actually executed

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11329]
![image](https://user-images.githubusercontent.com/183673/150696149-e1f7cfe0-5dd9-43af-a3a4-fc778b191dc9.png)

See the difference in `val` here which is the same time, but in my code with the timezone and in the log as UTC. This is unexpected.

**Comment by janpio** [comment]
I know about that limitation - just logging incorrect information is not the solution to that though. If we do not actually know the real value, we should make that clear. Logging showing incorrect information is one of the worst things it can do (besides not logging at all).

**Comment by SevInf** [comment]
I don't agree that we show incorrect value here. You are not passing date string with a timezone as an input,  you are passing the date object, and value of that object is a UTC date. How exactly you got this object should not be relevant to the logging. Instead of `new Date(string)` call it could've been `Date.now()`, `new Date(2022, 01, 10)` or anything more complicated. In that sense, I don't see a difference between, what happens here, and for example, logging `{ id: Number('1.000000000') }` as `{ id: 1 }`. From the point of the typesystem these values are absolutely the same and there is no property or method on `new Date('2022-01-01T11:00Z')` and `new Date('2022-01-01T12:00:00.000+01:00')` that would indicate otherwise

**Comment by janpio** [comment]
I do a Prisma Client Call.
Prisma Client logs a "Prisma Client call" that is different than my actual call.
🤷 

(If it is technically impossible to do anything different, it still does not make it expected or correct)

**Comment by SevInf** [comment]
My point is not so much about technically being impossible, I think we disagree about what exactly you passing as an input here.  
You are passing a UTC date, which you explicitly created from a date string before. You can also pass it `2022-01-01T12:00:00.000+01:00` string directly, in that case we would log it as is (that still won't store correct timzeone in DB, but that's another discussion)

As for different then the actual call point: no part of this message comes from a source code, arguments are reconstructed from their runtime values. So every value we print here is our best guess, not necessarily the exact thing user has written in their source file.

**Comment by janpio** [comment]
> So every value we print here is our best guess, not necessarily the exact thing user has written in their source file.

That was exactly my expectation though from how it is presented.
