### ISSUE TITLE
Weird bug reproducing only in VSCode debug mode

### ISSUE THREAD

**Issue by kakserpom** [prisma/prisma#11409]
### Bug description

```
await prisma.account.findMany({
  where: {
      owner_type: 'user',
      owner_id: 5n,
      cash: false
  },
  include: {
      currency: true
  }
})
```

> Error: 
> Invalid prisma.account.findMany() invocation:
> 
>   Failed to validate the query: Field does not exist on enclosing type. at Query.findManyaccount.account.currency.currency.round_quantity
>     at Object.request (/Users/denis/Documents/projects/*/tg-bot/node_modules/@prisma/client/runtime/index.js:39053:15)
>     at async test (file:///Users/denis/Documents/projects/*/tg-bot/bin/prisma-test.js:13:21) {code: 'P2009', clientVersion: '3.8.1', meta: {…}, stack: 'Error: 
> Invalid prisma.account.findMany() i…jects/*/tg-bot/bin/prisma-test.js:13:21)', message: '
> Invalid prisma.account.findMany() invocat…nt.account.currency.currency.round_quantity`'}
> clientVersion: '3.8.1'
> code: 'P2009'
> meta: {query_validation_error: 'Field does not exist on enclosing type.', query_position: 'Query.findManyaccount.account.currency.currency.round_quantity'}

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
```

**Comment by janpio** [comment]
Check these probably related issues: https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%22Field+does+not+exist+on+enclosing+type%22

**Comment by felix-h** [comment]
I was getting a similar error when using the VSCode debugger. My error description was 'InvalidArg', but the 'meta' property was undefined.
I am using "nvm" to manage node version and it turned out that launching with the debug config would not use the right node version. After adding 
**"runtimeVersion": "16.13.0"**
to the launch config, prisma client is working. So maybe check if this does the trick for you as well.

From my side, the suggestion here is just to log a more descriptive error message when running with an unsupported node version.
