### ISSUE TITLE
New binary equivalent for `uuid()`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11414]
## Problem

It is quite common to store UUID values in binary columns, because ["storing the human-readable characters uses over double the storage space, and means bigger indices and slower lookup."](https://stackoverflow.com/a/54759433) Currently Prisma only supports a [`uuid()` function to be used in `@default(uuid())`](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#uuid) that needs to be stored in a `String` column.

## Suggested solution

Implement an equivalent function that generates binary UUIDs, or a function to convert between binary and string representation.

## Alternatives

Use `@default(dbgenerated()))` and let the database handle everything, at the cost of bugs like https://github.com/prisma/prisma/issues/7010 and the workaround needed to make database side generated primary key values work anyway (mostly a problem in MySQL).

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
