### ISSUE TITLE
DATABASE_URL is baked in Dataproxy client proxy.js 

### ISSUE THREAD

**Issue by pfried** [prisma/prisma#11458]
### Bug description

When using `previewFeatures = ["dataProxy"]` the connection string is baked into the client when running `prisma generate`.

There is no way to either set it via environment variable nor passing it to the client on instantiation.

### How to reproduce

Checkout example from my [Example Code based on the Prisma Starter](https://github.com/Nantis-GmbH/prisma-proyx-database-url-bug) and run `yarn install`

1. Set environment variable to some invalid connection string: `DATABASE_URL=INVALID`
1. Run `yarn run generate`
2. Change either env variable to valid string or pass valid url to Constructor in script.ts
2. Run `yarn run dev`

Will fail with [P5002](https://www.prisma.io/docs/concepts/components/prisma-data-platform#p5002) 

Happy path is above setting env to valid path before client generation.

### Expected behavior

Can be passed in like

```
const prisma = new PrismaClient({
  log: ["query", "error"],
  datasources: {
    db: {
      url: "prisma://aws-eu-central-1.prisma-data.com/?api_key=ABC"
    }
  }
})
```

or in `.env` file with 

```
DATABASE_URL=prisma://aws-eu-central-1.prisma-data.com/api_key=ABC
```

### Prisma information

prisma 3.7.0 or ^3.8.1

### Environment & setup

- OS: Windows
- Database: Postgres via Dataproxy
- Node.js version: 16.10.0

### Prisma Version

```
prisma 3.7.0 or ^3.8.1
```

(tested with those versions)

**Comment by pfried** [comment]
Related to https://github.com/prisma/prisma/issues/10187

Obviously if the related issue had more context I could have found about that earlier

**Comment by millsp** [comment]
Hey @pfried. We have released some changes a few minutes ago in [prisma@3.15.0](https://github.com/prisma/prisma/releases). tl;dr;
* Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
* `import { PrismaClient } from '@prisma/client/edge'` for a Workers-compatible Prisma Client
* Please be aware that `.env` aren't bundled into the generated Prisma Client any longer ([see docs](https://www.prisma.io/docs/concepts/data-platform/data-proxy#edge-runtimes))
* You can also remove any package location aliasing from your build scripts
* Warnings around `eval` are now also fixed

Thanks, and your feedback is welcome.
