### ISSUE TITLE
Significant performance issues using linux-musl binary target

### ISSUE THREAD

**Issue by ivanstanev** [prisma/prisma#11462]
Hey!

We have been using Prisma in a Node.js API service running on Ubuntu and using the `debian-openssl-1.1.x` binary target. We recently switched to Alpine and changed to the `linux-musl` target. As soon as we deployed this we saw a significant increase in our overall p99 latency and in the CPU usage. The spikes in the p99 latency are also much worse now.

| | |
| -- | -- |
| <img width="1731" alt="Screenshot 2022-01-26 at 18 28 04" src="https://user-images.githubusercontent.com/16717473/151543086-b6beb010-b677-4b1c-9033-cdca22f73b12.png"> | <img width="1734" alt="Screenshot 2022-01-26 at 18 28 53" src="https://user-images.githubusercontent.com/16717473/151543104-05d93dba-ae53-477d-93ba-b696d5b11c8c.png"> |

Any ideas what could attribute to this performance degradation? We're running the following:
prisma: 3.8.1
@prisma/client: 3.8.1
Query Engine (Node-API): libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f

**Comment by pantharshit00** [comment]
Can you please tell me how much load(ie req/sec) is hitting those servers? Then we can try to reproduce these results ourselves. 

Also, make sure you are using same NodeJS version between the images.

**Comment by ivanstanev** [comment]
Hey @pantharshit00 we used Node 16 in both images
Our request rate is ~50 requests / second and we have 8 Pods serving the traffic

**Comment by millsp** [comment]
Hey @ivanstanev could you please try again with the latest version? Thanks.

**Comment by jkomyno** [comment]
Hey @ivanstanev, thanks for your answer, I also believe we can close this issue right now.
For what is worth, the `musl` standard library for C is notably slower than `glibc`, which you'd find installed in most other Linux distros. If performance is more of a priority for you than total disk size, I'd recommend sticking with a `debian` or `rhel`-like distro rather than Linux Alpine (which ships with `musl`). Cheers!
