### ISSUE TITLE
Preview feature feedback: `migrate diff` & `db execute`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#11514]
Please share your feedback about the new Preview `migrate diff` & `db execute` commands released in [v3.9.0](https://github.com/prisma/prisma/releases/tag/3.9.0) in this issue.

- If you encounter a bug, please open a bug report in this repo.
- If the feature is working well for you, please share this in a comment below or leave a :+1: on this issue.

If you have any questions, don't hesitate to ask them in the [#product-feedback](https://app.slack.com/client/T0MQBS8JG/C01739JGFCM/thread/C01739JGFCM-1631633975.005200) channel in the [Prisma Slack](https://slack.prisma.io/).

**Comment by KATT** [comment]
I guess this potentially closes #9707 😺

**Comment by livthomas** [comment]
Is it possible to execute multiple SQL files by a single `prisma db execute` command? None of the following methods work:
```bash
prisma db execute --preview-feature --schema ./prisma/schema.prisma --file ./prisma/views/*.sql
prisma db execute --preview-feature --schema ./prisma/schema.prisma --file "./prisma/views/view1.sql:./prisma/views/view2.sql"
prisma db execute --preview-feature --schema ./prisma/schema.prisma --file ./prisma/views/view1.sql --file ./prisma/views/view2.sql
```

**Comment by Jolg42** [comment]
@livthomas No only one file can be provided here to `--file` at the moment. So you would need to call `db execute` for each file.

What's are you trying to do here?, I'm curious to understand your need/workflow/context, so we can take this feedback in for a potential improvement.

Also, if you provide multiple files, what are your expectations? (Do you expect files to run in a specific order?, for example)

**Comment by livthomas** [comment]
@Jolg42 What I'm trying to do is to create database views in a seed command since Prisma doesn't support views at the moment (see #678).

I previously used `prisma.$executeRaw` which required me to have all the queries inside a TS file. With this new `db execute` command, I can have the views defined in separate SQL files which is much better.

The only thing that could be improved is an ability to execute all of them in a single command. I guess it would even be faster because of the overhead around connecting to a database, etc.

**Comment by livthomas** [comment]
@Jolg42 And to answer your last question: If it was possible to execute multiple SQL files in a single `db execute` command, I would definitely expect them to be executed in the specified order. Although the order is not really important in this particular use case (when creating views).

**Comment by Jolg42** [comment]
Thanks! This is great feedback, I'll share that with the team.

**Comment by blevine** [comment]
In the "Moving forwards and applying missing changes" section you say:

> You need to either alter or delete the offending rows.

Does this imply that you then issue manual commands to alter or delete the offending rows before proceeding to prisma migrate diff step?  I would never do this on a production database.

What if you realized ahead of time that this conflict would exist and you want to address it preemptively as part of the migration.  In other db migration tools, I would add code/script to to fix up the data prior to applying the new constraint.  How would this be supported in Prisma?

**Comment by tomhoule** [comment]
Hi @blevine  — since the migrations from migrate are arbitrary SQL, you can totally do that preemptively in the migration. The best practice is usually to keep schema and data migrations separated, but if it's more convenient, nothing prevents altering / sanity-checking the data from inside your schema migrations.

**Comment by SheaBelsky** [comment]
This is an awesome feature, especially for teams using Prisma as part of a CI/CD pipeline. 

My team's use case is deploying to a PostgreSQL database within an Azure environment. When we want to run migrations against the database, it's something I normally have to do manually from my computer. I would love to make migrations part of our deploy process, however I want to have our database get all database changes _in addition to_ migration history. I know I could just execute the SQL file against the database, but again I lose out on changing internal Prisma tables to know what migrations have been applied (and what their statuses are).

It would be great for this command (or another one) to generate an SQL file which would also include any updates to tables used to track migrations - That way the SQL file could be executed as part of a CI/CD process with different security provisions (virtual networks, authentication). Right now I'm not able to simultaneously authenticate with Azure _and_ run the migration in an automated environment - I can only do one or the other.

**Comment by floelhoeffel** [comment]
Hey Shea - thanks for the detailed feedback! I have some follow up questions to fully understand your need if you don't mind 😊

> My team's use case is deploying to a PostgreSQL database within an Azure environment. When we want to run migrations against the database, it's something I normally have to do manually from my computer.

Could you elaborate why you can't apply migrations in CI/CD. Did you consider using `migrate deploy` in CI?

> I would love to make migrations part of our deploy process, however I want to have our database get all database changes _in addition to_ migration history. I know I could just execute the SQL file against the database, but again I lose out on changing internal Prisma tables to know what migrations have been applied (and what their statuses are).
> It would be great for this command (or another one) to generate an SQL file which would also include any updates to tables used to track migrations - That way the SQL file could be executed as part of a CI/CD process with different security provisions (virtual networks, authentication). Right now I'm not able to simultaneously authenticate with Azure _and_ run the migration in an automated environment - I can only do one or the other.

Are you asking for a way to use the output from `migrate diff` as part of a normal migrations workflow (e.g. new file in migrations folder and after file is applied to the database also the table managing the migrations gets updated?

If easier, we could also hop on a call. You could email me at "loelhoeffel at our domain" so we can coordinate.

**Comment by SheaBelsky** [comment]
Thank you for reaching out to me! I will send you an email soon :)

**Comment by SheaBelsky** [comment]
Thank you for the reply!

> Could you elaborate why you can't apply migrations in CI/CD. Did you consider using `migrate deploy` in CI?

Our database exists within a virtual network in Azure's infrastructure. I haven't found a great way to create a CI/CD pipeline that also authenticates with a virtual network in order to facilitate connections. I could create a virtual machine for the sole purpose of CI/CD, but that might be overkill and potentially expensive for just migrating. (It might not be either of those things - it could be easier! But I've fought with it for a while and haven't found a great solution here.) If I had access to a single SQL file that took care of everything, I could execute it with something like this: https://github.com/Azure/sql-action


> Are you asking for a way to use the output from `migrate diff` as part of a normal migrations workflow (e.g. new file in migrations folder and after file is applied to the database also the table managing the migrations gets updated?

Something like that - I want to perform the entire migration in a situation where access to the CLI may not be possible, but access to the database would be (within a vnet or some other mechanism for executing SQL)

**Comment by floelhoeffel** [comment]
@SheaBelsky would programmatic access in node work? E.g. the ability to run `migrate.deploy()` from within your app code?

**Comment by tobiasdiez** [comment]
It would be good if the `migrations diff` command would fallback to existing information specified in package.json / the schema file. For example, instead of 
```bash
prisma migrate diff --preview-feature 
      --from-migrations <path to migrations>
      --to-schema-datamodel <path to schema>
      --shadow-database-url <database connection string>
```
on should be able to run `prisma migrate diff --preview-feature --from-migrations --to-schema-datamodel`, which then takes the migration and schema location from the package.json, and the database url from the schema file.

**Comment by tobiasdiez** [comment]
Sure! I think this is a good approach.

> You mention in your shortened example that the url is taken from the schema but the --to-schema-datamodel option would actually not take the url but the datamodel from the file.

Sorry for being imprecise. The path to the schema (the arg to --to-schema-datamodel) should be taken from `package.json`, while --shadow-database-url should fallback to the url specified in the schema file.

**Comment by janpio** [comment]
@tobiasdiez: I think you should split that out into a feature request, so we can tackle this later - when we have more confidence as @do4gr mentioned. Thanks.
