### ISSUE TITLE
Evaluate using merged PR titles additionally to / instead of closed issue titles for release notes

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11716]
We currently use the list of closed issues to build the release notes.

I think it would be interesting to see what using the merged/closed PRs would look like instead. That reflects the changes to the actual code much better, and also includes things that did not have issues (and does not include issues that were just closed without any action necessary).

Probably relevant code (via @millsp)
https://api.github.com/search/issues?q=org%3Aprisma
https://github.com/prisma/release-notes/blob/main/src/index.ts#L96

Internal discussion: https://prisma-company.slack.com/archives/C9D3H0P1A/p1644401858973059

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
