### ISSUE TITLE
Output version of generated Prisma Client in `prisma -v`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11807]
Currently you can output `prisma -v` and think you are all good, but you actually still have an outdated old Prisma Client generated with an older version that will fail, which you will only possibly notice in the Client error message. This would be easier to spot if `prisma -v` would also output the version (and location!) of the currently generated Client - and possibly even highlight an outdated version (or one that does not match your `@prisma/client` in your project).

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
