### ISSUE TITLE
Prisma Introspection Crashed on In-Memory CockroachDB 

### ISSUE THREAD

**Issue by ppoddar-affordably** [prisma/prisma#11866]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v16.13.2           | 
| Prisma CLI  | 3.9.2              | 
| Engine      | bcc2ff906db47790ee902e7bbc76d7ffb1893009| 

## Error
```
Error: [introspection-engine/connectors/sql-introspection-connector/src/introspection_helpers.rs:241:64] called `Option::unwrap()` on a `None` value
```

**Comment by janpio** [comment]
Thanks for the report. Can you share some additional information so we can potentially reproduce this? How does one run such an "In-Memory CockroachDB"? What version? Anything special about your schema or does it happen for all?

**Comment by pimeys** [comment]
So what could be happening here is we have foreign keys available with columns that do not exist in the table. We crash because the table does not have a column mentioned in the foreign key.

We load relations separately from the tables, so it would be very interesting to get a proper reproduction to find a solution for these cases.

**Comment by janpio** [comment]
Ping @ppoddar-affordably

**Comment by SevInf** [comment]
Hey @ppoddar-affordably.
Since we haven't heard back from you, we are going to close this issue. Feel free to open new one, providing all information necessary for reproduction.
