### ISSUE TITLE
mysql username parsing bug, only extracted partial with two `%3A` (:) in datasource url

### ISSUE THREAD

**Issue by ShadyZOZ** [prisma/prisma#11898]
one works fine
```
npx prisma init --url "mysql://ccc%3Afoo%3Addd:bar@127.0.0.1:2883/zzz"
Error: P1000: Authentication failed against database server at `127.0.0.1`, the provided database credentials for `ddd` are not valid.

Please make sure to provide valid database credentials for the database server at `127.0.0.1`.
```

**Comment by ShadyZOZ** [comment]
It seems to be a problem only when db connection returns an error.

**Comment by janpio** [comment]
Still a bug we should look into and fix.

**Comment by janpio** [comment]
You need to trigger the same error as @ShadyZOZ had, `Error: P1000: Authentication failed against database server ...` as that will try to pull in part of the connection string and display it - which then probably goes wrong and looses some information.

**Comment by jkomyno** [comment]
I was able to trigger Error P1000 by calling a specific version of `mysql`, see my updated comment above.
However, the root cause of the issue seems to lie in [`prisma-engines`](https://github.com/prisma/prisma-engines/tree/23eea17bd761acf388c556be3e94fe9070797c12/migration-engine/cli). The following command triggers the error mentioned in this issue:

`"~/work/prisma/prisma/node_modules/.pnpm/@prisma+engines@3.13.0-2.ba8e3c2c2615e6af9303b3930e7de9377999a0e7/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" cli --datasource "mysql://foo:bar@127.0.0.1:3306/tests" can-connect-to-database`

**Comment by jkomyno** [comment]
Note: the same error occurs even when using simpler user/password combinations, like `foo:bar` (updating the docker-compose.yaml) file accordingly

**Comment by jkomyno** [comment]
This issue is now solved (both when using library and binary engines), as can be tried with `prisma@^3.15.0` and `prisma@^4.0.0`.

## Setup

We prepare a `docker-compose.yml` file as follows:

```yaml
# docker-compose.yml

version: '3.7'

services:
  mysql:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "zzz"
      MYSQL_PASSWORD: "bar"
      MYSQL_USER: "ccc:foo:ddd"
    ports:
      - '3306:3306'
```

We can connect to such `mysql` service using the `mysql://ccc%3Afoo%3Addd:bar@127.0.0.1:3306/zzz` connection url,
where `ccc%3Afoo%3Addd` is the [percentage-encoded](https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters) username `ccc:foo:ddd`. Note that the mysql user is defined without special encoding in the `MYSQL_USER` variable in `docker-compose.yml` file.

## Usage

- Start the mysql service: `docker-compose up`
- In another terminal, try to connect to `mysql` using the wrong password, you can see that the user is logged as `ccc:foo:ddd`:

```text
❯ npx prisma init --url "mysql://ccc%3Afoo%3Addd:wrong@127.0.0.1:3306/zzz"
Error: P1000: Authentication failed against database server at `127.0.0.1`, the provided database credentials for `ccc:foo:ddd` are not valid.

Please make sure to provide valid database credentials for the database server at `127.0.0.1`.
```
- Now, try to connect to `mysql` using the right password:

```text
❯ npx prisma init --url "mysql://ccc%3Afoo%3Addd:bar@127.0.0.1:3306/zzz"

✔ Your Prisma schema was created at prisma/schema.prisma
  You can now open it in your favorite editor.

warn You already have a .gitignore file. Don't forget to add `.env` in it to not commit any private information.

Next steps:
1. Run npx prisma db pull to turn your database schema into a Prisma schema.
2. Run npx prisma generate to generate the Prisma Client. You can then start querying your database.

More information in our documentation:
https://pris.ly/d/getting-started
```
