### ISSUE TITLE
Query Engine tests with multi hostname MongoDB connection strings

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#11959]
MongoDB connection strings are not URIs. It would be great to have Rust-level tests to see if sharded strings work correctly with the Query Engine. The URI format is this:

```
mongodb://user:password@srv1.rgyl0.mongodb.net:27017,srv2.rgyl0.mongodb.net:27017,srv3.rgyl0.mongodb.net:27017/database?ssl=true&authSource=admin&retryWrites=true&w=majority
```

So we should have a few replicas, and test with a connection string that lists them like in the example.

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/12380

**Comment by matthewmueller** [comment]
Is this different than https://github.com/prisma/prisma-engines/pull/2702?

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
