### ISSUE TITLE
Unable to establish a connection once database recovers

### ISSUE THREAD

**Issue by chronotc** [prisma/prisma#12028]
## Bug description

If the initial request is sent while database connection cannot be established, all subsequent request will result in failures.

 ## Steps reproduction

1) Take down database
2) Initiate request `prisma.$queryRaw` (FAILS)
3) Bring up database
4) Initiate request `prisma.$queryRaw` (FAILS)

Both requests fail with
```
Can't reach database server at xxxx:xxx
```
```
  prisma:client:libraryEngine sending request, this.libraryStarted: false +5s
  prisma:client:libraryEngine library starting +0ms
  prisma:info Starting a postgresql pool with 21 connections.
  prisma:client:libraryEngine sending request, this.libraryStarted: false +7s
  prisma:client:libraryEngine library already starting, this.libraryStarted: false +0ms
```

## Expected Behavior

1) Take down database
2) Initiate request `prisma.$queryRaw` (FAILS)
3) Bring up database
4) Initiate request `prisma.$queryRaw` (PASSES)

See PR https://github.com/prisma/prisma/pull/12066

**Comment by Jolg42** [comment]
Note: @pantharshit00 it looks like the description was edited with some reproduction steps

**Comment by Dammmien** [comment]
Hi guys !

I have few similar random errors: P1001 Can't reach database server at xxxx:xxx
So the Prisma client seems to lose the connection with the Postgresql DB obviously ...
It’s not linked to the server load or too many connections because I have the same issue in staging environment with very low trafic
It’s happening on two different services: a NodeJS API and a web worker
Everything looks fine on Postgresql DB side and I have another service connected to the same Postgresql DB but with Sequelize as ORM and no issue in this service

Do you have any idea, what should I look for in order to fix it ?

**Comment by matthewmueller** [comment]
Internal Note:
- Decide if this is related to the connection pool issue? And what to do about it.

**Comment by Jolg42** [comment]
Note: See PR and the comments there https://github.com/prisma/prisma/pull/12066

**Comment by janpio** [comment]
We know that this is not related to the recent connection pool load issue, but generally could have been caused by the same code (connection pool). The PR makes it look like a different, TS Library Engine implementation problem. This has still to be understood and confirmed.
