### ISSUE TITLE
Change the contents of migration_lock.toml on Microsoft SQL Server

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12087]
Currently, we write `provider = "mssql"`, but that does not match the provider in the Prisma schema.

We should change this to `provider = "sqlserver"` for new migration_lock.toml files, but still accept the old version to avoid any breakage.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
