### ISSUE TITLE
Logging for Query Engine lifecycle and interactions

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12152]
Internal discussion https://prisma-company.slack.com/archives/C016KUHB1R6/p1646390705740259 showed that it would be useful to be able to enable a special logging mode that logs all the engine communication in Prisma Client, both for the general lifecycle (instantiate, start, stop, etc) but also queries. 

If that existed, we would know that what a `prisma.$disconnect()` really does to the engine, and what the next incoming query then does with the engine again. File for this would probably be https://github.com/prisma/prisma/blob/main/packages/engine-core/src/library/LibraryEngine.ts (and binary equivalent)

@millsp also mentioned that this might be useful in other areas.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
