### ISSUE TITLE
Better Error if files referenced in the connection string can not be found

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12214]
On Mongo if the tlsCAFile cannot be found, the returned error does not specify which file was not found or at which path the resolving failed. The parameter was `&tlscafile=../ca.crt`. If the path where the resolution failed was specified this could be an easy fix for the user. 

```
 Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: db-mongodb-nyc3-f6bed3e5.mongo.ondigitalocean.com:27017, Type: Unknown, Error: No such file or directory (os error 2) }, ] }
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
