### ISSUE TITLE
Test certificate file location from connection strings

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12278]
Multiple of our connectors allow to configure a certificate file via the connection string (at leat PostgreSQL, MySQL and MongoDB). We document that to be relative to the Prisma schema location - but it is unclear if that means only the default `prisma/schema.prisma` or also other locations via `--schema` or the `prisma.schema` object in `package.json`.

We should have tests for all these configurations (all engines, all connectors, all possible locations).

(There might also be other connection string parameters that expect a file, so these could also be tested the same way.)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
