### ISSUE TITLE
JEST: Breakdown into next steps

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12370]
Figure out what the next steps are to make progress on the memory leak issue and update the epic

**Comment by garrensmith** [comment]
At this stage, we have identified what the problem is. When the client code is generated we create a large DMMF variable that is basically a global variable that the GC can never reclaim. Jest keeps reloading the client so that DMMF value gets duplicated many times which leads to the memory increase. 

The way to fix it is to get the DMMF when the client is created and to clear that variable on `$disconnect`. 
A proof of concept is here https://github.com/prisma/prisma/pull/12502
But there is more work involved in getting it to the finish line.

**Comment by millsp** [comment]
Next steps:
* Re-discuss [initial exploration phase ](https://www.notion.so/prismaio/Prisma-Client-How-do-we-use-Schema-Schema-file-DMMF-on-runtime-7241e1616ed44273833fc9672cf7e21b)
* Begin experimenting with different outcomes
* Explore how to make the least breaking changes
* Measure/benchmark each of the outcomes
* Take decision/choose the best outcome

**Comment by kevinsimper** [comment]
Our tests began failing and it took me a bit to get that it was prisma 😅 

I was looking into running a global teardown, because we are using jest mock deep, but from @garrensmith comment it sounds like that does not solve it either.

I think our short term solution must be to split up our jest tests into smaller so that it does not crash our 8 GB CI test machine in GCP.

**Comment by kevinsimper** [comment]
Wuhu for Prisma v4 👏

**Comment by janpio** [comment]
If you have the time, please confirm that @m-allanson @kevinsimper that you can indeed not see any memory increase any more. We are pretty confident, but confirmation would be better of course. Thanks!

**Comment by m-allanson** [comment]
@janpio Yes, all good from this side. Thanks again for the work on this :)
