### ISSUE TITLE
Integration PR creation could also commit on integrated commit on `prisma-engines`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12520]
When we commit to `prisma-engines`, it triggers a new version of `engines-wrapper` for that version hash. That one then triggers an integration via PR in `prisma/prisma`. After that integration PR is opened, we could comment on the original `prisma-engines` commit to already leave a trace where integration is going to happen.

Manual example:
https://github.com/prisma/prisma/pull/12519
https://github.com/prisma/prisma-engines/commit/d15c884f70bfe28d0b3ee1a3efac7fdb991e5de4#commitcomment-69466881

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
