### ISSUE TITLE
Download url of prisma engines for Node-API Not Found on Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by helltf** [prisma/prisma#12662]
### Bug description

After installing prisma with npm I tried to generate the prisma client for my project via:
`npx prisma generate`

The request for the download is stopped because the following url is not Found
`https://binaries.prisma.sh/all_commits/1a2506facaf1a4727b7c26850735e88ec779dee9/linux-arm-openssl-1.1.x/migration-engine.gz`

Therefore no client will be generated and I can't use it inside of my programm because of the following error:
`Error: @prisma/client did not initialize yet.`

### How to reproduce

Occurs after running any prisma command with npx.

### Expected behavior

As mentioned in this discussion https://github.com/prisma/prisma/discussions/9656 the url is not working but is with linux-arm64-openssl-1.1.x instead. Nevertheless I cannot install the correct engine on linux system.
Furthermore changing the binaryTargets of the prisma client did not fix this problem.

### Prisma information

Current generator: 
`generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x", "linux-arm64-openssl-1.1.x", "linux-musl"]
}
`

But doesn't work either without binaryTargets  

### Environment & setup

OS INFO:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Kernel: Linux 5.4.83-v7l+
Architecture: arm

### Prisma Version

```
3.11.1 in package.json
```

**Comment by janpio** [comment]
This sounds related or similar to https://github.com/prisma/prisma/issues/5552. Possible?

**Comment by helltf** [comment]
Seems like. Is there no support for arm or is it just a bug?

**Comment by janpio** [comment]
We treat any not working installation as a bug first, but this one is possibly related to a missing feature: https://github.com/prisma/prisma/issues/8478

**Comment by baddri** [comment]
so umm, any solution yet?

**Comment by janpio** [comment]
Your problem is probably that you are using an operating system with OpenSSL 3, but a too old version of PRisma that did not support OpenSSL 3. Try upgrading your Prisma version - and if that does not work please open a new issue and provide all the information we need to understand what is happening.

**Comment by baddri** [comment]
I'm so sorry. that was my bad. i just add `binaryTargets` for ubuntu and it works just fine

![image](https://user-images.githubusercontent.com/49059318/175657966-484e0f7b-523d-44ea-ba31-7f5380f56039.png)

**Comment by Jolg42** [comment]
@saharshg I think I might be able to help you, but could you open [a new issue here first](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml)?
Please make sure to mention your Node.js version and environment info in the template.

**Comment by Jolg42** [comment]
Note for @helltf and @baddri if you are running on a Raspberry Pi

adding support for Prisma for Linux ARM 32bit is tracked in https://github.com/prisma/prisma/issues/5379

Though since Raspbian OS has a 64 bit version, it's the one currently recommended. Make sure the Node.js runtime is also 64bit, and it should work out of the box without specifying any `binaryTargets` with the latest version of Prisma.
