### ISSUE TITLE
Phrasing: make sure schema validation error messages do not have a time component

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12698]
In an internal proposal, the following validation error was proposed:

> // Implicit many-to-many relations cannot take a `references` argument anymore.
> // Please remove the `references` argument.
> // You can read more about many-to-many relations at https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations

@janpio noted that the time component ("anymore") will become misleading with time, so we should avoid it. We think there may already be error messages returned by schema validation that present this problem. We should review them and reformulate.

One challenge with this issue is that the error messages are very incompletely centralized, so we may have to scan the codebase by ourselves.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
