### ISSUE TITLE
How to use diff to generate a down migration

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#12781]
Problem:
I want a down migration for my up migration, how would I do that?

**Comment by floelhoeffel** [comment]
Tom's video transcript into steps:

- change datamodel by e.g. adding `model C {}`
- generate down migration by diffing datamodel to history, use script param to get SQL
- pipe output into file `down.sql`
- run `migrate dev` to generate up migration
- move `down.sql` next to up migration in folder
- use `db execute` in case you need to run the down migration

**Comment by tomhoule** [comment]
Here's an attempt at an outline, with different possibilities:

1. Edit your prisma schema 
2. Generate the down migration
  - with ` prisma migrate diff --preview-feature --from-schema-datamodel prisma/schema.prisma --to-migrations prisma/migrations --shadow-database-url $SHADOW_DATABASE_URL --script`
  -  or alternatively with `prisma migrate diff --from-schema-datamodel prisma/schema.prisma --to-schema-datasource prisma/schema.prisma` **if your database was in sync and up to date with your migrations before step 1**.
  - and in both scenarios, save the resulting down migration (SQL) script somewhere.
3. Generate the "up" migration with `prisma migrate dev`
4. Copy the down migration script next to the new migration's `migration.sql`

Remarks:
- The down migration must be generated first, because we need either a migrations directory or a database with the state _before_ the migration we are going to generate. We may relax that llimitation by allowing targetting migrations directories in a more fine-grained way, for example `--from-migration ./prisma/migrations/the-last-migration-before-the-new-one`.
- The first option in 2. is more robust than the second one, but it requires a shadow database URL.

---

Now to _use_ the down migration that was generated to roll back:

On the target (production) database:
- Use `db execute` to apply the SQL script for the down migration.
- Use `prisma migrate resolve --rolled-back <the-migration-name>` to record that you ran the down migration in the migrations table.
- Voilà

**Comment by tomhoule** [comment]
Link to the video in the internal slack: https://prisma-company.slack.com/archives/C02FNFLDUS3/p1649760874893109

**Comment by tomhoule** [comment]
Docs are live: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/generating-down-migrations

**Comment by janpio** [comment]
What would a streamlines version look like @enn-code? If you have suggestions, happy to consider.
