### ISSUE TITLE
GH bot that automatically posts the integration version Npm package name to PRs that start with `integration/`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12918]
https://github.com/prisma/prisma/pull/12897 is automatically published as `prisma@3.13.0-integration-add-spinner-to-introspection.1`. We could surface this in a comment on the PR. (Useful code: https://github.com/prisma/docs/blob/main/.github/workflows/list-changed-pages.yml)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
