### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by gustavo-alvarez-gcf** [prisma/prisma#12998]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull --force --schema src/prisma/gcfglobal.schema.prisma`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v16.14.2           | 
| Prisma CLI  | 3.12.0             | 
| Engine      | 22b822189f46ef0dc5c5b503368d1bee01213980| 

## Error
```
Error: [introspection-engine/connectors/mongodb-introspection-connector/src/sampler/statistics/indices.rs:167:71] called `Option::unwrap()` on a `None` value
```

**Comment by tomhoule** [comment]
Hi @gustavo-alvarez-gcf , thanks for the report! Can you tell us which version of mongodb you are using?

**Comment by gustavo-alvarez-gcf** [comment]
Sure, we use an M10 Atlas cluster with Mongo 5.0.7. Thank you so much.

**Comment by pimeys** [comment]
This is due to us expecting the indices we get from mongo to be reasonable, but they can actually be whatever.

An example where this crashes, with the indices:

```json
{
  "foo": 1,
  "foo.bar": 1
}
```

This then would lead to a data model, that is not really functioning correctly:

```prisma
type TestFoo {
  bar Json?
}

model Test {
  id  Int   @id @map("_id")
  foo Json?

  // what do we index here?
  @@index([foo])
  // no such field, validation error
  @@index([foo.bar])
}
```

The suggestion is to output an invalid data model here, and let the user fix the issues in the data. Currently this is not feasible with the dml library, and we should aim to have a simpler data structure for string rendering. Moving this (and the other issue) to wait for that moment.

**Comment by janpio** [comment]
Error report link in this issue: https://github.com/prisma/prisma/issues/12925

**Comment by tomhoule** [comment]
This was not meant to be closed, I wrote "In order to fix https://github.com/prisma/prisma/issues/12998", and github interpreted it as "this fixes ...". Reopening.
