### ISSUE TITLE
Keep migration/introspection engine test suite compile times in check

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#13028]
We observe a nearly 1 second compile time increase for a single PR in https://github.com/prisma/prisma-engines/pull/2858

![2022-04-27_10-04-57](https://user-images.githubusercontent.com/13155277/165481464-1b987054-ca33-4ef4-a950-d8f1165956c3.png)

Let's flesh out a proposal to — ideally — make most new tests have no impact on compile times, in the spirit of https://github.com/ziglang/zig/issues/11288.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
