### ISSUE TITLE
Error message when custom Node-API engine has wrong file extension

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#13041]
> @kbzowski btw, one thing that's not really documented anywhere right now: after building the engines from sources, you'll need to rename `target/release/libquery_engine.so` to `libquery_engine.so.node`. Otherwise Node.js won't recognise it as an addon and won't allow loading it.

_Originally posted by @aqrln in https://github.com/prisma/prisma/issues/3091#issuecomment-1109998372_

> (That sounds like something we could surface via a small error message if someone tries to set the engine to `*.so` @aqrln)

_Originally posted by @janpio in https://github.com/prisma/prisma/issues/3091#issuecomment-1110060787_

> @janpio that's a very good idea actually!

_Originally posted by @aqrln in https://github.com/prisma/prisma/issues/3091#issuecomment-1110840397_

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Comment by aqrln** [comment]
@jkomyno it's not even an issue anymore ever since we started using `process.dlopen` instead of `require`. You can name your engine file `libquery-engine.i-love-donuts` and it will still work, we don't care and neither do Node.js or the operating system. The issue should've been closed long ago 👍
