### ISSUE TITLE
Inline/bundle the contents of the prisma schema on generate

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#13052]
We could close a whole class of issues where the schema is not found (https://github.com/prisma/prisma/labels/topic%3A%20ENOENT%20schema.prisma) by inlining the contents of the `schema.prisma` directly into the generated `index.js`. Our logic happens to break usually when code is bundled (nextjs, svelte, webpack).

When code is bundled to another location, our lookup paths for the schema do not make sense any longer. We have logic to at best find the original generated folder, which works at best but has not guarantee it could find the correct folder and fails especially on monorepos.

A solution to this is to directly embed the prisma schema, which needs to be passed to the engines. Side note: We might experience the same thing again for sqlite databases since we resolve their normal location relatively to the generated client.

**Comment by orbiteleven** [comment]
I'm thinking/hoping this would finally allow us to move our repo over from Yarn v3 to pnpm. As it is, Prisma does not seem to behave well in a pnpm monorepo. I'd love to help, but TBH not sure I have the time to dive in on the Prisma codebase ATM. Happy to help test things, though. Cheers!

**Comment by Geebrox** [comment]
Any update on this? Would someone create a PR? I am stuck on this error. I cannot update the Prisma client to the latest version and use new features.

**Comment by itamar-getloam** [comment]
It seems the feature was partially implemented in 7ebcafed2 to support dataproxy engines. I added a `forceInlineSchema` parameter to the generator config in `schema.prisma` to force that behavior.

We had a *lot* of issues caused by the schema file lookup mechanism, this feature should solve most of them, as you said.

**Comment by millsp** [comment]
We have a PR in progress https://github.com/prisma/prisma/pull/13261 to make this the default. Currently the build step is causing the errors, that will be fixed via https://github.com/prisma/prisma/pull/13303. I'll soon share a version for you guys to try it out (I'd really appreciate if you can take the time to give any feedback).

**Comment by millsp** [comment]
Hey everyone, I have a testing version to share. If you have some time, could you please give a try?
* `npm i prisma@3.15.0-integration-fix-inline-schema.5` and 
* `npm i @prisma/client@3.15.0-integration-fix-inline-schema.5`

 Looking for your feedback :)

**Comment by Geebrox** [comment]
> Hey everyone, I have a testing version to share. If you have some time, could you please give a try?
> 
> * `npm i prisma@3.15.0-integration-fix-inline-schema.5` and
> * `npm i @prisma/client@3.15.0-integration-fix-inline-schema.5`
> 
> Looking for your feedback :)

Hello @millsp and thank you for the update. Tried to use the versions you have provided and got some errors.

### Error:

```shell
ERROR [Bootstrap] Error: Query engine library for current platform "darwin-arm64" could not be found.
You incorrectly pinned it to darwin-arm64
```
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/15965924/168294597-6ce997bc-33d5-4dec-9743-7e00925ccf9c.png">


### ENV:

```
- OS: macOS Monterey v12.3.1
- Database: MongoDB
- Node: v16.13.0
- NPM: v8.1.3
- Yarn: v1.22.17
```

### Reproduction:

I have created a branch in one of my repos where this issue happens: https://github.com/Geebrox/next-nest-mono

Steps to reproduce:

1. Clone the repo
2. Checkout to the branch called `prisma-13052` (`git checkout prisma-13052`)
3. Install dependencies (`yarn install`)
4. Populate `.env` vars
5. Run dev command (`yarn dev`)

**Comment by Geebrox** [comment]
@millsp Oh, it was my mistake, I forget to add `additionalModuleDirs` option for `webpack-node-externals`. I fixed that and tried again. Everything works fine with these updates on my side.

**Comment by janpio** [comment]
You actually reproduced another error we have and want to tackle @Geebrox - if you can put that into a branch and make sure it stays there, open a new issue about it. Would be awesome 😆

**Comment by Geebrox** [comment]
@janpio sure, I have pushed that fix on the same branch. Will keep that branch if someone faces the same issue in the future.

**Comment by janpio** [comment]
Thanks. So I can guess we can check out https://github.com/Geebrox/next-nest-mono/commit/84bd3748518ecbbbf26bfe32a3408756639942c6 and run the reproduction steps above?
Can you maybe quickly open a new issue with the error you got as title, and include the screenshot and the repo and your steps?
Then we can treat that separately <3

**Comment by yoav-getloam** [comment]
Hi, just checked the new version. Getting a new error:
`Runtime.UnhandledPromiseRejection - Error: Query engine library for current platform "rhel-openssl-1.0.x" could not be found. You incorrectly pinned it to rhel-openssl-1.0.x This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/var/task/dist/packages/platform/.next/server/chunks/libquery_engine-rhel-openssl-1.0.x.so.node") Searched Locations: /var/task/dist/packages/platform/.prisma/client /opt/build/repo/jumpy/packages/backend/prisma/<MY_CLIENT> /var/task/dist/packages/platform/.next/server /var/task/dist/packages/platform/.next/server /tmp/prisma-engines /var/task/dist/packages/platform/.next/server/chunks You already added the platforms "debian-openssl-1.1.x", "linux-arm64-openssl-1.1.x", "rhel-openssl-1.0.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma/issues/new
`
It does say it found rhel-openssl-1.0.x in my binaryTargets but still get the same error.
Any idea how to further investigate the issue?
Thanks!

**Comment by nvsd** [comment]
I get the same as @yoav-getloam with [sst](https://serverless-stack.com/).
`ERROR Runtime.UnhandledPromiseRejection: Error: Query engine library for current platform "darwin-arm64" could not be found.
You incorrectly pinned it to darwin-arm64`

I can also help with any investigation into the issue.

**Comment by orbiteleven** [comment]
FWIW this seems to work with the barebones example that @SimonBerens set up, forked here: https://github.com/orbiteleven/prisma-pnpm-workspace-test 🚀

It'll take me a little time to implement on our full app to test, but I'm encouraged 👍

**Comment by itamar-getloam** [comment]
Hi @millsp, could you give us some pointers to try and debug the issue @yoav-getloam mentioned?
Should we open a separate issue, or is it related to this one?

**Comment by millsp** [comment]
Do you get the same issue by using the latest `dev` version, or is it just on `3.15.0-integration-fix-inline-schema.5`?
* `npm i prisma@dev` and
* `npm i @prisma/client@dev`

**Comment by yoav-getloam** [comment]
Thanks for your response!
In dev I get the error that the prisma schema is not found, and so I can't check it individually.

**Comment by millsp** [comment]
I'm suspecting that this is a related problem, but not caused by the current changes.
It is likely that the engine was not copied or that the paths were different once deployed.
Could you please provide a reproduction to us so that we can look into this as well?

**Comment by Geebrox** [comment]
@millsp @janpio I have created #13460 to track the issue with the error that some users of monorepos are facing

**Comment by nvsd** [comment]
Hey, just wanted to check in and see if there is anything I can do to help with this issue?

**Comment by janpio** [comment]
> FWIW this seems to work with the barebones example that @SimonBerens set up, forked here: [orbiteleven/prisma-pnpm-workspace-test](https://github.com/orbiteleven/prisma-pnpm-workspace-test) 🚀
> 
> It'll take me a little time to implement on our full app to test, but I'm encouraged 👍

When I try your repository with the original reproduction steps I do get a response from the API, but that is hardcoded. My console meanwhile shows this:

```
error - ../node_modules/.pnpm/@prisma+client@3.15.0-integration-fix-inline-schema.5_vjfta67euzfky6sgwkl65f6s6m/node_modules/@prisma/client/runtime/index.js (44931:0) @ LibraryEngine.getLibQueryEnginePath
Error: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
You incorrectly pinned it to debian-openssl-1.1.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/workspace/prisma-pnpm-workspace-test/apps/frontend/.next/server/pages/api/libquery_engine-debian-openssl-1.1.x.so.node")

Searched Locations:

  /workspace/prisma-pnpm-workspace-test/apps/frontend/.next/.prisma/client
  /workspace/prisma-pnpm-workspace-test/node_modules/.pnpm/@prisma+client@3.15.0-integration-fix-inline-schema.5_vjfta67euzfky6sgwkl65f6s6m/node_modules/@prisma/client
  /workspace/prisma-pnpm-workspace-test/apps/frontend/.next/server/pages
  /workspace/prisma-pnpm-workspace-test/packages/prisma
  /tmp/prisma-engines
  /workspace/prisma-pnpm-workspace-test/apps/frontend/.next/server/pages/api


To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
null
```

Is that not what you were seeing here or am I missing something?

**Comment by janpio** [comment]
A general update on this issue for everyone following along:

This issue and connected PR was an attempt to solve the pretty common error message and problem `Error: ENOENT: no such file or directory, open '<...>/schema.prisma'` when running Prisma Client in a monorepo context. By inlining/bundling the schema, we hoped Prisma would not ned to read the schema file - and hence not opportunity for this error message.

What effectively happened via the PR in the integration version though was that we realized that the schema is of course not the only file the Client has to find and use, but right after the schema is read it will do the same for the Query Engine - which means you then get an error message containing `Error: Query engine library for current platform "..." could not be found.`.

Under https://github.com/prisma/prisma/labels/topic%3A%20ENOENT%20schema.prisma we are currently working systematically through all the issues for the original problem, and where we have reproduction projects we are having pretty good results coming up with temporary workarounds (e.g. adding something to your `next.config.js` when you are using Next.js, or something to your Webpack config if you are using NestJS).

If you have not yet, please check the other issues for one that matches your project. If we do not have a proper reproduction yet, please create one and add it to one of the issues. If you you can not identify the correct issue, just create a new one. This problem is super confusing so we will take care of crosslinking the relevant issues and comments. Thanks!

**Comment by leleofg** [comment]
@janpio any news about this issue?

**Comment by millsp** [comment]
We might bundle the Prisma Schema in the future, but in the context of Next.js we have done considerable progress in closing most of the issues related to "Schema not found", and displaying useful errors and workarounds.
