### ISSUE TITLE
Prisma client for Flutter/Dart

### ISSUE THREAD

**Issue by GNVageesh** [prisma/prisma#13122]
Prisma has been THE best orm for projects with typescript and nodejs... But it would be great if there is a prisma client/connector for Flutter/Dart.
It would make database handling much easier and faster.

Hope this feature request is considered.

**Comment by GNVageesh** [comment]
Looks like this is the one we are looking for. Not sure if it's official tho.

Thanks mate

**Comment by nikolasburk** [comment]
Hey everyone 👋  I just wanted to drop here that @odroe is working on this here: https://github.com/odroe/prisma-dart

**Comment by janpio** [comment]
Is this feature request different from the older, already existing https://github.com/prisma/prisma/issues/9473?

**Comment by GNVageesh** [comment]
Thank you @nikolasburk for letting us know about it. It is helpful

**Comment by medz** [comment]
> Hey everyone 👋 I just wanted to drop here that @odroe is working on this here: https://github.com/odroe/prisma-dart
> It is not an official Prisma product though.

Dart also does not have easy-to-use OOP and MVC frameworks. In addition to maintaining Prisma ORM for Dart, we are developing the https://github.com/odror/parrot framework.🤗

**Comment by tuga001-sme** [comment]
@janpio  I think we need official flutter version, maybe as fork  from https://github.com/odroe/prisma-dart

**Comment by medz** [comment]
> @janpio I think we need official flutter version, maybe as fork from https://github.com/odroe/prisma-dart

@tuga001-sme 
Obviously, this is also true. The API of Prisma Dart has always been designed with reference to the API of Prisma TS. According to Slava Egorov's reply in X post: https://x.com/mraleph/status/1843974645122519306, it is obvious that it does not conform to the design and usability habits of Dart.

It might be better for Prisma to make it officially. To be honest, I have tried my best to maintain it with any time I can.

I'm sorry that it has been half a month since the last update was released. I don't have time to make new features after Prisma 5.21.

I am currently looking for a stable job. To be honest, my current financial situation is not good. So the focus is not on Prisma Dart.

It might be better if Prisma officially makes Prisma on Dart/Flutter, because Prisma has sufficient funds and personnel. And there are almost no contributors to Prisma Dart since its release.

Given my current situation, I don't think I can continue to develop it well.

> It would be great if Prisma could take over. That way I can focus more on finding work to improve my current situation.
