### ISSUE TITLE
Better way to get integration versions of user contributed PRs

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#13145]
Right now we need to create a local branch starting with `integration/` to be able to get an integration branch of a PR a user opened. 

Example: https://github.com/prisma/prisma/pull/12907 => https://github.com/prisma/ecosystem-tests/pull/2692

This is quite a bit of work, hard to update and also confusing - so we should optimally find a better way to achieve this.

**Comment by Jolg42** [comment]
[Internal Slack discussion](https://prisma-company.slack.com/archives/C019HJREA93/p1672936227646439)

PR https://github.com/prisma/prisma/pull/17352

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
