### ISSUE TITLE
Backtraces are missing on windows in the error reporting UI

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#13315]
Example: https://prisma-errors.netlify.app/report/13234

We do not know at this point whether this is a problem with the binary, a configuration problem, or a problem in our error reporting infrastructure, so this would need to be investigated.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
