### ISSUE TITLE
Configurable binary asset download (source) location

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1333]
This feature request originated here https://github.com/prisma/prisma2/issues/916

and is not covered via https://github.com/prisma/prisma2/issues/506

Prisma CLI, tries to download binaries from Prisma's S3 bucket. In some environments, this download fails. 

This requires spec work but a potential solution can be to have a configurable CDN URL via an env var like `PRISMA_CDN_URL`. 

The responsibility of maintaining a mirror would be on the users. 

An alternative is to link binaries to a release: https://github.com/prisma/prisma2/releases

**Comment by game7** [comment]
I've also been having proxy/firewall issues but after digging around the code I've discovered that the [binary asset locations are already configurable via environment variables](https://github.com/prisma/prisma-client-js/blob/master/packages/fetch-engine/src/download.ts#L129).  In my case I'm able to wget the binaries down to my container via our corporate proxy and simply point to them locally using [these environment variables](https://github.com/prisma/prisma-client-js/blob/master/packages/fetch-engine/src/download.ts#L46):

````
const binaryToEnvVar = {
  'migration-engine': 'PRISMA_MIGRATION_ENGINE_BINARY',
  'query-engine': 'PRISMA_QUERY_ENGINE_BINARY',
  'introspection-engine': 'PRISMA_INTROSPECTION_ENGINE_BINARY',
}
````

**Comment by prisma2user** [comment]
Original reporter of #916, was touching base with Prisma2 again to see how things were going here.

I took a quick look at the currently supported method of overriding the prisma 2 binary files via environment variable, but did noticed that these appear to require this to be a local path to the binary already on disk.

Since this issue is still open, I wanted to reach out see if it will be possible to allow have this support a http base domain / server and path where these files can be downloaded from an internal artifact server either instead of or addition to a local path to binary on disk.

The reason for this is that it is easier to specify an environment variable to our artifact server that will automactially proxy / download the binaries and host them internally on our network for the install process to request via install than it will be to manually download specific versions of binary files to servers outside of the install process and then link them since one does not know what binary they need as it relates to what version of prisma one is installing.

No think about rolling out a solution for many developers in an environment like this. Behind the scenes we can deploy these environment variables on every linux box we have with puppet, but i cant deploy every version on a binary to local disk for a developer and ensure they are using the right one... but if I can deploy a environment variable that says instead of getting your prisma binary from https://some-s3-bucket.aws.com/path/to/prisma-binaries/, where your install script will try to obtain the prisma.gz, migration and other gz files.... to instead get them from https://company-artifact-server.company.com/repository/prisma-binaries, and your install script downloads your gz files from this url where my artifact server on the backend will proxy out to obtain / import your binaries and host them internally for future requests... hopefully you csn see how this method is one that is much more friendly.

Again, I provided some additional use cases / scenerios in the origional ticket, but I can speak in further detail or show examples of how we use such artifact servers for proxying these artifacts if that will help.

**Comment by janpio** [comment]
We discussed this internally, and think we will introduce a `PRISMA_BINARY_MIRROR` environment variable. 

This will be used to try to download the binary on installation of `prisma2` and `@prisma/client`, or when some functionality is triggered that uses these binaries (as the initial download is not always possible). (Code that needs to be touched and use the value in the end: https://github.com/prisma/prisma-client-js/blob/5ebab94559c985ef6dab765b82254f10eaff841c/packages/fetch-engine/src/util.ts#L76-L79)

**Comment by timsuchanek** [comment]
Support for the env var `PRISMA_BINARIES_MIRROR` is now implemented.
A valid example URL is: `https://binaries.prisma.sh`

You can try it out in the latest alpha:
`@prisma/cli@alpha` & `@prisma/client@alpha`

**Comment by wbunting** [comment]
For anyone coming to this later -- another way to consider rather than `wget` the binaries during the build is to vendor the binaries to a path in the repository and then point the environment variables at:

```
const binaryToEnvVar = {
  'migration-engine': 'PRISMA_MIGRATION_ENGINE_BINARY',
  'query-engine': 'PRISMA_QUERY_ENGINE_BINARY',
  'introspection-engine': 'PRISMA_INTROSPECTION_ENGINE_BINARY',
}
```

during the build. That avoids needing to do any request through a corporate proxy
