### ISSUE TITLE
The Next.js Prisma template has a type error!

### ISSUE THREAD

**Issue by Devner-tour-guides-collective** [prisma/prisma#13536]
### Bug description

Installed the next.js prisma template, and I discovered it has a type error. I would fix this asap!

<img width="521" alt="image" src="https://user-images.githubusercontent.com/106288660/170808783-267eb02b-55fb-4eed-8aed-ee21dc20031b.png">

### How to reproduce

...

### Expected behavior

.

### Prisma information

...

### Environment & setup

...

### Prisma Version

...

**Comment by jkomyno** [comment]
Hi, thank you for rising this issue.
I have indeed found a type error in [this Next.js example](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes) (which should be fixed by https://github.com/prisma/prisma-examples/pull/3802), but it was a different type error than the one reported here.
Would you please provide a link to the Next.js template you're referring to? Thanks

**Comment by janpio** [comment]
Looks a bit like https://github.com/prisma/blogr-nextjs-prisma - Can you confirm @Devner-tour-guides-collective?

**Comment by nikolasburk** [comment]
It could also be one of the fullstack examples in the `prisma-examples` repo: https://github.com/prisma/prisma-examples/#fullstack

**Comment by mcbethio** [comment]
@Devner-tour-guides-collective Without knowing the exact template you are referred to, it's hard for us to fix.

Because it's been 9 months I'll close the issue as we've not had a response however please re-open the issue and we'll continue to look at it.
