### ISSUE TITLE
Prisma with PostgreSQL fails with GLIBCXX error

### ISSUE THREAD

**Issue by Arteneko** [prisma/prisma#13576]
### Bug description

Using the standard prisma commands on an Arch Linux setup, "everything worked" until today (regular updates, maybe some package broke ?).

I get this error when trying to run `yarn prisma migrate dev --name init`.

```
Error: db error: ERROR: could not load library "/usr/lib/postgresql/llvmjit.so": /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/postgresql/llvmjit.so)
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:250
```

What's surprising to me is that this folder doesn't exist, and my current glibc installation is version `glibc 2.35-5`.

I do have the `postgresql-libs` package installed (`postgresql-libs 14.3-1`), and psql works perfectly fine (I can connect to local and remote servers).

### How to reproduce

I honestly don't know, since I don't know what's the source

### Prisma information

- Prisma version `prisma@npm:3.14.0`
- Yarn version 2
- Yarn rebuilt already run

### Environment & setup

- OS: Arch linux
- Database: PostgreSQL
- Node.js version: v18.2.0
- Yarn version: 3.2.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.14.0
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by Arteneko** [comment]
Edit: The remote cluster I was targeting hasn't been upgraded, and apparently the prisma tool requires it to be properly upgraded. I don't know the correlation between both that would make psql behave as usual and not prisma

**Comment by Arteneko** [comment]
Yeah, kinda. What's left for me to wonder is how `psql` can not crash and `prisma` crash...

I would guess `psql` doesn't depend on llvmjit, does prisma?

**Comment by janpio** [comment]
That is a very valid question 🤔 Are you sure you used your local `psql` to connect to the same removate cluster where you got that error message?

In our understanding it is the remote cluster that depends on llvmjit, and not something running on your local machine. Remember, the error message that Prisma is giving you is something that the remote database server returned when Prisma tried to run a query or connect to it. It is not something that happens on your computer.

**Comment by Arteneko** [comment]
Yup, definitely.

> it is the remote cluster that depends on llvmjit, and not something running on your local machine

This is what I understood too, which is what's surprising to me... Does that mean that psql doesn't use the "standard" remote API ? that's weird, and probably way out of scope for prisma, but still curious

**Comment by janpio** [comment]
The only thing that is left might be that what you did with `psql` and with Prisma was just different enough to trigger different queries. If you for example only connected with `psql` and selected a database and ran a `SELECT`query, but ran `prisma migrate dev` with Prisma - that would lead to very different queries under the hood of course and then only one of those failed - but running the same query with `psql` would have also given the same error message. Possible?

**Comment by aqrln** [comment]
To reiterate what was said above, the error came from the remote database and not from Prisma (PostgreSQL server tried to load the `llvmjit.so` library, and couldn’t because it was compiled with newer C++ standard library than was present on the system).

The question of why the error only occurred when using Prisma but not psql is a good one, but regardless of the reason it would still be a problem on the database server side and not on the database client side.

The most plausible explanation to me is that the queries issued via psql weren’t complex enough to trigger JIT compilation (according to https://www.postgresql.org/docs/current/jit-decision.html, Postgres estimates the cost of the query first, and only JIT compiles it if the cost passes a certain threshold).

I'll go ahead and close this issue since it was a database setup problem and not an issue in Prisma after all — please let us know if there's still anything we could or should do. And thanks for opening the issue, it was the right call to let us know and take a look at this!
