### ISSUE TITLE
Support ULID

### ISSUE THREAD

**Issue by p6l-richard** [prisma/prisma#13679]
## Problem

> UUID can be suboptimal for many use-cases because:
> 
> It isn't the most character efficient way of encoding 128 bits of randomness
> UUID v1/v2 is impractical in many environments, as it requires access to a unique, stable MAC address
> UUID v3/v5 requires a unique seed and produces randomly distributed IDs, which can cause fragmentation in many data structures
> UUID v4 provides no other information than randomness which can cause fragmentation in many data structures

From the [ULID spec](https://github.com/ulid/spec).

The Lexicographically sortability would especially be useful for [cursor-based pagination](https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination) which requires sorting by a unique, sequential column.

## Suggested solution

Support ULID in the prisma schema, by defining:
`@db.Ulid`

**Comment by mbrookson** [comment]
It would be great to see this feature supported!

Since [ULID](https://github.com/ulid/spec) is designed to be the same 128-bits as UUID it should work with the underlying database type, but using this means Prisma throws the error because it is validating the string length which is only 26 characters for ULID.

**Comment by rafaell-lycan** [comment]
I've found this thread as my company uses `ULID` via a Golang lib and generates the `@id` on the backend instead of relying on the DB.

I've asked about `CUID` and the backends have answered they did research but options and `ULID` was the "best option at that time" (~5-6 years ago)

**Comment by lamanabie** [comment]
In postgres you can create function to generate ULID id (uuid v7 or uuid v8) https://gist.github.com/kjmph/5bd772b2c2df145aa645b837da7eca74

**Comment by ikeyan** [comment]
@matus-sabo that's cool, but it's UUID, not ULID.

**Comment by pksunkara** [comment]
I am the author of https://github.com/pksunkara/pgx_ulid  and I would be willing to implement this. @janpio and prima people, do I have the go-ahead?

**Comment by janpio** [comment]
What exactly is even needed here if there is a PostgreSQL extension?
Is https://www.prisma.io/docs/concepts/components/prisma-schema/postgresql-extensions not enough?

**Comment by pksunkara** [comment]
But `@db.Ulid` is not supported in the schema types though?

**Comment by janpio** [comment]
Ah, I see that the extension also adds a new `ulid` type in PostgreSQL, additionally to the function to create one?
Can a generated value only be stored in such a `ulid` column, or also as a normal text string?

Currently Prisma does not offer a way for extensions to add native types.

**Comment by pksunkara** [comment]
> Can a generated value only be stored in such a ulid column, or also as a normal text string?

Yes, a generated value can only be stored in such an `ulid` column. It is visible to end-users as a string, but internally it's stored in a much more compact format which is why a new type was necessary.

> Currently Prisma does not offer a way for extensions to add native types.

Yup, which is why I was offering to create a native type `Ulid` in Prisma query engine. All I need is a pointer to the specific part of the code.

**Comment by pksunkara** [comment]
I guess the only way to solve this would be use a custom type as specified in #5039? But there's nothing happening on that.

**Comment by pksunkara** [comment]
It is actually stored in the same format, but since it needs to be read differently, that is why a new type is needed.

**Comment by Falmarri** [comment]
Are ULIDs still needed now that v7 UUIDs are coming into the spec? Should probably just use that.

**Comment by kibertoad** [comment]
I'm linking https://github.com/prisma/prisma/issues/24079 here, as it aims to address the same problem in a slightly different way.

**Comment by JoaoVitorLima242** [comment]
Please, add support for that!

**Comment by pksunkara** [comment]
I think this needs to be reopened because what was added is support for generating ulids only and not an ulid type in schema.

```
  id    String @id @default(ulid())
```

But if you are using the [`ulid`](https://github.com/pksunkara/pgx_ulid) postgres extension, it providers an `ulid` type and the generator function is named `gen_ulid()`.

So, for db schema:

```sql
CREATE TABLE users (
  id ulid NOT NULL DEFAULT gen_ulid() PRIMARY KEY,
);
```

The `schema.prisma `that is generated doesn't work:

```
/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by Prisma Client.
model users {
  id          Unsupported("ulid") @id @default(dbgenerated("gen_ulid()"))

  @@ignore
}
```

So, this issue hasn't been solved since the original ask was to add support `ulid` type itself, not just generation.

**Comment by kawinie** [comment]
We should reopen this issue
