### ISSUE TITLE
use `count` and execute SQL count(*) return value type is different

### ISSUE THREAD

**Issue by apprat** [prisma/prisma#13723]
### Bug description

After enabling improvedQueryRaw, the database can correctly return the bigint type, but using prisma.model.count() is still the number type. Is this a bug?

### How to reproduce

```typescript
const [{ count }] = await Database.$queryRawUnsafe(`select count(*) from "user"`) as { count: any }[]
console.log(typeof count)
const count2 = await Database.user.count()
console.log(typeof count2)
```
>out: bigint number

### Expected behavior

Either unify as number or unify as bigint

### Environment & setup

- OS:  Windows
- Database: PostgreSQL
- Node.js version: 17.1

### Prisma Version

```
prisma                  : 3.15.0
@prisma/client          : 3.15.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules\.pnpm\@prisma+engines@3.15.0-29.b9297dc3a59307060c1c39d7e4f5765066f38372\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules\.pnpm\@prisma+engines@3.15.0-29.b9297dc3a59307060c1c39d7e4f5765066f38372\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules\.pnpm\@prisma+engines@3.15.0-29.b9297dc3a59307060c1c39d7e4f5765066f38372\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules\.pnpm\@prisma+engines@3.15.0-29.b9297dc3a59307060c1c39d7e4f5765066f38372\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : b9297dc3a59307060c1c39d7e4f5765066f38372
Studio                  : 0.462.0
Preview Features        : interactiveTransactions, fullTextSearch, improvedQueryRaw
```

**Comment by jkomyno** [comment]
Hi, could you please paste the text of your Prisma schema here?

**Comment by apprat** [comment]
> Hi, could you please paste the text of your Prisma schema here?

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions", "fullTextSearch", "improvedQueryRaw"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model file {
  id                                           BigInt                @id @default(autoincrement())
  hash                                         String                @unique @db.VarChar(255)
  mimeType                                     String                @db.VarChar(255)
  size                                         BigInt
  createTime                                   DateTime              @default(now()) @db.Timestamp(6)
  metadata                                     Json?
  ext                                          String                @db.VarChar(255)
  @@index([hash])
}

model user {
  id                                            BigInt                  @id @default(autoincrement())
  name                                          String?                 @unique @db.VarChar(32)
  gender                                        Int                     @default(0) @db.SmallInt
  password                                      String?                 @db.VarChar(255)
  createTime                                    DateTime                @default(now()) @db.Timestamp(6)
}
```

**Comment by janpio** [comment]
You are expecting a BigInt because you have more than max Int `user`s in that database?

**Comment by janpio** [comment]
That is tree - if the column can take max BigInt entries, this would be a problem with this type. We possibly should take this into consideration.

**Comment by aqrln** [comment]
Although it is somewhat confusing, I don't believe it's a bug.

The `count()` method always returns a JavaScript number — that is a part of the API contract. It hasn't been changed because there was no reason to change it intentionally, and doing that would have been a big breaking change.

As for the `$queryRaw`, there was a bug where some values were converted to wrong type and information was lost. Now (first under the `improvedQueryRaw` feature flag and then in GA since Prisma 4.0.0) we try to always return the _actual_ data type from the database, which fixed a big cluster of issues. Unfortunately this means that in some cases the results might look unintuitive since the actual data type is quite different from what might have been expected. We can't (and must not) change those types because we don't know the meaning of the raw query, so we just return data as they are. In this case, the database returns an int64, which is mapped to a bigint in JavaScript. You could get a different result depending on the database or its configuration.

I'm going to go ahead and close this issue. Please let us know if you think this was a mistake!

**Comment by janpio** [comment]
Does that not also meant that `count()` is broken for tables with more entries than MAXINT? That would deserve another feature request or improvement issue then to be fixed in some way, right?
