### ISSUE TITLE
Support supplying intended preview features to CLI commands

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#13757]
# Problem 

There are a bunch of commands that would benefit from being able to supply (or even override) the preview features array from the CLI.

The simplest example is `db pull` which you can run as `prisma db pull --url=...` for databases and connection strings. In Introspection-CI for example we use this to introspect a schema file just from a connection string (as it saves us having to create a minimal schema file to add the connection string to). This unfortunately does not work for connectors that require a preview feature to even allow Introspection of such a connection string (Recent examples were MongoDB and CockroachDB). There we implemented workarounds to have or create a minimal schema file that includes the preview feature, so that the command then will work.

This also applies to other commands like `db push` or `migrate dev`.

# Solution

We could introduce a new CLI parameter (undocumented, for internal use) that allows setting the preview feature string via the CLI, similar to how `--url` or `--datasource-provider` (for `init`) works. The paramter could be `--previewFeaturesList=x,y` which would then be translated to `previewFeatures = ["x", "y"]` in the resulting schema.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
