### ISSUE TITLE
Intermittent P1001 - "Can't reach database server..."

### ISSUE THREAD

**Issue by r1si** [prisma/prisma#13770]
### Bug description

While my app is running, I occasionally see logs for error P1001. The app continues to function and has access to the database for subsequent requests.

### How to reproduce

This seems to be random, but seems to occur most often when the app is under load and has multiple connections to the database.
The problem occurs on localhost DB and remote

### Expected behavior

I'd like this error to provide more information. It is a strange error to receive while your app is actively connected to the database.

### Environment & setup

- OS: Windows/Linux
- Database: 10.6.7-MariaDB
- Node.js version: 16

### Prisma Version

```
Connector: MySQL/MariaDB
Prisma 3.15.1
```

**Comment by r1si** [comment]
as UPDATE: On mysql Stats i have a lot of Aborted clients (about 17 k in some hours)

**Comment by r1si** [comment]
from mysql log here the problem (on localhost not remote connection) 
`2022-06-14 12:09:56 2802 [Warning] Aborted connection 2802 to db: 'DB_NAME' user: 'DB_USER' host: 'localhost' (Got an error reading communication packets)`

I have a lot of line like this.... 
DB_NAME and DB_USER is only a placeholder (with user that use node)

On same server run another PHP app that use this DB with no problem....

**Comment by r1si** [comment]
@jkomyno Hi Alberto, do you have any specific tests to recommend ? so I can give you more information about the problem.

**Comment by r1si** [comment]
From further tests I conducted: 
The problem occurs mainly (I am not sure to say "only") if I launch a node script multiple times sharing the same prisma installation.
Can this be a problem?

**Comment by Janushan** [comment]
I experience the same issue
Seems to be when there's a high amount of read / writes (100,000s) in the running operation

**Comment by Janushan** [comment]
Is this related to this issue - https://github.com/prisma/prisma/issues/13306

**Comment by rflorence** [comment]
I'm experiencing the same problem using Prisma 4.2.1 with AWS Lamba and RDS Postgres. A few times a day, we will get an error that it can't reach our database, but nothing in the RDS metrics indicate that the database is doing anything unusual.

**Comment by averyyip** [comment]
Likewise, running into the same issue here. Looks like it is happening when the DB is under load (lots of reads)

**Comment by r1si** [comment]
Personally, I gave up using prisma because of this bug. 
Too unstable for enterprise use.

I also don't understand why after months no one has considered this

**Comment by FredLackeyOfficial** [comment]
Happens constantly on the first request for any Node service.  The first request fails every time.  Running the same code a second time, without restarting, it works perfectly.  This is on a 32GB MacBook Pro M1 running the following:

@prisma/client : 4.4.0
prisma 4.4.0
node 16.17.0
macos 16.6
docker 20.10.17, build 100c701
docker compose 2.10.2

Have not looked into it, but it almost feels like the PrismaClient is using some type of singleton pattern and throwing the error prior to some underlying piece initializing.  That could explain why subsequent calls succeed.

**Comment by jkomyno** [comment]
Hi @FredLackeyOfficial, would you please be able to share a minimal project that allows us to reproduce the issue you're describing? Knowing how to exactly trigger this bug would allow us to dig deeper in search for a solution. Thanks

**Comment by janpio** [comment]
Please open a new issue if you are still experiencing this, and provide as much informaion as possible for us to reproduce the problem. Thanks!

**Comment by caleblawrence** [comment]
I work with @rflorence who commented a while back saying we were running into this error.

We solved this by upgrading our database to a bigger instance. The free memory it has was very low because we were running on a `t3.micro` instance. Hope that might help anyone else who has run into this issue. The specific metric is "freeable memory" which was very low and it led to random disconnections.

**Comment by capaj** [comment]
This is still an issue. We're running into this on CI, our dev and prod.

Here's a sample stack trace:
```
Invalid `prismaClient.favorites.create()` invocation in
/home/runner/work/official-graphql/official-graphql/graphql/test/_fixtures/favorite-fixture.ts:24:42

  21     longitude: string | null
  22   }
  23 > => {
→ 24   const f = await prismaClient.favorites.create(
Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
 ❯ test/_fixtures/favorite-fixture.ts:24:42
     22|   }
     23| > => {
     24|   const f = await prismaClient.favorites.create({
       |                                          ^
     25|     // @ts-expect-error
     26|     data: fields
 ❯ Zr.handleRequestError node_modules/@prisma/client/runtime/library.js:171:6414
 ❯ Zr.handleAndLogRequestError node_modules/@prisma/client/runtime/library.js:171:5948
 ❯ Zr.request node_modules/@prisma/client/runtime/library.js:171:5786
 ❯ t._request node_modules/@prisma/client/runtime/library.js:174:10455
 ❯ Module.generateFavoriteFixture test/_fixtures/favorite-fixture.ts:24:13
 ❯ Module.generateMatchFixture test/_fixtures/generateMatchFixture.ts:25:21
 ❯ generateMatchFixturesForAllTypes src/resolvers/Relationship.resolver.fn1.spec.ts:304:15

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "batchRequestIdx": undefined,
  "clientVersion": "4.11.0",
  "code": "P1001",
  "meta": {
    "database_host": "localhost",
    "database_port": 5[432](https://github.com/official-love-guru/official-graphql/actions/runs/4346412281/jobs/7592438006#step:9:433),
  },
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 67 passed | 6 skipped (74)
      Tests  369 passed | 5 skipped | 53 todo ([453](https://github.com/official-love-guru/official-graphql/actions/runs/4346412281/jobs/7592438006#step:9:454))
   Start at  17:57:26
   Duration  512.53s (transform 4.99s, setup 22.52s, collect 278.13s, tests 1010.76s)
```

We have pool_timeout=0 so it should never time out on connection.
There is something rotten in the prisma connection pooling implementation.

**Comment by aravind605** [comment]
● Test suite failed to run

    Can't reach database server at `localhost`:`5432`

    Please make sure your database server is running at `localhost`:`5432`.

      at startFn (node_modules/@prisma/client/runtime/library.js:101:2598)

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  CustomGC

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:985:29)
      at load (node_modules/@prisma/client/runtime/library.js:73:326)
      at node_modules/@prisma/client/runtime/library.js:73:759
      at runInChildSpan (node_modules/@prisma/client/runtime/library.js:70:25817)
      at Fr.loadLibrary (node_modules/@prisma/client/runtime/library.js:73:677)
      at Vt.loadEngine (node_modules/@prisma/client/runtime/library.js:101:557)
      at Vt.instantiateLibrary (node_modules/@prisma/client/runtime/library.js:100:1478)
      at Vt.start (node_modules/@prisma/client/runtime/library.js:101:2081)


In my case individual tests run fine but test suite fails at the end.

**Comment by janpio** [comment]
If you still have a problem, open a new issue and provide all the information the template asks for. Thanks.

**Comment by Arlen22** [comment]
It was happening for me with Aurora Posgresql Serverless v2 with a 0.5-2 ACU and Prisma 5.12 on an EC2 instance, and explicitly called $disconnect on the PrismaClient after 5 seconds of inactivity. The PrismaClient was being created fresh usually because the auth is short-lived. I was not calling $connect first.

I upgraded to 5.22 and set it to call $connect first, and so far it seems like this has fixed it. It keeps calling $connect until it doesn't throw, but so far the first call has always been successful. I don't know for sure which of those fixed it.

**Comment by YuzuruS** [comment]
We hit this exact symptom in production (Prisma 6.19.2, ECS Fargate, RDS SQL Server) and managed to correlate it end-to-end — application logs at millisecond precision against the database server's own diagnostics (RDS `system_health` Extended Events), so posting the mechanism here for future travelers, since "unable to reproduce" was what closed this issue.

**What the correlated traces show:**

```
02:04:10.130  last normal request
   (≈7s of silence)
02:04:16.6    DB side: burst of login-path security_error events
              (server processing our fresh connection attempts, slowly)
02:04:17.130  P1001  ┐
02:04:17.154  P1001  ├ 3 requests, ~100ms window
02:04:17.231  P1001  ┘
02:04:17.426  fully recovered
```

Two stacked mechanisms, both specific to long-running processes (which is why serverless setups rarely see it and why it resists reproduction):

1. **Cold pool after quiet hours.** quaint's default `max_idle_connection_lifetime` is 300s, so after a traffic lull every pooled connection is evicted at the next checkout and each incoming request pays for a fresh connect (TCP + TLS + login). If the server happens to process login slowly at that moment (our DB demonstrably did — see the security_error burst), the default 5s `connect_timeout` expires and Prisma reports `P1001` even though the server is reachable. The message "Please make sure your database server is running" is misleading in this case.
2. **Stale idle reuse.** An idle connection severed by a middlebox (e.g. AWS NLB's 350s idle timeout) *before* eviction kicks in gets handed out dead, failing the first query on it with the same P1001/P1017 family.

**The frustrating part:** quaint already implements borrow-time health checks (`Builder::test_on_check_out` + `health_check_interval`, with `QuaintManager::check` doing a `SELECT 1`) — mobc transparently replaces a connection that fails the check, which directly addresses mechanism 2 — but no connector URL parser exposes these options, and Prisma only builds pools from the URL. The machinery exists and cannot be enabled.

Filed prisma/prisma#29786 with the full analysis, and opened prisma/prisma-engines#5846 exposing `test_on_check_out` / `health_check_interval` as connection-string parameters (opt-in, default off, same pattern as `max_connection_lifetime`). For mechanism 1, raising `connect_timeout` above the default 5s is the practical workaround today.
