### ISSUE TITLE
fetch-engine: download.test.ts should check hashes of all platforms 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#14120]
In this test

https://github.com/prisma/prisma/blob/131d75a2f3fd25fd3a22b1a57b599c7335aea9e6/packages/fetch-engine/src/__tests__/download.test.ts#L57-L94

The hashes are not checked for all platforms 

We should check the hashes for all platforms, since we just downloaded them there.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
