### ISSUE TITLE
NotFoundError not exported

### ISSUE THREAD

**Issue by PatrikValkovic** [prisma/prisma#14209]
### Bug description

When user uses `rejectOnNotFound` or `findFirstOrThrow`/`findUniqueOrThrow`, there is no way how to catch this exception specifically. Because Prisma doesn't export `NotFoundError`, user can't use `instance` operator and therefore can decide only based on the error message.

I believe the `NotFoundError` should be exported and therefore I set this up as a bug.

### How to reproduce

Run `prisma generate` and inspect the generated file.

### Expected behavior

There is `NotFoundError` exported, so the user can decide using check `error instanceof Prisma.NotFoundError`.

### Prisma information

No schema or queries are neccessary.

### Environment & setup

Is environment agnostic.

### Prisma Version

I tried prisma clients in versions `3.13.0`, `3.15.2` and `4.0.0`.

**Comment by janpio** [comment]
I think this was already fixed via https://github.com/prisma/prisma/pull/14076 Agree?
It should be available in the current `dev` version for testing, and later this month in Prisma 4.1.0.

**Comment by aqrln** [comment]
@bbenezech this sounds like a separate issue for me, is that right? If that's the case, could you please open a separate GitHub issue for this to avoid any confusion, and, most importantly, avoid your report being lost, since the issue @PatrikValkovic refers to has already been fixed, and someone might close it without looking at your comment.

**Comment by janpio** [comment]
@PatrikValkovic Can you confirm that the PR above solved your problem?

**Comment by miguelff** [comment]
@PatrikValkovic `NotFoundError` was an implementation detail when `findFirstOrThrow` and `findUniqueOrThrow` where _emulated_ on the client rather than implemented on the engine. [Since 4.6.0](https://github.com/prisma/prisma/pull/16162), the error became deprecated and converted to a `PrismaClientKnownRequestError`. If you needed to perform conditional checks on this type of error, you could rely on its error code. [The one for this error  is `"P2025"`](https://www.prisma.io/docs/reference/api-reference/error-reference#p2025).

```typescript
/**
 * @deprecated please don´t rely on type checks to this error anymore.
 * This will become a PrismaClientKnownRequestError with code P2025
 * in the future major version of the client
 */
export declare class NotFoundError extends PrismaClientKnownRequestError {
    constructor(message: string);
}
```
