### ISSUE TITLE
Specify the error that is thrown with findUniqueOrThrow and findFirstOrThrow

### ISSUE THREAD

**Issue by Doxmare** [prisma/prisma#14317]
## Problem

When findUniqueOrThrow or findFirstOrThrow don't find a valid record, RxJS's NotFoundError is thrown. This crashes the NodeJS server with NestJS. A custom interceptor is needed to catch the NotFoundError and throw something that is used by the project, e.g. NestJS's NotFoundException.

## Suggested solution

In PrismaClient constructor add notFoundException to optionsArg to specify which Exception is thrown with findUniqueOrThrow or findFirstOrThrow.

**Comment by SevInf** [comment]
Hi @Doxmare.
I think there is a misunderstanding, Prisma does not use RxJS. So, `NotFoundError` comes from Prisma, not from RxJS. Unfortunately, it's not exported in `4.0.0` but it will be fixed in `4.1.0` which is coming out on Tuesday, the 19th.

As for feature request for customizing the exception, we already [have an open request about that](https://github.com/prisma/prisma/issues/14091), so I am gonna close this one for now. Feel free to comment on #14091 if you want to add information for our consideration.
