### ISSUE TITLE
Mutation Concurrency

### ISSUE THREAD

**Issue by dsbert** [prisma/prisma#144]
I was not able to find any information on this in the documentation. How does graph cool handle mutation concurrency?

Are all mutations in a single request run under a transaction or is it possible for two clients to mutate the same objects at the same time?

**Comment by marktani** [comment]
If you're running two `updateModel` mutations from different clients on the same node, both will run after each other - depending on which reaches the API first, the outcome will be different.

Do you have a specific use case where you're concerned about this? This would make it easier to talk about this topic :slightly_smiling_face:

**Comment by kbrandwijk** [comment]
+1 for me. Being able to handle concurrency is crucial. Two clients, both with a local copy of an object, both updating that object, one overwriting the changes of the other. Standard solutions: retrieve, perform concurrency check (based on a field not updated in the client, like a version number or lastupdateat field), update within a transaction. However, doing this in a pre_write hook would only work if retrieving and updating would happen inside a transaction (which they don't). What might work is placing a write lock on the record at the start of the request pipeline, so we can safely do concurrency checking.

Alternatively, I think this could be solved using a permission query, becausing there you have $input_... and $node_... so you could actually check if the record is not updated in the meantime based on that field.

**Comment by kbrandwijk** [comment]
There are three ways of implementing this (well, at least the ones that I see):

- Allow system fields to be part of an update mutation, and use permission query to perform concurrency check manually (related to #236)

- Duplicate permission query functionality for concurrency queries, that way the client knows what caused the updated to fail (because in option 1 the failed concurrency check would come back as permission error)

- Make concurrency checking a first class citizen of the system. This would mean flagging which fields on a Type are involved with concurrency checking, and performing the check automatically, without the user having to write his own query for it. 

1. is easiest, 2. is most flexible, 3. is most user friendly

**Comment by dsbert** [comment]
I think this depends on #74.
