### ISSUE TITLE
Calling `dmmf` raises "Schema parsing - Error while interacting with query-engine-node-api library" misleading error message when there is a schema validation error.

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14588]
For instance, trying to use an invalid referential action prints the following error:

```text
Get DMMF: Schema parsing - Error while interacting with query-engine-node-api library
    Error code: P1012
    error: Error validating: Invalid referential action: `SetDefault`. Allowed values: (`Cascade`, `Restrict`, `NoAction`, `SetNull`)
```

t means that calling `NodeAPIQueryEngineLibrary.dmmf(datamodel)` had thrown an error which was successfully JSON-parsed. This is coherent with what was happening before the getConfig/getDmmf refactoring (https://github.com/prisma/prisma/blob/3.11.0/packages/sdk/src/engine-commands/getDmmf.ts#L58-L64).

In practice, such an error doesn't necessarily imply a schema parsing issue, so we should be able to disambiguate actual "Schema Parsing" errors vs these "Invalid Request" errors.

See internal discussion [here](https://www.notion.so/prismaio/Phase-1-Report-on-findings-f21c7bb079c5414296286973fdcd62c2#1b1afacfff5543979fe9bed951fa5a2b).

**Comment by jkomyno** [comment]
**Note**: `Error P1012` is considered a `SchemaParserError` according to the [Rust code](https://github.com/prisma/prisma-engines/blob/a3623c31d4eb22f2dccd198738b449488c9b55dd/libs/user-facing-errors/src/common.rs#L182-L186).

**Comment by Jolg42** [comment]
@jkomyno I recall that what @janpio reported in conversations on zoom which then got turned into this issue is that the following bit:
`- Error while interacting with query-engine-node-api library` is unexpected here.

It is indeed an error from `Schema parsing` but `- Error while interacting with query-engine-node-api library` makes us/the user think that there was an error about the communication with the `query-engine-node-api library`.
So here the communication with the engine works as expected and the message is misleading.
