### ISSUE TITLE
`findOne` optimization

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1470]
To [quote from an earlier `specs` issue](https://github.com/prisma/specs/issues/242#issuecomment-548382431):

> One of the main usecases of ~~Photon~~ Prisma Client is to use it inside a GraphQL server. The resolver system of a GraphQL server is prone to suffer from the N+1 problem. To mitigate this problem users can choose to implement the DataLoader pattern within the application server. This burdens our users with unnecessary work that is not related to their core domain. This issue explores how we could include a DataLoader implementation within ~~Photon~~ Prisma Client.

As a first step we want to look specifically into optimizing `findOne` queries by batching them.

**Comment by maartenraes** [comment]
For reference: 
We've been testing with photon/prisma-client quite a bit and we have following graphql query
```
    activities(where: $where) {
      id
      name
      maxParticipants
      abbreviation
      activityType {
        name
      }
      price
      lessons(orderBy: {start: ASC}) {
        start 
        end
        classroom { 
          location {
            name
          }
        }
      }
      registrations { 
        id
      }
    }
  }
```
After some timing references we found out that for this gql it takes 3sec to fetch only 10 entries of this entity, which seems rather long. 

After some more investigation indeed the N+1 problem is present in the current library, but even with the N+1 solved database queries seem to take +- 40ms, which is still kinda slow. Is this also caused by the N+1 problem or is this just Prisma Client doing things that we cant see?

**Comment by mavilein** [comment]
Hey @maartenraes 👋 ,

you said: 
> but even with the N+1 solved database queries seem to take +- 40ms

How did you solve the N+1 problem?

Generally your query could we slow for several reasons:
1. What kind of `where` are you using at the top level? Maybe it's an expensive filter that requires a table scan in the database.
2. Maybe your `activities` table has a lot of entries. (So scanning would be more expensive)
3. Maybe your database is missing indexes that are needed for quick relation traversal. Did you use `prisma migrate` to setup your schema? Then those indexes are missing for sure since we currently do not add them by default.
4. Be aware that this query seems to require joins between at least 6 tables. This is quite heavy.

Having said that your stated query time of 3 seconds still seems slow to me. My hunch is that the N+1 problem and missing indexes are the big problems here.

Sorry for responding with such an open ended comment but performance is complicted 🙂 . But we really need more details on the parts involved to say something more accurate. Happy to give more feedback once you provide more details 🙏

**Comment by maartenraes** [comment]
@mavilein
We didn't really solve it, we just added timings just before and just after resolvers to see how fast queries were resolved. 

1. Doing all saved up queries in one go (what batching would look like) manually in Postgres takes about 16ms, with the exact where on the toplevel. So I don't think that's the issue.
2. Activities doesn't have that many entries, during our tests about 40. So even if Postgres would be scanning it shouldn't take that long.
3. We have put indexes on all foreign keysrelations that matter to activities

**Comment by timsuchanek** [comment]
Yes! And another question I have for you @maartenraes, what is the distance between database and backend where you have Prisma Client running? That is one of the biggest factors when it comes to performance.

**Comment by maartenraes** [comment]
@timsuchanek I've updated my comment, accidentally saved the comment but wasn't done writing it

**Comment by timsuchanek** [comment]
@maartenraes you're too fast for me :D Thanks for the answer!
The `lessons` and `registrations` resolvers, can you show the Prisma Client calls that you're making there? Is it `findOne` or `findMany`?

**Comment by maartenraes** [comment]
@timsuchanek Both are `findMany` but every classroom within a lesson is also fetch with a `findOne ` I suppose. Deduping would also help a lot in this case since most lessons of a singular activity are always in the same classroom, so that would spare like 10 queries for each activity. 

Let take 10 activities, with 10 lessons, same classroom, 10 registrations. This would then be (with N+1) 
1 activityQuery + 10 lessonsQueries + 10 classroomqueries + 10 registrationQueries + 10 activityTypeQueries + 1 activityTypeQuery = 32 queries

And this is only for 10 activities, which isn't that much. Even with paged tables 50-100 is a frequent pagesize.

**Comment by martonlanga** [comment]
Hey @maartenraes, how did you add foreign keys manually? I'm trying to add them as well, to see how much faster the queries run.

**Comment by timsuchanek** [comment]
Thanks @maartenraes! We'll also tackle optimizing multiple `findMany` calls in the future, however that's a separate issue that is being tracked here: https://github.com/prisma/prisma2/issues/1477

Feel free to comment there with your use-case if you want to add anything :)

**Comment by divyenduz** [comment]
Internal note: dropping from current sprint

**Comment by mavilein** [comment]
**Plan:**
1. do protocol change to allow batches
2. write load tests that send a batch of `findOne` with the new protocol
3. implement optimization in the query engine (probably as a protocol adapter)
4. verify improvements and write small memo about it

**Comment by pimeys** [comment]
Memo: unsurprisingly faster with optimization.
![batch](https://user-images.githubusercontent.com/34967/74955310-5fa90d80-53fc-11ea-9f8e-ffae37e177ad.png)
Green: batching without optimization
Purple: with optimization

Tested three queries in batches of 100, `$user_id` randomized from 1 to 3000. 3000 users, 30000 posts and 30000 comments.

```graphql
query NoJoin {
  findOneUser(where: { id: $user_id }) {
    firstName
    lastName
  }
}
```
```graphql
query OneJoin {
  findOneUser(where: { id: $user_id }) {
    firstName
    lastName
    posts {
      content
    }
  }
}
```
```graphql
query TwoJoins {
  findOneUser(where: { id: $user_id }) {
    firstName
    lastName
    posts {
      content
      comments {
        content
      }
    }
  }
}
```

**Comment by pimeys** [comment]
Backend (engines) merged to master today.

**Comment by janpio** [comment]
Status: Engine work is done (see above), now Prisma Client work is left: https://github.com/prisma/prisma-client-js/issues/523

**Comment by timsuchanek** [comment]
Note: Also improve debug logging around this.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by cunisia** [comment]
Shouldn't we update the [Query optimization
 article](https://github.com/prisma/docs/blob/main/content/300-guides/100-performance-and-optimization/085-query-optimization-performance.mdx) so that users know `findFirst` are also batched when occurring in the same tick and having the same `where` and `include` parameters ?

**Comment by janpio** [comment]
Can you open an issue over at https://github.com/prisma/docs? Include a link to this issue here of course.

**Comment by cunisia** [comment]
Sure it's done [here](https://github.com/prisma/docs/issues/2523)

**Comment by enioxt** [comment]
Hi Prisma team! Sharing a common mitigation pattern for GraphQL + Prisma:

**Problem:**
GraphQL resolvers tend to cause N+1 patterns when calling `findUnique/findFirst` per parent row (especially nested fields).

**Mitigation patterns:**
- Use DataLoader (or equivalent) to batch lookups by ID.
- For lists, collect IDs and use `findMany({ where: { id: { in: [...] } } })` + map.
- For nested relations, prefer a single batched query per relation type rather than per parent.

**Expected benefits:**
- Collapses 1 + N into ~2–3 queries, reducing latency and DB load significantly on large lists.

**If useful, I can contribute:**
- A short guide or example for Prisma + GraphQL (e.g., DataLoader-based batching for resolvers)
- Micro-benchmarks showing the tradeoffs
- Documentation improvements for common N+1 scenarios

---
**Context:** We recently optimized a similar pattern achieving 67x query reduction (activepieces/activepieces#9744) using systematic batch loading.
