### ISSUE TITLE
CLI: `migrate status` should return a non-successful exit code (1) when a failed migration is found or an error occurs

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#14860]
### Bug description

From https://github.com/prisma/prisma/issues/12349

`migrate status` returns a successful exit code (0) in unexpected situations like
    when a failed migration is found
    P1000: Authentication failed against database server at localhost

### How to reproduce

- when a failed migration is found
```
npx prisma migrate --create-only
# edit the .sql file and add "BROKEN"
npx prisma migrate deploy
npx prisma migrate status
```

- P1000: Authentication failed against database server at localhost
```
# edit .env and change the username or password to an incorrect one
npx prisma migrate status
```

### Expected behavior

It should return a non-successful exit code -> 1

### Prisma Version

```
4.3.0-dev.27
```

**Comment by Jolg42** [comment]
It will now exit(1) = error in these cases

    if database connection error
    If databaseIsBehind (= unapplied migrations)
    If historiesDiverge (= migration history diverged)
    If we can't find a migration table (= not managed by Prisma)
    If failed migration(s) are found

**Comment by Jolg42** [comment]
It's now in our internal dev version `4.3.0-dev.56` and up, and will be part of the 4.3.0 release.

**Comment by jacobchrismarsh** [comment]
Replying to [this comment from the linked PR](https://github.com/prisma/prisma/pull/14866/files#r950184741)

> If `databaseIsBehind` = unapplied migrations -> exit(1)


The other instances of errors make sense, but does this one? I'm not sure that unapplied migrations are error-worthy.

I only bring this up because my team used `prisma migrate status` as a part of our build process to list all unapplied migrations and then apply them. This change broke our pipeline by introducing a new error.
