### ISSUE TITLE
Expose `Debug` in `Prisma` namespace

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#15021]
Before https://github.com/prisma/prisma/pull/14537 it wasn't possible to enable `DEBUG` logs in the edge client when not running in Node.js.

Now we made the edge client read the injected `DEBUG` env var on initialization in the environments where it is possible, but there are still cases where it won't get picked up — namely, CFW Module Workers, since there are no globally scoped env vars.

One can pass 

```ts
__internal: {
  debug: true
}
```

to the arguments of `PrismaClient` constructor to enable logs for `prisma:client` there, but it's not a part of the public API, and there's no way to enable other debug logs.

**Suggested solution:**

Expose `Debug` in `Prisma` namespace to make the following possible:

```ts
Prisma.Debug.enable('prisma:*')
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
