### ISSUE TITLE
[Introspection] @map error resolving logic

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1520]
There are multiple Introspection bugs that are caused because of problems with `@map`:

- https://github.com/prisma/prisma2/issues/1499 - 2 fields are `@map`-ped to the same string
- https://github.com/prisma/prisma2/issues/1502 - numbers only fields are `@map`-ped to empty string
- https://github.com/prisma/prisma2/issues/1504 - a table is `@map`-ped to a name that alreadx exists

All these are because the `@map` logic currently look at what is happening around it, and has no logic how to avoid duplications or cases like empty string at all.

We need some logic on how `@map` should decide what to do in these cases.

---

Naive suggestions:
- Add `_x` where `x` is the smaller possible number
- Names with only numbers are replaced with english representations of these numbers

**Comment by sorenbs** [comment]
I would like to avoid introducing weird naming schemes. Instead I would like for us to detect that there is a conflict, and comment out the offending field or model.

I understand that this will cause ripple effects, where the relations to a commented-out model will have to be commented out. I accept this implementation complexity, as we need to be able to do this no matter what, because this is our guard-rail concept.

**Comment by janpio** [comment]
We will need to investigate what this could look like:
https://github.com/prisma/prisma2/issues/1523

**Comment by janpio** [comment]
This is now handled well enough.
