### ISSUE TITLE
Add support for PlanetScale serverless driver

### ISSUE THREAD

**Issue by twnlink** [prisma/prisma#15265]
## Problem
PlanetScale offers a [serverless driver](https://github.com/planetscale/database-js) for environments like Cloudflare Workers and Deno Deploy, but Prisma does not have support for it.

## Suggested solution
Adding a PlanetScale serverless driver to Prisma would solve this problem. I don't know the internals of Prisma, but PlanetScale's serverless driver is MySQL-compatible, just over HTTP. I imagine one could potentially reuse code from Prisma's existing MySQL driver to achieve this.

## Alternatives
You could use the Prisma Data Proxy with PlanetScale, but it's an additional layer to jump through and adds an additional service to worry about.

**Comment by tavindev** [comment]
Yes!! This would be a very appreciated feature.

**Comment by tavindev** [comment]
I made a PlanetScaleDriverEngine on my forked repo. I don't know if it is actually right and I have no idea how to test it tbh. I just looked at the DataProxyEngine and made this one. Not sure if it's of any help, but here's the link.

https://github.com/tavindev/prisma/commit/a000fc8d14792c16b0b179a8e5d5fbdd37b8c7c6

**Comment by mattrobenolt** [comment]
:wave: Hello, from PlanetScale here. I'd be happy to help in any way I can to make this happen.

**Comment by essarn** [comment]
When this is the done we have the ultimate solution to databases and computing. Prisma with PlanetScale running on Workers ❤️

**Comment by essarn** [comment]
Any update on this? Seems pretty straightforward but looking forward to it nonetheless.

**Comment by MaxBittker** [comment]
What is the advantage of the PlanetScale serverless driver that we could expect, over the current connection method? Faster connection establishing protocol?

**Comment by Cr3atable** [comment]
> What is the advantage of the PlanetScale serverless driver that we could expect, over the current connection method? Faster connection establishing protocol?

If you're using PlanetScale in a serverless environment then it should be faster than using PlanetScale + Prisma Data Proxy because the PlanetScale serverless driver is closer to PlanetScale. It'd also be cheaper given you would only have to pay for one service.

**Comment by MaxBittker** [comment]
What about over Prisma + connection URL (to a Planetscale DB URL), with no Prisma Data Proxy?

**Comment by Cr3atable** [comment]
> What about over Prisma + connection URL (to a Planetscale DB URL), with no Prisma Data Proxy?

This is not possible in multiple serverless environments, including Cloudflare Workers and Vercel Edge Functions.

**Comment by MaxBittker** [comment]
I see, thank you. 
I didn't realize the difference between Vercel Serverless Functions and Vercel Edge Functions.
Sorry to derail the important issue!

**Comment by tavindev** [comment]
Will this be added to the roadmap at some point?

**Comment by agcty** [comment]
Ok, so been thinking about how to pull this connector off.

Essentially, PlanetScale's HTTP API handles routing caching, pooling and everything else automatically. (https://planetscale.com/blog/introducing-the-planetscale-serverless-driver-for-javascript). This means there is no need for a data proxy in between.

From planetscale's examples, you simply need to send an SQL query to their endpoint:

```js
import { connect } from '@planetscale/database'

const config = {
  host: '<host>',
  username: '<user>',
  password: '<password>'
}

conn.execute('SELECT * FROM users WHERE email=?', ['foo@example.com'])
```

Because connecting to the database, etc. is handled by planetscale, you don't need a very complex query engine that does all of that. 

Instead, the query engine/connector would just need to translate a query from @prisma/client to SQL and use the fetch API. 

However, as @janpio pointed out here (https://github.com/prisma/prisma/discussions/16310), it seems like the overall architecture of prisma might make such a connector not a straight-forward thing to build. I assume this is because query engines act as GraphQL servers among other things and it's hard getting all of these moving parts to work in a serverless / non-node environment.

Anyway, what we'd need for a connector like this is to simply translate the query from @prisma/client to SQL. As simple as it sounds, I think it is a little harder than one might think but definitely possible.

Seems like @prisma/client runs a gql query against the engine which handles forming an SQL statement, connections etc. Best shot imo would be to not mess with the GraphQL part (as long as this can run serverless) and make a connector that just does http requests?

Would be cool if the client could just return a fully formed SQL statement without the engine, but that is I guess what the engine is purpose-built for, knowing about which database you use etc.

**Comment by janpio** [comment]
Spot on analysis @agcty. Of course, Prisma can develop in a direction where all this is possible, but it will take some time (and you might be aware of all the other things we need to work on in the meantime as well)

**Comment by jferrettiboke** [comment]
I'm very interested in this topic as well in this Edge-first era we live in.

As @agcty very well described, it would be enough for us if Prisma could form the SQL statement somehow so that we can use it and forward it to PlanetScale.

PlanetScale and Prisma should partner to make this happen. It would be a win-win for everyone!

**Comment by jferrettiboke** [comment]
FYI, in the meantime, developers can use [Kysely](https://github.com/koskimas/kysely).

Kysely is a very nice solution that works on the Edge. Its adoption among developers who are excited about an Edge-first approach is increasing rapidly. Kysely also has support for the PlanetScale serverless driver, [`kysely-planetscale`](https://github.com/depot/kysely-planetscale).

Being said this, I believe Prisma delivers a better DX than Kysely. But Prisma doesn't work with PlanetScale serverless driver, and Kysely does. 😃 I hope to see Prisma bringing support for the PlanetScale serverless driver in the near future. 🙏🫶

I'd be more than happy to contribute to this but based on past experiences, it's kinda hard to contribute to Prisma at this level. Not imposible though if we plan properly! But first, I guess Prisma internal teams must set goals and strategies to make a plan.

**Comment by davidthomasparks** [comment]
Just popping in to +1 this issue. I've used Kysely in the meantime in edge environments, but the DX from Prisma is miles ahead imo. This would be amazing!

**Comment by rodbs** [comment]
Not sure if this is related to the fact of making Prisma client work with Cloudflare Workers (Fetch API). It'll highly appreciated it!

**Comment by arguiot** [comment]
Also, I believe that Prisma could be able to work even without the driver if it's tweaked a bit. In the docs, they say that Prisma Client won't work on Cloudflare Workers because it doesn't support TCP.

But this isn't the case anymore (https://blog.cloudflare.com/introducing-socket-workers/) and I'm sure there is a way to make Prisma support that.

**Comment by janpio** [comment]
> But this isn't the case anymore ([blog.cloudflare.com/introducing-socket-workers](https://blog.cloudflare.com/introducing-socket-workers/)) and I'm sure there is a way to make Prisma support that.

As far as we know unfortunately not usable in our Rust based Engines as this modifies the Javascript internals of `fetch` an related to achieve this.

**Comment by arguiot** [comment]
Ok, but then, would that not be easier to make the engine query PlanetScale directly through HTTP (the same way the server less driver works)?

Like if you have some guidance on how the internals work, I'm sure that me or someone could open a PR on the engine to make that happen.

Currently, Prisma works this way:

![](https://www.prisma.io/docs/static/5023a684d8dfe7c5a41ca7f532a5b440/42cbc/typical-flow-query-engine-at-runtime.png)

If, instead of setting `mysql` as the provider in the `.schema` file, but `planetscale`, the engine would just query the database using HTTP. Then, we would just be able to run the Rust engine on the edge using WASM.

I know Prisma wants as much people to pay for the Data Platform, and so this is not the top priority. But because of this, requests are slower. But @janpio, honestly, if you guys make the edge-native `planetscale` engine  that described paid, I would pay for it and other people would as well I think.

**Comment by janpio** [comment]
This has nothing to do with our Data Platform, believe me. The platform would also benefit from being able to talk to PlanetScale Serverless. Instead, it has to do with this not being as simple but requiring product design and significant implementation, and us having other priorities right now. If it were simple, and we had nothing else to do, we would have already prioritized and implemented it.

**Comment by jferrettiboke** [comment]
> As far as we know unfortunately not usable in our Rust based Engines as this modifies the Javascript internals of fetch an related to achieve this.

Vercel supports WebAssembly in Vercel Edge Functions at least, so it’s possible to compile and run Vercel Edge Functions with languages like Rust, Go, C, etc. https://vercel.com/blog/introducing-support-for-webassembly-at-the-edge

My question is, what would it be needed in order to make Prisma edge-compatible with Vercel then? 🤔

**Comment by janpio** [comment]
Vercel supporting Webassembly is nice but irrelevant, as that is now how our architecture works right now.

We need to prioritize this work and do it in the way that is required to make the PlanetScale serverless driver work in Prisma ORM. See my previous messages in this thread.

**Comment by michealroberts** [comment]
I'd appreciate the work if we can get our planetscale database to work within the Vercel edge runtime.

**Comment by Izhaki** [comment]
A note from an OoD (out-of-depth) person.

Like others, really disappointed that the prisma client does not support vercel edge functions, specifically as it is such a high-quality product. But I can only guess supporting this won't be a great deal of work.

Fundamentally, the client has two separate concerns:

## Convert - the prisma client API to SQL queries

If we lunch the client with `{log: ['query']}`, we can already see the SQL queries on stdout. So clearly there is some boundary for these.

## Connect

I guess it made sense to assume MySql connections, but this assumption no longer hold - more and more people need, and products support, edge limited runtime.

Evidently, something very similar was done with `@prisma/client/edge`, only that currently it is locked to Prisma's Data Proxy. This is redundant effort to PlanetScale's Javascript client (which supports edge functions), and hits some connection pool via HTTPS.

# Proposed Solution

So I can imagine something like this:

```ts
import { connect } from "@planetscale/database";
import { PrismaClient } from '@prisma/client/edge';

const config = {
  host: "aws.connect.psdb.cloud",
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
};

const connection = await connect(config);

export const prisma =
  new PrismaClient({
    fetcher: (query: string) => connection.execute(query),
  });
```

## A Better Future?

Although a huge breaking change, if the API employ high-level of composition, I can see future versions working like this:

```ts
import { PrismaClient } from '@prisma/client';
// Then either:
import { connect } from '@prisma/client/mysql';      // Current default mysql connection - no edge support
import { connect } from '@prisma/client/edge';       // General
import { connect } from '@prisma/client/data-proxy'; // Prisma's data-proxy

const connection = connect({ options});

const prisma = new PrismaClient({connection});
```

**Comment by james-elicx** [comment]
> Like others, really disappointed that the prisma client does not support vercel edge functions, specifically as it is such a high-quality product. But I can only guess supporting this won't be a great deal of work.
>
> ## Convert - the prisma client API to SQL queries
> If we lunch the client with `{log: ['query']}`, we can already see the SQL queries on stdout. So clearly there is some boundary for these.
> 
> ## Connect
> Evidently, something very similar was done with `@prisma/client/edge`, only that currently it is locked to Prisma's Data Proxy. This is redundant effort to PlanetScale's Javascript client (which supports edge functions), and hits some connection pool via HTTPS.

@Izhaki  Did you read this thread before commenting? You seem to have completely glossed over Prisma's architecture, specifically the fact that the Prisma Client depends on the Query Engine to transform the input into SQL statements. Whereas, your reply operates under the assumption that the Client can transform the input into SQL itself. It is this very reason that makes implementing something like the PlanetScale serverless driver incredibly challenging and a multi-month project, as, from the sounds of things, you would need to change some of the core architectural designs.

This is why to use Prisma on the edge runtime you have to go through the data proxy, otherwise, you wouldn't be able to interface with the query engine.

**Comment by Izhaki** [comment]
Yeah, sorry but I completely glanced over the rest of this thread (lots too read, little time), but now having properly gone through it, I see most of what I've proposed have already been discussed.

I still have one thought to share, and this (again) could be me not fully understanding how Prisma Client works in complex situations. Yet there goes it:

Queries as follows:

```js
  const posts = await prisma.post.findMany({
    where: {
      published: true,
    },
  })
```

- Return an SQL statement (as we can see with {log: ['query']})
- Require Node Runtime
- Require knowledge of the Query Engine

As a developer, I can look at the SQL queries produced and reverse engineer them into an "Execution Plan" - essentially parameterised SQL queries (so `published: true` will be a parameter; this is same as [Planet Scale Boost](https://planetscale.com/features/boost) or what Neo4J does by default).

So in theory, in the same way we run `prisma generate`, we could have `prisma plan` - which takes all the possible queries (say, using some JS file that exports them all), and produces parameterised SQL Queries. These can be then used on Edge functions. 

- I don't know if it is possible to covert the prisma client API to parameterised SQL queries that way, but seems like less effort than the current proposal. 
- Even if we could just `console.log` these SQL queries, we'll be happy to manually copy/paste them into our edge functions. But they could also be integrated back into the client.
- Obviously, this is a departure from how the client API is consumed at the moment.
- Yet, if doable, this will deliver value and those who are keen to use edge functions will have a workaround and are more likely to stick with Prisma.

**Comment by janpio** [comment]
Your suggestion does not work as soon as you have dynamic input to your queries. Many users construct the actual queries dynamically on different outputs. Beyond that, just _finding_ all the queries in a codebase on build time is close to impossible.

As said before the way forward here is pretty clear: We need to 1) adapt our architecture to make it possible to use the Node PlanetScale Serverless driver, or 2) re-implement said serverless driver against their serverless API in our current architecture. Both valid approaches, but not top of our priority list right now.

**Comment by janpio** [comment]
As you can see in the roadmap it is the top priority right now. All recent releases included fixes for the serverless experience (Preview Json Protocol, Webpack plugin for Next.js workaround, improved connection pooler support with `directUrl`, smaller CLI engine sizes, massively smaller Client engine sizes, even our Accelerate early preview), and we will continue with that. This issue is also on our radar for that as well obviously, but comes after others as it requires a quite substantial change (as described above) - which we are also investigating and working on, but won't make it in the next few releases.

**Comment by jokull** [comment]
For people that want this I highly recommend using Prisma for schemas, migrations and an overall great CLI developer and team experience. For the queries themselves you can just flip over to Kysely that supports all the serverless drivers at this point (neon, planetscale and cf d1). [prisma-kysely](http://github.com/valtyr/prisma-kysely) generates kysely bindings from Prisma schemas. The main thing you lose is js runtime columns stuff like `updatedAt` - those will have to be specced out with `dbgenerated`like so: `@id @default(dbgenerated("gen_random_uuid()"))`.

**Comment by hanssonduck** [comment]
> For people that want this I highly recommend using Prisma for schemas, migrations and an overall great CLI developer and team experience. For the queries themselves you can just flip over to Kysely that supports all the serverless drivers at this point (neon, planetscale and cf d1). [prisma-kysely](http://github.com/valtyr/prisma-kysely) generates kysely bindings from Prisma schemas. The main thing you lose is js runtime columns stuff like `updatedAt` - those will have to be specced out with `dbgenerated`like so: `@id @default(dbgenerated("gen_random_uuid()"))`. Personally I actually prefer Kysely for composing queries, it's a bit more flexible and close to SQL, but still has typed results.

Another great alternativ is [drizzle-orm]https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/drizzle-team/drizzle-orm&ved=2ahUKEwiThevP8-L9AhUmVvEDHc7aDWMQFnoECBYQAQ&usg=AOvVaw3J6QK2m21izU9lKn43GukM). It supports both schema management and serverless environments like planetscale so there is no need to use prisma at all.

**Comment by maoosi** [comment]
In case you are looking for a temporary solution that works on Edge and uses PlanetScale serverless driver, I’ve been cooking something up at kuizto (a preview version will be published in the coming weeks): https://github.com/kuizto/prisma-edgeql

It is designed for my own use case, only supports a very limited subset of the Prisma Client API and is intended to be a temporary solution until Prisma officially releases support for Edge environments.

In case you want to comment or feedback on the idea, please use the discussions section on the repo itself, so we can keep this issue thread on topic.

**Comment by kirkouimet** [comment]
This is awesome

**Comment by sighash256** [comment]
> As you can see in the roadmap it is the top priority right now

@janpio, do you have an ETA?

**Comment by janpio** [comment]
No. We never communicate ETAs.

And note that this sentence was _not_ about specifically supporting the Planescale Serverless driver.

**Comment by sighash256** [comment]
cool, ty :)

**Comment by kayandra** [comment]
@janpio is it possible to jump on a short call with the team? I would love to take this on and I can give 1 month of my time to work, test and fix issues.

**Comment by janpio** [comment]
I unfortunately don't think this is suitable for a user contribution. As described above, supporting Planetscale's Node serverless driver requires us to fundamentally rethink and rework how Prisma's Query Engine works. (If you do have concrete suggestions, I am @janpio on slack.prisma.io as well and happy to hear your thoughts via DM!)

But I can share we recently started to investigate an approach for this. We have a concrete idea that could work, but we do not know yet if the performance and ergonomics in the end will be good enough to make it a real part of the product. We'll keep you updated.

**Comment by kayandra** [comment]
> I unfortunately don't think this is suitable for a user contribution. As described above, supporting Planetscale's Node serverless driver requires us to fundamentally rethink and rework how Prisma's Query Engine works. (If you do have concrete suggestions, I am @janpio on slack.prisma.io as well and happy to hear your thoughts via DM!)
> 
> But I can share we recently started to investigate an approach for this. We have a concrete idea that could work, but we do not know yet if the performance and ergonomics in the end will be good enough to make it a real part of the product. We'll keep you updated.

No problem, glad to hear you're already working on it internally.

**Comment by kirkouimet** [comment]
Wanted to add some perspective from my company - I personally desperately want Prisma to support working on the Cloudflare without having to go through Prisma's Cloud Proxy. We want to use Prisma to manage all of our SQL queries, but being forced to go through the Prisma Cloud Proxy in order to work on the edge is super scary for our company. The Prisma Cloud Proxy is clearly a new product that needs time to mature. We've had multiple issues with queries not going through the proxy and in a production environment we will be totally hosed if Prisma Cloud Proxy goes down.

Moving forward - we either need to get away from the Prisma Cloud Proxy or we need it to grow into a strong product that we can pay for and get an SLA.

Obviously, I would prefer to just hit PlanetScale directly without having to go through an additional hop of the Prisma Cloud Proxy, and I can see how the team's incentives don't align with this - why would the Prisma team actively develop a solution which would drive people away from their new Prisma Cloud Proxy product?

Looking forward to stronger production-worthy solutions in either direction.

**Comment by amlcodes** [comment]
not to mention, it seems like Prisma Cloud Data Proxy product is frequently unsuccessfully serving the edge compatible modules in the first place. #19174  (having the issue on planetscale and vercel (and dataproxy))

**Comment by AlvaroAquijeDiaz** [comment]
we may need yet another ORM

**Comment by arturenault** [comment]
Any updates on this? Would love this feature as I haven't really found a good ORM to connect to planetscale on the edge

**Comment by dgurns** [comment]
Try [Kysely](https://github.com/kysely-org/kysely) and its [Planetscale driver](https://github.com/depot/kysely-planetscale). It's a query builder, not an ORM, but it gives you type safety like Prisma. It's lightweight and can run on the edge. I've switched from Prisma and am very happy with it. Only downside is you need to construct nested objects yourself, but in practice I haven't found that to be a big deal.

**Comment by janpio** [comment]
We are working on adding support for the Planetscale serverless driver so you can use Prisma in these use cases again. 
(Kysely is great though, if it suits your needs it is a good solution for talking to Planetscale. You can even stay with your Prisma schema and Prisma for migrations with https://github.com/valtyr/prisma-kysely)

**Comment by cdcarson** [comment]
Hi all. I wrote a thing called [Frieda](https://github.com/cdcarson/frieda).  It's not for everyone. It's not Prisma, and it doesn't help you write complex SQL. All it claims to do is write decent, well-typed, application code for the _specific stack_ of the PlanetScale Serverless Driver + a serverless javascript/typescript application. 

I'd really appreciate other people using that planetscale/javascript stack trying it out and telling me what they think about the approach. Again, Frieda is not Prisma. It's just an alternative approach.  Please post a comment on [this thread](https://github.com/cdcarson/frieda/discussions/41)  or raise an [issue](https://github.com/cdcarson/frieda/issues) rather than replying here (That is, don't spam this issue.) Thanks!

**Comment by hanssonduck** [comment]
We need do to something like this right now yeah `bun install node-gyp`.

**Comment by janpio** [comment]
Hey, we at Prisma have been working on this for the past few weeks. Soon, we'll have something to share and test!
If you are interested in helping us, please respond to this super short survey and leave your email address so we can get in touch with instructions: https://pris.ly/survey/driver-adapter-planetscale Thanks.
