### ISSUE TITLE
Allow sharing files generated by `prisma generate` from Windows to Mac/Linux

### ISSUE THREAD

**Issue by hanar3** [prisma/prisma#15325]
### Bug Description

EDIT: After investigating more, I discovered this is more easily reproducible if you run prisma generate from Windows. 

Running `prisma generate` on windows produces a few paths on the generated code, which would cause prisma to throw if using the generated code on a different machine. So, basically, if i generate files on a windows machine (say my personal machine), and try to use it on my work machine (a Mac), this would fail, because the paths generated are windows-specific.

### How to reproduce

1. Generate the client from one environment (tried it with windows)
2. Try to use generated files from other environment (Mac/Linux) - ideally, call it from within a file in the `src`folder while the schema itself is on root.
3. Prisma will throw a very cryptic error, saying `Error: ENOENT: no such file or directory, open 'schema.prisma'` - this is because prisma fails to resolve the path based on the "common paths" that it defines during codegen here:
```ts
const foundDirname = !regularDirname && findSync(process.cwd(), [
    "src\\generated\\prisma-client",
    "generated\\prisma-client",
], ['d'], ['d'], 1)[0]
```

This does not work, obviously - and, to be clear I'm not claiming it _should_, i just had a lot of trouble figuring out this error, although the only reason this doesn't not work, doesn't seem to be due to a very OS specific reason, it seems to be because when we call prisma generate on a windows environment, windows will use `\\` on most of the paths, on `generated/prisma-client/index.js`, If I fix the paths to use a single `/` rather than the double `\\`, it seems to work fine.

### Expected behavior

If possible, the ability to share generated files between environments, if not, perhaps a less cryptic error message would help. Something along the lines of `Unable to locate schema file, did you run prisma generate?`.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "./generated/prisma-client"
  binaryTargets = ["native", "linux-musl", "darwin"]
}

datasource db {
  provider = "mongodb"
  url      = env("MONGO_URI")
}

model Post {
  id          String   @id @default(auto()) @map("_id") @db.ObjectId
  text       String
}
```

In `src/test.ts`
```ts
import { PrismaClient } from "../generated/prisma-client";
const prisma = new PrismaClient({ log: ["query"]  });
```

### Environment & setup
- OS: Windows (to run prisma generate) / Mac (to try to run the files generated on windows)
- Database: Mongo
- Node.js version: 16.13.2

### Prisma version
```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by hanar3** [comment]
Sorry - will do!

**Comment by jkomyno** [comment]
Hi @hanar3, if I understood correctly, you currently:
- generate `prisma` types of a project in a system (e.g. windows)
- (I assume) commit those `prisma` output files and push to remote repository
- open the same repository on another system with different path separators (e.g. linux/mac)

And this procedure ends up failing because we're hard-coding the path separator of the first system (e.g., `\\` on windows), which fails with an obscure error message in linux/mac, which require the usage of `/` as a path separator). Did I get that right?

**Comment by aqrln** [comment]
I see this is marked as a feature request, but I'm even somewhat leaning towards considering the current behavior a bug. Generating a client on one platform and then using it on another is a supported use case generally, that's why we have the `binaryTargets` field in the schema. Also I think it should work the other way around (I believe a client generated on Linux or Mac will work on Windows if you have `windows` in `binaryTargets` — please let me know if I'm wrong and it doesn't), so it would make sense if it was symmetrical.
