### ISSUE TITLE
Data Platform: Offer users ideas on missing indexes

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#15418]
## Problem / Solution

This is not an easy problem, but a feature I would be willing to pay for in the proxy/data platform you are building would be a query analysis that offers suggestions on missing indexes that would speed the optimization process.

Better even if I can see the query plans with problematic sections (usually sequential scans), fork the db (with copy on write so it's instant), add the new index and see the query plan.

## Alternatives

Currently I am using the GCP query insight which is decent, but I still need to analyse the query plan, clone my db (pretty slow on gcp), connect with an external tool, create the index and then re-try my query.

**Comment by martzoukos** [comment]
Hello Emile!

Thank you for your feedback and for providing details about your current workflow, this helps us categorize and understand insights like yours. This is indeed a candidate solution that we are considering for the mid-term (think "a couple of quarters" time horizon) and I would love to jump in a quick call with you to learn more about your current workflow and also how you would imagine this working for you: https://calendly.com/martzoukos/45-min-discovery-call 

Otherwise, if you don't have time now, may we get in touch with you in the future once we have something like a beta version of such a feature for you to try it out?

**Comment by Sytten** [comment]
Hello @martzoukos!

Happy to take a call with you, I am also in the `prisma company` slack if you want to reach me (channel `#collaboration-emile`). This is just a vague idea I had while working on optimisation for a client (I opened a bunch of issues related to that at the same time as this one). I thought it would be valuable to share since it's a problem I expect others will encounter and an argument in favour of using your managed service.
