### ISSUE TITLE
Prisma Migrate prevents using special index functionality of CockroachDB.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#15447]
## Problem

We'd like to create an index that uses the `STORING` clause, [available in CockroachDB](https://www.cockroachlabs.com/docs/v22.1/create-index#store-columns). Something like this:

```sql
CREATE INDEX "Reservation_foo_bar_idx" ON "Reservation"("foo", "bar") STORING ("col1", "col2", "col3", "col4");
```

We can add an index like this in `schema.prisma`:

```
@@index([roomId, endDate])
```

and then edit the generated migration file to add the `STORING` clause. But the next time the `migrate dev` is run, the system will delete the old migration and replace it with one where the `STORING` clause is not there.

## Suggested solution

Extend index configuration to allow a `storing` field for CRDB, or adjust Prisma Migrate to not delete the index when the introspection doesn't exactly match on clauses that wouldn't be recognized by Prisma Migrate anyway.

## Alternatives

~Right now, what we're doing is this:~

```
// @@index([roomId, endDate])
```

UPDATE this workaround doesn't work either, Prisma Migrate will delete it.

**Comment by AndrewSouthpaw** [comment]
One of the CRDB engineers is wondering what command is used to introspect the schema? Is it `information_schema`?

**Comment by nvanbenschoten** [comment]
`STORING` columns are referred to as `INCLUDE`-d columns in Postgres. See https://www.postgresql.org/docs/current/sql-createindex.html. CockroachDB also supports this syntax.

It looks like Prisma does not yet support INCLUDE clauses on index definitions: https://github.com/prisma/prisma/issues/14699.

**Comment by nvanbenschoten** [comment]
This has also been mentioned in the following two issues: https://github.com/prisma/prisma/issues/8584 and https://github.com/prisma/prisma/issues/8547.

**Comment by janpio** [comment]
Please one of you add a comment to https://github.com/prisma/prisma/issues/8584 that this is the equivalent to a `STORING` index in CockroachDB (basically the technical information you included in the original description @AndrewSouthpaw) - that would extend the issue to include CockroachDB support.

As you realized this is a missing feature (no way to express this kind of index in Prisma Schema), tracking in #8584. Migrate is removing the unknown index, because you currently can only define a standard index in the PSL (and you do).

What happens if you do _not_ include the `@@index([roomId, endDate])` in your schema - does Migrate still drop it on the next generated Migration @AndrewSouthpaw?

Is the CockroachDB syntax for this limited to a simple list of "included" columns @nvanbenschoten or are there more advanced cases (with functions, transformation, some other thing than a "list of column names")? If not, that would be neatly scoped to a very straightforward syntax (which we like, as it makes things easier to implement).

Right now the most straightforward workaround is probably to remove the query that "messes" with the index from the generated migrations before executing them. Each time. (We realize that is not great and am now thinking about alternatives)

**Comment by AndrewSouthpaw** [comment]
> What happens if you do not include the @@index([roomId, endDate]) in your schema - does Migrate still drop it on the next generated Migration @AndrewSouthpaw?

Migrate still drops it at the next generated migration, yeah.

> Is it limited to a simple list of "included" columns

AFAICT [from the docs](https://www.cockroachlabs.com/docs/stable/indexes.html#storing-columns) and the [railroad diagram](https://www.cockroachlabs.com/docs/v22.1/create-index.html#standard-index), that's correct.

<img width="1114" alt="Cursor_and_CREATE_INDEX___CockroachDB_Docs" src="https://user-images.githubusercontent.com/5187404/193101058-125fff49-1f1d-4abf-8764-39e6713ed99f.png">

**Comment by janpio** [comment]
I added a comment to the feature request with the CockroachDB details: https://github.com/prisma/prisma/issues/8584#issuecomment-1319191995

**Comment by janpio** [comment]
I am closing this here then, as I think #8584 asks for exactly this functionality. What you describe of it dropping it and replacing it with a normal index unless you modify the migration file is expected until that is implemented or we change the behavior otherwise.
