### ISSUE TITLE
Error: [libs\sql-schema-describer\src\mssql.rs:317:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\ncreate default D_BIT_OFF\r\nas 0\r\n`" 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15704]
Command: `prisma db pull`
Version: `4.4.0`
Binary Version: `f352a33b70356f46311da8b00d83386dd9f145d6`
Report: https://prisma-errors.netlify.app/report/14349 
OS: `x64 win32 10.0.19044`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\mssql.rs:317:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\ncreate default D_BIT_OFF\r\nas 0\r\n`"
    at ChildProcess.<anonymous> (\prisma\build\index.js:91744:28)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by Jolg42** [comment]
It looks like the same user opened an issue here https://github.com/prisma/prisma/issues/15675

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior.

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
Reproduced: The line breaks cause this, see https://github.com/prisma/prisma/issues/24275
