### ISSUE TITLE
`update`/`upsert`/`delete` should take `UserWhereInput`

### ISSUE THREAD

**Issue by Thore1954** [prisma/prisma#15721]
## Problem

Currently there are suggestions on adding methods like `updateFirst` (#4349) or `updateUnique` (#6440), but in fact there's no need for an `update` method that takes `UserWhereUniqueInput` because it's not going to be batched by the dataloader whereas there's a need for an `update` method that takes `UserWhereInput` and returns the first updated record that matches the criteria.
## Suggested solution

`update` should take `UserWhereInput` instead of `UserWhereUniqueInput`.
## Alternatives

You can try loading the record beforehand by `findFirst` and then perform an update by it's pk, but that's not ideal.

**Comment by janpio** [comment]
The general need of `update` to take at least one of the fields (currently: only) of `WhereUniqueInput` is not because of the dataloader, but because it guarantees that only maximum 1 field will be updated. We do not want to change that.

If you want to update (potentially) more rows `updateMany` is the way to go (and if you need the updates fields returned instead of just the count, that is an unrealted issue).

**Comment by Thore1954** [comment]
In that case it makes sense to have separate `updateUnique` and `updateFirst` per other issues.
