### ISSUE TITLE
Further expand tests around referential actions, referential integrity and relationMode

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#15733]
Follow up for https://github.com/prisma/prisma/issues/10806 and https://github.com/prisma/prisma-private/issues/197

Details see internal document:
https://www.notion.so/prismaio/Phase-2-prepare-for-GA-fe01774a66a74d64a495ec89fad11e17#91024db079a54ceba2a96cacfaee591e
https://www.notion.so/prismaio/Phase-2-5-sprint-4-6-0-prepare-for-GA-189bbdf542a64bbf96ca07dd196f26c4#1cd9b00ac6d845dab7a7fd842f6a27ca

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
