### ISSUE TITLE
Error: Command failed with exit code 101: /home/vscode/.cache/prisma/binaries/cli/4.2.0/2920a97877e12e055c1333079b8d19cee7f33826/prisma-query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#15791]
Command: `prisma generate`
Version: `4.2.0`
Binary Version: `2920a97877e12e055c1333079b8d19cee7f33826`
Report: https://prisma-errors.netlify.app/report/14373 
OS: `x64 linux 5.10.0-18-amd64`

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
