### ISSUE TITLE
Deal with extensions that are not installed/present

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#15888]
When extensions are not present or installed, you get a kind of plain PostgreSQL error message. It might be useful to catch that and present a custom error message with a link to documentation.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
