### ISSUE TITLE
Prisma Client Incorrect INT Column Size

### ISSUE THREAD

**Issue by ApocalypseCalculator** [prisma/prisma#16144]
### Bug description

Apologies if this is the wrong place for this bug report, but here goes: 

When I'm trying to insert a JS `Date.now()` value as an INT into the DB, I get the following error: 
```
Inconsistent column data: Conversion failed: Value 1667622359143 does not fit in an INT column, try migrating the 'createtime' column type to BIGINT
```

This doesn't seem right, as the SQLite INT data type can hold up to [nearly 10e20](https://stackoverflow.com/a/4448400)

If this is documented somewhere in the Prisma docs I couldn't find it :(

### How to reproduce

Run included example

### Expected behavior

I expected the database to accept the value

### Prisma information

```prisma
datasource db {
    provider = "sqlite"
    url      = "file:data.db"
}

generator client {
    provider = "prisma-client-js"
}

model Test {
    id         String  @id
    amount     Int
    createtime Int
}
```

```js
prisma.test.create({
    data: {
        id: "0",
        amount: 1,
        createtime: Date.now()
    }
})
```

### Environment & setup

- OS: Windows 10
- Database: SQLite
- Node.js version: v16.13.1

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
```

**Comment by SevInf** [comment]
Can confirm with the provided instructions.

**Comment by lobotomoe** [comment]
Same issue:

```
Conversion failed: Value -1001752844027 does not fit in an INT column, try migrating the 'chatId' column type to BIGINT
```

**Comment by Weakky** [comment]
Hey @ApocalypseCalculator and @lobotomoe,

While you're correct that SQLite can technically hold larger values in INT columns, we've had to take the unfortunate decision to narrow down the range of accepted values on SQLite's INT columns so that it fulfills the assumptions of Prisma's types.

Unlike most RDBMS, SQLite column types are virtually useless. You can store pretty much anything you want in an INT column type. This used to cause issues on the Prisma Client & Query Engine because int values above `Number.MAX_SAFE_INTEGER` were deserialized as regular numbers, leading to precision loss.

To prevent this, we decided to narrow down the range of accepted values for an INT column so that it matches other database rules:

- `INT` column: int32 range
- `BIGINT` column: int64 range

Note that migrating your `createtime` column to `BIGINT` will make the Prisma Client deserialize the `createtime` results as Javascript's native `BigInt`.

Once more, you might find that frustrating as there's technically a whole range of int values that could be handled with a regular JS number. Specifically, (taking the positive range to simplify), all numbers between `int32::MAX` and `Number.MAX_SAFE_INTEGER`.

We've also had to take the painful decision to ignore that. Dynamically deserializing int64 numbers to either `Number` or `BigInt` based on whether they're greater than `Number.MAX_SAFE_INTEGER` felt like a much worse trade-off, because it meant you could end up with unpredictable runtime errors in production. So, we decided to aim for consistency and deserialize everything above `int32::MAX` as a Javascript's `BigInt`.

Hope this explanation will make sense to you both. For reference, here's the original issue that lead to this change: https://github.com/prisma/prisma/issues/12784.

I'm closing the issue now but feel free to ask more questions/re-open if you have better ideas how this should be handled.

Thank you 🙏
