### ISSUE TITLE
Add documentation to "PrismaClient is unable to be run in the browser"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#16153]
Many people, often not super experienced, encounter this. Although the error message is correct, we could probably do a better job at explaining what they are doing "wrong" and how they can solve it. The best solution would probably be to add this to the docs, and then add a link to the current error message (via pris.ly).

**Comment by NanoCode012** [comment]
I had this error when I was trying to run Prisma on Vercel’s Middleware which runs on the Edge (V8) instead of normal Nodejs runtime.

I didn’t think this was an issue since my idea was that it’s still running “on a server” and not on client/browser. 

Solution was to make sure that the middleware does not import any file which also imported Prisma client or use Prisma directly.

Hopefully, this case of mine can help save someone’s time.
