### ISSUE TITLE
DateTime is typed as Date but actual value is string

### ISSUE THREAD

**Issue by savaparoski** [prisma/prisma#16399]
### Bug description

DateTime is typed as Date but actual value is string
DateTime gets typed as **Date** in generated prisma client while return value is **string**

### How to reproduce

1. Go to https://github.com/savaparoski/prisma-wrongly-typed
2. Clone repo
3. Install dependencies
4. Run docker compose up
5. Generate prisma client
6. Run ts-node index.ts

### Expected behavior

Expected that DateTime maps to string type.

### Prisma information

https://github.com/savaparoski/prisma-wrongly-typed/blob/master/schema.prisma

### Environment & setup

 https://github.com/savaparoski/prisma-wrongly-typed

### Prisma Version

```
4.6.1
```

**Comment by johnkm516** [comment]
The actual value isn't a string. Not sure what your example repo is supposed to prove. Are you saying because console.log is converting the Date to a string when logging it's of the string type? 

console.log will stringify objects. It does not mean the objects you log are of type string. 

To see the actual type perhaps try : 
```
  console.log(typeof(findRes?.createdAt))
  console.log(findRes?.createdAt instanceof Date)
  console.log(findRes?.createdAt.constructor.toString())
```

**Comment by savaparoski** [comment]
True
