### ISSUE TITLE
Transpile of PrismaClient constructor taking a long time

### ISSUE THREAD

**Issue by kennytraction** [prisma/prisma#16418]
### Bug description

TypeScript is taking a long time (>3 minutes) to transpile code that includes creating a new instance of `PrismaClient`. It seems much of that time is spent type checking the `PrismaClient` constructor.

### How to reproduce

Use a larger schema with the following few lines of code. Run `tsc` on the project containing this code.

```
import { PrismaClient } from '@prisma/client'
export class MyPrisma {
  prisma: PrismaClient
  constructor() {
    this.prisma = new PrismaClient()  // This lines takes ~3 minutes to transpile
  }
}
```

Removing the line that creates an instance of `PrismaClient` results in the code transpiling very quickly.

### Expected behavior

I expect that transpiling code that includes using the `PrismaClient` constructor to not take minutes.

### Prisma information

Our schema currently has ~247 models. We may be able to share it privately.

### Environment & setup

- OS: Windows, MacOS, Docker
- Database: PostgreSQL
- Node.js version: 14.17.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at ..\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at ..\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at ..\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at ..\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by millsp** [comment]
I have not been able to reproduce this on our latest version. I find that measuring with time isn't the best way to measure because it can vary wildly depending on your setup. At least, I can see that you are running on macOS so you should have something decent. On my test it takes around 15 seconds @4.5GHz. I have added a totally not scientific [test](https://github.com/prisma/prisma/actions/runs/5753933820) to check that it can compile under a minute on CI. We have type performance tests in the making, in the mean time, this is not too bad. I used a real-world 230 model schema from Odoo.
