### ISSUE TITLE
Log client errors to log file, submit on next CLI execution

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1659]
Quoting @schickling 

> If there’s an unexpected error in the client, the client should create a “error trace file” that will then be picked up by the CLI to prompt the user to report the detailed error. 

---

(Input from @albertoperdomo via https://github.com/prisma/prisma-client-js/issues/661)

What we think we would need to implement:

1. dump errors during runtime into log files if `NODE_ENV != "production"` or version includes `dev` (because CLI probably only exists there)
2. (optional) automatic restart after a panic, could be dangerous if an infinite loop is hit
3. truncate the file if based on filesize, i.e. 1MB or time, i.e. 1 day
4. have the timestamp of the last occurrence
5. debounce or throttle to avoid spamming the file system
6. (optional, too complex?) de-duping occurrences of the same error

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
