### ISSUE TITLE
prisma deploy --dry-run broken

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1669]
**Current behavior**
`prisma deploy --dry-run` returns the following, even for a fresh service. 

```
divyendusingh [prisma-101]$ prisma deploy --dry-run
Performing dry run for service `prisma-101` to stage `dev` on cluster `local` 329ms
Service is already up to date.
```

**Reproduction**

Initialize a project with `prisma init`. 

Use `prisma local nuke` to clean up the local. 

Try `prisma deploy --dry-run`. 

**Expected behavior?**

`prisma deploy --dry-run` should show the actual deploy behavior as a dry run but it stats that everything is up to date even for a fresh service.

**Comment by johannpinson** [comment]
Hello guys,

I always have this bug, can you re-open the issue?

**Comment by johannpinson** [comment]
@marktani @divyenduz 

This is an example of a strange `--dry-run` (coupled with `force`).
It will remove useless type, but data exists, so I added the `--force` flag to see the changes expected, but the CLI said `Service is already up to date.`
(Is it maybe because just before I already made a `prisma deploy -d`?)

<img width="630" alt="capture d ecran 2018-08-09 a 16 11 00" src="https://user-images.githubusercontent.com/2202989/43904566-427eff06-9bef-11e8-9d82-769e4903ab0d.png">

**Comment by johannpinson** [comment]
Hello @marktani @divyenduz 

Any news about this point?

I also just saw an other (potential) problem:
After the `prisma deploy --dry-run`, if the process don't throw an error, after displaying the `Service is already up to date", it runs the different `hooks/post-deploy`, but does it have to run?
I personally use it to run a `npm scripts` after a deployment, but after a `--dry-run`, I don't want it (it just to test and be sure of the modifications which will be apply).

**Comment by jhalborg** [comment]
Go away stale bot!

**Comment by bwobst** [comment]
Bump so this issue isn't marked as stale again.

**Comment by do4gr** [comment]
It also seems that the CLI ignores unknown / misspelled arguments. I think this can lead to unintended consequences for example if one wants to run `prisma deploy --dry-run --force` to preview changes but accidentally types `prisma deploy --dryrun --force` the changes are immediately applied including potential  data loss.
