### ISSUE TITLE
`fieldReference` doesn't work to toggle a boolean value

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#16715]
### Bug description

`fieldReference` doesn't work to toggle a boolean value.

### How to reproduce

See this repo for a reproduction: https://github.com/nikolasburk/fieldReferenceBug

### Prisma information

v4.7.1

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fieldReference"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: v16.1.0

### Prisma Version

```

```

**Comment by Weakky** [comment]
Hey @nikolasburk,

This is not expected to be working. 

First, field references only work in filters atm. Secondly, you're treating a field reference as a boolean value but the value of `prisma.post.fields.published` is _not_ a boolean. It's a field that contains metadata that lets the QE render the column name instead of a scalar value.

If we had an API to express what you're trying to do, it'd probably look like so instead:

```
const updatedPost = await prisma.post.update({
  where: { id: 1},
  data: {
    published: { not: { prisma.post.fields.published } }
  }
})
```

But that's _not_ possible today. If you want to persist this, you should either rephrase it the issue as a feature request or open a new one entirely.

I'm closing this now, feel free to re-open it if you want to rephrase it as a feature request. Cheers!
