### ISSUE TITLE
Development setup: command to use the npm version of prisma/prisma with locally built engines

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#16767]

**Comment by SevInf** [comment]
I've built a script for this some time ago: https://gist.github.com/SevInf/3ce6aae708e12edabcb33967bc11d404

**Comment by tomhoule** [comment]
Reopening to document @SevInf 's solution for non-nix users, and maybe more.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
