### ISSUE TITLE
psl: replace SchemaAst with a lossless AST

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#16841]
## Problems with the current implementation

- We can't refer to AST nodes in a fine-grained way. We would for example like to be able to have a reference to a specific expression inside an array expression inside an attribute.
- We lose information like comments.
- We can't treat different AST nodes in a generic way (they're different types).
- We lose a lot of information on how schema nodes are ordered.
- We are allocating a lot of strings and vectors.

## Options

- rust-analyzer style AST with rowan
  - https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/syntax.md
  - https://ericlippert.com/2012/06/08/red-green-trees/
- zig-style AST
  - https://media.handmade-seattle.com/practical-data-oriented-design/
  - https://github.com/ziglang/zig/blob/master/lib/std/zig/Ast.zig
- ... ?

## Path to replacing the AST

- Replace pest with the new parser
  - Challenge: we have to reimplement reformatting.
- Slowly remove bits of SchemaAst, until we only have the lossless AST and parser-database.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
