### ISSUE TITLE
Pagination issue with cursor and sorting by createdAt

### ISSUE THREAD

**Issue by chrisbull** [prisma/prisma#16991]
### Bug description

When using @prisma/client and doing a query with findMany, there is a bug with cursor and sorting by createdAt. 
Duplicate results exist when the initial query runs and then the secondary query runs with the cursor. At first I thought it was and issue with my code, assuming I was doing something wrong, or missing something. But after several attempts and testing, and then removing the `orderby: { createdAt: 'asc' }` the results are correct with no duplicates.

### How to reproduce

```ts
const items = await prisma.product.findMany({
  take: limit + 1, // get an extra item at the end which we'll use as next cursor
  where: {
    title: { search },
  },
  cursor: cursor ? { id: cursor } : undefined,
  orderBy: {
    createdAt: 'asc',
  },
})
```

```
model Product {
  id String @id @default(uuid())
  title String?

  createdAt DateTime @default(now())
  updatedAt DateTime @default(now()) @updatedAt
}
```

### Expected behavior

Expected results to be unique with pagination. But the first and second page returns the same results.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.12.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
Preview Features        : fullTextSearch
```

**Comment by lamanabie** [comment]
U need `unique column such as an ID or a timestamp`, you need at least one unique index when sorting

[sorting-and-cursor-based-pagination](https://www.prisma.io/docs/concepts/components/prisma-client/pagination#sorting-and-cursor-based-pagination)

**Comment by mcbethio** [comment]
Hey @chrisbull,

@lamanabie is correct that we need to establish uniqueness when sorting for the the cursor to work.

I suspect that the timestamp field you are using contains lots of duplicates as some records were probably inserted at exactly the same time. 
Something like the following could potentially work for you, but you need the addition of an id field - which needs to be unique.
```
    const secondQueryResults = await prisma.product.findMany({
        take: limit,
        skip: 1,
        where: {
            title: {
                contains: 'product'
            },
        },
        cursor:  { id: myCursor },
        orderBy: [
            {
                createdAt: 'asc',
            },
            {
                id: 'asc',
            },
        ],
    })
```

I will close this issue as there isn't anything for our devs to fix although feel free to re-open if you are not happy with the outcome.

**Comment by jedwards1211** [comment]
@mcbethio Using the `id` as a cursor is brittle.  If a product with a given `id` gets deleted in the middle of pagination, Prisma won't be able to look up that product to get its `createdAt`.  You could iterate backward over previous results one by one trying them until you hit one that isn't deleted, but that's annoying, and you shouldn't have to, because it's not necessary with a better cursor design as outlined below.

Note: companies like Stripe use ids as cursors, but they can afford to because they need to soft delete everything anyway.  If using the id as a cursor seems like common practice, that's why - but anyone doing so is using soft deletes, or they're a hastily written startup product that will have to make breaking changes to their API someday to make it more reliable.

The more robust and flexible approach is to include all sort column values in your cursors.  So for example if you're sorting on `(createdAt ASC, id ASC)`, the cursor should really be the `{ createdAt, id }` of a given `product`.  Given that, you would do a SQL tuple comparison like `("createdAt", id) > (:createdAt, :id)`, which would work even if the product with `id` no longer exists.

In MongoDB AFAIK there isn't an operator as elegant as tuple comparison, instead you have to expand to `"createdAt" > :createdAt OR ("createdAt" = :createdAt AND id > :id)`.
Googling for "Mongo multicolumn pagination" yields some examples like this:

```
  if (query.previous_cursor) {
    const [cursorId, cursorDate] = query.previous_cursor.split('_')
    q.$or = [
      { last_used: { $lt: new Date(cursorDate) } },
      {
        last_used: new Date(cursorDate),
        _id: { $lt: new ObjectId(cursorId) }
      }
    ]
```

**Comment by janpio** [comment]
If you think this is something we should revisit @jedwards1211, best open a new issue. Thanks!
