### ISSUE TITLE
Prisma Client: Add tests for `orderByNulls` preview feature for MongoDB

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#17100]
While checking https://github.com/prisma/prisma/issues/17081

I didn't find any tests in prisma/prisma running on MongoDB
Currently, the following databases are tested 
```js
    {
      provider: 'sqlite',
    },
    {
      provider: 'postgresql',
    },
    {
      provider: 'mysql',
    },
    {
      provider: 'sqlserver',
    },
    {
      provider: 'cockroachdb',
    },
```
https://github.com/prisma/prisma/tree/main/packages/client/tests/functional/order-by-null

**Comment by SevInf** [comment]
I don't think it's supported for mongo: https://github.com/prisma/prisma/blob/main/packages/client/tests/functional/order-by-null/tests.ts#L158

**Comment by Jolg42** [comment]
I could not find anything about it not being supported on MongoDB though 🤔 

- https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-with-null-records-first-or-last
- https://github.com/prisma/prisma/issues/14377
- https://github.com/prisma/prisma/releases/tag/4.1.0

**Comment by Weakky** [comment]
<img width="553" alt="image" src="https://github.com/prisma/prisma/assets/25233379/eb060ff4-df6e-46f0-8bf5-231f50166a55">

It is in the docs (might have been updated since you linked it). MongoDB is intentionally not supported yet because supporting the feature required too many hacks. The connector doesn't have the capability and thus doesn't expose the API at all. We could review that in the future but I'd suggest we keep it that way for now.
