### ISSUE TITLE
Make cuid2 available in `@default`

### ISSUE THREAD

**Issue by Yiak** [prisma/prisma#17102]
## Problem

`cuid()` is deprecated now due to security reasons, can we let [`cuid2`](https://github.com/paralleldrive/cuid2) be an option when generating ids?

**Comment by magoz** [comment]
Also interested in this. Any plans?

**Comment by Jolg42** [comment]
Hello!
Where did you find the news? Just curious on how you found out about this `cuid` being deprecated, it looks like this is only one week old to me.

Notes:

The JS package says https://github.com/paralleldrive/cuid
Status: Deprecated due to security. Use [Cuid2](https://github.com/paralleldrive/cuid2), instead.
> Note: All monotonically increasing (auto-increment), and timestamp-based ids share the security issues with Cuid. V4 UUIDs and GUIDs are also insecure because it’s possible to predict future values of many random algorithms, and many of them are biased, leading to increased probability of collision.

Prisma actually uses the Rust version https://crates.io/crates/cuid (based on the JS lib) which doesn't have a replacement for now:
https://github.com/mplanchard/cuid-rust/issues/4

**Comment by Jolg42** [comment]
Notes:
It looks like we were using the `cuid` npm package, but only for generating a random if for our test setup.
It will be removed in https://github.com/prisma/prisma/pull/17200

After that, the only version we use is https://crates.io/crates/cuid in prisma-engines
https://github.com/search?q=repo%3Aprisma%2Fprisma-engines+cuid+language%3ATOML&type=code&l=TOML

**Comment by Jolg42** [comment]
Note: the Rust author of the `cuid` create wants to add support for `cuid2` 💚 . Let's check back once it's done.

**Comment by magoz** [comment]
That's awesome, @Jolg42! Thanks

**Comment by cupcakearmy** [comment]
Seems like the first release dropped https://crates.io/crates/cuid2

**Comment by immjs** [comment]
Has it been changed yet?

**Comment by Jolg42** [comment]
The [cuid2](https://crates.io/crates/cuid2) crate has been published to crates.io, at version 0.1.0 (not quite ready to commit to API stability yet, but will soon!)

All cuid v1 functions in the `cuid` crate have been marked as deprecated, and a new [`cuid2()`](https://docs.rs/cuid/latest/cuid/fn.cuid2.html) function has been added.

_Originally posted by @mplanchard in https://github.com/mplanchard/cuid-rust/issues/4#issuecomment-1399374710_

**Comment by Yedidya10** [comment]
Hi. I have not been able to fully understand what has developed so far. Is it safe to use @default(cuid()) even though it is deprecated?

**Comment by mplanchard** [comment]
I don’t anticipate any changes in the fundamental `cuid2() -> String`
portion of the rust API, so that is safe to build on. The only thing that
might change before I publish a 1.0 release are some of the details of the
config builder for generating IDs with custom lengths or other parameters,
as well as adding WASM support.

The upstream cuid2 JS crate has also made some minor algorithm changes
recently that I need to review, but that won’t change the API for
generating IDs at all.

**Comment by mplanchard** [comment]
Regarding the deprecation, I don't know the position of the Prisma team, but the position of the author of cuid and cuid2 is that folks should move to cuid2 as soon as they're able to. My personal opinion is that the rust port of the original cuid algorithm doesn't suffer from some of the issues that affected the reference implementation (portability and variable length), but the new version _is_ more collision resistant, so it's still good to migrate when possible.

**Comment by kevinvdburgt** [comment]
Any workarounds available to already use cuid2 with the current release of prisma?

**Comment by ciscoheat** [comment]
@kevinvdburgt You can always remove the `@default` attribute and use the cuid2 library to add them yourself for the fields in question, it's not too much of a hassle.

**Comment by rothlis** [comment]
> @kevinvdburgt You can always remove the `@default` attribute and use the cuid2 library to add them yourself for the fields in question, it's not too much of a hassle.

This and we have used a Prisma middleware to generate cuid2 ids.

**Comment by ciscoheat** [comment]
Ah yes, a middleware should be the best solution.

**Comment by 413n** [comment]
> This and we have used a Prisma middleware to generate cuid2 ids.

@rothlis Could you provide a snippet of the middleware?

**Comment by rothlis** [comment]
It would look something like

```ts
prisma.$use(async (params, next) => {
  if (params.action === "create") {
    params.args.data.id ??= createId()
  }
  return next(params)
})
```

You can also focus specific models with `params.model`.

**Comment by ciscoheat** [comment]
Remember to handle `createMany` as well. Maybe we should do a little community effort to make a snippet like this? As a gist?

**Comment by jpmelnik** [comment]
I'm trying a Middleware approach but validation with ZOD z.string().cuid2() didn't pass.

Is any extra configuration necessary?

**Comment by DinoZoidDev** [comment]
What's the status of this implementation? cuid2 has been deprecated for a couple of months and has clearly stated that it has security vulnerabilities. No harsh feelings toward the Prisma team!

**Comment by whygee-dev** [comment]
Does the rust port obscure the creation order or does it have the same problem as the original cuid v1 implementation in this regard ? If no, I really think cuid2 should be available to use with prisma as soon as possible

**Comment by janhesters** [comment]
@Jolg42 Any updates on this? 😊

**Comment by AaryanAdil** [comment]
would love an update on this.

**Comment by jam-fran** [comment]
I like the middleware approach, but how do we make typescript happy if we're not manually providing the id when we create a resource? I suppose I could leave the `default(cuid())` in my schema file, but that doesn't seem like good practice if it's purely to satisfy typescript.

**Comment by Vashiru** [comment]
I've created an elaborate ticket over [here](https://github.com/prisma/prisma-engines/issues/3826) based on the comments from @Jolg42 which I think specifies everything that needs to be done. Would be great if somebody can pick this up as I'm not a rust developer myself.

**Comment by tomhoule** [comment]
@Vashiru I'm not involved in this, so I don't have the context myself to drive the discussion.

One concern I remember being raised is the length of cuid strings. Is it the same between cuid 1 and 2? Prisma users may have designed their database schema (e.g. fixed length string columns) around that, so we have to be sure we won't break them.

**Comment by Vashiru** [comment]
Well fixed length would already be a bit of an issue. Digging through some tickets, Prisma 1 originally used varchar(25). As it turns out, the original rust implemenation could already generate longer ones, 26 has been seen. The solution for this has been to increase this to varchar(30). All the discussion of this can be found in: https://github.com/prisma/prisma-engines/issues/878. This has /not/ been done for the upgrade script from Prisma 1 to 2, but anything created in Prisma 2 should be varchar(30).

That being said, the original creator of CUID has pointed out that you shouldn't depend on it being a fixed length ever:  https://github.com/paralleldrive/cuid/issues/164.

But it looks like cuid2, as seen here: https://crates.io/crates/cuid2, uses a length of 24 according to the readme. This fits within the varchar(30) that has been set in the default.

@tomhoule Is there somebody we can tag to get the right context for the discussion?

**Comment by ari-becker** [comment]
> @Vashiru I'm not involved in this, so I don't have the context myself to drive the discussion.
> 
> One concern I remember being raised is the length of cuid strings. Is it the same between cuid 1 and 2? Prisma users may have designed their database schema (e.g. fixed length string columns) around that, so we have to be sure we won't break them.

@tomhoule is there a reason why Prisma couldn't just add `cuid2()` as a separate function for `default()`, while deprecating (but not removing) `cuid()`? This makes `cuid2` available for new users and for users willing to make the time to migrate, while not affecting existing schemas. I don't understand why this needs to be an either/or decision, why not both?

**Comment by llravelo** [comment]
Looking forward to a native `cuid2()` implementation!

**Comment by benjamin-guibert** [comment]
Hello, I am not sure to follow: is `cuid()` still using the v1 today? Should we still use the workaround in order to use the v2?

**Comment by llravelo** [comment]
@benjamin-guibert Prisma still uses v1, but there are a number of workarounds suggested in this thread.

**Comment by benjamin-guibert** [comment]
Thank you @llravelo. Isn't it as critical as it sounds, the security concern? I'm trying to understand why this is not a priority (6 months old). 🤔

**Comment by janhesters** [comment]
@Jolg42 

> Note: the Rust author of the cuid create wants to add support for cuid2 in the crate 💚 . Let's check back once it's done.

The crate has since been published 😊👍 

https://crates.io/crates/cuid2/

**Comment by reubenporterjisc** [comment]
Hi, any updates on whether this will be added into prisma when using `cuid()` to generate ids?

**Comment by jitterbux** [comment]
Any news on CUID2?

**Comment by reubenporterjisc** [comment]
Hi, any updates on this? If this was built into Prisma it would save all of the manual workarounds. Thanks!

**Comment by njoshi22** [comment]
OK I'm surprised this is still open - any updates here?

**Comment by kakarot-dev** [comment]
Why is this still not implemented?

**Comment by demsey2** [comment]
2.9K issues, 168 PRs, they must have some issue with people/projects management

**Comment by DePasqualeOrg** [comment]
> I think there might be some performance considerations in moving away from sequential K-Sortable ids like cuid v1 or uuid.
> 
> cuid v2 isn't K-Sortable and is also harder to cursor paginate.

See the section on performance here:

[https://github.com/paralleldrive/cuid2#note-on-k-sortablesequentialmonotonically-increasing-ids](https://github.com/paralleldrive/cuid2#note-on-k-sortablesequentialmonotonically-increasing-ids)

> TL;DR: Stop worrying about K-Sortable ids. They're not a big deal anymore. Use createdAt fields instead.

**Comment by cryptrr** [comment]
The problem with createdAt fields is that it will kill Prisma's cursor pagination feature.

In that case you need an extra database call to get the createdAt field of the row before you can do any further pagination operation

**Comment by cryptrr** [comment]
Yep, everyone uses cryptologically generated strings for such purposes, not cuids.

The problem here must be that CUID being sortable basically enables the cursor based pagination feature of prisma. 

Must be the reason why they are not migrating to cuid2

**Comment by cyrilchapon** [comment]
Surprisingly, am I the only one here with the exact same requirement; but different use-case ? ☺️

Cuid2 tend to have another strong advantage against cuid1 : configurable length. I'm in a situation where I'd love to (voluntarily) reduce the collision-safety and the ids length; just for the pleasure to have short ids.

Thus, I just would love to can :

```prisma
  id  String  @id @default(cuid2(length: 10))
```

**Comment by sooxt98** [comment]
I can see there's half baked cuid2() that doesn't support custom length yet
https://github.com/prisma/prisma-engines/pull/[4218](https://github.com/prisma/prisma-engines/pull/4218)

**Comment by nrdobie** [comment]
I have made a slightly more improved version of the extension that will automatically apply to all models without having to continuously update the extension.

https://gist.github.com/nrdobie/c8255815b0083acf98be3e84bfd7c8a8

```typescript
import { createId } from "@paralleldrive/cuid2";
import { Prisma } from "@prisma/client";
import { produce } from "immer";

const cuid2Extension = Prisma.defineExtension({
  name: "cuid2",
  query: {
    $allModels: {
      create({ query, args }) {
        const argsWithNewId = produce(args, (draft) => {
          draft.data.id = createId();
        });

        return query(argsWithNewId);
      },
      createMany({ query, args }) {
        const argsWithNewIds = produce(args, (draft) => {
          if (Array.isArray(draft.data)) {
            draft.data = draft.data.map((item) => {
              item.id = createId();
              return item;
            }) as typeof draft.data;
          } else {
            draft.data.id = createId();
          }
        });

        return query(argsWithNewIds);
      },
    },
  },
});

export default cuid2Extension;
```

**Comment by thomasfr** [comment]
Any updates or ETA on CUID2 support for Prisma?

**Comment by nrdobie** [comment]
I converted my solution into a package that is easy to make it easier to use CUID2 with Prisma. I am willing to add additional features if people need some extra complexity.

[prisma-extension-cuid2](https://www.npmjs.com/package/prisma-extension-cuid2)

**Comment by Sczlog** [comment]
> > I think there might be some performance considerations in moving away from sequential K-Sortable ids like cuid v1 or uuid.
> > cuid v2 isn't K-Sortable and is also harder to cursor paginate.
> 
> See the section on performance here:
> 
> https://github.com/paralleldrive/cuid2#note-on-k-sortablesequentialmonotonically-increasing-ids
> 
> > TL;DR: Stop worrying about K-Sortable ids. They're not a big deal anymore. Use createdAt fields instead.

createdAt is not a good choice for cursor as it is not unique

**Comment by dever23b** [comment]
> > > I think there might be some performance considerations in moving away from sequential K-Sortable ids like cuid v1 or uuid.
> > > cuid v2 isn't K-Sortable and is also harder to cursor paginate.
> > 
> > See the section on performance here:
> > 
> > https://github.com/paralleldrive/cuid2#note-on-k-sortablesequentialmonotonically-increasing-ids
> > 
> > > TL;DR: Stop worrying about K-Sortable ids. They're not a big deal anymore. Use createdAt fields instead.
> 
> createdAt is not a good choice for cursor as it is not unique

Unless I'm misunderstanding you, I think the solution for your concern is to pull the (non-sortable) ID in the result fieldset, sorted by createdAt, and use the ID as the cursor to continue pagination.

Forgive me if I'm writing the right answer to the wrong question.  But I believe much of the concern about sortable IDs resolves down to when those IDs are public and can be referenced externally (because then bad actors can guess IDs and potentially access out of scope data).  One potential solution, if you absolutely must use sortable IDs, is to store multiple IDs and keep the sortable IDs private from ever being displayed to users.

**Comment by birukbelay** [comment]
> this

i agree with this, why are we removing the old one, there are case one may want to use k-sortable ids, And the security issue is dependent on your use-case, there are cases where you might even need to use the int auto increment as an id, you don't create an issue on that saying it is insecure, it is not a bug it is a feature

**Comment by dvins** [comment]
It's great that Prisma now has UUID v7 support, but instead of adding more new things can we address the security issues in existing support, namely replacing `cuid` with `cuid2`?

**Comment by mplanchard** [comment]
> i agree with this, why are we removing the old one, there are case one may want to use k-sortable ids, And the security issue is dependent on your use-case, there are cases where you might even need to use the int auto increment as an id, you don't create an issue on that saying it is insecure, it is not a bug it is a feature

I also agree with this take. I'll be updating the rust crate shortly to remove the deprecation warnings on CUID1 functions, and will commit to supporting both 1 and 2 variants going forward. Hopefully will get that done and a new release out this week.

Note that I do not work for and am in no way associated with prisma, so this has minimal bearing on the issue being discussed here, I think.

**Comment by birukbelay** [comment]
> > i agree with this, why are we removing the old one, there are case one may want to use k-sortable ids, And the security issue is dependent on your use-case, there are cases where you might even need to use the int auto increment as an id, you don't create an issue on that saying it is insecure, it is not a bug it is a feature
> 
> I also agree with this take. I'll be updating the rust CUID crate shortly to remove the deprecation warnings on CUID1 functions, and will commit to supporting both 1 and 2 variants going forward. Hopefully will get that done and a new release out this week.
> 
> Note that I do not work for and am in no way associated with prisma, so this has minimal bearing on the issue being discussed here, I think.

thanks, that would be amazing, and am glad you see the benefit of having cuid variant 1, i hope the prisma team will also see it that way.

**Comment by mplanchard** [comment]
FYI I have published a new version of `cuid` that un-deprecates v1 CUIDs instead providing disambiguated top-level functions like `cuid1()` and so on. 

The top level `cuid()` function remains deprecated (since it is not version specific) and will be removed in a future release. Please use `cuid1()` or `cuid2()` instead.

The other major feature of the release is that we now verify we can build for the `wasm32-unknown-unknown` and `wasm32-wasi` targets, so it should be possible to include `cuid` or `cuid2` in libraries being built for WASM targets. Especially with the full deprecation of v1 CUIDs by the team maintaining the original JS implementation, it is my intent to at some point provide JS bindings to the rust library as well. 

Note that because system hostname is not available on WASM, we are instead using a randomized value when constructing the fingerprint for v1 CUIDs. The fingerprint is only calculated once, so it will be consistent for the duration of a process, but unlike on other systems, it will not be consistent for the same host across runs. If that is a problem for you, please raise an issue so we can discuss it.

The release also includes a few other quality of life improvements. Please see the release notes for details: https://github.com/mplanchard/cuid-rust/releases/tag/cuid-v1.3.3

**Comment by anaibol** [comment]
+1

**Comment by jacstrong** [comment]
Any movement on this?

**Comment by anaibol** [comment]
+1

**Comment by kaeon** [comment]
+2

**Comment by jkomyno** [comment]
Hey folks! It's been a while, but `cuid(2)` support is expected for the next release (ETA: before the end of November 2024)!
`@default(cuid())` is interpreted as `@default(cuid(1))`, so we keep generating cuid v1 by default, as usual.
Thanks for the patience, we'll hope you'll enjoy this upcoming release :) 

---

@mplanchard, I've read [your comment](https://github.com/prisma/prisma/issues/17102#issuecomment-2295467786), but as you can see from https://github.com/prisma/prisma-engines/pull/5047's description, I wasn't able to run `cuid@1.3.3` out-of-the-box due to incompatibilities with the `wasm32-unknown-unknown` target.
Feel free to check out my changes (on behalf of Prisma) [here](https://github.com/prisma/cuid-rust/tree/v1.3.3-wasm32-unknown-unknown) instead. If you'd be down, we'd love to contribute this upstream.

**Comment by carlosyan1807** [comment]
wow, finally.
thank you!!

support custom length and fingerprint?

**Comment by mplanchard** [comment]
@jkomyno happy to accept changes upstream! Also happy to make necessary changes, but it's not immediately clear to me from skimming that MR what needs to be changed for wasm32-unknown-unknown

**Comment by ericelliott** [comment]
I realize this is an old, closed thread, just want to clarify that v1 was deprecated because it leaks the generation timestamp - all other id specs that also leak generation timestamp are also vulnerable, including any Rust port implementation of the original algorithm. There are links to actual security incidents that resulted from timestamp leaks in the Cuid2 docs.
