### ISSUE TITLE
printDatasource: bring SQL Server on par with PostgreSQL = print database name, schemas & location

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#17237]
For PostgreSQL we do for example
```
Datasource "my_db": PostgreSQL database "test1", schema "public" at "localhost:5438"
```
Only for the relevant CLI commands where a connection url might be used used.

But for SQL Server since the connection url is different, it's a JDBC string, we didn't implement the parsing and only output 
```
Datasource "my_db": SQL Server database
```

We could do better here and do the same as PostgreSQL, in https://github.com/prisma/prisma/pull/16868 we added support for printing the `schemas` from the datasource block.

Code is here for the printing 
https://github.com/prisma/prisma/blob/main/packages/migrate/src/utils/printDatasource.ts

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
