### ISSUE TITLE
`migrate dev`: Do not create and drop shadow database when there are not migrations to apply on it

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17309]
Testing of https://github.com/prisma/prisma/issues/17160 indicates that we are also trying to create a shadow database and later drop it again when we do not even have any migration files to apply to it we could diff against. This is wasteful and makes understanding things much harder to understand, especially when they go wrong like in #17160.

I suggest we skip any shadow database related logic when there are not migration files. We can assume the resulting schema would be empty.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
