### ISSUE TITLE
Migrate a database without downtime

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma#1730]
Hi guys.

What about migrating a database without downtime on production? I think we should start planning this to avoid catastrophes within the production database.

I know Prisma offers some mechanisms to alter data structure but I feel like it is not enough. I mean it is not a smooth transition. Let me explain you why.

Imagine an API processes many requests to make payments. It could be catastrophic if you deploy exactly at the same moment that the API is processing data and other requests to external services on behalf of the users. You could also have other good reasons, among others, such as don't bother users with internal errors and giving them a bad experience, or just don't interrupt your sales and keep making money.

Whatever your reason is, in order to avoid this, there are patterns when migrating a database without downtime (you could want to [read more about this](https://www.google.no/search?q=How+to+migrate+a+database+without+downtime%3F)).

Could it be possible to avoid these issues and automate the transition in a better way without downtime?

**Comment by sorenbs** [comment]
Thanks for bringing this up @jferrettiboke 

The first link from your google search is a good primer on migrating databases without downtime. https://dzone.com/articles/safe-database-migration-pattern-without-downtime
It is a pattern that can be applied to any database including Prisma. It is quite a lot of work to do, so that is why we don't require Prisma users to follow a pattern like this.

We will document these patterns better in the future, and maybe add features that makes it easier to achieve zero-downtime deployments for complex changes to your data schema.
