### ISSUE TITLE
Differentiate P1001 between "not reachable" and "timed out"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17534]
Issues like https://github.com/prisma/prisma/issues/17529 show that it would be highly beneficial to differentiate to the users if the connection was just too slow, or if there really is no database behind.

Possible differentiated error messages:

1. `Can't connect to database server at ...`
2. `Can't connect to database server at ... after 'timeout' of Xs`

Internal discussion: https://prisma-company.slack.com/archives/CEYCG2MCN/p1673460751726619

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
