### ISSUE TITLE
Warning for too many active clients is shown even when past clients got disconnected

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#17560]
This code:

```ts
  for (let i = 0; i < 11; i++) {
    const prisma = new PrismaClient()
    await prisma.$connect()
    await prisma.$disconnect()
  }
```

still produces the warning:

```
warn(prisma-client) There are already 10 instances of Prisma Client actively running.
```

even though previous client instances got disconnected and no longer active.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
