### ISSUE TITLE
Emit a warning when database URL is pasted directly into the schema

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#17640]
## Problem

It should generally be considered a bad practice to paste a private database URL into the schema directly. If the user commits that schema by accident somewhere, or deploys it somewhere, they will be exposed to a security risk.

## Suggested solution

I suggest that we emit a warning on `prisma generate` (maybe others too?) when we detect any URL that isn't pointing to `localhost` or `127.0.0.1` is pasted in the schema. This way, we can raise awareness around security and suggest users to either use `.env` or environment variables.

**Comment by petradonka** [comment]
Hi @kunal00000 👋  Thank you for opening the PR 🙌  

As we reviewed your PR, we have noticed that the warning we had intended to show up when you run `prisma generate` with a private database URL in your schema was already present. That's a miss on us, we had another issue tracking that work, and didn't close this one when we completed it.

We really appreciate the time and effort you've put into this though, and would still like to recognize that with rewarding you the bounty, as you were our first bounty-hunter! 🌟

**Comment by janpio** [comment]
This was implemented as part of https://github.com/prisma/prisma/pull/20731, which was shipped with [release 5.2.0](https://github.com/prisma/prisma/releases/tag/5.2.0).

**Comment by kunal00000** [comment]
Hi @petradonka, thank you for your kindness 🙏. Would you like to get this done in other commands too (as I saw that it was not present in the `prisma migrate dev` command).

**Comment by janpio** [comment]
No, we intentionally only want a warning in `prisma generate` because that is the only command that actually persists a hard coded value in the generated Client. For `migrate dev` we feel that having a hard coded URL is a valid use case, and if you go into dangerous territory with `prisma generate` - you _will_ get the warning.

We might tighten that later, but for now we are waiting for feedback on this level of deterrant of putting a plain connection string.
