### ISSUE TITLE
Prisma engines not found for Linux

### ISSUE THREAD

**Issue by saharshg** [prisma/prisma#17677]
### Bug description

While running `npx prisma init` it throws this error:
Downloading Prisma engines for Node-API for debian-openssl-1.1.x [ ] 0%Error: request to https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/debian-openssl-1.1.x/prisma-fmt.gz.sha256 failed, reason: unable to verify the first certificate

I believe the prisma binaries are missing from npm

### How to reproduce

1. Install prisma for nodejs
2. Run `npx prisma init`

### Expected behavior

It should generate prisma/schema.prisma

### Prisma information

schema.prisma is not generated

### Environment & setup

- OS: Ubuntu 20.04.5 LTS, 64-bit
- Database: Postgres with Supabase
- Node.js version: v18.12.1

### Prisma Version

```
4.9.0
```

**Comment by janpio** [comment]
This sounds like a network problem on your machine. Can you download https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/debian-openssl-1.1.x/prisma-fmt.gz.sha256 manually in your browser? What about via `wget` in the command line?

**Comment by saharshg** [comment]
I am able to download this engine directly but not sure why it throws error saying unable to verify first certificate

**Comment by janpio** [comment]
That would be node not being happy with the certificates in your environment, and hence dismissing the download.

You might be able to workaround it by setting `PRISMA_ENGINE_MIRROR="http://binaries.prisma.sh` as an environment variable before executing the command. This will download the engines via HTTP instead of HTTPS which should not have this problem
