### ISSUE TITLE
.prisma/client: Name can't start with a dot

### ISSUE THREAD

**Issue by atulshrma91** [prisma/prisma#17685]
### Bug description

When prima client is generated with custom output path, it throws error `.prisma/client: Name can't start with a dot`
<img width="842" alt="Screenshot 2023-02-02 at 12 29 24 AM" src="https://user-images.githubusercontent.com/17331167/216137738-bc0fb4bf-1c79-409a-9d0c-01bac37c38d7.png">

### Expected behavior

I want to run yarn normally after manually generating the client.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.13.2

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
```

**Comment by atulshrma91** [comment]
This occurs in monorepo workspace when custom output path for the prisma client is specified in schema.prisma using `yarn` instead of `npm`

**Comment by janpio** [comment]
Thanks for the additional information, that is helpful. Can you maybe create a minimal reproduction and put it on GitHub? That would be optimal for us reproducing and understanding the problem. Thanks.

**Comment by apopant** [comment]
I thought that `GENERATED_PACKAGE_NAME` is the issue here
https://github.com/prisma/prisma/blob/50ae94a9c0c63cb869b0bc3cbd2798db896e31ca/packages/client/src/generation/generateClient.ts#L24

but I changed the monorepo setup so that it is generated within a project but ignored by TypeScript and use relative imports instead of `.prisma/client`

Details:
- generate the client within my db provider, but outside of src (I selected build output, since it is already ignored on that repo) `output  = "../build/prisma-client"`
  - db-provider-service
    - build
      - prisma-client
    - prisma
      - schema.prisma
    - src
      - index.ts with `export * from '../build/prisma-client';`
- within my db provider import it from build (and the yarn build script contains `prisma generate`)
  - `import { Prisma, PrismaClient } from '../build/prisma-client';`


for watching changes (watch in parallel with prisma watch and tsc -w) I can do it hacky through tsconfig
```
  "include": ["src"],
  "files": ["build/prisma-client/index.d.ts"],
```
```
    "watch:prisma": "prisma generate --watch",
    "watch:ts": "tsc -b -w --preserveWatchOutput",
    "watch": "run-p watch:prisma watch:ts",
```

**Comment by millsp** [comment]
Hey @atulshrma91 we have fixed this issue by generating a valid name of the form `prisma-client-<unique_id>` and getting rid of `.prisma/client`. We also added an end to end test with `yarn` classic. You can already try it out via `@prisma/client@dev`.

**Comment by cpojer** [comment]
Is there a reason why the prisma client id has to be dynamic with a unique id? With Prisma 5.9.0+, when using a custom client name, eslint plugins like [`eslint-plugin-import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) will complain that the name listed in the client's `package.json` is not listed in the project using prisma. I assume that previously the fake `.prisma/client` id was referred to by another prisma package directly which is no longer the case.

The only workaround I've found is to patch that eslint plugin to ignore the prisma client name.

Instead of giving it a unique id, could you not just use the specified `clientOutput` name for both the folder name as well as the package name? That would make things a lot simpler.

**Comment by SevInf** [comment]
@cpojer could you open an issue and provide the reproduction?
We add unique id because in some cases, if you have multiple clients with the same package name and version combination at different locations, Typescript will merge type declarations from those locations together and that will break all the clients. Using just the output name in those cases will not guaranteed to prevent that from happening.

**Comment by cpojer** [comment]
Here you go: https://github.com/prisma/prisma/issues/22967

Repo with repro: https://github.com/cpojer/prisma-eslint-repro
