### ISSUE TITLE
Simplify running database tests locally

### ISSUE THREAD

**Issue by eviefp** [prisma/prisma#17817]
Right now, the way I run tests locally is:

```bash
make dev-<some_db>
cat .test_database_urls/some_db
# copy that connection string
env TEST_DATABASE_URL="<paste>" cargo test ...
```

And if I need to switch, I'll have to do everything all over again.

This gets significantly worse if something changes and I need to update, say, the tests for all PG versions (we run PG 9, 10, 11, 12, 13, 14, and 15).

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
