### ISSUE TITLE
Warn when using generated Prisma Client that is older than `@prisma/client` in `package.json`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17848]
Internal context: https://prisma-company.slack.com/archives/C9D3H0P1A/p1675967998029079?thread_ts=1675965809.195339&cid=C9D3H0P1A

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
