### ISSUE TITLE
Prisma trace has unaccounted time

### ISSUE THREAD

**Issue by arcticmatt** [prisma/prisma#17853]
### Bug description

I recently implementing Prisma tracing, but have noticed that many of my traces have unaccounted time.

For example, see the screenshot below (from Honeycomb). `prisma:engine:serialize` finishes pretty quickly, but the entire operation takes *much* longer, and it's quite unclear why.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/4356178/217980899-ffceda06-238d-40c9-915d-bf4dcfc9ff25.png">

Here's another example.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/4356178/217981242-d8a84b01-8ce7-4abf-ab2d-749548c3e347.png">

### How to reproduce

Here's the code I'm running to register tracing:

```
export default function registerTracing() {
  const contextManager = new AsyncHooksContextManager().enable();

  api.context.setGlobalContextManager(contextManager);

  const traceExporter = new OTLPTraceExporter({
    headers: {
      "x-honeycomb-team": getApiKey(),
    },
    url: "https://api.honeycomb.io/v1/traces",
  });

  // Configure the trace provider
  const provider = new BasicTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: getServiceName(),
      [SemanticResourceAttributes.SERVICE_VERSION]: "1.0.0",
    }),
    sampler: new ParentBasedSampler({
      root: new TraceIdRatioBasedSampler(0.01),
    }),
  });

  if (isProd()) {
    provider.addSpanProcessor(new BatchSpanProcessor(traceExporter));
  } else {
    provider.addSpanProcessor(new SimpleSpanProcessor(traceExporter));
  }

  // Register your auto-instrumentors
  registerInstrumentations({
    instrumentations: [new PrismaInstrumentation({ middleware: true })],
    tracerProvider: provider,
  });

  // Register the provider
  provider.register();
}
```

### Expected behavior

I expect Prisma's spans to accurately reflect how long the entire operation takes.

### Prisma information

See above for code that registers tracing.

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
4.4.0
```

**Comment by aqrln** [comment]
This is most likely caused by concurrency. Right now we set the `spanId` and `parentSpanId` via the internal Span constructor for the engine spans re-created in the `@prisma/instrumentation` package so the engine subtree is correct itself, but it's not guaranteed that it's being attached to the correct `prisma:client:operation` client span because we're not actually setting the parent ID for the top level engine span, we're relying on us being in the correct client span at the time we receive the spans in the engine logs which is actually not true when there are concurrent queries.

I will check if this is the case and let you all know the result.

We are also fixing how the engine to client span conversion works, so if this is the cause, it's going to be fixed soon.

(https://github.com/prisma/prisma/issues/19580#issuecomment-2461798257)
