### ISSUE TITLE
`... the provided database credentials for `(not available)` are not valid.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17977]
```
➜  workspace git:(master) ✗ npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "mydb", schema "public" at "localhost:26257"

Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `(not available)` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
```

The `(not available)` is totally unexpected there and unclear why that happens.

See this Codesandbox for state of project: https://codesandbox.io/p/sandbox/runtime-frost-pxfzom?file=%2F.env&selection=%5B%7B%22endColumn%22%3A81%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A7%7D%5D
(Rough description: Docker Compose with Cockroach DB, connection string for that but with `postgresql` provider)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
