### ISSUE TITLE
Consider using TypeScript decorators instead of the `schema.prisma` DSL

### ISSUE THREAD

**Issue by distributev** [prisma/prisma#1805]
Many years ago Java did not have annotations so many frameworks (ORM, webservices and all other framework types) were using code generation. This practice came along with unnecessary complexity and random "edge cases" and because of that was almost completely replaced once the Java language got support for annotations. 

Typescript already has support for Decorators and Interfaces. 

https://www.typescriptlang.org/docs/handbook/decorators.html

The same information which is currently provided through the schema.prisma could be provided through couple of TypeScript annotations on top of plain TypeScript model objects. You continue to get all the benefits of TypeScript while getting rid of the complexity which code generation comes with. When I say complexity I refer to the extra "code generation" step which is required for the developer to remember to execute + the possible extra errors / situations which are usually triggered by the "code generation" step and which the developer has no other option but to deal with the new possible errors / situations. At that point the question I asked myself was "Is the code generation really necessary? Do I really need to write in the prisma.schema language and then generate TypeScript  when I could write directly in TypeScript?"

Below is an example of a Java project which is using annotations to provide GraphQl meta-information

https://github.com/Enigmatis/graphql-java-annotations

From the ORM perspective here is how JPA annotations are used to configure persistence.

https://www.baeldung.com/jpa-entities

Java Persistence API -

The Java Persistence API (JPA), in 2019 renamed to Jakarta Persistence, is a Java application programming interface specification that describes the management of relational data in applications using Java Platform, Standard Edition and Java Platform, Enterprise Edition/Jakarta EE.

https://en.wikipedia.org/wiki/Java_Persistence_API

**Comment by distributev** [comment]
another good alternative might be to provide TypeScript annotations as a 2nd option to the existing schema.prisma for developers which prefer to stay 'code generation' free

**Comment by yi-ge** [comment]
another good alternative might be to provide json schema generate schema prisma.

**Comment by J-Rojas** [comment]
The Prisma team has acknowledged the need for ['code-first](https://www.prisma.io/graphql)' approaches in tools like TypeGraphQL, but they haven't built something that would address the gap in schema generation from code.

**Comment by thebiglabasky** [comment]
Hi,
The reason for having the Prisma schema is to allow addressing more than TypeScript as a language: there are a lot of people using JavaScript, and we also have a Go client that uses the same schema. The PSL then allows easier versioning of the schema, generation of migrations declaratively. It also allows getting custom generators built by the community to generate more specific outputs (e.g. DBML, TypeGraphQL...)
By acting as the single source of truth for the schema, it helps to get a holistic understanding of it at a glance.
We don't plan to replace it with annotations as that would make Prisma TypeScript-specific and lose a handful of benefits outlined above.
We're interested in providing more flexibility so that people could have more control over types we generate or customize these, and as such we're interested in specific problems users face which we could address.
Examples: 
* https://github.com/prisma/prisma/issues/5273
* https://github.com/prisma/prisma/issues/5258
* https://github.com/prisma/prisma/issues/5998
Meanwhile, I'll close this issue as we're not considering doing that anytime soon.
Thank you!

**Comment by n4an** [comment]
> Hi, The reason for having the Prisma schema is to allow addressing more than TypeScript as a language: there are a lot of people using JavaScript, and we also have a Go client that uses the same schema. The PSL then allows easier versioning of the schema, generation of migrations declaratively. It also allows getting custom generators built by the community to generate more specific outputs (e.g. DBML, TypeGraphQL...). By acting as the single source of truth for the schema, it helps to get a holistic understanding of it at a glance.
> 
> We don't plan to replace it with annotations as that would make Prisma TypeScript-specific and lose a handful of benefits outlined above.
> 
> We're interested in providing more flexibility so that people could have more control over types we generate or customize these, and as such we're interested in specific problems users face which we could address.
> 
> Examples:
> 
> * [Service Classes (e.g. for NestJS) #5273](https://github.com/prisma/prisma/issues/5273)
> * [Document, how to use Prisma in a wrapper function #5258](https://github.com/prisma/prisma/issues/5258)
> * [Convert the Models from Types to Classes #5998](https://github.com/prisma/prisma/issues/5998)
> 
> Meanwhile, I'll close this issue as we're not considering doing that anytime soon. Thank you!

Thar are very ugly, decorators are cool!
