### ISSUE TITLE
Generate `@prisma/client` even when schema is empty?

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1809]
Origin https://github.com/prisma/prisma2/issues/1592

Is it something we want to do?

If so we'll need to change `generate` errors into warnings and think of a nice DX when using the (empty) generated client in code.

**Comment by janpio** [comment]
Can we we actually generate anything with no models?
What happens if you try to use that?
How can we tell users trying to use that empty Client what is going on?

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/121665749-23ecf800-cac6-11eb-911e-3fbe336a295b.png)

This is the current behavior. It doesn't generate the client which is correct imo.

I am going to close this discussion.

**Comment by RyanHedges** [comment]
First time using Prisma in a project so if there is something I'm not understanding, please share! 😄 

I'm in the processes of initializing a new application. Please note, that while developing I often try to make small commits with changes that are always ready to be deployed. For example, I have a commit that "adds prisma client package in package.json", and a following commit that sets up how I'll interact with the Prisma client wrapped in a service object. In a future commit, when I'm implementing business logic, I was planning on adding the models/migrations I need.

Now I realize I can just and add business logic to my prisma client initialization commit, but I'd like to keep it separate if possible.

With the current behavior, I cannot launch my app because prisma client fails (as expected based on this thread) with 
```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```

and the `npx prisma generate` fails with the previously posted image.

I think it could be beneficial to have a way to integrate with Prisma client without having to immediately pair it with a model. Even if it's something where I have to explicitly type in into `schema.prisma` something like `skip` to change the default behavior.

I'm using Prisma in Nest.js v8. Thanks!

**Comment by Jolg42** [comment]
Hi @RyanHedges, thanks for the feedback!

You could try setting the following env var to true:
```
PRISMA_SKIP_POSTINSTALL_GENERATE=true
```
Which will disable the `generate` triggered during the `postinstall` lifecycle and not error anymore.

I don't think it covers what you want to do completely though and would recommend creating [a new issue ](https://github.com/prisma/prisma/issues/new/choose).

**Comment by RyanHedges** [comment]
Thanks for responding @Jolg42! I'll try out your suggestion and open up an issue if needed.
