### ISSUE TITLE
Interactive error report tests seem to have stopped working in Prisma Migrate

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#18097]
### Bug description

Interactive error reports seem to have stopped working in Prisma Migrate. This test is never run on CI so it never failed. I noticed this while updating the snapshots locally, which means it broke not too long ago.

https://github.com/prisma/prisma/pull/18089/files#diff-d8fe3ac965967ca6d525d527c6676c9b9a10a1aae9107958ef0f743a56f476f0L146-L165

### How to reproduce

Run the tests

### Environment & setup

- OS: Ubuntu 20.04
- Database: n/a
- Node.js version: 18

### Prisma Version

```
4.11.0-dev
```

**Comment by janpio** [comment]
Either this broke during 4.11.0 work, or this is not a universal problem as we have error reports for 4.10.1 from `prisma migrate` commands.

**Comment by jkomyno** [comment]
Interactive error reports still work for `migration-engine`. Looking at the tests to see what may be wrong there.

**Comment by millsp** [comment]
(Added this to Schema Team Planning)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
