### ISSUE TITLE
Database timeout error message (for wrong port)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1824]
During testing I messed up the port (for a MySQL database), and got this quite basic error message:

```
C:\Users\Jan\Documents\throwaway\1817>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Operation timed out (quaint timeout: tokio timeout)
```

Would be nice if that would be a bit more elaborate and possibly helpful.

**Comment by pantharshit00** [comment]
I got a pretty descriptive error message if I put the wrong port:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/22195362/76754697-8e6e9580-67a8-11ea-8b79-8e35ade96a3d.png">


I investigated further, this happens when a postgres instance is running instead of a mysql instance on the specified port:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/22195362/76754756-a6deb000-67a8-11ea-9661-7d37a9f88fb1.png">

Now we need to somehow detect which database we are actually introspecting and compare it with the given datasource in the url.

**Comment by janpio** [comment]
That might already be tracked via https://github.com/prisma/prisma2/issues/1736

What I am asking myself though: Why is the error message different?

**Comment by pantharshit00** [comment]
@janpio Is this still actionable now? Do you think we want to change the error message here?

**Comment by janpio** [comment]
If the error message is still about quaint and tokio timeout in the original case, then yes.

**Comment by pantharshit00** [comment]
We don't leak tokio and quaint in error message any more:
![image](https://user-images.githubusercontent.com/22195362/117015919-cf5c9d00-ad0f-11eb-8068-4549c9cfda2b.png)
