### ISSUE TITLE
Argument for `prisma studio` that injects a model for `_prisma_migrations` so it can be reviewed and modified with Prisma Studio

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#18311]
Right now you can not easily use Studio to review `_prisma_migrations` and its content. By injecting a predefined model into the schema for Studio, we could enable that easily.

Tasks:
- Figure out Prisma model reflecting `_prisma_migrations` (probably easiest via renaming an example created by Prisma into a different name so that Introspection/`db pull` does not ignore it any more)
- Expand `prisma studio` CLI command to have a parameter that modifies the schema file in memory (add model for `_prisam_migrations`) before handing it over to Studio
- Maybe: Handle errors when migration table does not actually exists

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
