### ISSUE TITLE
Filter and other arguments exposed in `select` call

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1833]
When I want to `select` fields from related objects, e.g.:

```ts
const result = await prisma.user.findMany({
    select: {
      id: true,
      posts: {
        select: {
          id: true
        }
      }, 
    }
})
```

I get objects like this back:

```js
[{"id":1,"posts":[{"id":1},{"id":2}]}]
```

However, I can also include `where` and other arguments in `posts` inside `select`:

```ts
const result = await prisma.user.findMany({
  select: {
    id: true,
    posts: {
      where: {
        id: {
          in: [1, 2, 3],
        },
      },
      select: {
        id: true,
      },
    },
  },
})
```

The resulting structures are the same. Are these arguments exposed on purpose. If so, what do they mean in this context? (What would be a situation where providing them impacts the fields on the returned model objects?)

**Comment by pantharshit00** [comment]
I tested this out and these arguments are meant to filter the selection result.
Since in your data, you have posts with id 1,2 which satisfies the in id 1,2 and 3 condition, it returns the exact same data.

With my code as following:
![image](https://user-images.githubusercontent.com/22195362/76865728-28a60a80-6889-11ea-92d5-1932f385775d.png)


The `where` parameter correctly filters out the posts:
![image](https://user-images.githubusercontent.com/22195362/76865776-378cbd00-6889-11ea-85e1-780bf887ee99.png)

(First run is without `where` parameter and the second run is with the `where` parameter.)


So these parameters are important if you want to do nested filtering.

**Comment by nikolasburk** [comment]
If that's the case, shouldn't filtering be applied on the same level as `select`?

```ts
const result = await prisma.user.findMany({
  where: {
    id: {
      in: [1, 2, 3],
    },
  },
  select: {
    id: true,
    posts: {
      select: {
        id: true,
      },
    },
  },
})
```

It feels wrong that the filtering happens _inside_ of `select`, I don't think that's intentional 🤔

**Comment by pantharshit00** [comment]
For future readers here, main distinction here is `where` inside of select filters the records per parent row while the top level one will filter out the parent row completely if it doesn't match the condition
