### ISSUE TITLE
impr: `directUrl` env var validation

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#18348]
When using `directUrl` pointing to an env var, we do not validate whether the underlying value is actually a `directUrl` or not.

i.e. if one accidentally sets a `directUrl` to be `postgresql://...`, the cli throws an error that using the data proxy is not supported for this command. It would be helpful if it would also then point out the env var mistake. That `directUrl`s are expected to be of `prisma://...` shape

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
