### ISSUE TITLE
Release process: separate publishing to npm registry and updating `latest` tag.

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#18477]
Right now, they are performed in a same step. Splitting them would allow us to:

- Prevent partial publish situations, where release script fails somewhere in the middle.
- Perform some of release verification steps before updating `latest` and detect some of the packaging problems before they get to the users.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
