### ISSUE TITLE
SQL logs with Accelerate have a trailing space at the end

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#18480]
SQL logs with Data Proxy have an extra space at the end compared to logs with regular client.

This is not a big issue but it may be annoying when doing things like snapshot testing and switching between direct connection to the database and the Data Proxy.

#### Steps to reproduce:

1.  Use Data Proxy client
2.  Enable query logs: `const prisma = new PrismaClient({ log: [{ emit: 'event', level: 'query' }] })`
3.  Add event handler: `prisma.$on('query', (e) => console.log(JSON.stringify(e.query)))`
4.  Do some queries so that events are emitted

```diff
             without Data Proxy ↓
-"SELECT ... WHERE 1=1 OFFSET $1"
+"SELECT ... WHERE 1=1 OFFSET $1 "
                 with Data Proxy ↑
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
