### ISSUE TITLE
Add `binaryTargets` aliases for common deployment targets

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#18555]
At the moment, users need to know which OS/distro their deployment target uses and what OpenSSL version it uses. We could simplify the life for them if we introduce aliases for common deployment platforms. For example:

```
"aws-lambda" = "rhel-openssl-1.0.x"
"vercel" = "rhel-openssl-1.0.x"
"azure" = "debian-openssl-1.1.x""
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
