### ISSUE TITLE
@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### ISSUE THREAD

**Issue by morshedulmunna** [prisma/prisma#18606]
### Bug description

My prisma Generate already Done. but still show this error when i running the server.

`[Nest] 6788  - 04/03/2023, 2:57:04 AM   ERROR [ExceptionHandler] @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.`

// This is your Prisma schema file,

```
generator client {
  provider = "prisma-client-js"
  output   = "./generated"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum Status {
  true
  false
}

model User {
  id       Int     @id @default(autoincrement())
  name     String?
  email    String  @unique
  phone    String?
  password String
  todo     Todo[]
}

model Todo {
  id         Int      @id @default(autoincrement())
  todo       String
  createDate DateTime @default(now())
  updateAt   DateTime @updatedAt
  status     Status   @default(true)
  userId     Int
  User       User?    @relation(fields: [userId], references: [id])
}

```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
 "prisma": "^4.12.0",
     "typescript": "^5.0.3"
```

**Comment by jkomyno** [comment]
Hi @morshedulmunna, could you please show us the directory structure of your project, and how you import the Prisma Client in TypeScript/JavaScript?

We see you're using a custom `output` attribute in the `generator client` block of your schema, which means the artifacts generated by `prisma generate` will be placed in the `./generated` folder you've specified.

**Comment by morshedulmunna** [comment]
it will be fix when i import prisma client from generated folder. 
but when i important from @prisma/client then give a error.

but now its fix.

**Comment by edwardz8** [comment]
add following to package.json:

"build": "npx prisma generate && nuxt build", 

and run npm run build before you push to main.

**Comment by aqrln** [comment]
Hi @morshedulmunna and thanks for opening the issue.

As you already figured out in https://github.com/prisma/prisma/issues/18606#issuecomment-1494145704, when using custom output, you need to import the generated client from the directory it was generated to, that's the expected behaviour.

Importing the client from `node_modules` is only possible when generating the client in the default location in `node_modules` (`node_modules/.prisma/client`), the forwarding shims in the `@prisma/client` package won't be able to find your custom client otherwise. While it may seem that we could patch the files in `@prisma/client` upon generation to forward to the last custom client location, that would be problematic for several reasons:
* Changing the files in an existing package does not play well with how package managers work and can lead to unexpected consequences, and, depending on the package manager, can be reverted when you install or upgrade even unrelated packages.
* It might also defeat the purpose of using a custom output in the first place, and would not make much sense with multiple clients in a single app (which is a common use case for using custom output paths).

I'll go ahead and close this issue, please let us know if there's anything we haven't considered, and please open a new issue if you encounter this error unexpectedly when you don't believe it should happen.
