### ISSUE TITLE
EPERM error on Windows when generating the client in reproductions in the repo

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#18864]
Steps to reproduce:

0. Use Windows
1. Build the Prisma repository
2. Go to `reproductions/basic-sqlite`
3. Run `prisma generate`

```
prisma\reproductions\basic-sqlite on  main [!] via  v18.15.0 took 14s
❯ pnpm prisma generate
> Downloading Prisma engines for Node-API for windows [==========          ] 49%Error: EPERM: operation not permitted, unlink 'C:\Users\Alexey\prisma\packages\engines\query_engine-windows.dll.node'
```

This happens consistently at 49%<sup>&#42;</sup> of downloading when I try again.

<sup>(&#42; at least reported 49%, I suspect it might actually be downloaded at this point)</sup>

**Comment by aqrln** [comment]
Resolved by manually removing the older engine file. Let's see if this happens later with a new engine commit.

Also to add to the footnote in the original post, it does look like the progress indeed ends at around 50% even when all goes well.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
