### ISSUE TITLE
Type-safe configuration

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#18960]
## Problem

Follow up from here https://github.com/prisma/prisma/issues/18907#issuecomment-1524127587.

The current way to configure the Prisma CLI is to put a [field into `package.json` called `prisma`](https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location) and then put the right config in there. The problem with this approach is developer experience in that it is not type safe, has no autocomplete, and offers no opportunity for JSDoc.

## Suggested solution

I imagine that a `prisma.config.ts` (and also support for `.js` `.mjs` etc.) file would have better developer experience. It would require an import to get the benefit of type safety e.g.:

```ts
import { settings } from 'prisma'

export default settings({
  prismaDirectory: './app/prisma/',
})
```

Since these settings would be to configure the CLI the import could come from the `prisma` package.

## Alternatives

There might be a way to get JSON schema setup such that the `prisma` field is typed, but I'm not sure how that would work and what its tradeoffs would be.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
