### ISSUE TITLE
Prisma Client explorer

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1904]
Based on @FluorescentHallucinogen's idea which is described [here](https://github.com/OneGraph/graphiql-explorer/issues/10#issuecomment-590539831), we could build a "Prisma Client explorer" that lets you visually explore the Prisma Client API and create Prisma Client queries.

Here's an [image](https://user-images.githubusercontent.com/7892779/75189579-89956380-575f-11ea-8b06-b622653f895b.png) copied from the mentioned issue that illustrates this idea:

![image](https://user-images.githubusercontent.com/4058327/77307308-4a741700-6cf9-11ea-8c53-57dcada7bc59.png)

A few ideas how this could be realized:

- as part of Prisma Studio
- as a docs page
- as a standalone app

**Comment by Nishchit14** [comment]
It would be a super astonishing feature. It would help us to think the same for Firecamp for Prisma.

**Comment by FluorescentHallucinogen** [comment]
Ideally, this should be a VSCode extension.

**Comment by Nishchit14** [comment]
Got it @FluorescentHallucinogen, means It would work great with Monaco editor, right? I would suggest designing it individually and bind that component with diff editors.

**Comment by FluorescentHallucinogen** [comment]
Any news?

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
