### ISSUE TITLE
Allow field names that start with numbers

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1980]
# Problem

Right now the field names can only _contain_ numbers, but they may not start with them. This prevents from easily introspecting existing schemas where this is the case.

# Suggested solution
1. Introspection policy/configuration: allow users to customize how to transform field names which aren't compatible into another compatible name
2. Upon introspection, prefix fields starting with a number with a standard character, e.g. "_"

## Additional considerations

This will likely involve considerations in the Prisma Client API, since field name can't start with numbers.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
