### ISSUE TITLE
Prisma Client auto-install on generate is not well tested

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19814]
Related https://github.com/prisma/prisma/pull/19259

Optimally, we would have tests for the auto-install during generate.

> So, there are a few reasons these changes would be very tricky to test. One problem is this logic requires an existing Prisma version to install: so either we'd need to implement falling back to last stable version when detecting that this is running in tests, or this would need to be tested in the ecosystem-tests and not here. In the former case, another problem would be that we lack an e2e test setup similar to https://github.com/prisma/prisma/tree/main/packages/client/tests/e2e but for Windows (for the first error message).
> 
> The second error message is even trickier to test because if it was triggered at all, then it's probably a bug by itself.
> 

_Originally posted by @aqrln in https://github.com/prisma/prisma/issues/19259#issuecomment-1594952787_

**Comment by Templer44** [comment]
Hello @Jolg42, 

Looking more into this issue, my team and I have a few questions to ask: 
-What is the scope of the test? What exactly are we testing for when auto-installing during generate? 
-Is this test expected to be done in an e2e windows environment?  
-Are we still testing how the original issue happens due to auto-install?

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
