### ISSUE TITLE
type saftey issue: prisma.table.create() allows input of columns that don't exist

### ISSUE THREAD

**Issue by TamirCode** [prisma/prisma#19827]
### Bug description

For example if I have a model of user:
```ts
model User {
    id        Int      @id @default(autoincrement())
    username  String   @unique
    password  String
}
```
then the query allows me to pass an input that doesn't exist without TS warning me that there is a mistake, unless i put the object directly without creating a variable.
```ts
let myInput = { username: "e", password: "e", email: "e" }
const user = await prisma.user.create({
  data: myInput // typescript doesnt warn me that email doesnt exist
})

const user2 = await prisma.user.create({
  data:  { username: "e", password: "e", email: "e" } // typescript correctly warns me
})
```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: v18.16.0.

### Prisma Version

```json
	"dependencies": {
		"@prisma/client": "^4.15.0",
		"@trpc/server": "^10.29.1",
		"@types/cors": "^2.8.13",
		"cors": "^2.8.5",
		"express": "^4.18.2",
		"zod-prisma-types": "^2.7.4",
		"zod": "^3.21.1"
	},
	"devDependencies": {
		"@types/express": "^4.17.17",
		"@types/node": "^20.3.0",
		"nodemon": "^2.0.20",
		"prisma": "^4.15.0",
		"ts-node": "^10.9.1",
		"typescript": "^5.0.2"
	}

```

**Comment by nullndr** [comment]
This is not a bug with prisma, it is just how typescript and it's structural type system works.

When you do something like: 

```ts
const user2 = await prisma.user.create({
  data: { username: "e", password: "e", email: "e" },
})
```

You are creating an object of type `UserCreateArgs["data"]`, and ts correctly warns you about the key `email` since it does not belong to the type.

In the first case, you are creating the object `myInput` of type `{ username: string, password: string, email: string }`, this type is _structurally_ assignable to `data`, so typescript does not warn you.

In order to check for the `email` keys you have two options:
- correctly type `myInput` 
- the [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator) operator

For more info about the structural type system of typescript, see [here](https://www.typescriptlang.org/docs/handbook/type-compatibility.html).

**Comment by TamirCode** [comment]
Indeed this is default typescript behavior. Prisma is innocent
![image](https://github.com/prisma/prisma/assets/66864667/004b987d-7300-4902-8f5d-1d9454f323dd)
