### ISSUE TITLE
Improve the Schema Relation API

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#1985]
The [latest schema relation API design](https://prisma2.netlify.com/reference/tools-and-interfaces/prisma-schema/relations) is the following:

```prisma
model User {
  id        Int      @id @default(autoincrement())
  posts     Post[]
}
model Post {
  id         Int     @id @default(autoincrement())
  author     User    @relation(fields: [authorId], references: [id])
  authorId   Int
}
```

**I would like to propose a simpler, more intuitive alternative:**
```prisma
model User {
  id        Int      @id @default(autoincrement())
  posts     Post[]
}
model Post {
  id         Int  @id @default(autoincrement())
  authorId   Int  @relation("author", model: User, references: [id])
}
```

1. Simpler because the entire `Post` to `User` relation is 1 line instead of 2 lines.
2. More intuitive because it’s immediately clear which is physical vs which is virtual. A physical field always has a scalar type (`authorId  Int`) and virtual field is always a model (`posts  Post[]`)
3. Then the whole “Link field” concept can be removed (This is a confusing concept, even for people like me who really understand DB design)
4. Compound foreign keys relations can instead be handled by adding `@relation` on a `@@unique` definition like `@@unique([field1, field2]) @relation(...)`

**Comment by Sytten** [comment]
I agree the syntax is nicer but we need a way  to specify the name of the virtual relation when you do something like `prisma.post.findOne().author()`.

**Comment by janpio** [comment]
Thanks for your issue @flybayer. You know we appreciate the feedback ❤️ 

Right now we think the bit more verbose syntax is the right thing to do: We are creating a baseline that we can build on in the future with this - which hopefully will include simplifications or optional parts to get back to a streamlined syntax for the "straightforward" cases.

Your suggestion is actually pretty close to one of the alternatives we looked at internally, but as many others that one started to break down when the combinations become really complicated: Overlapping compound foreign keys with half overlapping indexes and maybe some column renaming thrown in. It took us quite some time to come up with a syntax that covers those.

---

Let me respond to some individual bits from your message, I am curious about your thoughts and if I can explain our thinking a bit:

> `  authorId   Int  @relation("author", model: User, references: [id])`

Right now the first param of `@relation` defines the name of the relation (~ foreign key), but that of course is something that could be changed. I note that you are looking for a way to name the "relation field" here that will be offered by Prisma Client, correct?

> 2\. More intuitive because it’s immediately clear which is physical vs which is virtual. A physical field always has a scalar type (`authorId  Int`) and virtual field is always a model (`posts  Post[]`)

That is actually part of what we are doing, because the fields that make up a relation, still _are_ real fields. In the past you did not really have a way to access both relation and foreign key column, now you do.

> 3\. Then the whole “Link field” concept can be removed (This is a confusing concept, even for people like me who really understand DB design)

We recognized that as well - it was just confusing - and renamed the concept: The keys that are used as `fields` in an `@relation` are now referred to as "relation scalar fields" (the preview docs you link to are also updated). 

Using the example from above:

```
  author    User @relation(fields: [authorId], references: [id]) // relation field
  authorId  Int                                                  // relation scalar field
``` 

Just focusing on this wording, and not the general verbosity, does this make more sense to you than "link field"?

> 4\. Compound foreign keys relations can instead be handled by adding `@relation` on a `@@unique` definition like `@@unique([field1, field2]) @relation(...)`

Why `@@unique`?  
A FK often needs an index on its fields to be allowed (and of course it makes sense for performance reasons), but what is the thought begind mixing these two different concepts together? What if I only want an index that has additional columns at the end (e.g. a,b,c while the FK should only be a,b)

How would you represent a relation over fields `field1` and `field2`, but an additional index over `field2` and `field3`? (Bonus points if one of the database column is also renamed in some way)

---

Thanks again for this feedback.

**Comment by flybayer** [comment]
@janpio the new documentation is much better! The "two line" syntax makes sense now. The relation field directly maps to the foreign key declaration in SQL.

I first posted in Slack asking to understand why the more verbose syntax was chosen, and was encourage to create an issue. So here we are :)

From my perspective, I think this issue can be closed.

**Comment by janpio** [comment]
The wish to improve and simplify the API still is valid and correct - so we can keep this open.

**Comment by janpio** [comment]
A year later, it is clear that we will not change the relation syntax any more as while it might be a tiny bit verbose, it has clear benefits vs. this suggestion (like that you can just remove the relation, but keep the scalar relation field as it is as a normal scalar field in the model)
