### ISSUE TITLE
add CHANGELOG.md

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#1995]
One document that comprises information from https://github.com/graphcool/prisma/releases

**Comment by paolodina** [comment]
Have you considered to use something like this? https://github.com/semantic-release/semantic-release

I'm not confident with semantic release done in js/node, but I use an equivalent of semantic-release for python projects and the whole process (generating CHANGELOG.md too) is greatly simplified. The initial setup might take a bit, but once done everything should work ootb. I noted that project's contributors don't adopt a common convention for commit messages; maybe it'd worth start using [Angular's commit message guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines). my2c

**Comment by johannpinson** [comment]
Effectively, some tools like [comittizen](https://github.com/commitizen/cz-cli) or [standard-version](https://github.com/conventional-changelog/standard-version) can facilite the task, as Lerna for the npm part.

But one important part will be to separate the release of the "Server" and the "CLI" because they don't be necessary linked.
It may be more difficult to adjust the good version of the CLI to use with this or that version of the server, but now the beta is out, both products may have their own release rule.

Another very good point will be the creation of a "Migration" section between release into the docs website, especially when breaking change are added (like the #1947 as example).
