### ISSUE TITLE
When I run this command : npx prisma migrate reset Get an error

### ISSUE THREAD

**Issue by zkrana** [prisma/prisma#20086]
### Bug description

Can anyone please help me to figure out this issues: When I run this command : `npx prisma migrate reset` It shows error:
```
EPERM: operation not permitted, unlink 'C:\Users\shuvo\OneDrive\Desktop\ecommerce-admin\node_modules.prisma\client\query_engine-windows.dll.node'
```
### How to reproduce

This command shows error: npx prisma migrate reset

### Expected behavior

Database reset successful.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  relationMode = "prisma"
}

model Store{
  id          String @id @default(uuid())
  name        String
  userId      String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows 10
- Database: PlanetScale
- Node.js version: v18.13.0

### Prisma Version

```

```
prisma": "^4.16.1

**Comment by Jolg42** [comment]
Looking at your file path `EPERM: operation not permitted, unlink 'C:\Users\shuvo\OneDrive\Desktop\ecommerce-admin\node_modules.prisma\client\query_engine-windows.dll.node'`

This looks like a general issue with Windows when a process is somehow holding on a file, which is probably triggered here by OneDrive.
Try to remove your project from OneDrive or at least make sure `node_modules` are excluded from OneDrive.

Note: this is triggered by `npx prisma migrate reset` because it also runs `npx prisma generate` at the end, you can disable this by passing `--skip-generate` to migrate commands.
But this issue should still happen in the end when running `npx prisma generate`.

**Comment by zkrana** [comment]
Thank you so much. It's solved.
