### ISSUE TITLE
CLI: `generate` should surface better which generator causes an error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20117]
There are cases like https://github.com/prisma/prisma/discussions/20069 where a custom generator causes a crash, and it is very easy to mistake as a Prisma problem as the output does not directly imply which generator crashed. We should explicitly add that and make sure it is easy to understand and connect these dots.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
