### ISSUE TITLE
`this.$on("beforeExit")` doesn't work anymore on 5.0.0

### ISSUE THREAD

**Issue by maxime4000** [prisma/prisma#20171]
### Bug description

Using prisma v5 and having a prismaService, the new code doesn't work anymore.
https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services

### How to reproduce

https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services

### Expected behavior

beforeExit should be a typing option ? now it's never

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```
V5 latest no schema really required

### Environment & setup

- OS: macos
- Database: not important but is mongodb
- Node.js version: 18.16.0

### Prisma Version

```
v5.0.0
```

**Comment by janpio** [comment]
Yes, this is a breaking change:

> ## Removal of the `beforeExit` hook from the `library` query engine
> 
> We removed the `beforeExit` hook from the default `library` Query Engine. We recommend using the built-in Node.js exit events.
> 
> ```diff
> -prisma.$on('beforeExit', () => { /* your code */ })
> 
> +process.on('beforeExit', () => { /* your code */ })
> // Alternatives
> +process.on('exit', exitHandler)
> +process.on('SIGINT', exitHandler)
> +process.on('SIGTERM', exitHandler)
> +process.on('SIGUSR2', exitHandler)
> ```
> 
> We recommend taking a look at the [upgrade guide](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#removal-of-the-beforeexit-hook-from-the-library-engine) to learn how you can migrate to Prisma 5.

https://github.com/prisma/prisma/releases/tag/5.0.0

We'll make sure that guide is updated now.

**Comment by janpio** [comment]
I'll keep this issue open until we have actually updated that guide - this way it is easier for other people to find. 

Thanks for reporting so quickly by the way!

**Comment by divyansh7924** [comment]
@maxime4000 
This works, replace `prisma.enableShutdownHooks(app);` with `app.enableShutdownHooks()` and remove function `enableShutdownHooks` from PrismaService.

Final implementation would look something like this, https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown

**Comment by aqrln** [comment]
Hi @maxime4000 and anyone else who faces the same issue! As already correctly pointed out above, you should use the normal shutdown hooks and lifecycle events in NestJS as you would in any other NestJS application not using Prisma. The Prisma guide in the NestJS documentation and our guides and examples are unfortunately a little bit outdated in this regard: this kind of special integration for shutdown hooks with Prisma hasn't been required for a while already since the introduction of the library engine, but it continued to work as we kept the `beforeExit` event for backwards compatibility until Prisma 5. Sorry for this omission, we will make sure to update everything as soon as possible!

To migrate to the standard NestJS shutdown hooks, you need to do the following steps:
1. Replace the invocation of the custom `prismaService.enableShutdownHooks(app)` method in the application entry point with the built-in `app.enableShutdownHooks()`.
2. (optional, only if applicable) If any custom logic except `app.close()` was added to the `beforeExit` event handler, it must be moved to `onModuleDestroy`, `beforeAppicationShutdown` or `onApplicationShutdown` lifecycle hooks. The difference between them is described in [NestJS documentation](https://docs.nestjs.com/fundamentals/lifecycle-events). `onModuleDestroy` would be the closest equivalent in terms of control flow, but other methods may be more appropriate — use your best judgement.
3. Remove the custom `enableShutdownHooks` method completely from your `PrismaService` class as it’s not needed anymore.

**Comment by DevVictorr** [comment]
I read it in the docs and that way it worked for me

```
async enableShutdownHooks(app: INestApplication) {
    process.on('beforeExit', () => {
      app.close();
    });
  }
```

**Comment by cassepipe** [comment]
The outdated guide was not very clear eithter, it shows this snippet of code :
```typescript
import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```
Which already looks like it's fixing something but then you are refered to another place that mention a problem that you would think the snippet above solves and you are shown another snippet...
```typescript

// main.ts
...
import { PrismaService } from './services/prisma/prisma.service';
...
async function bootstrap() {
  ...
  const prismaService = app.get(PrismaService);
  await prismaService.enableShutdownHooks(app)
  ...
}
bootstrap()

```

This is very unclear. 
And to solve this it seems I have the choice between replacing the problematic call with `process.on`, remove the call altogether...
But I also have to set up the main entry point ? What's the point of calling `app.enableShutdowHooks()` anyways ? It takes no argument ?
So *both* snippets *were* actually needed...

**Comment by aqrln** [comment]
Docs and examples have been updated on both NestJS and our side, I'll go ahead and close this issue.
