### ISSUE TITLE
Allow specifying alternative location for schema.prisma

### ISSUE THREAD

**Issue by vieirai** [prisma/prisma#20199]
## Problem

When building Node/TS lambdas with AWS SAM, all we can specify is the path to a lambda handler.
AWS SAM does not allow us to include other static files within our lambda code.

The AWS solution for this is to use lambda layers, but those get mounted at `/opt`, which means that our code won't be able to find `schema.prisma`.

## Suggested solution

We can make the above work for the prisma engine binary as there's an environment variable which allows us to set a custom path (`PRISMA_SCHEMA_ENGINE_BINARY`), but not for `schema.prisma`.
Ideally, there would be an environment variable to allow us to also set a custom location for `schema.prisma`.

## Alternatives

There isn't much in the way of alternatives here.
The only "option" is to have a post build script, which copies the prisma files inside AWS SAM's build folder (`.aws-sam/build/{lambdaName}/`). 
This is a very hacky solution as we're relying on the folder structure of AWS SAM not changing, as well as the fact, that by pure chance SAM chooses to deploy any extra files we drop in there right now, but this could change at anytime.

The only other alternative is to change our IAC approach completely, and replace AWS SAM with the Serverless framework or CDK, but that could be weeks of work depending on the project.

## Additional context

N/A

**Comment by janpio** [comment]
(Sorry, you seem to have misunderstood. I meant you could create an issue about the _problem_ you are having with AWS as a bug issue, optimally with a reproduction, so we can take a look of what is happening there. You can of course link to #2746 as a possible suggested solution.)

**Comment by janpio** [comment]
Right now this issue is just a rewording of https://github.com/prisma/prisma/issues/2746 with some additional information, so I will close it for now.

Please open a new issue to describe the concrete problem you are having with AWS SAM, what you are doing exactly, what does not work or what error you are getting. Then we can look into that, understand and potentially fix it - and if not maybe prioritize https://github.com/prisma/prisma/issues/2746 higher than it currently is. Thank you.
