### ISSUE TITLE
CLI command that leads you to a (for you relevant) engine download page

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20223]
Some users can not download Prisma's engines via Node. We could have a CLI command that sends them to a page that has the correct links for their current CLI version, and then instructs them how to download and configure them to be used. 

(Could take `binaryTargets` into account.)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
