### ISSUE TITLE
findMany wrong result when using every relation

### ISSUE THREAD

**Issue by azertyalex** [prisma/prisma#20464]
### Bug description

When requesting all posts where the name of a  category does not exist. All posts without any categories are returned.

### How to reproduce

1. Go to https://playground.prisma.io/examples/reading/find/find-all
2. Use following code
```js
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

await prisma.post.update({
  where: {
    id: 1
  },
  data: {
    categories: {
      set: []
    }
  }
})
const allPosts = await prisma.post.findMany({
 include: {
   categories: true
 },
  where:{
    categories: {
      every: {
        name: 'something else'
      }
    }
  }
});
console.log(allPosts)
```

output:
```js
node /code/index.js
[
  {
    id: 1,
    createdAt: 2022-12-20T11:50:46.108Z,
    title: 'Hello World',
    published: false,
    authorId: 1,
    categories: []
  }
]

```

### Expected behavior

It should not return any posts

### Prisma information

https://playground.prisma.io/examples/reading/find/find-all

### Environment & setup

https://playground.prisma.io/examples/reading/find/find-all

### Prisma Version

https://playground.prisma.io/examples/reading/find/find-all

**Comment by miguelff** [comment]
I reproduced the issue, although I'm leaning towards not considering it a bug. 

This is an edge case on the [semantics](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#relation-filters) of `every` and `none`. For an empty set, you can consider that all elements match any criteria, or that none of them match any criteria, because there are no elements to match the criteria against. 

And this is indeed how collections in many programming languages work:

```javascript
// js
const criterion = (currentValue) => currentValue < 40;
const arr = [];
console.log(arr.every(criterion));
// => true
```

```ruby
# ruby
2.7.2 :009 > [].none? { |x| x==2 }
 => true
2.7.2 :010 > [].all? { |x| x==2 }
 => true
 ```
 
 The case of `some` is clearer, there has to be at least one element in the relation to match. So there's no ambiguity here, it will always return false for the emtpy set.

**Comment by azertyalex** [comment]
What would I have to do to get all posts where category name is 'something else' and a post must have at least one category?
