### ISSUE TITLE
Numeric values returned from Postgres act like strings using numeric operations

### ISSUE THREAD

**Issue by ekzyis** [prisma/prisma#20486]
### Bug description

We have upgraded from Prisma v2 to v5 and we noticed that the value returned from the following raw query (as an example) behaves weird now:

```javascript
const [{ x }] = await models.$queryRaw`SELECT 1::NUMERIC AS x`
console.log(x + 1) // prints 11
```

After some further investigations, we realized that it returns `Prisma.Decimal` which does not support numeric operations as expected. Methods from [decimal.js ](https://mikemcl.github.io/decimal.js/)have to be used now:

```javascript
const [{ x }] = await models.$queryRaw`SELECT 1::NUMERIC AS x`
console.log(x.plus(1)) // prints 2
```
Furthermore, using `typeof` or `instanceof`, one can not detect that this will behave like a string:

```javascript
const [{ x }] = await models.$queryRaw`SELECT 1::NUMERIC AS x`
console.log(typeof x) // "object"
console.log(x instanceof String) // false
console.log(util.inspect(x)) // 1
```

We have read the upgrade guides for [v3](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3), [v4](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4) and [v5](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5) and the only documented change that we found and might be related to this is this:

> Raw queries now deserialize scalar values to their **corresponding JavaScript types**. Note that Prisma infers types from the values themselves and not from the Prisma Schema types.

![2023-08-01-204229_685x357_scrot](https://github.com/prisma/prisma/assets/27162016/f2f1c75c-32e3-4e0e-aec0-b959a1c6a6e9)

-- https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4#client-changes

We are creating this issue here (and not in the library) since we were caught off guard by this from Prisma.

**We did not expect that Prisma would convert a numeric value from the database into something that does not support numeric operations and even behaves like a string instead. We admit that we should have checked how `Prisma.Decimal` behaves when using numeric operations. However, I think it is reasonable to expect that a value returned as a number does indeed behave like a number when used with numeric operations. Also when reading "corresponding Javascript types", we would not expect that types from a third-party library are used but native Javascript types.**

So maybe this is indeed a bug and the Prisma team is not aware of this behavior?
Or was this behavior deemed reasonable?

### How to reproduce

```javascript
const [{ x }] = models.$queryRaw('SELECT 1::NUMERIC as x')
console.log(x + 1)
```

Output:
> 11

### Expected behavior

```javascript
const [{ x }] = models.$queryRaw('SELECT 1::NUMERIC as x')
console.log(x + 1)
```

Output:
> 2

### Prisma information

schema irrelevant

### Environment & setup

- OS: Linux 6.4.3-arch1-2
- Database: PostgreSQL v13.2
- Node.js version: node v16.16.0 (npm v8.11.0)

### Prisma Version

```
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0

```

**Comment by SevInf** [comment]
Hi @ekzyis.
This is intentional and you are indeed required to use `Decimal` JS methods instead of built-in operators in this case.

>However, I think it is reasonable to expect that a value returned as a number does indeed behave like a number when used with numeric operations

It is also reasonable to expect that value returned from a database will not lose precision when converted to JS. While with `SELECT 1` query that might not seem like a problem, in general, Postgres `NUMERIC` type is fixed-point while JS `number` is floating point with a lower precision guarantees. Unfortunately, JS does not have means to implement fixed-point numbers while still preserving built-in mathematical operators. So, we are in a situation where we have to choose between two evils: either we lose some data we read from the DB or we require to use `value.add(1)` rather than `value + 1`. And out of those two options, first one sounds like a potentially much bigger problem. Situation might change if JS will get [it's own `Decimal` type](https://github.com/tc39/proposal-decimal), but so far it's just Stage 1 proposal.

If in your case you don't care about precision that much (or you expect it to always fit into `number`) you can cast it to `FLOAT` instead of `NUMERIC`.

I am going to close the issue now, since this works as indented and there is nothing actionable for us in this case.
