### ISSUE TITLE
Prisma json types generation with offical support

### ISSUE THREAD

**Issue by yeongjet** [prisma/prisma#20524]
I think that prisma json types is essential feature while using json type, I know that we already have [prisma-json-types-generator](https://github.com/arthurfiorette/prisma-json-types-generator), it works fine (prisma < 5.0) but delays to support latest prisma (5.0+), when I updated to prisma 5.0 version, I have to change my codes(append `as any` to that json field while reading or writing) while prisma-json-types-generator disabling.

**Comment by janpio** [comment]
I think you are asking for https://github.com/prisma/prisma/issues/3219, correct?
If you agree, feel free to leave your message as a comment in that issue, it adds valuable context and reasoning. Thanks.

**Comment by yeongjet** [comment]
Yeah, I saw that issue before, I just hope that prisma support it in native.

**Comment by janpio** [comment]
We started helping out Arthur of `prisma-json-types-generator` at least for now: https://github.com/arthurfiorette/prisma-json-types-generator/issues/122 

We know and agree that this would be best supported at a Prisma native level, which is why we keep https://github.com/prisma/prisma/issues/3219 around and will hopefully be able to prioritize that soon.
