### ISSUE TITLE
Add an option to force generate/run client with all preview features on

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#20797]
Sometimes, some combination on preview features don't work with each other and we don't notice the issue until one of them goes GA because client test suite usually tests features in isolation.
Ecosystem tests generally run with preview features disabled and that also can cause some issues go unnoticed for a long time.
Third-party tools/libraries/clients developers might also need a way to ensure that their code works with every preview feature Prisma ships it.

To make it easier to surface such problem, we should have a way of enforcing all preview features without editing schema file. For example, this could be enviornment variable:

```sh
PRISMA_ENABLE_ALL_PREVIEW_FEATURES=1 prisma generate
```

or a flag to `generate`:

```
prisma generate --enable-all-preview-features
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
