### ISSUE TITLE
Pre-hook and Post-hook support for Prisma schema

### ISSUE THREAD

**Issue by shimjudavid** [prisma/prisma#2125]
## Problem

Currently, Prisma 2.0 doesn't support features like Mongoosejs's 
 Schema.virtual() and Schema.methods()  OR  SequelizeJS 6.0 's Schema.Getters() and Schema.Setters(). 

One common use case is - User Scheme. With the help of these hooks, we can hash the user password, generate Salt, as well as compare the plain password with hashed one etc.. before adding a user to DB.

**Comment by victordombrovskiy** [comment]
Use case that I would like to be supported by prisma hooks:

I want to send an email message after an Email node is created. I could do that manually after prisma.email.create call, but if I have a lot of such calls across my codebase, I can forget to add this "post-create" logic somewhere. Moreover, I want to do the same if an Email node is updated. So, post-save hook (i.e. hook that will be called after create or update) would help here. Okay, I even can simulate hooks by creation of a proxy around prisma and call my hooks in right places (what I am actually doing right now in my code base), but I can't simulate hooks behavior in a completely correct way, because of this issue, for example: if I create User and then Email in nested create, my only User's hooks will be called, but Email's hooks - not. The only way to fix it is by calling of Email hooks from User hooks manually. But all of this gets too complicated to be supported by a super small team. So, would be enormously great if Prisma could support hooks.

**Comment by schickling** [comment]
Closing in favor of https://github.com/prisma/prisma-client-js/issues/669
