### ISSUE TITLE
Add timestamp to schema filenames generated from re-introspection 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2135]
## Problem

Right now it's very easy for someone to lose manual changes they made to their Prisma schema when they're re-running introspection because introspection overwrites the current `schema.prisma` file. 

Although we provide warnings for this behavior pretty much everywhere in the docs, it's only a matter of time until someone shoots themselves in the foot with this behavior. 

## Solution

If  `schema.prisma` already exists, introspection could append a timestamp to the file name to make it clear that this is the new one.

**Comment by thebiglabasky** [comment]
The current (re-)introspection behavior relies on makes it so that the result can be directly used.
We should advocate for relying on either Git or local history (for fancy editors like IntelliJ for example), until we would look at something like a `--backup` option (for example).
Given the current topics on our plate, I don't see this tackled anytime soon, so would welcome contributions!

**Comment by janpio** [comment]
Turned out not to be a problem.

**Comment by nikolasburk** [comment]
> Turned out not to be a problem

These are the best ones 😄
