### ISSUE TITLE
Cascading Deletes (NO_ACTION) 

### ISSUE THREAD

**Issue by maarteNNNN** [prisma/prisma#2159]
# Bug Report
#1262 This is where I found the information.
When using NO_ACTION and deploying with `prisma deploy` I get an error:
```
Errors:

  Post
    ✖ not a valid value for onDelete
```
**Current behavior**
```graphql
author: User! @relation(name: "PostsRelation", onDelete: NO_ACTION)
```
produces an error
however using:
``` graphql
author: User! @relation(name: "PostsRelation", onDelete: SET_NULL)
```
Works fine.

**Expected behavior?**
NO_ACTION should be working.

**Comment by do4gr** [comment]
Hey, if you follow the comment thread in that issue you will see that we decided to not implement NO_ACTION in the first draft. We want to make sure that there is a real need for it before implementing it. I will update the top comment to reflect this decision.

**Comment by marktani** [comment]
In this case, the `NO_ACTION` option should be removed from the docs [here](https://www.prisma.io/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#graphql-directives) @nikolasburk.

**Comment by marktani** [comment]
Please leave the issue open until the documentation is updated 🙂

**Comment by ed-zm** [comment]
is this available for graphcool?

**Comment by do4gr** [comment]
@ed-zm No, this is a Prisma only feature.

**Comment by nikolasburk** [comment]
`NO_ACTION` has been entirely removed from the docs 👍

**Comment by leszekhanusz** [comment]
> What would put this on the list of a "real need?" I expect this behavior for an ERP I'm working on. It makes no sense to push relational integrity to the application layer.

Not only it makes no sense but it is actually impossible to implement safely in the application layer.
If we want to implement it we need multiple prisma queries:

- first check if there exists related items
- then delete if no related items found

Because both those queries together are not atomic we are left with a possible **race condition** if a related item is added between those two queries from another client.

If we were sending SQL, we would be able to solve that by putting all that in a transaction, but it is not possible with prisma queries.

So for me too the NO_ACTION cascade (on delete restrict) is absolutely needed.
