### ISSUE TITLE
Studio ignores `PRISMA_QUERY_ENGINE_{LIBRARY, BINARY}` variables

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#21926]
To reproduce:

1. Ensure all downloaded binary at default locations are removed (that incudes `engines` package as well as `~/.cache/prisma` directory.
2. Download custom binary and but into any non-default location
3. Set either `PRISMA_QUERY_ENGINE_LIBRARY` or `PRISMA_QUERY_ENGINE_BINARY` env var to point to that custom location.
4. Try to start Prisma studio.

Error you will be getting:

```
 Error: spawn /Users/serhii/.cache/prisma/master/0a383f5645e8d5567f55109a60ec45c0c2c8e719/TEST_PLATFORM/query-engine ENOENT
```

So, Studio still tries to load the engine from default location. When looking at the code, Studo indeed has it's own code for resolving binaries that ignores env vars. [Link to private repo](https://github.com/prisma/studio-code/blob/main/packages/pcw/src/paths.ts#L23)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
