### ISSUE TITLE
Warn on unsupported database versions

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2211]
Cases like https://github.com/prisma/prisma/issues/2194 show that it might help avoid some problems if we would warn on unsupported database versions.

If checking for the version means additional queries, it might help to only do that on error.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
