### ISSUE TITLE
CI slash commands should automatically trigger build

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#22232]
We have a number of slash commands / magical comments on PR that alter the build:

- `ci test all` for running binary engine test suite
- `/integration` for publishing integration version of the branch
- `/engine-branch` for building custom engine branch

All of them require us to re-run pipeline manually after adding or removing the command. It would convenient if re-run happened automatically when the body of the PR/comments changed.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
