### ISSUE TITLE
Updating an array using `set` doesn't work

### ISSUE THREAD

**Issue by sagi-orchid** [prisma/prisma#22511]
### Bug description

I am using Prisma 5.7.1 with Postgres 16
I have a schema with a simple string Array.

I have some logic that accepts a new array, then checks if the array has any new values, and if so, creates a new array with all unique values and updates the existing one in the database. It's pretty simple, yet it doesn't seem to work.

The syntax I use:

```
this.prisma.resource.update({
        where: { id: existingResource.id },
        data: {
          someAddresses: {
            set: newAddresses,
          },
        },
      })
```

The operation throws no errors, but in the end of the day the record in my database stays the same.

### How to reproduce

1. Create a schema with a string array
2. Create a record with an array and some values
3. Try to update the existing array with other values, using `set`.

### Expected behavior

I would have expected the database record to hold an array with the new values I supplied to the update function.

### Prisma information

```
model Resource {
  id             String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  name       String
  someAddresses    String[] @map("some_addresses")
  apps           String[] @db.Uuid

  @@map("resources")
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL@16.1
- Node.js version: 20.1

### Prisma Version

```
5.7.1
```

**EDIT**
They dont get updated even when I use `push`. I think it might have to do something with the fact I use uuid as id

**Comment by sagi-orchid** [comment]
Closing this because apparently the issue was I didn't awaited the operation... not sure why its needed as I didn't want to wait for this operation by design

**Comment by mel-habip** [comment]
> Closing this because apparently the issue was I didn't await the operation... not sure why its needed as I didn't want to wait for this operation by design

Hi there!

I had this issue before too and was confused. 

If you want to continue in a synchronous way instead of using `await` , you can do one of a few options:
- then/catch/finally : the promise will execute if you define (even if blank) a callback
- `Promise.all(arrayOfPromises)` with a then/catch/finally block
- `$transactions` API

If you often have a use case where you want to send the request to the DB but don't care about the response, you can wrap the Prisma request in an async function. That being said, I feel like you should always treat a rejection appropriately.

**Comment by janpio** [comment]
Explanation of _why_ this is needed: https://www.prisma.io/docs/orm/reference/prisma-client-reference#prismapromise-behavior
