### ISSUE TITLE
Add syntax highlighting to more tools

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2335]
While we already have syntax highlighting for VSCode and GitHub, we should also add syntax highlighting to the following tools:

- [prism.js](https://prismjs.com/)
- [highlight.js](https://highlightjs.org/)
- [bat](https://github.com/sharkdp/bat)
- [sublime text](https://www.sublimetext.com/)

**Comment by steebchen** [comment]
IntelliJ would be awesome

**Comment by Jolg42** [comment]
A rather big one is WebStorm

**Comment by pantharshit00** [comment]
I have a personal project which already implements this for vim: https://github.com/pantharshit00/vim-prisma

**Comment by matthewmueller** [comment]
I've split these into separate issues because their popularity is quite different. We're currently working on the prism.js solution because we need consistent highlighting on homepage and docs.

The rest of the these, let's see how many people want them. Fortunately, most of them build on the [.tmLangauge file](https://github.com/prisma/vscode/blob/master/syntaxes/prisma.tmLanguage.json) we've already created for VSCode.

- Sublime Text: https://github.com/prisma/prisma/issues/2336
- Prism.js: This will probably be solved here: https://github.com/prisma/prisma2-docs/issues/270
- Highlight: https://github.com/prisma/prisma/issues/2337 
- Bat: https://github.com/prisma/prisma/issues/2338
- IntelliJ: https://github.com/prisma/prisma/issues/2339
- WebStorm: https://github.com/prisma/prisma/issues/2340
