### ISSUE TITLE
`✘ [ERROR] near "��": syntax error at offset 0` when running `wrangler d1 migrations apply` with Prisma generated migration (on Windows, using Powershell)

### ISSUE THREAD

**Issue by CasperSK89** [prisma/prisma#23702]
### Bug description

I get an error while trying to apply my migration with wrangler.
![error](https://github.com/prisma/prisma/assets/77106172/819e5432-4c31-493f-be3b-b3f47ef4335e)

I'm using the [guide here.](https://www.prisma.io/blog/build-applications-at-the-edge-with-prisma-orm-and-cloudflare-d1-preview)

Here is the log:
[wrangler-2024-04-02_17-44-57_583.log](https://github.com/prisma/prisma/files/14841812/wrangler-2024-04-02_17-44-57_583.log)

Here is the migration file (as txt instead of sql):
[0001_create_user_table.txt](https://github.com/prisma/prisma/files/14841861/0001_create_user_table.txt)

### How to reproduce

I run the following command in terminal:
npx wrangler d1 migrations apply prisma-demo-db --local

### Prisma information

schema.prisma
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

### Environment & setup

- OS: Windows
- Node.js version: v18.20

packages:
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "npm run build && wrangler pages dev ./dist",
    "postinstall": "nuxt prepare",
    "deploy": "npm run build && wrangler pages deploy ./dist",
    "build-cf-types": "wrangler types"
  },
  "dependencies": {
    "@prisma/adapter-d1": "^5.12.0",
    "@prisma/client": "^5.12.0",
    "nuxt": "^3.11.1",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240329.0",
    "nitro-cloudflare-dev": "^0.1.4",
    "prisma": "^5.12.0",
    "wrangler": "^3.43.0"
  }
}
```

### Prisma Version

```
prisma                  : 5.12.0
@prisma/client          : 5.12.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.6.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
Preview Features        : driverAdapters
```

**Comment by janpio** [comment]
You can also work around this by using another "terminal" than Powershell, for example Cmd or Git bash.

The underlying cause here is that using `command > foo.sql` in Powershell (the default in VS Code) by default creates a UTF16 LE file, instead of the usual UTF-8 one. Pretty weird choice by Windows and Powershell, and there is no simple way to change that. `wrangler d1 migrations apply` does expect a UTF-8 file though, and can not read the initial characters of the created file - and throws that error.

(This more popular issues is caused by the same problem: https://github.com/prisma/prisma/issues/17558)

We are currently evaluating what we can do in this situation to avoid this or help you realize the problem without having to open an issue here.

**Comment by Jolg42** [comment]
👋🏼 

I'm not a Windows user, though I used Windows to reproduce and could feel the pain of this issue.

Good news 🎊 -> there is now an easy way to avoid this since https://github.com/prisma/prisma/releases/tag/5.12.1 just released a few minutes ago.

I added to `migrate diff` an output option `-o` or `--output`.

Example usage for an initial migration:
```sh
npx prisma migrate diff --script --from-empty --to-schema-datamodel ./prisma/schema.prisma --output ./schema.sql
```

By letting the Prisma CLI do the writing, it avoids the problem of using the redirect with PowerShell ✅ 
And I think it's a useful option to have in general too 🙌🏼 

Let us know what you think if you have any feedback 💚
