### ISSUE TITLE
Remove `warn(prisma-client) This is the 10th instance of Prisma Client being started.` warning in Edge (and potentially) other envs)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#23763]
When running Prisma Client in Cloudflare Workers, it must be instantiated _inside_ the handler:
- that's where the DB URL env var is available which is needed to instantiate the driver adapter
- I/O objects can't be shared across Worker instances

This is different compared to the recommendation typically given for using Prisma Client in Serverless environments where it's supported to be instantiated _outside_ the handler.

Instantiating Prisma Client outside the handler enables reuse of the instance across different function invocations. This also helps prevent the warning: `warn(prisma-client) This is the 10th instance of Prisma Client being started.`

Since in CF workers, instantiating inside the handler is the only option, the warning is unavoidable and should be removed.

**Comment by Jolg42** [comment]
We fixed that with https://github.com/prisma/prisma/pull/24245 which is part of the next release, `5.15.0`

Note from the private tracking issue: The "warn(prisma-client) This is the 10th instance of Prisma Client being started. Make sure this is intentional." occurring in @prisma/client warning was originally designed for avoiding excessive memory when using the binary query engine. This is not needed when using edge functions, and should be removed when we detect that an adapter is passed to the PrismaClient constructor.
