### ISSUE TITLE
I get this error while querying data: `JSON.stringify cannot serialize BigInt.`

### ISSUE THREAD

**Issue by TechGunners** [prisma/prisma#23857]
### Bug description

I get this error while querying data: `JSON.stringify cannot serialize BigInt.`
But the interesting part is I'm nowhere using JSON.stringify 

```typescript

			return db.blog.findMany({
				where: { published: true },
				take: 500,
				select: {
					id: true,
					title: true,
					cover: true,
					views: true,
					created: true,
					user: { select: { username: true, name: true, pp: true, verified: true } }
				}
			})
```

### How to reproduce

don't really know, it just happened
[Here's the repo link if you want to investigate](https://github.com/TechGunnerINC/TechGunner)

### Expected behavior

query successfully

### Prisma information

[Schema file]( https://github.com/TechGunnerINC/TechGunner/blob/Prime/backend/prisma/schema.prisma)

### Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Bun version: 1.1.3

### Prisma Version

5.12.1

**Comment by AmirhoseinBrz** [comment]
hi , this error not related to prisma
i have same problem in nest js 
if you remove the return keyword and log the value it should work fine 
 
it's because node js 
you can fix that by using this code 

`BigInt.prototype["toJSON"] = () => +this;`

here i convert type to number for my use
you can change it to string

`BigInt.prototype["toJSON"] = () => this.toString();`

hope it is useful !

**Comment by TechGunners** [comment]
@AmirhoseinBrz Can you please tell where to place this code, and yes it works just fine when logging it

**Comment by AmirhoseinBrz** [comment]
> @AmirhoseinBrz Can you please tell where to place this code, and yes it works just fine when logging it

sure
Before using models that have bigInt types in prismaService
or you can add this to your main file befor every module load in you app
