### ISSUE TITLE
Support UUID v7

### ISSUE THREAD

**Issue by kibertoad** [prisma/prisma#24079]
## Problem

Efficient cursor-based pagination relies on lexicographical and chronological sorting support, which is not provided by older UUID versions.

## Suggested solution

UUID v7 fills a big gap in the database space by addressing the need for the lexicographically and chronologically sortable identifiers. CUID and ULID are strong contenders, but they come with a significant adoption friction involved, due to not being UUID-compatible, and hence not qualifying as a drop-in replacement. Also Prisma currently doesn't support ULID at all, and for CUID only deprecated version 1 is supported.

Implementing UUID v7 support on Prisma level would have a huge impact for addressing this need and enabling the adoption of the new standard. Since it is storage-compatible with UUID v4, it could already be adopted in existing databases with very little changes. 

UUID v7 was already published as an RFC, see https://www.rfc-editor.org/info/rfc9562, so it should be safe to implement it already.

There is an existing Rust implementation: https://crates.io/crates/uuid7 - it implements the published RFC, and can be used to provide support.

Usage syntax could be identical to the existing CUID support:
```
  id   String @id @default(uuidv7())  @db.Uuid
```

## Alternatives

* Implement new spec-compliant v7 implementation from a scratch - that would be extra work for unclear benefits.
* Wait till databases implement UUID v7 support natively - since approval is going to happen past the PostgreSQL feature freeze period, it is likely to take at least two years until this is going to happen.

**Comment by sergeyprokhorenko** [comment]
UUIDv7 with exactly the same structure as the existing [implementation in Rust](https://crates.io/crates/uuid7), has already been [implemented in ClickHouse](https://clickhouse.com/docs/en/sql-reference/functions/uuid-functions#generateUUIDv7) DBMS.

But ClickHouse ensures monotony even for multithreading, which is impossible to achieve in Rust in isolation from the DBMS. [The PostgreSQL proposal](https://commitfest.postgresql.org/47/4388/) does not provide monotonicity for multithreading due to complexity.

I recommend using an existing implementation in Rust. Someday in the future it will be possible to replace it with some implementation that ensures monotonicity for multithreading.

For generation on the client side, I recommend using [this implementation](https://www.npmjs.com/package/uuidv7) from the same author.

**Comment by kibertoad** [comment]
rfc-9562 was published (https://www.rfc-editor.org/info/rfc9562), I've updated the ticket accordingly

**Comment by kibertoad** [comment]
https://crates.io/crates/uuid7 was updated to clarify being in sync with the published RFC, I've edited the issue description accordingly.

**Comment by mcuelenaere** [comment]
I've taken a stab at this at https://github.com/prisma/prisma-engines/pull/4877

**Comment by SevInf** [comment]
https://github.com/prisma/prisma-engines/pull/4877 have been merged

**Comment by mhadi512** [comment]
Thanks guys for this amazing feature, I was handling UUIDv7 using Prisma middleware. But now it's  part of the package.

I'm trying to enable it, but it doesn't reflect.
Do I need to enable a preview feature?

here is my schema code:
```
model Users {
  id   String @id @default(uuid(7)) @db.Uuid
  name String
}
```

package.json:
```
"@prisma/client": "5.18.0",
...
"prisma": "5.18.0",
```

Am I missing something?

**Comment by aleclarson** [comment]
Hello Prisma team, I'm wondering if Prisma will automatically use Postgres 18's `uuidv7()` function if I use `@default(uuid(7))` in my `schema.prisma` file, or has that not been implemented yet? If not, it'd be useful to have for those of us who use raw SQL queries.
