### ISSUE TITLE
[introspect] Expose database classification feature

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2424]
https://github.com/prisma/prisma/issues/2183 implemented a Introspection Engine feature that tries to classify the introspected database: Prisma 1, Prisma 1.1, Prisma 2 or Non-Prisma.

We need this exposed in a temporary way in the `introspect` success output (with and without `--print`) so we can verify the results. Please find a "quiet" way to put it into the success output.

Later this will be used as input to show a message that links to our P1->P2 upgrade strategy.

**Comment by Jolg42** [comment]
“version” from introspection looks like this
result.version = 'Prisma2' | 'Prisma1' | 'Prisma11' | 'NonPrisma'

See https://github.com/prisma/prisma-engines/pull/726/files

We can add that to https://github.com/prisma/prisma/blob/master/src/packages/sdk/src/IntrospectionEngine.ts

**Comment by Jolg42** [comment]
It looks like it returns undefined for now, so I pinged @do4gr

**Comment by janpio** [comment]
> It looks like it returns undefined for now, so I pinged @do4gr

how was this fixed? did it actually need fixing?

**Comment by Jolg42** [comment]
I shipped it in the CLI and @do4gr will check on the engines why it is undefined, it will work after that 😃

**Comment by Jolg42** [comment]
@janpio It was [fixed by @do4gr](https://github.com/prisma/prisma-engines/commit/86cf27779951480f87f6bbdb15a3722c5756a8e4) and shipped in 2.0.0-alpha.1218

Example
<img width="535" alt="Screen Shot 2020-05-18 at 12 06 02" src="https://user-images.githubusercontent.com/1328733/82201152-37985000-9900-11ea-84a4-bd1380d8e3fb.png">

with --print
<img width="526" alt="Screen Shot 2020-05-18 at 12 05 37" src="https://user-images.githubusercontent.com/1328733/82201159-39621380-9900-11ea-845e-57d0c20e1bd8.png">
