### ISSUE TITLE
Prisma 1 CLI (for versions smaller than 1.34) and Prisma 2.0 CLI share the same command

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2433]
This might be an issue for folks upgrading to Prisma 2 who want to run Prisma 1 and Prisma 2.0 side-by-side and gradually upgrade their application.

Right now, both the Prisma 1 CLI for all versions before 1.34 and the Prisma 2.0 CLI are invoked using this command:

```
prisma
```

I tested in one project and when I had both installed as dev dependencies:

```
npm install @prisma/cli --save-dev
npm install prisma@1.30 --save-dev
```

In that case, it always seemed to invoke the Prisma 1 CLI for me.

Can we somehow add the previous versions of the Prisma 1 CLI to the `prisma1` npm package as well?

**Comment by pantharshit00** [comment]
I think it is a very bad idea to replace a previous version as that will broke any existing system that depends on that version.

I am also pretty sure npm doesn't let you publish to a older tag again. It is better if this is addressed by proper documentation.

**Comment by nikolasburk** [comment]
Just to clarify, I didn't suggest to replace any previous version. I was asking about potential solutions. 

One idea I think would be to date back the `prisma1` CLI and map it to previous `prisma` CLI versions, but I also doubt that npm allows that (but maybe it does?).

Ideally I think you could do: `npm install prisma1@1.30` and it would just install the `1.30` version of the `prisma` CLI that's now invoked with the `prisma1` command.

**Comment by janpio** [comment]
We can do that: We would check out the old tag, apply all the changes required to go from `prisma` to `prisma1` (roughly https://github.com/prisma/prisma1/commit/7bef3c5d1837c9b1dd81ad109872df7677849e36 + https://github.com/prisma/prisma1/commit/75b3a115ca4ff014ba0de92c997706b7252f6be8), and publish these new code states at their respective versions. It is a lot of manual though. It would also need to happen before we publish a new version for `prisma1` so that this one then can become `latest` again.

So definitely doable.

**Comment by pantharshit00** [comment]
Ok, I do understand now. releasing a version `1.30` users would be nice as many people are using it as it is prior to the datamodel change.

**Comment by janpio** [comment]
We are not going to touch older Prisma 1 CLI versions. 
If we do anything here, we will release new versions.
