### ISSUE TITLE
Zero-code instrumentation

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#24376]
> Adam from [Metis](https://www.metisdata.io/) here.
> 
> One thing that would be great to see is support for autoinstrumentation with out-of-process configuration from OpenTelemetry. See [this link](https://opentelemetry.io/docs/instrumentation/js/automatic/)
> 
> Autoinstrumentation enables turning open telemetry on by installing a couple of OTel libraries and setting some environment variables. This way users can enable instrumentation without modifying their application code at all. This works great for many libraries including pg (Postgres driver), Sequelize or web servers. See the [list](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#supported-instrumentations)
> 
> I think Prisma should support autoinstrumentation by environment variables as well (or generally, Prisma should integrate with OTLP to support any kind of autoinstrumentation). This way users would be able to enable OpenTelemetry with no application code changes, and could use tools like [Metis](https://www.metisdata.io/) out of the box.

_Originally posted by @adammetis in https://github.com/prisma/prisma/issues/14640#issuecomment-1858061194_

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
