### ISSUE TITLE
Docs include incorrect information regarding Vercel deployment fix

### ISSUE THREAD

**Issue by Bestulo** [prisma/prisma#24431]
### Bug description

On the docs:

https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/vercel-caching-issue

the recommended solution to host a nextjs project on Vercel is to use `"postinstall": "prisma generate"`, but I tried it and got the following error

```
/bin/sh: line 1: prisma: command not found
```

I swapped `prisma generate` to `npx prisma generate` and the project built correctly.

### How to reproduce

1. Set up a nextjs project with a prisma client
2. Set up `"postinstall": "prisma generate"` in the `package.json` `scripts` section.
3. Deploy to vercel (by using cli or pushing & importing the project on the web ui)
4. Look at the logs

### Environment & setup

- OS: Idk, whatever vercel uses

### Prisma Version

```
5.15
```

**Comment by jkomyno** [comment]
> On the docs:
> 
> https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/vercel-caching-issue
> 
> the recommended solution to host a nextjs project on Vercel is to use `"postinstall": "prisma generate"`, but I tried it and got the following error
> 
> ```
> /bin/sh: line 1: prisma: command not found
> ```

Hi @Bestulo, can you please share your `package.json` file, and in particular the `scripts` section? I suspect you're trying to run a bash script in there, e.g.,

```json
{
  "scripts": {
    "postinstall": "./postinstall.sh"
  }
}
```

which would indeed fail on

```sh
# ./postinstall.sh

prisma generate
```

as the terminal shell wouldn't know how to resolve the `prisma` package (unless it's installed globally).
This is fixed by writing `npx prisma generate` or `pnpm prisma generate` in the bash script, which informs the system to resolve the `prisma` CLI via Node.js.

On the other hand, if the package.json had something like

```json
{
  "scripts": {
    "postinstall": "prisma generate"
  }
}
```

you wouldn't need to prepend `npx` or `pnpm` to that script.

Can you please share whether your case falls in a similar situation? Thanks!

**Comment by DanielMartinezSebastian** [comment]
I hope this solution helps you.
Don't use the postinstall script in your package.json. In Vercel / Settings / Build Command you should use `npx prisma generate && next build`.
