### ISSUE TITLE
Instrumentation: Problems in working with Elastic APM

### ISSUE THREAD

**Issue by samirotiv** [prisma/prisma#24715]
### Bug description

I am instrumenting our NestJS application using the Elastic APM OpenTelemetry Bridge. It seems to work fine with all other instrumentation libraries, such as Redis and NestJS, but is not working with Elastic.

Perhaps related to #14887 

When I enable Elastic APM OpenTelemetry Bridge and I enable Prisma Instrumentation, I get an error:

```
TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/home/samir/git/dir/server/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:126:37)
    at /home/samir/git/dir/server/node_modules/@prisma/instrumentation/dist/chunk-VVAFFO6L.js:59:20
    at Array.forEach (<anonymous>)
    at ActiveTracingHelper.createEngineSpan (/home/samir/git/dir/server/node_modules/@prisma/instrumentation/dist/chunk-VVAFFO6L.js:44:27)
    at ro.createEngineSpan (/home/samir/git/dir/server/node_modules/@prisma/client/runtime/library.js:122:1645)
    at vr.logger (/home/samir/git/dir/server/node_modules/@prisma/client/runtime/library.js:112:1167)
    at /home/samir/git/dir/server/node_modules/@prisma/client/runtime/library.js:112:922
```

### How to reproduce

1. Set up Elastic APM either using a cloud trial or using Elastdocker
2. Instrument the code as shown below
3. Observe the logs

otel.ts:
```
import { NodeSDK } from '@opentelemetry/sdk-node';
import { ConsoleSpanExporter } from '@opentelemetry/sdk-trace-node';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { PrismaInstrumentation } from '@prisma/instrumentation';

export function registerOtelInstrumentations() {
    registerInstrumentations({
        instrumentations: [
            getNodeAutoInstrumentations(),
            new PrismaInstrumentation(),
        ],
    });
    console.log('Registered instrumentation');
}
```

initelastic.ts:
```
import * as apm from 'elastic-apm-node';

import {
    APM_API_KEY,
    APM_SECRET_TOKEN,
    APM_SERVER_URL,
    APM_SERVICE_NAME,
} from './env';
import { registerOtelInstrumentations } from './otel';

// Elastic instrumentation MUST BE FIRST
// If not, the host IP addresses etc. goes wrong.
let apmInstance;
if (!apmInstance) {
    console.log('Apm instance initialized');
    apmInstance = apm.start({
        serviceName: APM_SERVICE_NAME,
        serverUrl: APM_SERVER_URL,
        secretToken: APM_SECRET_TOKEN,
        apiKey: APM_API_KEY,
        opentelemetryBridgeEnabled: true,
    });
}

// OpenTelemetry Instrumentation always must be second
registerOtelInstrumentations();

export default apmInstance;
```

Import initelastic.ts as the first line in entry point.

### Expected behavior

Expect Prisma to not give errors, and Prisma spans to start showing up.

### Prisma information

Running Prisma 5.16.1 

### Environment & setup

- OS: Windows 11 with WSL
- Database: Postgresql 14
- Node.js version: Node 20

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.16.1
@prisma/client          : 5.16.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : tracing
```

**Comment by bplies-ATX** [comment]
My team is also encountering this but we also get the error even if we remove Elastic APM.  Seems to me that Prisma instrumentation doesn't work as-is after applying the simple [usage instructions](https://github.com/prisma/prisma/blob/main/packages/instrumentation/README.md#usage) .

As far as Elastic APM is concerned, OpenTelemetry [is listed as a supported technology](https://www.elastic.co/guide/en/apm/agent/nodejs/master/supported-technologies.html#compatibility-opentelemetry) and has a document describing what is necessary to [enable OTel bridging](https://www.elastic.co/guide/en/apm/agent/nodejs/master/opentelemetry-bridge.html).  But that doesn't help because the application cannot start with prisma instrumentation configured.

The only possible clue that I've found is that from the OP's stacktrace: 
```
TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/home/samir/git/dir/server/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:126:37)
    at /home/samir/git/dir/server/node_modules/@prisma/instrumentation/dist/chunk-VVAFFO6L.js:59:20
    at Array.forEach (<anonymous>)
```
Within the bundled chunk is: 
```
      const span = new import_sdk_trace_base.Span(
        tracer,
        import_api.ROOT_CONTEXT,
        engineSpan.name,
        spanContext,
        import_api.SpanKind.INTERNAL,
        engineSpan.parent_span_id,
        links,
        engineSpan.start_time
      );
```
Where within my IDE at least  `import_sdk_trace_base.Span` is ~~strikethrough~~ with context:
> Span.d.ts(37, 8): The declaration was marked as deprecated here. 
@deprecated — calling Span constructor directly is not supported. Please use tracer.startSpan.

That deprecation can be [found here](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/Span.ts#L96-L107).

I interpret this to mean that prisma instrumentation should change [these lines](https://github.com/prisma/prisma/blob/main/packages/instrumentation/src/ActiveTracingHelper.ts#L64-L73): 
```
      const span = new SpanConstructor(
        tracer,
        ROOT_CONTEXT,
        engineSpan.name,
        spanContext,
        SpanKind.INTERNAL,
        engineSpan.parent_span_id,
        links,
        engineSpan.start_time,
      )
```

To something like: 
```
const span = tracer.startSpan(/* stuff */)
```

See [SDK code](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/Tracer.ts#L65-L69).

**Comment by iknowcss-invenco** [comment]
I'm having the same problem as others describe above. Following @bplies-ATX's comment and reviewing the SDK, I created a patch and applied it to my local node_modules. 

Essentialy I changed [these lines of code](https://github.com/prisma/prisma/blob/main/packages/instrumentation/src/ActiveTracingHelper.ts#L76C1-L85C8) from this:

```typescript
const span = new SpanConstructor(
  tracer,
  ROOT_CONTEXT,
  engineSpan.name,
  spanContext,
  spanKind,
  engineSpan.parent_span_id,
  links,
  engineSpan.start_time,
)
```

...to this

```typescript
const span = tracer.startSpan(
  engineSpan.name,
  { kind: spanKind, links, startTime: engineSpan.start_time },
  ROOT_CONTEXT
);
```

and then it worked correctly on my machine.

**Comment by samirotiv** [comment]
@iknowcss-invenco This is great, I am going to send a PR to Prisma with this.
