### ISSUE TITLE
Raw Query Throws an Error in Release 5.17.0

### ISSUE THREAD

**Issue by david-ember** [prisma/prisma#24824]
### Bug description

When invoking the the raw query call, an error is thrown when that wasn't the case before version 5.17.0. For example, we have a health check endpoint that invokes:

```ts
prismaClient.$queryRaw`SELECT 1`
```

In versions 5.16.2 and prior, this worked fine. Now we see: `TypeError: t.map is not a function`

### How to reproduce

1. Specify version `5.17.0` in `package.json` for the `prisma`, `@prisma/client`, and `@prisma/adapter-pg` dependencies
2. Run `npx prisma generate`
3. Launch application and invoke the raw query mentioned above

### Expected behavior

Should execute without any errors.

### Prisma information

We have the following generator client and datasource setup:

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
  engineType    = "library"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

The raw query we used:
```ts
prismaClient.$queryRaw`SELECT 1`
```

### Environment & setup

- OS: **Debian**
- Database: **PostgreSQL**
- Node.js version: **v20.9.0**

### Prisma Version

```
5.17.0
```

**Comment by SevInf** [comment]
Hi @david-ember.
I can not reproduce the issue. `SELECT 1` query returns `[ { '?column?': 1 } ]` for me. Could you provide a reproduction repository that we can run and see it happen?

**Comment by gustawdaniel-statscore** [comment]
In build I see:

```
      unpack(t, r, n) {
        if (!t || (t.data && (t = t.data), !t)) return t;
        let i = Object.keys(t)[0], o = Object.values(t)[0], s = r.filter((u) => u !== "select" && u !== "include"), a = _i(o, s), l = i === "queryRaw" ? bl(a) : kn(a);
        return n ? n(l) : l;
      }
```

then

```
    function bl(e) {
      let t = [], r = om(e);
      for (let n = 0; n < e.rows.length; n++) {
        let i = e.rows[n], o = { ...r };
        for (let s = 0; s < i.length; s++) o[e.columns[s]] = ct(e.types[s], i[s]);
        t.push(o);
      }
      return t;
    }
```

then 

```
    function om(e) {
      let t = {};
      for (let r = 0; r < e.columns.length; r++) t[e.columns[r]] = null;
      return t;
    }
```

and problem is with reading `length` from undefined because argument of `bl` is empty array `[]`.

**Comment by SevInf** [comment]
@gustawdaniel-statscore can you please share the repository where we could see the error happens. We know how our code looks like, it does not help us with reproduction.

**Comment by gustawdaniel-statscore** [comment]
I can't send you repository, because it is closed source but I can recommend focus on 

```
a = _i(o, s)
```

If `a` is `[]` then we will see error with getting columns length, columns will be undefined and then length from undefined throws exception.

In next release you can throw error earlier, eg inside of `_i` function if it return empty array. Maybe thanks to this approach in 5.17.1 we will see more readable error messages.

**Comment by SevInf** [comment]
@gustawdaniel-statscore respectfully, again, I don't need pointers to our code or debugging tips. I am asking for a code and setup that shows the error happening. The one provided at the start at the issue does not reproduce it. I am not asking for a full private repo of your projet, but simple repo whith just one `queryRaw` call would be enough.

**Comment by apolanc** [comment]
Hey @gustawdaniel-statscore, following the previous comment, are you able to provide us with a reproduction?

**Comment by apolanc** [comment]
Hi @gustawdaniel-statscore,

Since we're unable to reproduce this issue we will close now. If you continue to have issues with this and can provide us with a reproduction please do so.

Thanks.

**Comment by vtgen** [comment]
following up i am having the same issue, with the same upgrade.  5.16 is fine, 5.17 brbeaks.

my clicking throuogh the unminified code is similar to @gustawdaniel-statscore 's comments.

```
    TypeError: Cannot read properties of undefined (reading 'length')

      250 |
      251 | const involvedEntitiesPromise = deps.db.$queryRawUnsafe(`select (1)`);
    > 252 | const involvedEntities : any= await involvedEntitiesPromise;
          |                               ^
      253 |   const entitiesGrouped: Record<
      254 |     number,
      255 |     {

      at om (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:5438)
      at bl (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:5244)
      at _n.unpack (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:8476)
      at _n.mapQueryEngineResult (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:6943)
      at Object.singleLoader (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:6361)
      at _n.request (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:121:6628)
      at l (node_modules/.store/@prisma-client-virtual-917fe57161/node_modules/@prisma/client/runtime/library.js:130:9355)
 ```
 
 the code baase i found this is also closed source; and i have not been able to find a simple reproduction.
 
 the repro doesn't work with no schema.  i haven't yet figured out which part of the schema is causing it; but i feel logically it must be some emergent behavior that arises due to some idiosyncrasy in the schema itself.
 
 what i can say for sure is that the same error is thrown whether or not we use queryRaw or queryRaw unsafe.
 
 one thing that sticks out to me, fwiw, is `...at Object.singleLoader`
 
 the reference to 'singleLoader' when docs are explicit that [queryRaw returns an array](https://www.prisma.io/docs/orm/prisma-client/queries/raw-database-access/raw-queries#return-type)
 
 smells to me like the issue.
 
 i also tried with and without the adapter (it is postgres here too) and could find no differences.
