### ISSUE TITLE
[Introspection] Identify Prisma 1 Id defaults

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2499]
## Problem

Prisma 1 IDs are introspected as Strings without a default/`@default`. 

## Suggested solution

Introspection can be improved following this logic:

1. Is it a `Prisma1` or `Prisma11` classified database schema?
2. Is there a primary key column of type `char(25)` or `char(36)`?
3. If yes, apply the following default:
	- `char(25)` -> `@default(cuid())`
	- `char(36)` -> `@default(uuid())`

## Additional context

- Internal investigation document https://www.notion.so/prismaio/String-IDs-Details-47a2e3f256a848479cc3d34f51e23986
- Related issues that will keep this information on Re-Introspection: https://github.com/prisma/prisma/issues/2534
- Will close this issue: https://github.com/prisma/prisma/issues/1897

**Comment by do4gr** [comment]
Additionally we should generated warnings for cases where we do such an inference. Since this is based upon us recognizing the schema as P1 migrated and this itself is only a heuristic. 

We would therefore render the defaults but emit warnings at the same time, so the user knows these are not based on information in the SQL schema.
