### ISSUE TITLE
Output warning when `schema.prisma` was changed after last `prisma generate`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2508]
A common thing that happens to me is that I forget to `prisma generate` after schema changes. That means that when I run a Prisma Client query, it will fail. It would be handy if that would be recognized and I would get an appropriate error message telling me that my local schema file was changed vs. the one from the generated Client, and I should regenerate and try again.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
