### ISSUE TITLE
Override "Engines hash" that is used to download Engines from S3

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2517]
Currently the string that is used to identify the Engines to be downloaded from S3 comes from `package.json`. It would be nice if we could override this manually with an ENV var to force the download and usage of a different Engine build. This will enable nice things like for example using Engines from a branch in `prisma-engines` in the future.

**Comment by janpio** [comment]
Internal note: https://prisma-company.slack.com/archives/CUXLS0Z6K/p1600071534002400?thread_ts=1600067400.000700&cid=CUXLS0Z6K

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
