### ISSUE TITLE
PNPM update

### ISSUE THREAD

**Issue by Andrewx24** [prisma/prisma#25256]
## Problem
This project is not compatible with the latest version of PNPM 

## Suggested solution
Update it to the latest version of PNPM 

## Additional context
PNPM compatibility

**Comment by chrisdedow** [comment]
second this.

**Comment by jkomyno** [comment]
Hi @Andrewx24 and @chrisdedow, can you please clarify this problem?
What happens when installing Prisma via the newest pnpm version? Please post a reproduction repository here to help us jump on it. Thanks!

**Comment by Andrewx24** [comment]
When I ran pnpm install on my terminal. This what I got.
Your pnpm version is incompatible with "/prisma".

Expected version: >=8.6.7 <9
Got: 9.11.0

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".

**Comment by SevInf** [comment]
@Andrewx24 I guess you are running `pnpm install` on prisma repositiory, not your own personal project? Becuase non of our public packages have `pnpm` entry in `engines` field, only monorepo root does. 

If so, then we can't update pnpm until Prisma 6 because Prisma 5 still needs to support Node 16 and PNPM 9 requires Node 18+. We won't be able to run our test suite on Node 16 if we do the upgrade.

**Comment by aqrln** [comment]
We're using pnpm 9 now.
