### ISSUE TITLE
Clarify schema comments

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2546]
https://github.com/prisma/specs/tree/master/schema#comments

![image](https://user-images.githubusercontent.com/183673/82809393-4c3e9000-9e8c-11ea-861f-a6b1481fe405.png)

https://github.com/prisma/vscode/pull/151#pullrequestreview-417577009 highlighted to me, that [my understanding](https://github.com/prisma/vscode/pull/151#issuecomment-633527292) was a bit different from how others interpreted the specs.

Before `///` is not implemented in Introspection and Migrate at all, we should clarify that this is indeed what we want.

**Comment by matthewmueller** [comment]
I wrote this section of the spec and I agree that this should be clarified.

### Problem

Sometimes we want comments to be available inside tools like `prisma generate`, sometimes they're just for us and we don't want to expose them outside the schema.

Additionally it might be nice to persist comments in the database themselves, because SQL databases can support adding comments and this would allow non-prisma tools that work with the database to pick up these comments.

### Potential Solution

This solution is roughly modeled after how GraphQL does `#` vs. `//` where `#` is `///` in our case. The only difference is that triple slashes can also affect migrate.

#### Triple-slash Comment (`/// comment`)

The original intention was meant to do 2 things simultaneously:

1. Show up in the AST, so you can generate documentation based on it.
2. Migrate would persist these in the database if the database supported it.

Free-floating triple-slash comments (see thumbnail above) apply to 1., but not 2.

##### Open Questions

 - does it make sense to conflate these 2 features? It could also make sense to introduce a `@comment()` for this case.

#### Double-slash Comment (`// comment`)

Just meant for the schema, would not show up in either the AST and migrate would not pick these up. 

From VSCode's lens, it still probably make sense to show these, but this decision would  need to be made on a tool by tool basis.

**Comment by janpio** [comment]
In the past: Some comments go into the database, some don't.
Now: Some comments go into the DMMF, some don't.

**Comment by matthewmueller** [comment]
Started writing more context here, but I feel like it's been spelled out pretty clearly in the last comment. @janpio let me know if there's anything else you want me to clarify.

**Comment by janpio** [comment]
As long as there are "Open Questions", I do not know what should be taken as the final decision for any implementation work. Also, I think consensus was that comment should not influence the database at all right now during the meeting?

**Comment by matthewmueller** [comment]
More conversation about the feature and open question: https://prisma-company.slack.com/archives/CFM8D5VHC/p1595508773048200

My takeaway is don't make any unnecessary breaking changes unless we have more concrete feedback.
