### ISSUE TITLE
Support a Date Scalar Type 

### ISSUE THREAD

**Issue by aaronhayes** [prisma/prisma#255]
**Problem**

Lots of databases support Date types. We don't have support them yet because not all databases support them.

**Possible Solution**

In the databases that support Date types, we can use [datasource-specific attributes](https://github.com/prisma/prisma/issues/194).

> **Original Solution**
> 
> It would be useful to have a `Date` scalar type in addition to `DateTime`. It's a common requirement so it would make sense to build into the core scalar types. 
> 
> As an alternative is there a way to define custom types which make use of the underlying database types? I've had a look at this [documentation](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#type-definitions) but that seems to extend the type with constraints. 
I'm interested in something like

```prisma
type Date = @pg.date

```

**Comment by matthewmueller** [comment]
Stepping back to address clarify the problem for newcomers.

**Problem**

Lots of databases support Date types. We don't have support them yet because not all databases support them.

**Possible Solution**

In the databases that support Date types, we add use [datasource-specific attributes](https://github.com/prisma/prisma/issues/194).

**Comment by albertoperdomo** [comment]
This is now supported in the native types feature (in Preview). You can find the docs for it here: https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#datetime
