### ISSUE TITLE
[Introspection] Investigate if our Introspection queries (can) return the correct order of columns

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2554]
To implement https://github.com/prisma/prisma/issues/2434 we need to know if the queries we are using to return the columns of a table can be modified to return them consistently in the order defined by the user.

(PHPMyAdmin for example let's you easily reorder your fields or add fields at a specific location in the list of columns - so for MySQL this has to be possible.)

**Comment by janpio** [comment]
Possible query for Postgres is included in https://github.com/prisma/prisma/issues/2434#issue-617526216

**Comment by carmenberndt** [comment]
Update:
| Database | Link to current query | New Query |
| ----- | ------ | ---- |
| MySQL | https://github.com/prisma/prisma-engines/blob/c65f7b5d18ee8dbd0f43f654571bd3e85b625d80/libs/sql-schema-describer/src/mysql.rs#L180 | `SELECT                column_name column_name,                data_type data_type,                column_type full_data_type,                column_default column_default,                is_nullable is_nullable,                extra extra, table_name table_name            FROM information_schema.columns            WHERE table_schema = ?            ORDER BY ordinal_position` | 
| PostgreSql | https://github.com/prisma/prisma-engines/blob/c65f7b5d18ee8dbd0f43f654571bd3e85b625d80/libs/sql-schema-describer/src/postgres.rs#L138 |  `SELECT  table_name, column_name,   data_type,  udt_name as full_data_type,  column_default,          is_nullable,          is_identity,                 data_type             FROM information_schema.columns             WHERE table_schema = $1            ORDER BY ordinal_position`   |
| SQLite | https://github.com/prisma/prisma-engines/blob/c65f7b5d18ee8dbd0f43f654571bd3e85b625d80/libs/sql-schema-describer/src/sqlite.rs#L127 | existing one seems fine to me already | 

While this works for introspection, the same query has a different result when used in the MigrationEngine.
Before MigrationEngine  sends the schema to the database, the fields are in correct order, after that they are ordered differently.

**Comment by carmenberndt** [comment]
Open Questions:

- What happens to someone who introspected their schema before?
E.g. If `id, foo, bar` is in my db, it would have been written as `bar, foo, id` in the schema. 
On next `introspect` it will be in the actual order. This would mean for all existing users the order in their schema would fundamentally change. This might be problematic, especially if they have other changes at the same time.
- What happens if you create a new database with migrate, then run `introspect` again on that?
I'd expect `migrate` to create the fields in the exact order of the schema.
- What happens if I change the order of my fields in the schema, then run `migrate` again?

**Comment by do4gr** [comment]
Regarding the last point, I think migrate would just ignore the different order.

**Comment by janpio** [comment]
Which would then lead to reordering on the next `introspect` again for the user. We should create an issue for Migrate to support reordering of columns then I guess (Might be a fun follow up task for you @carmenberndt!)
