### ISSUE TITLE
Improve Prisma binding example

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2560]
https://github.com/graphql-boilerplates/node-graphql-server/blob/master/advanced/src/schema.graphql

It's not clear how to download the `database.graphql` schema. Some improvements:

* rename `database.graphql` to `prisma.graphql`
* add a note how to download `prisma.graphql` using `graphql get-schema`
* mention https://github.com/prismagraphql/prisma/blob/master/examples/hooks/ example

**Comment by splodingsocks** [comment]
That'd be really helpful.

Right now I'm looking at

https://www.prisma.io/docs/reference/service-configuration/prisma.yml/overview-and-example-foatho8aip

And seeing that the sample `yaml` file has these commands in it:

```
hooks:
  post-deploy:
    - graphql get-schema --project db
    - graphql prepare
```

Which I added, and I thought they worked because they show green checks after a deploy:

![image](https://user-images.githubusercontent.com/1227109/40853731-5ba70cce-658c-11e8-980e-ea968f895cd3.png)

but I don't have any executable in my path called `graphql`, so it didn't work. What package is that executable from? And why didn't the yaml post-deploy show a failure status when a non-zero exit code was returned?

**Comment by splodingsocks** [comment]
(After a quick google I know that `graphql` is from the npm package `graphql-cli`.[

**Comment by marktani** [comment]
Thanks @splodingsocks, it seems that errors in hooks are swallowed and execution continues. I documented this here: https://github.com/prismagraphql/prisma/issues/2362. I wasn't aware that execution is marked as successful. I will add this as a comment in the other issue. We'll look into this soon!

**Comment by divyenduz** [comment]
@splodingsocks : Thanks for raising the issue, can you please confirm that `graphql-cli` is also not a dev-dependency for you in `package.json` because we resolve both global executable paths and executable binaries from `node_modules`.
