### ISSUE TITLE
Package subpath './runtime/library.js' is not defined

### ISSUE THREAD

**Issue by interk0t** [prisma/prisma#25660]
Hi! Installed dependencies for Prisma
`"@prisma/client": "^5.22.0",
"prisma": "^5.22.0"`
Created a small structure of files .prisma and successfully performed file generation operation using the command
`pnpm prisma generate`
Tables were also successfully created in the database itself using the command
`pnpm prisma db push`
Successfully built the server
`pnpm run build`
But when starting the server I get the following error

`[INFO] Loading NodeJS packages...
[ERROR] "server" package loading failed, exception stack:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime/library.js' is not defined by "exports" in D:\frontend\RAGEMP\server-files\node_modules\.pnpm\@prisma+client@5.22.0_prisma@5.22.0\node_modules\@prisma\client\package.json at throwExportsNotFound (internal/modules/esm/resolve.js:285:9) at packageExportsResolve (internal/modules/esm/ resolve.js:491:3) at resolveExports (internal/modules/cjs/loader.js:450:36) at Function.Module._findPath (internal/modules/cjs/loader.js:490:31) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27) at Function.Module._load (internal/modules/cjs/loader.js:743:27)
at Module.require (internal/modules/cjs/loader.js:965:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (D:\frontend\RAGEMP\server-files\node_modules\.pnpm\@prisma+client@5.22.0_prisma@5.22.0\node_modules\.prisma\client\index.js:26:5)
at Module._compile (internal/modules/cjs/loader.js:1076:30)`

at the same time, any other libraries and dependencies that I installed in the project via pnpm install .... work on the server and there are no errors

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by gniting** [comment]
The error you're seeing suggests that there's a problem with the Prisma client's runtime library. This could be due to an incompatibility between the Prisma version and your project's setup.

One possible solution is to regenerate the Prisma client with a specific output path. You can try modifying your schema.prisma file to include a custom output path for the generated client. Add the following to your generator block in the schema file:

```
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}
```

After modifying the schema, run `pnpm prisma generate` again to regenerate the client.

If the above doesn't work, you might need to update your import statement. Instead of importing from @prisma/client, try importing from the specific generated path:

`import { PrismaClient } from '../node_modules/.prisma/client'`

**Comment by interk0t** [comment]
and after generation I have the following structure
![image](https://github.com/user-attachments/assets/8866186d-dfe9-4b3f-ac7c-704e1e544eec)

**Comment by interk0t** [comment]
but if my import will be like
`import { Item, PrismaClient } from '../../../node_modules/.prisma/client';`
i will get next error when start the server 
`[INFO] Loading NodeJS packages...
[DONE] "server" package has been loaded.
[INFO] Starting packages...
[DONE] Server packages have been started.
(node:22208) UnhandledPromiseRejectionWarning: Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `Node.js`).
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

**Comment by gniting** [comment]
The error you're seeing `(SyntaxError: Unexpected token '??=')` suggests that the generated code is using newer JavaScript syntax that your current Node.js version might not support. This could be due to the custom output path interfering with the normal package structure.

To resolve this issue, try the following:
* Remove the custom output line from your `schema.prisma` file. Let Prisma use its default location.
* Delete the `node_modules` folder and the `package-lock.json` file (or `yarn.lock` if you're using Yarn) to ensure a clean slate.
* Run `npm install` (or `yarn install`) to reinstall your dependencies.
* Run `npx prisma generate` to regenerate the Prisma Client.
* Try starting your server again.

If you still encounter issues after these steps, it might be worth checking your Node.js version. Ensure you're using a recent version of Node.js that supports the syntax used by the generated Prisma Client.

**Comment by interk0t** [comment]
> The error you're seeing `(SyntaxError: Unexpected token '??=')` suggests that the generated code is using newer JavaScript syntax that your current Node.js version might not support. This could be due to the custom output path interfering with the normal package structure.
> 
> To resolve this issue, try the following:
> 
> * Remove the custom output line from your `schema.prisma` file. Let Prisma use its default location.
> * Delete the `node_modules` folder and the `package-lock.json` file (or `yarn.lock` if you're using Yarn) to ensure a clean slate.
> * Run `npm install` (or `yarn install`) to reinstall your dependencies.
> * Run `npx prisma generate` to regenerate the Prisma Client.
> * Try starting your server again.
> 
> If you still encounter issues after these steps, it might be worth checking your Node.js version. Ensure you're using a recent version of Node.js that supports the syntax used by the generated Prisma Client.

I tried it and I get the same error as at the very beginning
`[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime/library.js' is not defined by "exports" in.........`


I still returned to the export option
`output   = "../../node_modules/.prisma/client"`
and noticed a difference in the appearance of the bundle
if I don't use prism in the project then my bundle looks like this and everything runs without errors
//index.js

![image](https://github.com/user-attachments/assets/8578349e-d8f3-4f47-80ef-8d33b41da629)

but as soon as i start using prisma my bundle turns into this

![image](https://github.com/user-attachments/assets/34e45fe6-91da-45da-8318-49348dc7fa7d)

considering that I excluded the prisma from the assembly in the bundle like this in rollup

![image](https://github.com/user-attachments/assets/343fbf16-f036-4c13-a9ee-3af9d8880e18)

**Comment by interk0t** [comment]
the last option seems to work - the Node already sees the prisma and reads the code, but what to do with this error....

`SyntaxError: Unexpected token '??='`

maybe I'm compiling the bundle incorrectly, but for some reason this problem only concerns the prisma

**Comment by interk0t** [comment]
> v22.5.1

I figured out what the problem is, my server runs on node 14.10.1 and the thing is that I can't influence it, the only option is to include prisma in the final bundle and transpile the code for node 14.10.1, but when building I get the error
`[!] (plugin rpt2) RollupError: [plugin rpt2] ../node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/default.js: Unknown version 14.10.1 of Node.js`

**Comment by itzcodex24** [comment]
Hey guys, experiencing the exact same issue. @interk0t could you please detail how you got around this?
