### ISSUE TITLE
Allow `id` inputs to be `string` or `number` if the id type is `Int`

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#2580]
## Problem
We have an unpleasant DX experience with Blitz/Next.js because Prisma strictly enforces the id input type. 

We have routes like `/pages/[id]` which results in a params object of `{id: '123'}` for a route of `/pages/123`.

So this means that in every single component where we are using the route parameter, we have to manually run `parseInt(id)` before passing to Prisma.

## Suggested solution
It would be super nice if Prisma would also allow string inputs for ids and automatically handle `parseInt`. 

Rails does this, and it's very nice because you never have to think about it.

**Comment by Sytten** [comment]
We have a lot of `parseInt` in our codebase due to GraphQL ID being a string. Though I am not sure losing the typing is worth the convenience...

**Comment by riccoski** [comment]
> We have a lot of `parseInt` in our codebase due to GraphQL ID being a string. Though I am not sure losing the typing is worth the convenience...

I ended up adding a custom scalar for ID to parse ID into an Int and serialize it back to string for the frontend

**Comment by flybayer** [comment]
We have added a new hook in Blitz that mostly solves this for us.

```tsx
// Converts taskId to number and has proper typescript return type
const taskId = useParam('taskId', 'number')
```

We also [opened a feature request for Next.js](https://github.com/vercel/next.js/issues/13534) to add number parsing to its router.

**Comment by thebiglabasky** [comment]
Hi @flybayer 

I think that we would rather leave the application layer in charge of dealing with parameters and types to perform changes rather than pushing some magic down at the data access layer ideally.
This would otherwise introduce behaviors defeating the type-safety aspect that Prisma holds dear :)

That means we're unlikely to implement this in the foreseeable future, so I will close the issue to make that clear.
If anyone feels strongly about this and wants to comment, we'll be happy to reconsider and reopen.

Thanks!
