### ISSUE TITLE
New known error: User can not access database table

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2606]
See error message from https://github.com/prisma/prisma/issues/2569

```
   5 export const getLocationTypes = async (req,[object Object], res) => {
   6   const query = req.query
   7   try {
   8     console.log('getLocationTypes running!');
→  9     const locationTypes = await prisma.location_type.findMany(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42501"), message: "permission denied for table location_type", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3485), routine: Some("aclcheck_error") }) }) })
    at PrismaClientFetcher.request (/mnt/c/wdt/wdt-express/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:693:15)
```

This should be a known error:
> Current database user can not access table `location_type`.

or similar.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
