### ISSUE TITLE
Multiple datasources not working

### ISSUE THREAD

**Issue by peterp** [prisma/prisma#265]
I'm following the documentation to target multiple datasources:

```
datasource postgres {
  provider = "postgres"
  enabled = env("POSTGRES_URL")
  url = env("POSTGRES_URL") 
}

datasource sqlite {
  provider = "sqlite"
  enabled = env("SQLITE_URL")
  url = env("SQLITE_URL")
}
```

```terminal
$ echo $POSTGRES_URL
postgresql://peterp:xxx@localhost:5432/peterp?schema=public

$ prisma2 lift up
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Expected a boolean value, but failed while parsing \"postgresql://peterp:xxx@localhost:5432/peterp?schema=public\": failed to parse bool.", "Environment variable not found: SQLITE_URL."] }', src/libcore/result.rs:997:5
stack backtrace:
```

`Environment variable not found: SQLITE_URL.` 

```terminal
$ export SQLITE_URL=false

$ prisma2 lift up
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Expected a boolean value, but failed while parsing \"postgresql://peterp:xxx@localhost:5432/peterp?schema=public\": failed to parse bool."] }', src/libcore/result.rs:997:5
```

`Expected a boolean value, but failed while parsing \"postgresql://peterp:xxx@localhost:5432/peterp?schema=public\": failed to parse bool."`

**Comment by peterp** [comment]
For now my solution is:

1. Wrap the `env()` call in `bool()`: `bool(env("POSTGRES_URL"))`
2. Define the datasource that I don't want, e.g.: `export SQLITE_URL=0`

**Comment by peterp** [comment]
I'm solving this by doing the following:

```
datasource myDatasource {
  provider = env("PRISMA_PROVIDER")
  url = env("PRISMA_URL")
}

```

**Comment by pantharshit00** [comment]
Multiple datasources are currently not implemented. But if you want to switch sources, you are doing it right using environment variables.

**Comment by sameoldmadness** [comment]
> Multiple datasources are currently not implemented.

Would it make sense to add a note to the [docs](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#switching-data-sources-based-on-environments)?

I've spent a couple of hours trying to make it work : )

**Comment by peterp** [comment]
@sameoldmadness probably makes sense, maybe we... either you or me... should add a pull-request to the docs?

**Comment by sameoldmadness** [comment]
I'll create a PR later today, if it's ok.

**Comment by tvvignesh** [comment]
@pantharshit00 One more thing which I should add here is that while we can manually add the datasource by editing the schema file, it would be great if we provide ability to add multiple data sources via the CLI too. Currently if I try to add a datasource again using init, it says:

```
Error: Can't start prisma2 init as /path/to/mydirectory/prisma/schema.prisma exists.
Please run prisma2 init in an empty directory.
```

**Comment by pantharshit00** [comment]
With the `prisma2 init` command this is kind of expected as it will try to bootstrap a new project. But I do think a dedicated command for this will add some value.

Right now we are working on a better CLI flow. Please have a look here:https://prisma-specs.netlify.com/cli/

**Comment by tvvignesh** [comment]
> With the `prisma2 init` command this is kind of expected as it will try to bootstrap a new project. But I do think a dedicated command for this will add some value.
> 
> Right now we are working on a better CLI flow. Please have a look here:https://prisma-specs.netlify.com/cli/

Really love the flow diagram which you guys have here: https://prisma-specs.prisma.now.sh/cli/figma-proxy?id=822:4

Looks like a lot of planning has gone in behind the scenes

**Comment by hitochan777** [comment]
The latest docs seems to say that multiple datasources are supported but I still have the same problem. Has this feature been implemented?

**Comment by pantharshit00** [comment]
No, they are not implemented yet. Can you please point me where it is mentioned?

**Comment by hitochan777** [comment]
Sorry, to be precise, I was talking about switching between datasources depending on environment variables. As [Current docs](https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#switching-data-sources-based-on-environments) says, I was able to switch datasources with environment variables. It was a bit confusing because I needed to specify all the environment variables referred in the `prisma.schema` file when running `prisma2 generate`, otherwise it gave me an error. On the other hand, during runtime I only needed to pass the one whose datasource I want to use.

**Comment by pantharshit00** [comment]
@hitochan777 We are aware of the fact that right now we require env vars as a hard dependency. #800 tracks that and we will fix that soon.

**Comment by konsumer** [comment]
with this:
**schema.prisma**:
```graphql
datasource myDatasource {
  provider = env("PRISMA_PROVIDER")
  url = env("PRISMA_URL")
}
```

**.env**:
```sh
PRISMA_PROVIDER=sqlite
PRISMA_URL="file:data.sqlite"
```

I get this error:
```
Error: Error in datamodel: ErrorCollection { errors: [FunctionalEvaluationError { message: "A datasource must not use the env() function in the provider argument.", span: Span { start: 0, end: 89 } }] }
```

**Comment by Sytten** [comment]
Seems clear enough, you cannot use `env` in the provider, its embedded quite deep in the grammar actually.

**Comment by konsumer** [comment]
@Sytten Yeh, I mean I understand what the error message says. It seems like a fairly common need to not use your production database in dev. I'd like to use SQLite locally, so I don't have to run a postgres server in docker for local dev.

**Comment by Sytten** [comment]
Thats usually not a good idea to change database for local development since each database behave quite differently and it would be hard to optimize queries correctly. Plus with native types on the roadmap I am not sure it would even make sense to support this use case. Its so easy so spawn a DB in docker and most CI platforms have companion services you can launch to do end to end testing.

**Comment by konsumer** [comment]
@Sytten regardless of your opinion of my dev-setup, the fact remains that the above advice no longer works. I'll also add that the main point for using prisma, for me, is that it abstracts this stuff away. I haven't had any issues if I switch database-types in prisma2, I just can't do it with an env-var (as stated above.)  If you look at the [database feature support matrix](https://www.prisma.io/docs/reference/database-connectors/database-features) you'll see that there isn't any "query optimization" I could even be doing here. It's basic (shared) types & CRUD, and regardless of which database I use, the syntax to query with prisma is identical. I'm won't be using (optional, not implemented) native-types, specifically because I value prisma's cross-database capabilities, in this situation. What do you even mean by  "optimize queries correctly" in this case? Sure, I'd be doing lots that if I was using raw SQL (I mean even field/value quoting differences between postgres, mysql, and sqlite require some care) but with any multi-database ORM, when you haven't shot yourself in the foot with native-type requirements, it's not really a thing. prisma1 could do it fine, as can knex or any other ORM, so it's not an unreasonable thing to add to this issue.

**Comment by pantharshit00** [comment]
@konsumer I think https://github.com/prisma/prisma/issues/1487 will solve your problem. We intent to get rid of provider block entirely and infer database type from url

**Comment by konsumer** [comment]
@pantharshit00 yep, that would totally cover my use-case.

**Comment by schickling** [comment]
Closing in favor of #1487
