### ISSUE TITLE
document connectionLimit configuration setting

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2653]
**Is your feature request related to a problem? Please describe.**
There is no documentation about the `connectionLimit` configuration setting.

**Describe the solution you'd like**
All relevant information about the `connectionLimit` setting should be added to the docs, and ideally also in a new example.

It might be beneficial to specifically mention that the env vars like `SQL_CLIENT_CONNECTION_LIMIT` and `SQL_INTERNAL_CONNECTION_LIMIT` are not in use anymore.

**Additional context**
You can find some information about this here: https://github.com/prismagraphql/prisma/issues/2640

**Comment by andrewjmead** [comment]
I was just trying to figure out how to do this. Is it enough to set "connectionLimit" in the docker-compose.yml file using `connectionLimit: 10` inside the default database? Do I also need `SQL_CLIENT_CONNECTION_LIMIT` and `SQL_INTERNAL_CONNECTION_LIMIT`?

**Comment by mavilein** [comment]
The version `1.12` contains a fix for the `connectionLimit` setting. From this version on Prisma will use exactly the number of connections specified. However this setting must be set to at least **2**. This is because we need one connection for the management API. All the remaining connections are used for the service APIs.

**Comment by mavilein** [comment]
We should still do this @nikolasburk @marktani

**Comment by marcosfede** [comment]
can you please add some docs on this? What's the default value?
