### ISSUE TITLE
Update docs/tutorial/examples for exists

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2685]
**Describe the bug**
Docs/tutorials/examples are outdated for `db.exists` API. 

**To Reproduce**
- Follow `db.exists` [here](https://www.prisma.io/docs/graphql-ecosystem/graphql-binding/prisma-binding-gai5urai6u)
OR
- Follow `db.exists` [here](https://github.com/howtographql/graphql-js) 
OR
- Follow `db.exists` [here](https://www.howtographql.com/graphql-js/7-subscriptions/)

**Expected behavior**
Docs should follow API of 2.x binding. 

**Screenshots**
Exists in new API is wrapper in `where`
<img width="597" alt="screen shot 2018-06-25 at 11 16 14 am" src="https://user-images.githubusercontent.com/746482/41841673-324040b8-7869-11e8-9d0b-41fbd217d248.png">

**Versions (please complete the following information):**
- `prisma-binding` 2.x

**Additional context**
https://stackoverflow.com/questions/51013126/graphql-mutation-throwing-error

**Comment by Muppet-training** [comment]
Can someone please explain this further.. 😊

export Interface Exists{
  Link: (Where?: LinkWhereInput) => Promise<boolean>
  User: (Where?: UserWhereInput) => Promise<boolean>
  Vote: (Where?: VoteWhereInput) => Promise<boolean>
}

This is the error I am getting..
Apparently it's caused by the 'exists' function having the wrong syntax..
However I don't know how to solve it.
Below is the code 👇🏼

async function vote(parent, args, ctx, info) {
	const { linkId } = args;
	const userId = getUserId(ctx);
	const linkExists = await ctx.db.exists.Vote({
		user: { id: userId },
		link: { id: linkId }
	});
	if (linkExists) {
		throw new Error(`Already voted for link: ${linkId}`);
	}

	return ctx.db.mutation.createVote(
		{
			data: {
				user: { connect: { id: userId } },
				link: { connect: { id: linkId } }
			}
		},
		info
	);
}

<img width="1235" alt="screen shot 2018-07-17 at 6 50 28 pm" src="https://user-images.githubusercontent.com/10666103/42806721-6c54498a-89f2-11e8-96f5-e92d11f4e210.png">

**Comment by Piepongwong** [comment]
I had the same issue. First, make sure your cli and server have both the same versions. Second, delete the "generated" directory and run `prisma generate` with a complete clean slate.
