### ISSUE TITLE
Query engine panics when the ID used to create a record and the actual ID in the database are different

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2687]
## Bug description

If the ID of a row is different in the database from the ID used to create that row, Query engine panics with:

```
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead
```

## How to reproduce

1. Use this SQL schema to reproduce

```
DROP TABLE IF EXISTS `User`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

2. Use this `schema.prisma` to generate the client.

```
model User {
    id   Int    @id
    name String
}
```

Note that the schema is missing the ` autoincrement` that is present in the SQL

3. Send the following query through the client

```
const data = await prisma.user.create({
  data: {
    id: 0,
    name: 'Alice',
  },
})
```

4. Observe the error 

```
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead
```

Here is a video that demonstrates this error: https://www.loom.com/share/40f6c9f4392a4f75a246d34319d710d8

## Expected behavior

Possibly a known error? 
Or a runtime failure that detects the client being out of sync with the schema. 

## Prisma information

```
@prisma/cli          : 2.0.0-beta.8
```

## Additional Information

- https://github.com/prisma/prisma/issues/1822
- https://github.com/prisma/prisma/issues/1772
- https://github.com/prisma/prisma/issues/1826
- https://github.com/prisma/prisma/issues/1823

**Comment by divyenduz** [comment]
The circumstances in which I ran into this was due to a bug in the migration engine https://github.com/prisma/migrate/issues/467

1. Migrate a database with 

```
model User {
    id   Int   @default(autoincrement()) @id
    name String
}
```

2. Drop the autoincrement from the schema and re-generate the client

```
model User {
    id   Int   @id
    name String
}
```

In my case, I ran into this out of sync issue because of this bug in Prisma migrate: https://github.com/prisma/migrate/issues/467

3. Send the following query through the client

```
const data = await prisma.user.create({
  data: {
    id: 0,
    name: 'Alice',
  },
})
```

4. Observe the error 

```
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead
```

**Comment by dpetrick** [comment]
I investigated this and came to the surprising conclusion that the issue is not the drift between schema and db - it's `0` as a value. Any other value works as expected, but MySQL seems to interpret providing 0 as an equivalent to `NULL` or `DEFAULT`, causing the following behavior:
- Core extracts the identifier (0) from the incoming data.
- Core inserts.
- Core fetches back with 0, nothing returns, error is thrown and transaction is rolled back.
- Meanwhile, MySQL _did_ insert data, but not with 0 but with whatever the autoinc sequence is currently at.

This is an unfortunate edge case but one that I will not fix for now. We should wait for users to actually encounter this edge case before deciding to spend more engineering time on it.
