### ISSUE TITLE
Implicitly inserting null values for mutations

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2755]
@mellogarrett commented on [Tue Jul 10 2018](https://github.com/prismagraphql/prisma-binding/issues/201)

I have a `services` database table (Postgres) with a `NOT NULL` constraint on one field; `created_at`.

When I use the `ctx.prisma.mutation.createService` prisma binding, it automatically adds `null` for each value that I don't specify, which breaks the aforementioned not-null constraint.

So when I run this:
```js
ctx.prisma.mutation.createService({
  service_name: "test",
  status: "On",
  user: "abc123"
}, info)
```
it throws this error: 
<img width="664" alt="screen shot 2018-07-10 at 2 11 14 pm" src="https://user-images.githubusercontent.com/9908831/42529484-9a7cce5a-844c-11e8-8d10-b70dffed422c.png">
The second to the last `null` is where the `created_at` column is

**Comment by marktani** [comment]
Hey @mellogarrett, thanks a lot for your report.

Could you please complete the information according to [the bug report template](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md)? 🙂Thanks!

**Comment by mellogarrett** [comment]
**Describe the bug**
see above

**To Reproduce**
Steps to reproduce the behavior:
1. Create Postgres DB with `services` table with this script:
```sql
CREATE TABLE services (
  service_id SERIAL,
  import_running BOOLEAN,
  service_name VARCHAR(256),
  status VARCHAR(256),
  recovery_options TEXT,
  running_as_user VARCHAR(256),
  startup_type VARCHAR(256),
  version_hash VARCHAR(512),
  tenant_key VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at TIMESTAMP,
  CONSTRAINT pk_services PRIMARY KEY (service_id)
);
```
2. Launch Prisma Server and `prisma deploy` with the below as your `datamodel.graphql`
```graphql
type Service @pgTable(name: "services") {
  id: Int! @unique @pgColumn(name: "service_id")
  confirmed_at: DateTime
  created_at: DateTime
  import_running: Boolean
  recovery_options: String
  running_as_user: String
  service_name: String!
  startup_type: String
  status: String!
  tenant_key: String!
  version_hash: String
}
```
3. Open Prisma Server Playground
4. Run above `createService` mutation
5 See error about violating not-null constraint

**Expected behavior**
I expect all mutations to only include values for fields I specify in my prisma binding call, not insert `null` for missing fields. 

**Screenshots**
see above

**Versions (please complete the following information):**
 - OS: `macOS High Sierra`
 - Prisma CLI version `prisma/1.11.0 (darwin-x64) node-v9.10.1`
 - Prisma Server: `1.11.0`

**Comment by marktani** [comment]
Similar to [this issue](https://github.com/prismagraphql/prisma/issues/2754#issuecomment-405831568), I am not able to deploy a Prisma service with `id: Int!`.

How were you able to deploy a service with `id: Int!`? I get this error:

  Service
    ✖ The field `id` is reserved and has to have the format: id: ID! @unique or id: UUID! @unique.

**Comment by mellogarrett** [comment]
I was connecting to an existing database defined with `service_id SERIAL PRIMARY KEY`
