### ISSUE TITLE
@prisma/client to point to generator client output dir?

### ISSUE THREAD

**Issue by AviBueno** [prisma/prisma#3068]
## Problem
When setting an output value on the generator, the client is indeed generated in that location.
However, `node_modules/@prisma/client/index.d.ts` continues to import from `.prisma/client` (which probably shouldn't get generated once a different output dir was defined?)

## Suggested solution
Have `node_modules/@prisma/client/index.d.ts` import the client from the new output target instead of the default one.

### Motivation

The motivation is to be able to ship an already generated and tested client (e.g. as a deployment artifact) instead of generating it on the target machine.

### Example

For this generator definition:

```
generator client {
    provider = "prisma-client-js"
    output   = "../prisma/client"
}
```

Then instead of `export * from '.prisma/client'`, `node_modules/@prisma/client/index.d.ts` is expected to be:

```
export * from '../prisma/client'
```

### Bug or feature?

Can't decide if this behavior is by design or if it's an inherent bug, so opening as a feature request.

**Comment by pantharshit00** [comment]
This is intended. If you are generating the client into a custom location, you will need to import it from there.

`@prisma/client` package is there for `postinstall` hook and a convenient way of importing the client if you are using the defaults. We call it a "facade" package. We don't write anything to `@prisma/client` package now. Client is now written to `node_modules/.prisma` so that it can survive pruning which yarn tends to do. Before that change we used write the whole client in the `@prisma/client` folder.


Also, read about the facade package here: https://github.com/prisma/prisma-client-js/issues/261

**Comment by AviBueno** [comment]
Thanks. Closing the issue.
