### ISSUE TITLE
Prisma Client Default Generator Output Inconsistent with Examples in Docs

### ISSUE THREAD

**Issue by marcaaron** [prisma/prisma#3130]
**Describe the content you'd like to see**
Currently the default generator output is set to `./generated/prisma` while many of the guides reference and advise to pull in the prisma constructor via `./prisma-client`. It might cause some confusion for people going through the getting started docs since generate and post deploy hooks are set by default, yet they are asked to add `./prisma-client` to the yaml file and run `prisma generate` which would leave them with two directories after calling `prisma deploy` and `prisma generate`

**Describe alternatives you've considered**
it might make sense to either change all the references to `./generated/prisma` or set the default output in the prisma.yml file to `./prisma-client`. both options would allow the user to simply skip the steps where they are asked to run `prisma generate` and amend the generate script in `prisma.yml`

**Comment by marcaaron** [comment]
The only reason I can think not to do this is that people will be missing out on an opportunity to understand how prisma knows where to place the generated schema. I'd suggest maybe adding a note in the getting started docs with a link to the `prisma.yml` section of the docs with instructions on how to customize this output.

**Comment by nikolasburk** [comment]
Thanks a lot for bringing this up @marcaaron! We indeed want to be as consistent as possible across documentation and examples, I've created separate issues that are a bit more actionable than this one and will close this one in favor of the other ones.

In general, we made the decision to always use `./generated/prisma-client/` as the value for the `output`.

Here's our reasoning for that:

- we want to be as explicit and clear as possible about the generated files 
- the generated files should be in a directory called `generated` to make it very clear where they're coming from and that they shouldn't be changed manually
- we call the generated directory `prisma-client` (instead of only `prisma` or only `client`) to make it very clear that it contains the files of the Prisma client
- there's a trailing slash to indicate that `prisma-client` is a directory and not a single file

This is the [issue](https://github.com/prisma/prisma/issues/3199) with the request to update `prisma init`. And this [issue](https://github.com/prisma/prisma/issues/3200) requests to update all docs and examples. I'll work on that soon!

Thanks so much for your input 🙏
