### ISSUE TITLE
Prisma Go Client - error when relying on default Endpoint for generated client

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/prisma#3302]
Version: 1.18.0

In the Go Client if you setup like this:

```go
        client := prisma.New(&prisma.PrismaOptions{
		Debug: true,
	})
```

When requests are made to the client you get this error 

`first path segment in URL cannot contain colon`

After doing a little research I stumbled upon this issue: https://github.com/golang/go/issues/19297
Maybe we need to `url.Parse` for this:

```go
          Client{
             Endpoint: (map[bool]string{true: exists.Endpoint, false: "`http://localhost:4466/go-gin/dev`"})[exists.Endpoint != ""],
             Debug:    exists.Debug,
	 }
```

Note supplying an Endpoint manually does work

**Comment by divyenduz** [comment]
I think this is related to this one: https://github.com/prisma/prisma/issues/3277

**Comment by dominikh** [comment]
This is a documentation issue, not a bug. 

If a PrismaOptions value is provided, all fields have to be set appropriately. That is, default values are only applied if a nil PrismaOptions was provided. This is done to avoid ambiguities concerning empty values (does an empty secret mean no secret, or the default secret?), and because in the majority of cases, providing a PrismaOptions should be unnecessary.
