### ISSUE TITLE
Finish `add npm/yarn/npx in front of suggested commands`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3328]
First part done in https://github.com/prisma/prisma/issues/3210

Not done in JavaScript files like preinstall postinstall (because JS).

I'm checking to do it in NodeEngine too, do you think I should require sdk @timsuchanek?
Not sure if we want that dependency just for that 🤔

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
