### ISSUE TITLE
brew sha256 mismatch

### ISSUE THREAD

**Issue by mberrueta** [prisma/prisma#3361]
**Describe the bug**
```
$ brew install prisma
==> Installing prisma from prisma/prisma
==> Downloading https://s3-eu-west-1.amazonaws.com/homebrew-prisma/prisma-1.19.0.tar.gz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 0f1e867eea6d09727bc763ba66680ad4c2d075ed618a5f54b9bdddcee7fbd991
Actual: 2517026215d5410cec07c0fe82ac11d60c2c201503f238ea16c7b48d7b7dcd84
```

**Comment by divyenduz** [comment]
@mberrueta : Thanks! I just fixed this. Please try `brew upgrade prisma`. But since you would have some brew cache already, I think you (specifically) might run into some trouble. I would recommend doing the following:-

```
brew untap prisma/prisma
brew uninstall prisma
brew tap prisma/prisma
brew install prisma
```

If there is still and error about "Already Downloaded" file, remove that path and run `brew install prisma` again. 

See if that works! 

Thanks!

**Comment by mberrueta** [comment]
it works, thanks!
