### ISSUE TITLE
`We can't release, as the e2e tests are not passing for the ${tag} npm tag!` logic should also check if tested version = version that should be promoted to release

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3370]
When checking the e2e tests for passing tests, it should not only look in the right branch but also double check that the last passing version actually is the same version as what we are currently trying to promote.

**Comment by pantharshit00** [comment]
@janpio Is this still relevant? I am not sure here.

**Comment by janpio** [comment]
Yep, I think that check did not change in the CLI/Client publish/release script, which means it would currently accept a passing e2e test for an old version instead of making sure it is actually the correct one.

The problem is here: https://github.com/prisma/prisma/blob/c8b882573ed9fe9a7b2affbb9b3bc8aa71955bb6/src/scripts/ci/publish.ts#L1284-L1296

It is checking the correct branch of e2e test, but does not check in any way that the last check run on that branch is the version we are trying to promote here.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
