### ISSUE TITLE
Support for Decimal type (Arbitrary Precision Numbers)

### ISSUE THREAD

**Issue by timleslie** [prisma/prisma#3374]
## Problem

The representation of `Decimals` and `Floats` are fundamentally different. Postgres supports the concept of [Arbitrary Precision Numbers](https://www.postgresql.org/docs/10/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL) via the `numeric`/`decimal` type. 

It would be useful for Prisma to provide a core data type `Decimal` to live alongside `Float` and `Int` in order to support arbitrary precision numbers.

## Suggested solution

Since the javascript `Number` type does not support arbitrary precision numbers fields with this value could be types as javascript `String` types.

## Alternatives

Arbitrary precision values can be stored in a `String` field, however this prevents filtering/sorting/aggregation. Values could also be stored as a `Float`, but this loses the arbitrary precision which is important in many applications. Values could also be stored as `Int`, with the decimal shift accounted for manually, but this does not support arbitrary levels of precision in the was a postgres `decimal` value does.

**Comment by timleslie** [comment]
This will hopefully be solved by https://github.com/prisma/prisma/issues/3447:

I suspect the definition would be something like

```
   myDecimalField String @mydb.numeric
```

**Comment by molomby** [comment]
#3447 is good and all but _surely_ this is a common enough requirement that it should be solved by Prisma in a more native fashion?

**Comment by MJGTwo** [comment]
I need this feature for storage of geolocations in MySQL. Float's length is arbitrary in length while Decimal adds exactness to the length of the number being stored. This is usually represented as `lat DECIMAL(10, 8) NOT NULL, lng DECIMAL(11,8) NOT NULL` because longitude involves the hundred's digit while latitude does not. Having this will allow for reduction of precision errors for storing geolocations. An alternative solution would be to use MySQL's Spatial data type, but discussion of that would be for a different issue I'd imagine.

**Comment by kaisellgren** [comment]
I need this too. The common use case is for example latitude & longitude. I'm using Int for that now (i.e. divide by 1000000 to get the decimal number you need). So lat `123.456789` becomes `123456789`.

**Comment by pantharshit00** [comment]
Decimal support was released in the preview of native types: https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#decimal

I think we never posted an update here so here we go.

**Comment by timsuchanek** [comment]
As this is implemented, I'll close this issue.
