### ISSUE TITLE
Support @export directive in queries and mutations

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#338]
The `@export` directive allows you to use the output of one query/mutation as input to another.

One example would be to query the id of the current `User` and use that to populate the `author` relation field of a new `Post`

Prototype is implemented in Sangria, but more work is required before this can be made available: https://github.com/sangria-graphql/sangria/pull/273

**Comment by danmkent** [comment]
Is the @exports directive an agreed standard for graphql that is likely to be supported by other graphql implementations, or is it specific to the sangria implementation?

**Comment by sorenbs** [comment]
@export was introduced as an Idea at [React Europe 2016](https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07). Facebook has an internal implementation that is molded to fit their batch service. See [Lees comment here](https://twitter.com/leeb/status/891105251754885120).

My feeling is that the community has to move this forward before a proposal for inclusion in the Spec can be made. What is your stance on this @OlegIlyenko?

**Comment by danmkent** [comment]
The feature seems really useful. My only concern about adding custom directives is that we then end up with every implementation supporting a different dialect of graphql and we lose the advantages of having a standard in the first place.

If features like this are "not part of graphql" as per the twitter post above, is there some other way for implementers to agree on common approaches so if they support the same features, they are done in a consistent way and we don't up having to learn several different dialects of graphql?

**Comment by OlegIlyenko** [comment]
I generally agree with both sides. 

On one hand we need to experiment in order to innovate and validate the concepts. This is where custom directives are quite helpful. Surely different people will implement (slightly) different semantics, but it's ok at this stace since we validating the concept and figuring how helpful specific semantics is. 

On the other hand, it can be quite beneficial to have a consensus on a specific semantics. As soon as we have proof that the concept works and useful we can put more effort and try to standardize it.

**Comment by kbrandwijk** [comment]
I think there's nothing wrong with using custom directives, the specs only describe that they can exist, and how they are defined.
About this specific `@export` directive, I feel a bit reluctant towards it. First of all, I think it should be used only on mutations, and not on queries. If data is related somehow, the graph should provide you with a way to 'get to it' in your query, without having to use results from one query in the next.

For mutations, most of the use cases where I have seen it described as useful are the result of 'traditional' RDBMS thinking. Nested mutations already allow you to define related nodes directly on create, and on update you would already have the id so there's no need to export it from your query results. I have yet to come across a use case that cannot be redesigned to avoid it.

Also, a mutation always works on a single node (well, at least until the FR is implemented to update using filter). But the result fields might include a child collection, causing the export to become a list. Now, if you have a second query or mutation that takes that export and uses it, does that mean that the query or mutation is repeated for all items in the list? Consider:
```
query {
  allUsers {
     id @export(as: "userids")
  }
}

mutation {
  addPost(userId: $userids, description: "test") {
    id
  }
}
```
Now look at the side effects. Either the mutation fails, because `userId` does not expect a list of id's, or the mutation would be run for every userId. But what if the result of the first query is a single id? Would it still fail? Or would this not be an allowed usage?

Repeating the mutation for all ids would resemble how SQL deals with subqueries, like `UPDATE tblXXX SET field = 'value' WHERE id IN (SELECT id from tblYYY where fieldZ = 'somevalue')`.

Other questions:
- When you export a field that has child fields, would you get them in your second query (`$allPosts.description`)?
- The proposed Sangria implementation allows exporting multiple sets of data to the same variable name. To me, this is also a very confusing implementation, because there's no Type restriction or anything.

Given all of the above, I think the `@export` directive needs to be specified very clearly, before even thinking about how it should be used.

**Comment by danmkent** [comment]
In that example, I would expect the mutation to fail. I would only export an array  if I was going to pass it to something that accepts an array (for example exporting a list of related Ids from one entity in a query and then using that to give another entity the same set of relations in a mutation)

The subsequent query or mutation should behave exactly like it is receiving the value from the client in a normal parameter - that fact it has come from an @export should not make any difference.

If @export is allowed on non-leaf elements of the query, I would expect their child query elements to be available. Again, exactly like I have passed equivalent structured data into a parameter from the client.
