### ISSUE TITLE
go client: find by unique returns a pointer to a model

### ISSUE THREAD

**Issue by gregwebs** [prisma/prisma#3387]
In code like the below:

``` go
modelPointer, err := gql.Model(prisma.ModelWhereUniqueInput{...}).Exec(ctx)
if err != nil {
	return nil, err
}
```

If the record does not exist for the unique input, the result will be an error: `query returned no result`.
This means there is no reason to return a pointer to the model that the client must de-reference. Idiomatic go would be to return the zero value `Model{}`. The contract in go is that the caller must always check the error first, not check for a null pointer and then check the error

On a related note, it is important for the client to be able to reliably determine if the error is due to the id no existing or some other reason. Currently, the client must string match for `query returned no result`. Prisma generates this code: `var ErrNoResult = errors.New("query returned no result")`. However, it should instead have an actual error type that should exist in the library. This makes it possible for the client to reliably use a type assertion.

``` go
type ErrNoResult {}
func (e ErrNoResult) Error() String {
  return "query returned no result"
}
```

**Comment by dominikh** [comment]
The core reason for why we're returning a pointer here is to stay close to the underlying schema and its notion of nullable values; since a unique query can fail, the result is nullable, thus we return a pointer.

Of course we already deviate from the schema in other places when it improves the API, so we could arguably do the same here. However, I don't see any reason to. If we weren't adhering to a schema at all, we'd probably make _all_ values be pointers, for a simple reason: models tend to get big, to the point that copying them around incurs a higher performance cost than the garbage collection and pointer dereferences caused by pointers.

You say that

> that the client must de-reference

The client doesn't have to unconditionally dereference the value. Plenty of other places of the generated API accept pointers to values, based on the notion of optional values. The _user_ won't necessarily have to dereference them either, unless they want to use the value in a subsequent query that requires a non-optional value. But the same is true for other interactions with nullable vs non-nullable types.

> The contract in go is that the caller must always check the error first, not check for a null pointer and then check the error

And the same holds true here: either the error is non-nil, or the value is. Never shall both be nil. While the API doesn't codify this, it is still common and idiomatic Go. The majority of functions that return (value, error) pairs return pointers, and implicitly guarantee a usable result if the error is nil, see net/http.NewRequest as one of thousands of examples.

I'll happily agree that the way we mix pointers and non-pointers takes some getting used to and may not be common for other APIs. The intent was and is to embed parts of the GraphQL schema in the type system. TypeScript benefits from an actual notion of nullable values, while we have to make do with pointers, which carry their own semantics separate from mere nilability. We've tried our best to make it as consistent as possible. An alternate approach would've been to always use pointers for models and do runtime checking that required values weren't nil. It was decided that we'd prefer a more self-documenting API, at the cost of having to switch between pointers and non-pointers.

Concerning error checking: there is no need for string matching. You can compare the returned error to the ErrNoResult variable, i.e. `err == ErrNoResult`; similar to how you'd check for io.EOF or sql.ErrNoRows. That's the whole purpose of making it an exported package-level variable.

Defining new types for errors only serves a purpose when these types contain additional information about the error (or if you subscribe to the notion of behavioural errors, but these would be overkill here IMO, and are up to personal taste.)

**Comment by gregwebs** [comment]
> Concerning error checking: there is no need for string matching. You can compare the returned error to the ErrNoResult variable, i.e. err == ErrNoResult; similar to how you'd check for io.EOF or sql.ErrNoRows. That's the whole purpose of making it an exported package-level variable.

Yes, that's right if it is a stable identifier. It was odd for me to see it is the error in the generated code? Can it be moved into the lib?
The problem with the style of `io.EOF` is that you cannot add any structured or non-structure information to it. If you want to move towards having a stable API (certainly not the case right now) and you might want to add some structure in the future, then the error type is preferable so it won't create a breaking change.

**Comment by gregwebs** [comment]
> The client doesn't have to unconditionally dereference the value. Plenty of other places of the generated API accept pointers to values,
This means you are asking the client to check for `ErrNoResult` and discard it.

> The core reason for why we're returning a pointer here is to stay close to the underlying schema and its notion of nullable values; since a unique query can fail, the result is nullable, thus we return a pointer.

Then there would be no reason to return `ErrNoResult` when it is not found since you are already encoding that as `nil` in the result.

> And the same holds true here: either the error is non-nil, or the value is. Never shall both be nil. 
I think this conflicts with the above. Returning `nil, nil` would make sense to me if you stick to the prior principle.

Definitely the biggest problem is with golang's confusing use of zero values and nil.

**Comment by dominikh** [comment]
> Yes, that's right if it is a stable identifier. It was odd for me to see it is the error in the generated code? Can it be moved into the lib?

We're trying to keep the runtime an implementation detail that users shouldn't have to directly interact with. The user-visible API should be self-contained in the generated client.

> and you might want to add some structure in the future, then the error type is preferable so it won't create a breaking change

That is true. We are, however, fairly confident that we won't be adding any information to this particular error.

> Then there would be no reason to return ErrNoResult when it is not found since you are already encoding that as nil in the result.

As you said, users shouldn't have to check for both an error and a nil value. The function can already fail for other reasons (network issues, database issues, timeouts), so it is only natural to return an error when no result could be found. This is in line with other Go APIs (again we point at the database/sql example.)

> This means you are asking the client to check for ErrNoResult and discard it.

This is not what I said. You were implying that the pointer would always have to be (explicitly) dereferenced. That is not true.
