### ISSUE TITLE
[Schema] Rename `datasource.url` to `datasource.connection`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3406]
Right now our `datasource` block has a `url` property for the connection string:

```
datasource pg {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
https://github.com/prisma/specs/tree/master/schema#datasource-block

While it is correct that this string often is in the form or a URL, this is just the form it takes. 
What it _is_, is the information of a connection used to connect to the database.

I suggest we discuss renaming `url` to `connection` to make this clearer.

**Comment by matthewmueller** [comment]
Do you still want to do this @janpio? Otherwise I suggest we close it.

I think it's okay even if it's not exact. More exact terminology would be:

- https://en.wikipedia.org/wiki/Data_source_name
- https://en.wikipedia.org/wiki/Connection_string

In practice though, most people call it `DATABASE_URL` or `POSTGRES_URL`.

**Comment by janpio** [comment]
My opinion on the term has not changed. If we decide not to do anything about it, of course this can be closed.

**Comment by pantharshit00** [comment]
I am going to close this.
