### ISSUE TITLE
Prisma Client diff on generate

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3407]
It would be awesome if _before_ generating a new client, you could get a overview of how your current client and the one that will be generated compare to each other. What new models, fields, attibutes, what got removed or renamed.

Naive, unclear suggestion:

```
- New field `foo` on model `Bar`
- Field `baz` on model `Example` is now of type String instead of Int
- Relation `brother` was removed from model `Friend`
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
