### ISSUE TITLE
Error: Schema parsing  thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by unlight** [prisma/prisma#3448]
## Bug description
Error while run prisma generate after introspect db
```
Introspecting based on datasource defined in prisma\schema.prisma …

✔ Introspected 489 models and wrote them into prisma\schema.prisma in 1.94s

*** WARNING ***

The following models were commented out as they do not have a valid unique identifier or id. This is currently not supported by Prisma.
- "measureProperties"

Run prisma generate to generate Prisma Client.
```

```
npx prisma generate
Error: Schema parsing

thread 'main' has overflowed its stack
```

## How to reproduce

See above

## Expected behavior

More informative error with line/col number

## Prisma information

version 2.5.1

## Environment & setup

```
@prisma/cli          : 2.5.1
Current platform     : windows
Query Engine         : query-engine c88925ce44a9b89b4351aec85ba6a28979d2658e (at d:\prisma-experiments\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli c88925ce44a9b89b4351aec85ba6a28979d2658e (at d:\\prisma-experiments\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core c88925ce44a9b89b4351aec85ba6a28979d2658e (at d:\prisma-experiments\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt c88925ce44a9b89b4351aec85ba6a28979d2658e (at d:\prisma-experiments\node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.261.0
```

**Comment by pantharshit00** [comment]
Hey @unlight 

This issue is most likely a duplicate of https://github.com/prisma/prisma/issues/3051

Can you please try this again on the latest dev version? We recently fixed this issue(https://github.com/prisma/prisma-engines/pull/1000) and it was merged three days ago so this is not the in the stable release yet. It will be next stable release (2.6.0) which we will release tomorrow.


To try it out now, install the dev version(`npm install @prisma/cli@dev @prisma/client@dev`)

**Comment by unlight** [comment]
@pantharshit00 
Yes it's working in `2.6.0-dev.57`
