### ISSUE TITLE
Improve error message when writing `NaN` (PostgreSQL)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3493]
When trying to write `NaN` to a model you get this error message:

```
PrismaClientKnownRequestError:
Invalid `prisma.withNan.create()` invocation in
/Users/divyendusingh/Documents/prisma/triage/prisma-client-js-797/write-nan-prisma-client.js:7:42

Missing a required value at `Mutation.createOneWithNan.data.WithNanCreateInput.num`
at PrismaClientFetcher.request (/Users/divyendusingh/Documents/prisma/triage/prisma-client-js-797/node_modules/@prisma/client/runtime/index.js:1:227598)
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
code: 'P2012',
meta: { path: 'Mutation.createOneWithNan.data.WithNanCreateInput.num' }
}
```

This happens because internally the `NaN` is turned into a `null`:

```
prisma-client mutation {
  prisma-client   createOneWithNan(data: {
  prisma-client     num: null
  prisma-client   }) {
  prisma-client     id
  prisma-client     num
  prisma-client   }
  prisma-client }
```

As the Prisma Engines can not deal with `NaN` right now anyway (https://github.com/prisma/prisma/issues/3492) the best solution here is to implement an error message similar to a type mismatch (`Argument num: Got invalid value 'NaN' on prisma.createOneWithNan. Provided String, expected Float.`) that tells the user about our limitation of not supporting `NaN` right now. It might also link to some documentation that explains this further.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
