### ISSUE TITLE
FaunaDB Status

### ISSUE THREAD

**Issue by weaversam8** [prisma/prisma#350]
Hi team!

Is Fauna support planned for Prisma 2? If so, is there currently ongoing work on this? If not, what would be the best way to go about adding a datasource for FaunaDB?

Thanks!

**Comment by pantharshit00** [comment]
FaunaDB support is planned. It most likely won't be released with the general release of Prisma 2 though as we are currently focusing on stabilizing the current connectors.

Also, we are writing a Rust client for faunadb, check it out here: https://github.com/prisma/faunadb-rust

**Comment by tibotiber** [comment]
Hi, quick question on this. I'm looking at [this page in the docs](https://github.com/prisma/prisma2/blob/master/docs/data-sources.md) and was wondering if FaunaDB support is planned as a GraphQL API or a full-blown database option? E.g. would index creation be managed by Prisma?

**Comment by pantharshit00** [comment]
I would be using the database client instead of the GraphQL API.

**Comment by schickling** [comment]
@tibotiber I'd like to provide a bit more context:

Fauna currently offers multiple different ways to access your data, most notably (1) Using FQL directly or via a language SDK (2) Using their GraphQL API.

In collaboration with Fauna, we've started working on a [Rust driver for Fauna](https://github.com/prisma/faunadb-rust) which will eventually enable Prisma to add support for Fauna based on (1). Fauna's GraphQL API (2) is a very high-level abstraction and comes with a notable set of tradeoffs that doesn't make it a great fit as a Prisma connector since it hides a lot of Fauna's critical lower-level controls.

**Comment by tibotiber** [comment]
Thanks for the clarification @schickling.

**Comment by earksiinni** [comment]
Just wondering what the current status of this feature is.

**Comment by JohnMilazzo** [comment]
Also curious about current status of this.

**Comment by albertoperdomo** [comment]
Hello everyone!

Thanks for showing interest in a FaunaDB connector for Prisma. I've created #2445 to keep track of the feature request. Please feel free to subscribe to that one to keep track of it and continue the conversation.

Thanks!
