### ISSUE TITLE
`format` invents a database field

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3514]
This is based on this issue: https://github.com/prisma/language-tools/issues/444

When you have a schema like this:

```prisma
model TestModel {
  id String @id @default(cuid())
  testModel OtherTestModel
}

model OtherTestModel {
  id String @id @default(cuid())
}
```

and then run `prisma format` it gets "fixed" to the following schema:

```prisma
model TestModel {
  id               String         @id @default(cuid())
  testModel        OtherTestModel @relation(fields: [otherTestModelId], references: [id])
  otherTestModelId String
}

model OtherTestModel {
  id        String      @id @default(cuid())
  TestModel TestModel[] // <- this should be camelCase?!
}
```

The back relation is expected here, as we want to help people out. What was unexpected for me was that we also add a relation scalar field `otherTestModelId String` that "backs" the `testModel` relation. A user would not have to create that field in the database.

**Comment by pantharshit00** [comment]
I think this is expected. Since OtherTestModel -> TestModel is a one to many relation, the database needs a way to store this relation and that is what `otherTestModelId String` is doing. It is a foreign key. All other fields are virtual and doesn't even exist on the database level. 


Avoiding that foreign key is part of #2018 which will be big effort. Right now we need you to define the foreign key explicitly.

**Comment by pantharshit00** [comment]
I am going to close this now
