### ISSUE TITLE
Do not run GitHub Action Workflows on fork of example repository

### ISSUE THREAD

**Issue by readywater** [prisma/prisma#3539]
## Problem
I started a new Prisma project to test out Prisma2 by building on [this example](https://github.com/prisma/prisma-examples/tree/master/javascript/rest-nextjs). As I was working on the project, I started getting Github Action errors saying that my allotted actions were being used up — within a few days hitting 100%. I hadn't realized it but Prisma was creating a bunch of actions that were running almost constantly.

I'm not sure where in the documentation this lives, but since it impacts a paid feature on Github (and sucked my resources dry so quickly), this should probably be flagged at some point during the database initialization phase. I've searched through the documentation for this, but wasn't able to find it using the action names and similar.

<img width="1184" alt="Screen Shot 2020-09-06 at 13 14 28" src="https://user-images.githubusercontent.com/202041/92324538-f1980100-f042-11ea-8bc8-08a63e3d1931.png">

## Suggested solution
- Explicit callout or setting when seeding the database. 
- Required and explicit statement in the schema.
- Reference the need for github actions in the example documentation

## Additional context
A buddy works on the Github Actions team, so I'll be chatting with him about this next week (as well as passing on this issue) to see if he has any suggestions.

**Comment by janpio** [comment]
Hi @readywater, that is definitely not intended from our side. Sorry.

We use Github Actions to run automation on the examples repository so it is always up to date with our latest development version of Prisma, and automatically run a large suite of integration tests. We did unfortunately not anticipate that this would also run in user forks of this repository, so never thought about how to avoid that.

The developers that built this automation are now already looking into how to avoid this in the future. To make sure you do not get any more costs or lose more quota, best remove the workflows for your fork in the `.github` folder.

Please also contact me at piotrowski@prisma.io for reimbursement of the GH Actions cost that you would now possible get because these Actions runs used up your quota.

**Comment by readywater** [comment]
Thanks @janpio, no worries on the reimbursement. Grateful for the work you all are doing on the Prisma infrastructure and been proud to build [Knowsi](https://knowsi.com) on top of it. Thanks for the explanation!

**Comment by janpio** [comment]
Seems the most promising option for us it to a) either completely change how we run our "update Prisma dependencies" workflows (and possibly put them in a separate repository, bot or even CI provider or b) adapt our workflows to only be run in the `prisma` org (similar to https://github.community/t/stop-github-actions-running-on-a-fork/17965/2). We'll probably opt for b) for now and see if this makes it work and acceptable for users (we are not 100% sure yet if this leads to _no_ minute quota usage yet or not).

**Comment by chrispat** [comment]
One option might be to put a condition on each job `if: github.owner == prisma` which would at least prevent the jobs for actually running on a VM for repos outside the prisma org.

**Comment by janpio** [comment]
While experimenting with something else, I got this message on a repository fork that had already included GitHub Actions workflow files: 

![image](https://user-images.githubusercontent.com/183673/92611161-cae30000-f2b8-11ea-9532-63caf65e50b3.png)

Did you get the same error message @readywater? That would mean that most users will look at the workflow definitions and we can possibly also add a README there or a comment in the workflow file to make this more prominent and include instructions to delete the update workflow.

**Comment by steebchen** [comment]
@chrispat Thanks, but this doesn't seem to work: https://github.com/prisma/prisma-examples/pull/1999. Am I doing something wrong? I tried `if github.owner == prisma` on a workflow level, and then tried `github.repository_owner == prisma` because I could only find the latter in the docs, but neither of them triggered a workflow.

**Comment by chrispat** [comment]
You are right it is github.repository_owner. We do not currently support the if condition on the workflow level so you would need to put it on each job.

**Comment by steebchen** [comment]
@chrispat Actually it works on a workflow level! We just had to quote the owner: `github.repository_owner == 'prisma'`.
