### ISSUE TITLE
Auto type `raw` result

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3551]
As typed template strings are landing in TypeScript soon, we could auto type the result of a [raw query](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access).

https://github.com/microsoft/TypeScript/pull/40336

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. Before doing that, we recommend you to check out the alternative strategy that Prisma has proposed: https://www.prisma.io/docs/orm/prisma-client/using-raw-sql.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
