### ISSUE TITLE
Better error handling for invalid tokens

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3585]
If the `PRISMA_MANAGEMENT_API_SECRET` is not set properly, we should print steps to resolve that issue.
An example for this error is discussed in https://github.com/prisma/prisma/issues/3502

**Comment by timsuchanek** [comment]
Also add note in `prisma token` command to explain the difference between `prisma cluster-token` command.

**Comment by divyenduz** [comment]
We do provide a message when `PRISMA_MANAGEMENT_API_SECRET` is incorrect and that looks like

```
divyendusingh [prisma-3359]$ prisma deploy
Creating stage dev for service prisma-3359 !
 ▸    Server at http://localhost:4466 requires a cluster secret. Please provide it with the env var
 ▸    PRISMA_MANAGEMENT_API_SECRET
```

We definitely need to change `cluster` -> `server`. 

The issue states that we should print steps to resolve this but that has multiple paths:

1. When logged in and the server is added to Prisma cloud, the CLI automatically resolved the management secret (magically). There was a bug in this workflow that cause some confusion but it is fixed now. 

1. When logged in but the server is not added to Prisma cloud or when logged out. We need to provide the management secret environment variable and the current message already suggests that. 

Following things can be done to resolve this:- 

1. Maybe we can have a unified documentation page that we can use here as an error which talks about various ways to resolve it. 

1. We can print the above two points to tell user more about their state (logged in or logged out, server added to Cloud or not) and tell them to resolve it. 

I prefer 1 because we can dynamically change that common documentation page.

**Comment by timsuchanek** [comment]
I agree solution 1 makes the most sense as we need to take both cases into account and can print additional information there without shipping a new CLI.

**Comment by nikolasburk** [comment]
I'm currently adding a `Troubleshooting` section to [this](https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/) docs page with the required info.

Let's adjust the CLI error message to:

"Server at __URL__ requires the Management API secret. Please set the the PRISMA_MANAGEMENT_API_SECRET environment variable.

Learn more about this error in the docs: https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4"

**Comment by nikolasburk** [comment]
When the `MANAGEMENT_API_SECRET` is set incorrectly, the CLI error message should say:

"Can not authenticate against Prisma server. It seems that your PRISMA_MANAGEMENT_API_SECRET environment variable is set incorrectly. Please make sure that it matches the value that was used when the Prisma server was deployed. 

For more info visit: https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/"

**Comment by divyenduz** [comment]
This is available in the last two latest stable versions `1.28.x` and `1.29.x`. I am closing this one, please re-open if required.
