### ISSUE TITLE
Json arrays are not properly stored in underlying postgres jsonb array type 

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3603]
## Bug description

The `Json[]` type seems to be incorrectly stored in the underlying database type `jsonb[]`. Right now it is stored as the first element of the underlying `jsonb[]` postgres array as a string instead of properly using the postgres array representation.

Examples:
- `[]` is stored as `{[]}` instead of `{}`
- `[{test:"test"}]` is stored as `{["{\"test\":\"test\"}"}` instead of `{{"test":"test"}}`
- `[{ test: "test" }, { test: "test2" }]` is stored as `{"[{\"test\": \"test\"}, {\"test\": \"test2\"}]"}` instead of `{{"test": "test"},{"test": "test2"}}`

## How to reproduce
1. Take the following schema and migrate it using Prisma Migrate
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Test {
  id   String @id @default(cuid())
  test Json[]
}

```

2. Generate the client and run the following script:
```js
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  const data = await prisma.test.create({
    data: {
      test: {
        set: [{ test: "test" }, { test: "test2" }],
      },
    },
  });
  console.log(data);
  prisma.$disconnect();
}

main();
```

3. Checkout the stored value in the database
## Expected behavior

Prisma should store the Json array properly so that array features provided by postgres can be utilised and existing json arrays can also be used.

## Environment & setup

- OS: MacOs 10.15.6
- Database: Postgres 11
- Node.js version: v12.18.2
- Prisma version:

```
@prisma/cli          : 2.7.0-dev.61
Current platform     : darwin
Query Engine         : query-engine a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt a6a6ecba74cbaeee0756c312b1b0f2502b27e49c (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.284.0
```

**Comment by janpio** [comment]
As I had trouble wrapping around my head around what exactly is happening here because of the overlapping syntax of JS and Postgres, I played around with it via a GUI:

1. When you run the code above from @pantharshit00, you get the following data:
![image](https://user-images.githubusercontent.com/183673/92953731-872bfa00-f462-11ea-9425-323fdf3ebf4d.png)
The generated SQL for that is: `INSERT INTO "public"."Test" ("id","test") VALUES ('ckeyheue800009eyc65vu5q0s','{"[{\"test\": \"test\"}, {\"test\": \"test2\"}]"}') RETURNING "public"."Test"."id"`

2. When you create an entry for `{ "test": "test" }, { "test": "test2" }` in the database manually, you get the following data:
![image](https://user-images.githubusercontent.com/183673/92953807-a6c32280-f462-11ea-92e2-689b12cea4e3.png)
The generated SQL for that is: `INSERT INTO "Test" (id,test) VALUES ('manual','{{"test": "test"},{"test": "test2"}}');`

So right now we are putting a JSON array of 2 objects into 1 element, but we want 1 objects each in 2 elements.

**Comment by tre-dev** [comment]
I've updated to `2.8.1` (from `2.7.1`) and the same code is throwing an error, when setting a `Json[]`.

Code:

```
timeline: {
  set: [
    {
      status: 'new'
      timestamp: moment.utc().toISOString(),
    },
  ],
}
```

```
Have: Object({"set": String("[{\"status\":\"new\",\"timestamp\":\"2020-10-11T17:19:40.192Z\"}]")}), want: Json]
```

**Comment by pantharshit00** [comment]
Hey @tre-dev 

Can you please open a new issue with a minimal reproduction? This current issue is about internal implementation detail and shouldn't affect the behaviour for you. 

Also, I don't remember we changed anything here yet so a new issue would be appreciated.

**Comment by tre-dev** [comment]
Sure, but my guess is that something indirectly affected it, as this error popped up right after I updated to `2.8.1`

**Comment by matthewmueller** [comment]
I think @pantharshit00 did a really good job laying out the expected behavior:

|                  Given                  |                       Actual                        |                Expected                |                 Description                  |
| :-------------------------------------: | :-------------------------------------------------: | :------------------------------------: | :------------------------------------------: |
|                  `[]`                   |                       `{[]}`                        |                  `{}`                  | Right now we store an array inside an array  |
|            `[{test:"test"}]`            |              `{"{\"test\":\"test\"}"}`              |          `{{"test":"test"}}`           | Right now we store an string inside an array |
| `[{ test: "test" }, { test: "test2" }]` | `{"[{\"test\": \"test\"}, {\"test\": \"test2\"}]"}` | `{{"test": "test"},{"test": "test2"}}` | Right now we store a string inside an array  |
|3|?|{3}|Actual not tested yet|

> Note: `{}` means an empty array.

This is quite important to fix before migrate becomes official, since fixing this in the underlying database will be a pain.

**Comment by Sytten** [comment]
My take on it like I said elsewhere is that the type `Json[]` probably should not exist since an array is a JSON. What I would do is a type `JsonObject` and allow that type to be an array.

**Comment by matthewmueller** [comment]
Interesting idea! I think I like this suggestion better because it would reduce our surface area. We'll chat through the tradeoffs before we sit down to implement this.

**Comment by janpio** [comment]
If the database supports a "list/array of `Json`" type, some people will use it and we should be able to introspect it. Seems like PostgreSQL does not differentiate between the types here at all:

> Arrays of any built-in or user-defined base type, enum type, composite type, range type, or domain can be created.

https://www.postgresql.org/docs/12/arrays.html

**Comment by matthewmueller** [comment]
That's a good point for keeping `Json[]`.

I just realized this isn't really about Migrate. We'll need to help anyone using `Json[]` in Client transition. 

For example, when we fix this behavior, people that have stored `{"{\"test\":\"test\"}"}` in their database will suddenly get back `["{\"test\":\"test\"}"]` rather than `[{"test":"test"}]`. 

Of course we need to do this, but it will be a breaking change for Prisma Client who relied on `Json[]` users and we need to make sure we communicate this.

**Comment by tre-dev** [comment]
I've tested storing array as `jsonb` and besides an empty Array being stored as `{}` they are as I would expect them. Only the types are not correct by `prisma`.

| Given | Expected | Database |
| --- | --- | --- |
| Empty Array | `[]` => type: any[] | `{}` => type: JsonValue |
| `Array[0]` | `[{ a: "b"}]` =>  type: any[] | `[{ "a": "b" }]` => type: JsonValue |
| `Array[1]` | `[{ a: "b"}, {c: "d"}]` => type: any[] | `[{ "a": "b" }, {"c": "d"}]` => type: JsonValue |

**Comment by dpetrick** [comment]
I investigated the issue and the engine exposes the correct API to do the correct things (validated in https://github.com/prisma/prisma-engines/pull/1354/files#diff-75b6d96ece3b54882a54bb29dbe12f1c0c3230024573d1b619ac83fae3c62247R1). However, my assumption is that the client doesn't use the API correctly, because it runs into a type dilemma.

To use json lists of any form correctly, the list also has to be encoded as a GraphQL list on the transport to the engine:
```graphql
mutation {
  createOneModel(data: {
    json_list_field: { set: ["Stringified Json 1", "Stringified Json 2"] }
  }) {
    id
  }
}
```

What the client likely does: 
```graphql
mutation {
  createOneModel(data: {
    json_list_field: { set: "Stringified Json list of Json 1 and Json 2" }
  }) {
    id
  }
}
```

Since all list-based APIs support coercion of a single value to a list (so you don't need to write list syntax all the time), you can provide either `[value]` or `value` for a list field with a single value. The engine coerces `value` to `[value]` if it encounters a list value but no actual list but a single value.

Alright, what I assume happens is: Because valid Json is just that - valid Json - for the client, it stringifies whatever valid Json it finds and stuffs that into the Json field. 

The client needs to either figure out how to distinguish Json[] and Json (that info should be readily available, no?), or we need to make the API super explicit and don't allow this to happen by design.

**Comment by matthewmueller** [comment]
See #4346 for a discussion on migrating.
