### ISSUE TITLE
Database URLs: should special characters in user name and password need to be percent-encoded?

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#3616]
As part of https://github.com/prisma/prisma/issues/2177  I investigated the database URLs we accept in datasource blocks. The password of the connection string in the issue contains a `#`, which isn't valid in a standard URL. As a consequence, it is rejected by the URL parser we use for postgres and mysql connection strings.

Both the [libpq manual](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNSTRING) and the [mysql JDBC connector docs](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html) say that percent-encoding is required for all components of the URL. Currently we have the same behaviour and can connect if the necessary characters in the password are properly percent-encoded.

We could implement non-standard parsing logic, or keep the current behaviour (i.e. use a spec-compliant URL parser). SQLite already has special handling since the connection strings for it aren't really URLs.

If we keep the current behaviour, it should be documented.

**Comment by ryancrosby** [comment]
I ran into a similar issue when using IAM Postgres authentication. I was generating the url using an instance of `URL`. This did not encode the "&" character, which caused a PAM error that was frustrating to debug. I ended manually creating the url, which I was able to get the password properly encoded. Ideally Prisma could raise a better error in this situation. Mostly I just wanted to share this in case other people are hitting this problem as well, this will be fairly common when attempting to use IAM since the password contains several special characters.

```
  // Does not properly encode the password
  const url = new URL(`postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}`);
  url.username = DB_USER;
  url.password = IAM_TOKEN;
  const prismaUrlParams = new URLSearchParams({
    schema: 'public',
    sslmode: 'require',
    sslaccept: 'accept_invalid_certs',
    sslcert: RDS_ROOT_CERT_PATH
  });
  url.search = prismaUrlParams.toString();
  const prismaURL = url.toString();

// Properly encodes the password
  const prismaURL = `postgresql://${DB_USER}:${encodeURIComponent(
    IAM_TOKEN
  )}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public&sslmode=require&sslaccept=accept_invalid_certs&sslcert=${RDS_ROOT_CERT_PATH}`;
 
 ```

**Comment by Jolg42** [comment]
Docs issue https://github.com/prisma/docs/issues/1057

**Comment by janpio** [comment]
This will now be handled on a documentation level, so this can be closed.
If we ever hit cases where our error messages could be more helpful, we will try to implement that - optimally just open an issue about your specific case.
