### ISSUE TITLE
this needs a reload hotkey

### ISSUE THREAD

**Issue by axe-z** [prisma/prisma#3707]
It's so damn frustrating , when you have an httpHeader entered with a token, loosing it on refresh, cause... it's the fastest way with a key combo. 

REFRESH NEEDS A KEY . 
pls.

**Comment by pantharshit00** [comment]
Hi @axe-z,

I am sorry about the trouble you are getting with the current behavior of the playground. I share the same frustration even though I never reported this. 


Since this issue is related to the graphql playground it would be better the track it in the playground repository. I have created an issue for this https://github.com/prisma/graphql-playground/issues/909.


You can follow this issue there. I am closing this one as this repository tracks issues for prisma not for playground.

**Comment by pantharshit00** [comment]
Update:

You can simply turn on `"editor.reuseHeaders": true,` on the playground settings and your problems should be solved.

**Comment by axe-z** [comment]
ok thanks, yet,,, That's not all, the refresh should have a key press option

**Comment by pantharshit00** [comment]
Hi,

I am unable to totally understand you now. Can you provide more detailed feedback with screenshots or a small gif so that I may help you 🙂

**Comment by axe-z** [comment]
weird thing is , refreshing the page ( cmd-r ) is now making a new tab
<img width="816" alt="capture d ecran le 2018-12-15 a 13 21 20" src="https://user-images.githubusercontent.com/27289270/50046142-51c76200-006c-11e9-9598-3139fffa67b3.png">

**Comment by axe-z** [comment]
I can download schema, yet I get weird code , (https://daringfireball.net/projects/markdown/) ?? 
Im not daringFireball, this is so weird. 

like an element of a GraphQL schema as no longer  suggestion for how to access supported similar data. Formatted in [Markdown](https://daringfireball.net/projects/markdown/).","type":"String","defaultValue":"No longer
