### ISSUE TITLE
`databaseType` isn't known by json-schema

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3739]
When using Prisma in combination with MongoDB right now and opening a `prisma.yml` file in VSC, you'll see the following warning message for the `databaseType` field:

![image](https://user-images.githubusercontent.com/1567498/50217303-9dd61780-0388-11e9-8c2c-22f99958ba6f.png)

I assume this is because the `databaseType` isn't yet published in the JSON schema on schema.org.

This is related to #3506

**Comment by azizuysal** [comment]
I think this only happens when you have YAML plugin (https://github.com/redhat-developer/vscode-yaml) installed in VSCode, as that plugin checks JSON Schema Store (http://schemastore.org/json/) to verify keys, and the prisma.yml entry there (http://json.schemastore.org/prisma) does not have a definition for 'databaseType'. A quick update would be nice.

**Comment by MichelMelhem** [comment]
no updates ?
