### ISSUE TITLE
Cannot find module ps-node in windows

### ISSUE THREAD

**Issue by lephenix1234** [prisma/prisma#3741]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 - Prisma Server: [e.g. `1.9.0`]
 - `graphql-cli`, `prisma-binding`, etc. if applicable

**Additional context**

**Comment by pantharshit00** [comment]
Hi @lephenix1234,

As I have already said in the forum thread I am unable to reproduce the issue that you are currently facing. Please provide me with the output of `prisma -v` so that I may investigate further into.

If you are using Mac you try installing prisma with homebrew:  https://www.prisma.io/docs/1.23/get-started/01-setting-up-prisma-demo-server-JAVASCRIPT-a001/#install-the-prisma-cli

You can also try to clean your npm cache via `npm cache clean` and try installing the cli again.

**Comment by pantharshit00** [comment]
I think this is no longer an issue.
