### ISSUE TITLE
Add commands for adding `generator` or `datasource` to prisma schema

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#375]
This feature request will track the suggestion of adding commands to add a datasource or generator to the schema via the CLI.

Right now since the core doesn't support the multiple sources this will take some time.

But in the future, we can have `prisma2 add source` and `prisma2 add generator` commands

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
