### ISSUE TITLE
Optional field is required in @@unique and where clause and doesn't accept null

### ISSUE THREAD

**Issue by LennardWesterveld** [prisma/prisma#3772]
## Bug description

When using optional relations in @@unique then the field is required in @@unique but it should just check if parentUuid isn't filled up it should just check if the name + tenant + parentUuid = NULL is unique.

## How to reproduce

Use this as schema
```prisma
model Tenant {
  uuid String @default(uuid()) @id
  name String

  @@map("tenant")
  AssetDirectory AssetDirectory[]
}

model AssetDirectory {
  @@map("asset_directory")
  uuid           String           @default(uuid()) @id
  name           String
  tenant         Tenant           @relation(fields: [tenantUuid], references: [uuid])
  tenantUuid     String
  parent         AssetDirectory?  @relation(fields: [parentUuid], references: [uuid])
  parentUuid     String?
  AssetDirectory AssetDirectory[] @relation("AssetDirectoryToAssetDirectory")

  @@unique([name, tenantUuid, parentUuid], name: "name_tenant_parent")
  @@index([name, tenantUuid, parentUuid])
}


```
Try to upsert an asset_directory 

```ts
      const assetDirectory = await context.prisma.assetDirectory.upsert({
            create: {
              name: "Asset Directory",
              tenant: {
                connect: {
                  uuid: "UUID",
                }
              },
            },
            where: {
              name_tenant_parent: {
                name: "Asset Directory",
                tenantUuid: "UUID",
              }
            },
            update: {},
          });
```

Will result in
`Argument parentUuid for where.name_tenant_parent.parentUuid is missing.`

Then I got an error that tenantUuid is not filled up because it is a required field, but it isn't in the schema I only want to check then if name + tenantUuid + parentUuid = NULL is unique if parentID is present I want to check if the name + tenant + parentUuid is unique but that way it isn't working right now. So i would assume that parentUuid if not required accepts null as a value so that it can check on that in the database.

## Expected behavior

I think if parentUuid isn't present in the where query it should check on parentUuid = NULL instead of giving an error. Filling in an empty string in parentUuid will result in duplicated entries because it just inserts always a new one.

## Environment & setup

- OS: Mac os
- Database: PostgreSQL
- Node.js version: 14.4.0
- Prisma version: 2.7.0
```
@prisma/cli          : 2.7.0
Current platform     : darwin
Query Engine         : query-engine eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.287.0
```

**Comment by pantharshit00** [comment]
I can confirm the behaviour, we will need to look into this.

**Comment by mavilein** [comment]
This is not a bug but how it is intended to work. Let me elaborate on the reason:

Unique constraints work in a kind of unintuitive way in SQL. Assume this simplified schema:
```prisma
model Foo {
    a Int
    b Int
    c Int?
    @@unique([a,b,c])
}
```
If you define a unique constraint like e.g. `@@unique([a,b,c])` this will translate to a correponding unique constraint in the SQL schema. In this example `c` is optional and hence the column allows `NULL` values. In this case the SQL database will allow to insert `(1,1,NULL)` **twice**!!⚠️ Why is that the case? The reason is that `NULL` does not equal `NULL` in SQL. Hence when the unique index is checked whether a row with the same values exists it won't find any because `NULL != NULL`.
This then bubbles up all the way to our API. Whenever you specify a `where` in our API to identify a single record we want to guarantee that only one record can be found. So in this example we don't allow to look up by `(1,1,NULL)` because we might find more than record matching this criteria. Hence we force our users to specify a value for `c` as well although it is optional. This guarantees that we will only find at most one record.

So how do you work around this limitation in SQL? I would change your example and add an additional unique constraint for `@@unique([name, tenantUuid])`. This new constraint ensures records are also unique when `parentUuuid` is null.
