### ISSUE TITLE
Send sql schema description with the introspection error reports

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3779]
This code is in  place but backend is not receiving them since error report number 2170 which is a long time ago: 
https://github.com/prisma/prisma/blob/4a96b6f272901d3d294c1b7b5cce27926b839792/src/packages/sdk/src/sendPanic.ts#L39-L53

We need to investigate and fix this.

After this is merged, I can display it in the UI.

**Comment by Jolg42** [comment]
I think we already send it if you look at this line https://github.com/prisma/prisma/blob/4a96b6f272901d3d294c1b7b5cce27926b839792/src/packages/sdk/src/sendPanic.ts#L79

**Comment by pantharshit00** [comment]
Yeah, but we need to check if this is actually sending something and it is not null.

Field is nullable in the backend for obvious reasons so it won't error if this is nullable:
![image](https://user-images.githubusercontent.com/22195362/94434987-31708500-01b8-11eb-90db-f9f2535a3650.png)

**Comment by janpio** [comment]
How can we test this code path manually @Jolg42?
Are there tests for it that ensure it is working?

**Comment by Jolg42** [comment]
In migrate we have a test https://github.com/prisma/prisma/blob/62ee40136872a7c55dd81afd404f9a049bedfe51/src/packages/migrate/src/__tests__/handlePanic.test.ts#L49

and a simple script you can run yourself https://github.com/prisma/prisma/blob/6d1b9e82f9a9b3a3bc72d8afc40041fa3bd2da00/src/packages/migrate/src/utils/test-handlePanic.ts

But this will not trigger the sqlDump because it needs to happen in introspection

**Comment by Jolg42** [comment]
Closed with https://github.com/prisma/prisma/issues/3486
