### ISSUE TITLE
Prisma Cloud and Local Instances stopped working with Heroku Postgres

### ISSUE THREAD

**Issue by prajjwaldimri** [prisma/prisma#3834]
**Describe the bug**
All the deployments on the prisma cloud and my local docker instances of prisma have stopped working.

**To Reproduce**
1. Use `prisma init` with Use Existing Database Option
2. Setup Postgres
3. Check Docker Logs they will show `org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres" Detail: User does not have CONNECT privilege.`

OR

1. Deploy to prisma cloud
2. The server will report as Not Reachable

**Expected behavior**
Access postgres db

**Screenshots**
![image](https://user-images.githubusercontent.com/9110203/50902720-a8447800-1441-11e9-8318-c20110c48c2e.png)
![image](https://user-images.githubusercontent.com/9110203/50902734-b4303a00-1441-11e9-8284-140f9ffc3379.png)

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.24.0
 - `prisma` CLI: 1.24.0
 - OS: Arch Linux

**Comment by prajjwaldimri** [comment]
Also getting this error when trying to deploy to cloud instance. Related to https://github.com/prisma/prisma/issues/3502

![image](https://user-images.githubusercontent.com/9110203/50903383-ad0a2b80-1443-11e9-9837-12f26959dec7.png)

**Comment by prajjwaldimri** [comment]
@pantharshit00 I switched to a native dB driver after the issue therefore I have no updates on this issue.

**Comment by figueiredoluiz** [comment]
This still an issue, it should not be closed.

I've been switching from Prisma documentation, git examples and tickets until finding this.
I tried all the methods, including using 100% the cloud interface to even create my Heroku database and no success.

**Error path 1:** Create the Heroku-Postgres database by Prisma panel, on Prisma init select the existing Prisma cluster previous created, can't deploy (the generated files and docs differ, you need to find your way out) 
**Error path 2:** On Prisma init, select create a new database with all Heroku Postgres information, docker up, Prisma deploy error "3015 Invalid signature"

Not the right channel, but you do have a big issue with the documentation, docs and CLI generate files have differences. Besides the use of the sample database, but due to this, I couldn't deploy anything at all.

**Comment by Fabiomad85** [comment]
Any Update About this issue?

**Comment by arifmahmudrana** [comment]
Also I face the same problem. I reset database in Heroku for postgres database. Then today when prisma deploy it worked. So problem may be from Database server possibly Heroku.
