### ISSUE TITLE
Support SQL Server in `executeRaw` and `queryRaw`

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#3861]
We need to parameterize the queries correctly. Different for MySQL and SQLite using `?` and PostgreSQL using `$1`, `$2` etc for parameter substitution, SQL Server has the `@P1`, `@P2` and so on where the number marks the parameter position as we do with PostgreSQL.

This should be handled in our client so the raw queries will not panic out immediately.

**Comment by timsuchanek** [comment]
Created an issue in https://github.com/blakeembrey/sql-template-tag/issues/18

**Comment by madebysid** [comment]
I looked into this a little, and here are my observations:

1. The reason you need `sql-template-tag` with the `pg` & `msql` libraries is because they do not support prepared statements natively.
2. It looks like https://github.com/tediousjs/node-mssql is the "official" client (kinda, at least it is what https://docs.microsoft.com/en-us/sql/connect/node-js/node-js-driver-for-sql-server?view=sql-server-ver15 points to). This is also called `mssql` on NPM.
3. `mssql` has support for prepared statements out of the box, so there's little need for `sql-template-tag` with it.
4. What I mean is that the issue @timsuchanek created is irrelevant. `sql-template-tag` cannot "support" `mssql` because `mssql` does not allow you to hook into their query logic. They do not support sending prepared statements without using their in-built classes / abstractions.

In order to accomplish this, we (prisma) would need to create these prepared statements ourselves rather than put it in `sql-template-tag` (because putting it there makes no sense)

Should I explain the same on https://github.com/blakeembrey/sql-template-tag/issues/18 and close it? I can work on adding prepared statement support for MSSQL in here.
