### ISSUE TITLE
Enable updating foreign keys in updateMany

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#3887]
I can update a foreign key using update one:

```graphql
mutation {
  updateOneNetwork(
    where: { id: "ckfxy9dh00003c5rp97l1cica" }
    data: { user: { connect: { id: "123" } } }
  ) {
    id
  }
}
```

but this doesn’t seem to be possible for update many (it’s of type XUpdateManyMutationInput which only allows updating scalar fields).

This should also be possible for `updateManyX`.

**Comment by dpetrick** [comment]
We're dropping this feature for now because of the following:
The issue itself only mentions connect, but fails to see the complete picture. At the moment we do not support operations on updateMany relation fields of a model at all. Introducing a single operation is half baking relation field support really, so I looked at all operations possible and thought about yes/no:
- connect - Yes: Original scope.
- create - Maybe: Strong candidate. Semantics: Create one record, connect all affected updateMany records to that one.
- connectOrCreate - Maybe: Logical consequence of the two above.
- set - Maybe: Semantics: For every affected updateMany record, connect a fixed set of records.
- delete - No: Unclear semantics.
- deleteMany - No: Even unclearer semantics.
- disconnect - No: Unclear semantics.
- update - No: Not possible.
- updateMany - No: Not possible.
The above leads to an asymmetric API - you can add stuff but can't remove it with updateMany. I believe I rediscovered why we didn't do it in the past.

The consensus is dropping it for now.

**Comment by dpetrick** [comment]
Update: This will somewhat be possible with the new unchecked writes (https://github.com/prisma/prisma-engines/pull/1315). This might be sufficient enough to close this.

**Comment by timsuchanek** [comment]
This is solved by unchecked writes. You can only do this from the side that has the foreign key though.

**Comment by steebchen** [comment]
I can confirm this works. Thanks!
