### ISSUE TITLE
Test more column type mismatches

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3927]
We have many possible combinations:

Saving a `String` into an `Int` column.
Saving an `Int` into a `String` column.
Saving a `Float` into a `Int` column.
...

And that with all the basic data types we have available.
And with all databases.

So we have many dimensions.

**Comment by pantharshit00** [comment]
ping @Jolg42 for reviewing this and to check if this is still relevant.

**Comment by Jolg42** [comment]
This still looks relevant to me.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
