### ISSUE TITLE
Preview feature feedback: `prisma db push --preview-feature`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4058]
Please share your feedback about the preview of `prisma db push` support that was released in [v2.10.0](https://github.com/prisma/prisma/releases/tag/2.10.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo.
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [#prisma2](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by murdockq** [comment]
I like this feature, it should make quick iteration in development easier. Can we have this configurable to have it point to a different DATABASE_URL, either through arguments or  allow specification or override the environment variable.  A couple approaches for the env var approach would be to allow specifying of stages that would then load different .env files like .env.production or .env.development ( [Custom Env Vars](https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used) )

Would it also be possible to do the same iteration of the migrations without always creating a new migration folder?  Essentially I would also like to iterate with just the migrate save feature but instead of creating a new folder every time it essentially does a squash and updates the most recent migration with changes.  That way when I check in a new schema change I will only have one migration folder.

**Comment by samrith-s** [comment]
I have the exact same problem as mentioned by @murdockq. Really need support for passing custom environment variables. Without that, this is a nightmare as I cannot automate quite a few things.

**Comment by Jolg42** [comment]
Note: Changes from 2.17.0 release https://github.com/prisma/prisma/releases/tag/2.17.0

### Improvements and changes for `prisma db push`

- `prisma db push` now handles unexecutable migrations better, offering a path forward by resetting the database. For example, adding a new required field without a default value when there are rows in the table is considered an unexecutable migration; in such situations you will be prompted to first reset the database.
- Changes to command options:
    - The flag `—-force` has been renamed to `--accept-data-loss` to be more explicit - this is required for certain changes that involve losing data, e.g. dropping a table or dropping a column if there are rows.
    - We've added a new flag `—-force-reset` which first resets the database and then updates the schema - this can be useful to start from scratch and as a way to deal with unexecutable migrations (see above).

**Comment by albertoperdomo** [comment]
Thanks for your valuable feedback and helping us improve Prisma!

This feature is GA since 2.22.x.
Feedback is still welcome, preferably via GitHub issues or discussions.
