### ISSUE TITLE
Go client: Why are basic types used as a pointer?

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#4082]
**Describe the bug**
Why are basic types used as a pointer?

```go
id := "f"
user, err := r.Prisma.User(prisma.UserWhereUniqueInput{
	Email: &"f", // obviously not possible
	ID: &id, // works but still annoying
}).Exec(ctx)
```

Shouldn't basic types always used without a pointer? I don't think using pointers in simple queries doesn't add much value, it rather creates more work for the user. Also it's weird that the struct in single methods is not a pointer, although structs would be probably useful to pass as a pointer.

**Comment by pantharshit00** [comment]
cc @dominikh

**Comment by dominikh** [comment]
Fields that are marked optional in the GraphQL schema are implemented as pointers in Go, while fields that are required aren't.

Go doesn't have a `Maybe` type, so the most common way of implementing optional values is via pointers. This allows us to tell apart "no value" from "zero value". For example, an age of `0` is different from `no age`. This becomes even more important in operations that update existing records. Setting a value to `0` is different from not changing a value.

There are other ways of implementing this, but none of them are any less cumbersome than using pointers to primitive types.

To make working with these pointers slightly less annoying we provide the `Str`, `Int32` and `Bool` helpers in the generated client, which take a value and return a pointer to the value.

Storing structs instead of pointers to structs may have a small performance impact, but it is greatly offset by all the other costs of doing network I/O that causes disk I/O.

**Comment by steebchen** [comment]
I am aware of non-existent null types in Go apart from pointers, but I was rather suggesting types like NullString, NullInt, etc. (like the sql package provides). However, after reading your comment, I just realized this would make everything even more complicated than just using pointers so forget that. Thanks for the explanation and the hint for the helpers.

About the struct parameters, though: Why are the structs for some methods not a pointer? It seems that most parameters (e.g. `UsersParams`, `UserWhereUniqueInput`) are all structs except for queries for single items like User which does not use a pointer. I'm rather asking about consistency and not performance.

Example for parameters which are sometimes a pointer and sometimes not (L22 and L23 use structs, L24 uses a pointer):

![selection_999 971](https://user-images.githubusercontent.com/5013932/53288735-6fabf400-378c-11e9-9eae-f70808a699f8.jpg)

Is there a reason for this?

**Comment by dominikh** [comment]
Structs are another case of required vs optional. Creating a user requires data on the user, but a user isn't required to have a `Connect`. Similarly, getting a single user requires a query, getting a list of users accepts a query optionally.

It can be summarized as: pointers for optional values, no pointers for required values.

**Comment by steebchen** [comment]
Argh. Makes sense. I'm thinking in other languages too much. Thanks!
