### ISSUE TITLE
disconnect not working with mongo connector

### ISSUE THREAD

**Issue by tafelito** [prisma/prisma#4106]
**Describe the bug**
The disconnect property seems no to be working when using the mongo connector. 
I have 2 collections, Rules and Groups, this is my schema

const typeDefs = `
  type Rule {
    id: ID!
    name: String!
    description: String
    disabled: Boolean!
    group: RulesGroup!
  } 

  type RulesGroup {
    id: ID!
    name: String!
    status: RulesGroupStatus
    rules: [Rule!]!
  }
`

What I'm trying to do is, update a rule, removing it from a group and inserting it to another. Here's how the mutation looks like

```
mutation updateRule {
  updateRule(
    data: {
      name: "Update Rule 2"
      group: {
        connect:{id: "..."}
        disconnect: true
      }
    }
    where: { id: "..." }
  ) {
    name
    group {
      id
      name
    }
  }
}
```
The rule is indeed added to the second group, but it's not removed from the first one.

**Expected behavior**
Be able to remove one relation and add another. Based on the docummenation, I should be able to use set like this, or an array of ids with disconnect.
```
set: [{
  id: "<old_id>"
}, {
  id: "<new_id>"
}]
```

I don't have set on my schema, I only have disconnect as a boolean.

**Versions**
 - Connector:`MongoDB`
 - Prisma Server: `1.27.0`
 - `prisma` CLI: `prisma/1.27.0 (darwin-x64) node-v11.2.0`
 - OS: `OS X Mojave`

**Comment by do4gr** [comment]
Hey, 

to me the generated operations seem to be correct. Rule always needs to have a group because the field is required. We therefore do not generate the disconnect operation since it would leave you in an illegal state. Set is not generated since it is not a list field.

You can just use a connect to connect another RulesGroup to your Rule and it will automatically disconnect the formerly connected one. 

If you would change Rule to be connected to several RulesGroups as an experiment I would expect the disconnect and set to show up. If you change it to a non-required non-list field the disconnect should be available. 

I hope this helps!

**Comment by tafelito** [comment]
That's the issue I have. When I connect the rule to a different RuleGroup, then the rule gets connected to the new group but it doesn't automatically disconnect from the old one as you mentioned.

I thought setting the disconnect to true was meant for that.


________________________________
