### ISSUE TITLE
Introspect in 2.11.0 changes all updatedAt properties' types to timestamptz and comments them out

### ISSUE THREAD

**Issue by kennytraction** [prisma/prisma#4216]
## Bug description

Using the latest release, 2.11.0, introspect will change all updatedAt properties' types to timestamptz and comment them out.

## How to reproduce

Given a PostgreSQL table:
```
CREATE TABLE IF NOT EXISTS "contact" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "updatedAt" timestamp(6) with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
```

Model prior to introspection: 
```
model contact {
  id                 String              @id @default(dbgenerated())
  updatedAt          DateTime            @default(now()) @updatedAt
```
Model after introspection:
```
model contact {
  id                 String              @id @default(dbgenerated())
  // This type is currently not supported.
  // updatedAt       timestamptz         @default(dbgenerated())
```
## Expected behavior

Expect introspect to not change the schema.

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 12.16.1
- Prisma version: 2.11.0

**Comment by pantharshit00** [comment]
I can confirm the behaviour change between 2.10 and 2.11. 

We will need to look into this more for details

**Comment by do4gr** [comment]
Hey @kennytraction, thanks for reporting this. 

During our work on the new native types feature we also looked into time and date types in Postgres. While doing this we discovered that our libraries in our Rust stack do not fully support types with timezone information. Before 2.11 we introspected both `timestamp with timezone` as well as `timestamp` as Datetime. That was not correct and lead to unexpected behavior when storing types with timezones. Since we are not able to cleanly support types with timezone information at the moment we decided to comment them out during introspection. Normal `timestamp` still works as expected though. 

One workaround I could see for you is to migrate the db column to just plain `timestamp` and do the conversion from and into your timezone before handing over the timestamps to the client. I know this is inconvenient, but we looked into supporting types with timestamp and currently this is not possible for us in a correct way.

**Comment by TLadd** [comment]
Would it be possible to suppress the warnings with a flag and restore the old behavior? It's reasonable to warn about the use of timestamptz if they lead to unexpected behavior but for apps that were working before it would be nice to have an upgrade path without having to migrate the database. I would expect a lot of people using postgres would be using timestamptz since [their docs explicitly suggest it over timestamp](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29).

**Comment by xiaoyu-tamu** [comment]
Could we just keep the old behavior if user didn't enable the nativeType preview feature?

**Comment by piemonte** [comment]
same discussion is also happening here, https://github.com/prisma/prisma/issues/2417
