### ISSUE TITLE
Sequential $transaction with $executeRaw

### ISSUE THREAD

**Issue by zachasme** [prisma/prisma#4269]
## Problem

We wish to run a series of `$executeRaw` queries in sequence using `$transaction`. Using prisma client `2.11.0`, the following:
```ts
try {
  await prisma.$transaction([
    prisma.$executeRaw`
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    `,
    prisma.$executeRaw`
      CREATE TABLE "Users" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4());
    `,
    prisma.$executeRaw`
      CREATE TABLE "Groups" (userId uuid NOT NULL REFERENCES "Users");
    `,
  ]);
} catch (error) {
  console.error(error);
} finally {
  await prisma.$disconnect();
}
```
throws
```
Invalid `prisma.executeRaw()` invocation:


  Raw query failed. Code: `42P01`. Message: `db error: ERROR: relation "Users" does not exist`
```

## Suggested solution

We would like to be able to recreate something like

```sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE "Users" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4());
CREATE TABLE "Groups" (userId uuid NOT NULL REFERENCES "Users");
COMMIT;
```

## Alternatives

For us, the only alternative is still to keep `pg` client around for schema migrations.

## Additional context

As mentioned in #3828, we have a simple schema migration system and wish replace the current pg client with prisma (which we are using for the rest of the application). The most critical migrations usually require multiple queries so until we can run each migration (which is a set of sql statements) in a transaction we have to keep both PostgreSQL clients.

*EDIT: wrong error message, also use extension*

**Comment by supermacro** [comment]
I was just about to create a github issue / feature request along these lines. So instead I'm simply going to add another similar use case for sequential transactions.

However, I'd like to add some specific context about my use case. 

What I'd like to be able to do is perform 2 DB operations serially, and use the result of the first operation in order to perform the second.

I'm working on a project that is conceptually the same as Reddit. 

You have `Posts` which have `Comments`.

```prisma
model Comment {
  @@map("comments")

  id                String   @id @default(cuid())
  parent            Comment? @relation(fields: [parent_comment_id], references: [id])
  author            User?    @relation(fields: [author_id], references: [id])
  anon_author_name  String?
  body              String   @default("")
  votes             Int      @default(0)
  post              Post     @relation(fields: [post_id], references: [id])
  post_id           String
  created_at        DateTime @default(now())
  updated_at        DateTime @updatedAt
  replies           Comment[] @relation("CommentToComment")
  parent_comment_id String?
  author_id         String?
}
```

Note the `Comment` type is recursive. I.e. you can have an infinite level of nesting hypothetically.

Without getting too lost in the details, I'm tracking the structure of a tree of comments on a per-post basis. Specifically; which comments for a post are the "leaf" nodes.

```prisma
// Tracks the state of the leaf nodes on a per-post basis
model CommentTreeState {
  @@map("comment_tree_state")
  post               Post @relation(fields: [post_id], references: [id])
  post_id            String @id
  comment_tree_leafs Json // stores an array of comment ids ["123", "345", "545"]
}
```

What I need is a way to add a comment and then* update the `comment_tree_state` serially in a transaction (since any new comment is, by definition, a leaf node). 

---

* I need to insert the comment first in order to get the id of the comment.

**Comment by supermacro** [comment]
Knex's api for transactions might be a good inspiration. 

https://knexjs.org/#Transactions
