### ISSUE TITLE
Golang, how to set up http method with GET?

### ISSUE THREAD

**Issue by Frank1e0927** [prisma/prisma#4285]
I followed the official document，and make up the go-prisma，but I find that all requests are get methods。

where can i set up the http request method???

is the gqlgen or? somewhere?

**Comment by matthewmueller** [comment]
Hi @Frank1e0927,

Thanks for reaching out, can you give an example of your Go code? 

Currently the HTTP requests is not configurable, but the HTTP client is configurable:

```go 
client := http.Client{}
prisma.New("my endpoint", "my secret", graphql.WithHTTPClient(&client))
```

I'm not sure if that would help your use case. 

I'm a little surprised you're seeing GET requests, because the logic should end up here: https://github.com/machinebox/graphql/blob/3a92531802258604bd12793465c2e28bc4b2fc85/graphql.go#L116 with a POST request.
