### ISSUE TITLE
Support for Postgres' SET command in raw mode/PG RLS policies in general

### ISSUE THREAD

**Issue by webbkyr** [prisma/prisma#4303]
## Problem
I'm looking to use prisma for an api I'm working on that has certain security requirements. We have a shared database and schema for the application, so we use pg's Row Level Security policies to limit row access based on a run-time variable.

I discovered that the SET command isn't supported by prisma's `executeRaw` option. For example:
```
await ctx.prisma.$executeRaw`SET jwt.claims.user_id = ${ctx.currentUser.userId}`;
```

Yields this error:
```
 "message": "\nInvalid `prisma.executeRaw()` invocation:\n\n\n  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near \"$1\"`",
```
Running the command without any variables works fine:
```
await ctx.prisma.$executeRaw`SET jwt.claims.user_id = 1`;
```
We are using @prisma/client and @prisma/cli version `2.8.0`.

## Suggested solution

Allow `executeRaw` to run the [SET](https://www.postgresql.org/docs/12/sql-set.html) command.

## Alternatives

An alternative solution, which I think is actually better but would likely require more work (?), would be to allow the client to apply configuration options to the database directly. OR, provide a hook after a connection is established to set a runtime variable. This would also address unreliable variables that may occur across multiple connections used by our resolvers.

Here is an example from [knex](https://knexjs.org/#Installation-pooling-afterCreate). Here is one from [postgraphile](https://www.graphile.org/postgraphile/usage-library/#pgsettings-function), which exposes `pg_settings` and is executed on each request.

In the meantime, I'd love to hear any suggestions on how others have solved this. Thanks for your consideration.

## Additional context

Sample RLS policy
```
CREATE POLICY user_select_policy
  ON tags
  FOR SELECT
  USING (
    user_id = current_setting('jwt.claims.user_id')::BIGINT
  );
```

Basic model

```
model Tag {
  id                      Int              @default(autoincrement())
  name               String
  userId              Int              @map("user_id")
  createdAt        DateTime  @default(now()) @map("created_at")
  taggings         Tagging[]

  @@id([id, userId])
  @@unique([name, userId], name: "name_and_user")
  @@map("tags")
}
```

The relation table, taggings, also has a user id contraint and an identical security policy.

**Comment by martineboh** [comment]
We’re going to start using Supabase to power automatic subscription for our GraphQL-SDL first Prisma app with PostgreSQL. Supabase require we set these options for PostgreSQL: 
`ALTER SYSTEM SET wal_level='logical';
ALTER SYSTEM SET max_wal_senders='10';
ALTER SYSTEM SET max_replication_slots='10';`

Since Prisma doesn’t recommend editing the migration.sql file directing and #executeRaw doesn’t yet support setting system level parameters in Postgres this way. This is really needed

**Comment by wadetandy** [comment]
Or team is also interested in an improved `SET` functionality, but I have an additional concern with the way I understand prisma connection management to work.  I am using SET to set the current user id so that postgres may use its row-level security (RLS) feature to restrict access based on auth context:

```typescript
await prisma.$executeRaw(`SET current_user_id = ${currentUser.id}`)
```

The most straightforward way is to set this variable on the connection as part of the authentication logic, but because the Prisma connection is shared and pooling happens on the agent side, there aren't the correct APIs to ensure that another parallel request won't overwrite the connection's `current_user_id`. Ideally we would be able to check out a prisma connection in from a local pool and hang it on the request context which gets passed through our application.

**Comment by Jolg42** [comment]
Hi @martineboh 

With the latest Prisma Migrate (Preview) you can actually edit the `migration.sql` file.

Here is an example where editing is used https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-flows/

Where did you see that's it's not recommended to edit it? (just curious to know)

Note: Only edit a migration if you didn't deploy it already to production

**Comment by crubier** [comment]
Being able to SET things per query is very important to use Postgres RLS, which are the best way to have complex authorization rules. This is a must have for my use case.

**Comment by matthewmueller** [comment]
The original problem can be solved by:

```ts
await ctx.prisma.$executeRaw(`SET jwt.claims.user_id = ${ctx.currentUser.userId}`);
```

There's a subtle difference between using tagged template literals (e.g. `$executeRaw` backtick) and functions  (e.g. `$executeRaw('...')`. With tagged template literals, we prepare the query to avoid potential SQL injections. With `$executeRaw` the function, we just pass it through. 

In most cases you want prepared statements, but in this case you want to use the function. 

The larger issue remains. As [@wadetandy mentioned](https://github.com/prisma/prisma/issues/4303#issuecomment-756157408), there's no way to hold a "sticky" connection from the connection pool for the duration of requests. 

With enough traffic, you're overriding other people's SETs. I don't see us exposing the connection pool since that brings a lot of other potential performance side effects, but maybe there's a way to have both. 

Since the discussion has diverged a bit, I've opened up another issue specifically for this issue: https://github.com/prisma/prisma/issues/5128

**Comment by janpio** [comment]
Update: There actually might be a nice Prisma level solution for this. Matt documented it at https://github.com/prisma/prisma/issues/5128#issuecomment-826679950 and we are looking for people that could have a look here. (Supabase users would be great candidates to help out here!)

**Comment by gmwill934** [comment]
Currently using prisma `3.6.0` and it looks like it's still unsupported

```
this.prismaService.$executeRaw`set local "app.current_tenant" = ${tenant.id};`
```

The error I get

```
PrismaClientKnownRequestError: 
Invalid `prisma.executeRaw()` invocation:

Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
```

**Comment by webdeb** [comment]
Sorry, just to add my two cents. this sounds like a feature request

```
// For example we could define how the session variable is structured

session Object {
  userId Int
  role String?
}

model Thing {
  name String
  secret String?
  vote Int

  @rowSecurity(insert, [session.role = admin or session.userId = userId], "Sorry, you are not authorised")
  @rowSecurity(update, [session.role = admin or session.userId = userId], [name], "Sorry, you are not authorised")
  @rowSecurity(read, true, [name])
}
```
For sure there are more scenarios, need to look in details, but is this something the prisma team is interested about?
