### ISSUE TITLE
query by ID, given null ID, returns a dangerously loose SQL

### ISSUE THREAD

**Issue by hyusetiawan** [prisma/prisma#4351]
## Bug description
assume we have the following query:
```
await ctx.prisma.user.findFirst({
				where: {
					id: ctx.session.userId,
				},
			})
```
if ctx.session.userId is null, it will execute a very loose query like so:
```
[0] prisma:query SELECT "public"."users"."id", "public"."users"."uid", "public"."users"."avatar", "public"."users"."email", "public"."users"."name", "public"."users"."createdAt", "public"."users"."updatedAt", "public"."users"."status" FROM "public"."users" WHERE 1=1 LIMIT $1 OFFSET $2
```

I think we should err on secure default behavior and hard throw at the application level before it even gets to DB level

## Prisma information
user schema:
```
model User {
  // this will be automatically sync as resource items
  id              Int              @id @default(autoincrement())
  uid             String           @unique
  avatar          String?
  email           String
  name            String
  membersOf       Membership[]
  createdAt       DateTime         @default(now())
  updatedAt       DateTime         @updatedAt
  status          UserStatus
  schemasAuthored ResourceSchema[]
  viewsAuthored   ResourceView[]
  itemsAuthored   ResourceItem[]
  groupAuthorsOf  Group[]


  @@unique([email], name: "users_email_unique")
  @@map("users")
}
```

## Environment & setup

- OS: 
- Database: postgres
- Node.js version: 14.14.0
- Prisma version: 2.11..0

**Comment by pantharshit00** [comment]
Hey @hyusetiawan 

Looks like you are passing `undefined` to your query instead of `null`. If you pass `null` to that query, your query will fail as your schema doesn't allow IDs to be `null`. You will get the following error from the runtime:
![image](https://user-images.githubusercontent.com/22195362/100358995-f30f0f00-301c-11eb-9705-657041ec7e9e.png)


Now, since you passing `undefined` to the client, it is equivalent of passing no filters at all. So in our query AST we denote it as `1=1` and selects the first result from using the limit + offset in the sql as you are performing a findFirst query. In the coming release, we will also omit the `1=1` from the generated SQL query. 


So please log your value and check that what you passing to the client. Please refer to this page for more information on `null` vs `undefined` in the Prisma client: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined

**Comment by hyusetiawan** [comment]
that is correct, it was undefined, i'll cast it to null, thanks!
