### ISSUE TITLE
sequence decorator doesn't restrict the size of allocation

### ISSUE THREAD

**Issue by YEriin** [prisma/prisma#4429]
in the datamodelv1.1, we can set the id field with the decorator @sequence(name: … initialValue: … allocationSize: 123), but it seems not to restrict the size in fact even if we insert 124 records.

Should it return some error while we insert the 124 record while the allocationSize is 123?

**Comment by pantharshit00** [comment]
@YEriin 

This is not the purpose of sequence decorator.

SQL databases allocate a bunch of ids at once to improve performance. `allocationSize: 100` will allocate 100 ids at once and keep them in memory and use them during insertion. The upside is improved performance but the downside is that this can create gaps in the ids. This is because on server restart/crash those in memory ids are considered lost and a new batch has to be allocated.

So this directive allows you to control this id "allocation" behaviour.

**Comment by YEriin** [comment]
thank u for your explanation
