### ISSUE TITLE
EPIC: Support for native database types

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#446]
Prisma handles values based on core types and best effort implementation as mentioned in this spec: https://github.com/prisma/specs/tree/master/schema#data-types

However, many databases support custom data types like JSON, timestamp without time zone, date, binary formats etc. 

Prisma should provide a mechanism to utilize these DB specific primitives. 

Related issues: 

- Custom Long type https://github.com/prisma/lift/issues/94
- DateTime scalar https://github.com/prisma/prisma2/issues/255
- JSON/JSONB types https://github.com/prisma/photonjs/issues/60
- Postgres timestampz https://github.com/prisma/prisma2/issues/552
- Query Postgres Table with UUID as ID raises error #479

Possibly related:
- Using Prisma enums results in setting DB-level default value #741

Spec issue https://github.com/prisma/specs/issues/119

**Comment by johannesschobel** [comment]
I would also love to see types for `varchar(x)`, `smallint`, `longtext` and so on. If a respective database does not support these types, it should "fallback" to the most appropriate type (i.e., `smallint -> int`.

In Laravel (PHP) they follow a similar approach as can be seen here in the docs:
https://laravel.com/docs/5.8/migrations#creating-columns
They just map to the "database equivalent of FLOAT" (or whatever).

In the grammars for the database engines (i.e., postgres, mysql, ...) this is handled as follows (example for `MediumInteger`)
PostgreSQL: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L487-L496
MySQL: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L501-L510
SQLite: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php#L484-L493

What do you think?

Can we (community) participate and support you in implementing such `Grammars` for the different Database Engines? If so, i can surely create such mappings and provide a PR? Would love to contribute to this awesome project!

All the best,
Johannes

**Comment by matthewmueller** [comment]
@johannesschobel it seems from these grammar files that they still provide common core types, just abstract over them (e.g. jsonb maps to text in sqlite).

Are there grammars that don't implement certain features where the database can't properly store the data type?

**Comment by johannesschobel** [comment]
In Laravel, you have to write "Migration Files", where you define your database structure. In this migration files, you can add fields and define respective types (i.e., `json`, `string`, `integer`, and so on.. )
You can take a look at how to create a migration here: https://laravel.com/docs/5.8/migrations#creating-columns

The `Grammar` files i linked above, are some kind of "mapping" for these `Laravel` types. That means, that laravel, for example, provides types (i.e., `json`) that may **not** be supported by your chosen database system (sqlite, mysql, ...). This "mapping" is then handled by the underlying grammar file.

I think, the grammars implement a certain interface where all these `Laravel Types` are defined and then are implemented in the concrete grammar.. But not sure

I hope this helps?! Do you require further information?

**Comment by matthewmueller** [comment]
@johannesschobel got it. thanks for clarifying, so in a sense they "upgrade" databases by adding features (e.g. jsonb for sqlite) . This works if all your database clients understand this agreement. 

What I was curious about is if Laravel changes the migration API based on the database. So for example, they remove `$table->jsonb` if you're working with an SQLite database. This is more what we are considering. 

We could always add more core datatypes to improve granularity and maybe we should. But it's a tradeoff. More datatypes means more surface area to "upgrade" for other databases. It also means that if we add a new core datatype tomorrow, we'll have to upgrade all datasources to support it.

**Comment by tomhoule** [comment]
See this comment https://github.com/prisma/lift/issues/116#issuecomment-537534050 for a case where we could need what is currently one core data type (`String`) to two database column types (`varchar` and `text`) due to database limitations.

**Comment by johannesschobel** [comment]
Dear @matthewmueller ,

thanks again for your reply on this. In some kind of way, `Laravel` enables new datatypes for underlying databases, yes. However, from 5.0 till 5.8 version (about 4 years) they did not change those `Laravel Types` - they only added new features (e.g., `$table->json`) when features where supported in a stable way from the database engines or can be mapped to "more basic datatypes" (i.e., `Text`) if no appropriate better type exist.

I really like the `Laravel` approach, as it - basically - is just an additional mapper / abstraction layer for the database types. This makes it incredibly easy to just add new databases "on the go". Changes to these grammars are quite limited (you can take a look at the git history of such files).

It is debatable, if all features provided by `Laravel Grammars` should be "ported" or not (i.e., naming conventions for index, ...) or if `Prisma` just takes the idea of mapping internal types to database specific types. Those grammars could also be extended quite easily if you have the need to specify a convention for naming your index structures...

----

Further, i don't think, that the `Laravel Migration` API changed significantly over time. Nevertheless, even if you would change your migration idea, you can still "correct" it in the grammars, right? :laughing:

**Comment by matthewmueller** [comment]
@johannesschobel Would you prefer these "upgrades" versus a grammar that's specific to the database?

For example, you could also have a grammar that doesn't implement `$table->json` for SQLite, but does for Postgres. Do you see that being an improvement or a step backwards?

**Comment by johannesschobel** [comment]
i think, that each specific `Grammar` (i.e., `PostgreSQLGrammar`, `SQLiteGrammar`) should extend a `BaseGrammar`, which may implement a common interface.

The abstract `BaseGrammar` could have some "default one-fits-all" mappings. For example, the `BaseGrammar` could map the `Prisma internal datatype JSON` by default to a `TEXT` datatype in the database. However, `PostgreSQL` offers a "native json support", therefore this "mapping method" may be overwritten in the `PostgreSQLGrammar` to map it to `JSON` instead.

**Comment by matthewmueller** [comment]
@johannesschobel what would you do for very postgres-specific types and extensions like `polygon`, `ipaddress` & `citext`?

**Comment by johannesschobel** [comment]
I think, i would add some kind of `getFallbackType()` method in the `BaseGrammar` which is extended by all other database-specific grammars.

This fallbackType returns, for example `text` as default type... Of course, this fallback Type can be overwritten for a specific implementation (i.e, the `PostgreSQLGrammar` may use `LargeText` as fallbackType, while `SQLiteGrammar` uses `Text`). 

If, for example, the developer defines `IPAddress` or `Polygon` as "Prisma Datatype`, and respective Datatype is not defined for the database, i would fallback to the `fallbackType`. For PostgreSQL this would be `LargeText` for example.

At a later point in time, you could just add the `getIPAddressType()` method to the `BaseGrammar` or whatever specific grammar and map it to a proper database field type. If, for example, `SQLite` still does not support `geo` types, just omit it - it will then fallback to the default..

What do you think?

**Comment by ctrlplusb** [comment]
I like the idea of being able to support underlying native types. 

I saw an example of a cool idea somewhere that would provide a lot more flexibility in this regard.

```groovy
scalar CIText = String @raw("citext")

model User {
  id  String @id
  email CIText
}
```

I really like this derived type idea. Something to keep in mind when spec'ing.

**Comment by namesphill** [comment]
Hey guys, do you an ETA for this feature, or at least JSON/JSONB in Postgres? Cheers!

**Comment by divyenduz** [comment]
---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_niko-public-1_stderr.log (timestampz)
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_sonarqube_stderr.log  (bytea)
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_standup-slack-bot_stderr.log (timestampz)

**Comment by webnoob** [comment]
Any news on being able specify DB field lengths?

**Comment by janpio** [comment]
> Hey guys, do you an ETA for this feature, or at least JSON/JSONB in Postgres? Cheers!

Basic Json support has been added with beta.4 and beta.5 - check the release notes for details.

> Any news on being able specify DB field lengths?

No. We are aware this is badly needed and are looking into how properly solve this in our context.

**Comment by beeplin** [comment]
@janpio maybe it can be done by introducing new `@type` midifier like: `fieldName  Int @type("bigint")`

and since js/ts lackes native types to handle differences between integers, floats, unsigned big integers etc, i think it can only rely on users to guarantee the validity of data type instead of doing automatic type.checking

**Comment by maoosi** [comment]
Just checking if any progress/updates on this? The biggest drawback for me right now is the limitation around the String definition, currently generating varchar(191) on MySQL rather than the text data type mentioned in the docs.

**Comment by mavilein** [comment]
In the last days we looked into this and have reached internal consensus on a proposal.

The proposal is based on the mechanism that a user is decorating a field with an additional attribute that specifies the native data type in the underlying datasource. The attribute is scoped to the underlying datasource by prefixing it with `{datasource_name}.{data_type_name}`. The scoping is intended for future proofing the schema for support for multiple datasources within one schema. 

```prisma
datasource mydb {
  provider = "postgres"
  url      = "..."
}

model Blog {
  id       Int    @id
  title    String @mydb.VarChar(99)
  someJson Json   @mydb.JSONB
}
```

Notes:
* If the user does not specify a custom type this way the existing default type mapping kicks in.
* A user can easily see which data types are used in the client and
which one in the datasource because the combination is spelled out explicitly.
* The name of the native type is the Pascal cased version of the original name in the docs of the database. E.g. `varchar(x)` on Postgres becomes `@myb.VarChar(x)`. 
* The user needs to know the compatibility of prisma and datasource types. E.g. a `String` is compatible with `@mydb.VarChar(x)` and `@mydb.Text`. But `String` is not compatible with `@mydb.XML`. The parser will validate this and error for wrong combinations. The VS Code extension will be to assist with this through auto completion.
* A native type always maps to exactly one Prisma data type.
* If a datasource with multiple providers is used (e.g. `provider = ["sqlite", "postgres"]`) an intersection of the native types of the providers is created. Only types that are part of this intersection can be used. This e.g. means that the `CiText` type for postgres is not available if sqlite is part of the providers as well.

**Comment by matthewmueller** [comment]
Thanks for writing this up. I'd still suggest we don't require manual type-mapping in the schema. I'd prefer:

```prisma
datasource mydb {
  provider = "postgres"
  url      = "..."
}

model Blog {
  id       Int              @id
  title    mydb.VarChar(99)
  someJson mydb.Jsonb
}
```

While the seeing your mapping is certainly nice to have, there are many times when our Prisma type doesn't translate into the generated parameters. For example:

```prisma
datasource mydb {
  provider = "postgres"
  url      = "..."
}

generator go {
  generator = "prisma-go-client"
}

model Blog {
  id       Int      @id
  createAt DateTime mydb.timeStamp
}
```

In Go this would map to `time.Time`, in Javascript this maps to `Date`. There will always be a mental link you need to make between:

```
Date => DateTime => @mydb.TimeStamp
```

I'd suggest we just ask the user to make this link:

```
Date => mydb.TimeStamp
```

Tooling can also aid this approach. There can be tooltips that tell you the mapping given the generator.

**Comment by timsuchanek** [comment]
Which database types are compatible with which prisma types, is something to be figured out anyway, latest when I use the client.
It can be figured out later in the execution / generation, but could also directly be visible in the schema.
That way, things are very explicit and as someone who reads the schema, I directly understand, what maps to what.

In general, I'm always a fan of early feedback in any workflow.
If I as a user early while writing the schema get feedback, e.g. through the VSCode extension, I directly can understand then already how the types map. The extension can also show you, what is available if you e.g. want something compatible with `String` with autocomplete, which is pretty awesome because that way you might explore db types you didn't even know about.
So the schema in that sense has a self-documenting nature.

As soon as you remove that information from the schema, especially as a new user or just a user who is not familiar with a specific native type, I somehow now need to look that up, open the docs etc. At least for me, it's not always clear which type maps to which.

Afterall the user just needs to learn the mapping of the Prisma type to the language type once and will always understand the schema (even though it looks more verbose).

**Comment by timsuchanek** [comment]
Another point about this is the mental model.
One of the big advantages of Prisma is the higher abstraction on top of low-level database types.
In my application, I just think about a String, no matter if it's stored as a `text` or `varchar(64)` in the database.
Achieving the split between this higher abstraction and native types is of course the big challenge.
By keeping a `String` as it is in the schema and just providing the "implementation detail" or "storage detail", I can still think about it from the Prisma boundary on as a `String`, meaning the Prisma interface is still just the good old `String` that I'm used to.

**Comment by matthewmueller** [comment]
> In general, I'm always a fan of early feedback in any workflow.
> If I as a user early while writing the schema get feedback, e.g. through the VSCode extension, I directly can understand then already how the types map. The extension can also show you, what is available if you e.g. want something compatible with String with autocomplete, which is pretty awesome because that way you might explore db types you didn't even know about.
> As soon as you remove that information from the schema, especially as a new user or just a user who is not familiar with a specific native type, I somehow now need to look that up, open the docs etc. At least for me, it's not always clear which type maps to which.

The main reason I brought up tooling is because tooling works _both ways_. For example, you could have faint, but always visible annotations in VSCode that show the mapping. The cool thing here is that you can go a step further and actually map it to your generated client type, not the Prisma type, which is a virtual type over the generated client type.

I'd like us to consider this without tooling. For example, using Notepad. Perhaps unrealistic, but it appropriately illustrates the mental hurdles involved in writing a correct schema with Native types.

> In my application, I just think about a String, no matter if it's stored as a text or varchar(64) in the database.

You can still do this. What you can't do is fool yourself into thinking that it's a String when it actually maps to a char.

**Comment by steebchen** [comment]
I agree with Matt. Another straightforward example is the `ip` type. With Matt's suggestion, you can do:

```
ip @pg.ip
```

Which will map the type to a string in js, and to a net.Addr in Go.

However, if we would need to use some data type, we would need to specify a Prisma data type, e.g. String:

```
ip String @pg.ip 
```

This would work for js, but not for go. It's not a string in go, so `String` is kinda wrong here.

---

We could solve this by introducing a new Prisma type, for example `IP`. However, note that we would need to do this for all custom types we want to support, even if they're just supported by a single database. However, it would still be confusing:

```
ip IP @pg.IP 
```

You still don't know what it maps to. It would map to net.Addr for go, but for js it would actually just be a string, so one might think "why can't I just use `String`?".

**Comment by matthewmueller** [comment]
The plan proposed by @mavilein is the direction we're heading. Unassigning myself as I'm not aware of anymore product work to be done here.

**Comment by Hebilicious** [comment]
Really excited for this one!
@mavilein How does this proposal deal with types such as geometry (postGIS) ? How do we map them to prisma?

**Comment by mavilein** [comment]
@Hebilicious : Geometry types are not part of this first effort for native types. Supporting those will be a separate effort since those types will also require special client APIs. If you have an opinion on how those APIs should look like feel free to open a separate issue and share your thoughts with us 🙏

**Comment by matthewmueller** [comment]
Thanks for the discussion everyone. Closing in favor of https://github.com/prisma/prisma/issues/3447

**Comment by willin** [comment]
@mavilein which version to support? using v2.6.0 now, found not yet.

**Comment by pantharshit00** [comment]
@willin The work is still ongoing and the discussion from this issue was summarised on #3447 and that issue is now tracking this

**Comment by devuxer** [comment]
Wonder if I'm missing something, because my timestamptz columns are not working in @prisma/client 2.26.0.

I get:

> *** WARNING ***
>
> These fields are not supported by the Prisma Client, because Prisma currently does not support their types.
> - Model "Info", field: "whenCreated", original data type: "timestamptz"
> - Model "Info", field: "whenUpdated", original data type: "timestamptz"

**Comment by poorvi-vaish** [comment]
can we use Buffer data type for images?

**Comment by janpio** [comment]
Please open a discussion for this question @poorvi-vaish. Thank you.
