### ISSUE TITLE
WhereUniqueInput creates OR query when using multiple parameters

### ISSUE THREAD

**Issue by ivopatty** [prisma/prisma#4509]
**Describe the bug**
When the client composes a query on multiple unique fields, Prisma generates an OR query based on the passed arguments. 

This currently results in a single matching Node being returned when the passed arguments do not match the actual outcome

**To Reproduce**

1. Create a model with 2 unique fields (i.e. email and username)
2. Insert a node where `email = test@test.com` and `username = user1`
3. Query the single node with parameters `email = test@test.com` and `username = user2`
4. The query returns `user1`

**Expected behavior**
I would expect a null value to be returned since the specified query does not match the result

**Screenshots**
<img width="1440" alt="Screenshot 2019-05-08 at 17 04 23" src="https://user-images.githubusercontent.com/1337913/57385826-75be4800-71b3-11e9-8955-37d11ad6eb47.png">

**Versions (please complete the following information):**
 - Connector: `Postgres` & `MySQL`
 - Prisma Server: 1.32.2

**Comment by do4gr** [comment]
Hey, I looked into the issue and this is a bug that stems from GraphQLs inability to express that we want exactly one unique field out of the possible ones there. We already had a check that at least one was provided, but we want exactly one. I added a validation that will generate a proper runtime error for your query. 

I added a test that documents our expected behaviour for WhereUniqueInputs and also shows the responses. You can find it here: server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/WhereUniqueSpec.scala
