### ISSUE TITLE
Preview feature feedback: Prisma Migrate

### ISSUE THREAD

**Issue by 2color** [prisma/prisma#4531]
Please share your feedback about the new Preview version of Prisma Migrate that was released in [v2.13.0](https://github.com/prisma/prisma/releases/tag/2.13.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-migrate`](https://prisma.slack.com/archives/CBFFY3066) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by xiaoyu-tamu** [comment]
Waiting for `nativeType` to be supported :-)

**Comment by himalayaahuja** [comment]
Was really expecting a stable production ready release for this, not another **PREVIEW** or **EXPERIMENTAL** release. :(

**Comment by albertoperdomo** [comment]
@xiaoyu-tamu Native type support is indeed on our list.

**Comment by albertoperdomo** [comment]
@himalayaahuja Preview is the a big stepping stone towards a production-ready release. We did a lot of changes to Prisma Migrate, which is why decided to release in Preview before going with GA.

**Comment by nickreynke** [comment]
Missing the beloved `--auto-approve`, in the case of running `prisma migrate dev --preview-feature` in a CI/CD pipeline where no user interaction is possible.

**Comment by 2color** [comment]
Hey @nickreynke 👋🏼,

`prisma migrate dev --preview-feature` is not actually intended for use in a CI/CD pipeline. Instead, it's recommended to use the `prisma migrate deploy --preview-feature` command which will apply the migrations without prompts.

**Comment by nickreynke** [comment]
Ah, thank you @2color ✌️

**Comment by CyberiumShadow** [comment]
Wanting to clarify here https://www.prisma.io/docs/concepts/components/prisma-migrate#lack-of-rollbacks--down-migrations

"Prisma Migrate does not currently roll back a migration without resetting the database. "

Does this mean that you generally shouldn't be rolling back a migration on production

**Comment by thebiglabasky** [comment]
The approach we favor the most is to adopt a "forward-only" migration policy where each migration is meant to put the schema in a shape that stays compatible with the previous version of the code so that rolling back the application code deployment is sufficient to maintain the application running without issues. That comes with choosing not to delete columns or tables which hold data in one go, but rather proceed with additive changes instead, or renaming whenever necessary rather than removing completely. Removing columns or tables from production can be fine once the said column or table isn't used anymore, ideally for some time, and that it doesn't come at the risk of locking tables accessed a lot, which could put down an application. That is worth removing columns and tables when the risk of removing them is generally low (e.g. traffic to the application is only going to lightly suffer a whole table lock), and the value of reclaiming the storage space is high.

Here's an article talking about forward-only migrations in practice which gives practical details about that: https://sbg.technology/2016/02/02/how-we-release-so-frequently/

The abstract version of how to proceed is described in this article: https://martinfowler.com/bliki/ParallelChange.html.

You can (and sometimes may inevitably have to) fix a failed migration manually e.g. if it failed halfway through the process, by crafting and running a custom SQL script. While that's something everyone tries to avoid as much as possible (it's risky, error-prone, stress-inducing, and usually painful), there is no way to have 100% guarantees that a "down" migrations would nicely get the schema back to its original state without risking to lose data: what if a part of the new version of the application worked and started adding data to the newly created columns? Rolling back would be dropping that data, which can cause users quite some frustration...

**Comment by albertoperdomo** [comment]
Hello @PhilippMolitor,

the feature request of being able to run Prisma Migrate programmatically is tracked here: https://github.com/prisma/prisma/issues/4703

What's your process for deploying new versions of your code? Is it automated? All it would take is to inject there a CLI call to `prisma migrate deploy`.

**Comment by PhilippMolitor** [comment]
I feel like handling this with a CLI call isn't clean at all. For example, with knex i did the following:

1. check the target databases migration status (older, newer, same)
2. if older, quit all other instances of the app, enable internal maintenance mode, apply migrations
3. if newer, throw error message and quit
4. if same, proceed with application bootstrapping

Doing all of this by parsing STDOUT doesn't really do it. Prisma is very clean in elegant in its API, so this should be no exception.

To deploy my code, for very small-scale apps i synced a git repo onto the target server and re-deployed docker containers. Other solutions get deployed via CI with SSH. I would really like the application to handle the database part on its own.

Thanks for your info on the thread that tracks this issue.

**Comment by albertoperdomo** [comment]
@PhilippMolitor Thanks so much for your follow-up comment adding color. Would you be interested in having a chat over Zoom to discuss your setup and expectations in more detail? If yes, can you please book some time with me here? when it works for you? (I'm going to be off for some days for the Christmas break, but there should be time available today/tomorrow and early January) - https://calendly.com/alberto-prisma/30-min-zoom-call

**Comment by PhilippMolitor** [comment]
@albertoperdomo Sure, sounds like a great way to have a positive impact, thank you. I will book a call.

**Comment by michiomochi** [comment]
Waiting for String character limitation 🙏 
I expected below code for character limitation.
```
model User {
  name String @limit(50)
}
```

**Comment by Jolg42** [comment]
Hi @michiomochi, indeed it's not ready yet but we are actively working on it, we call this the "Native Types" feature and you can track its progress here https://github.com/prisma/prisma/issues/3447

**Comment by PhilippMolitor** [comment]
@Jolg42 having a generic length attribute would be really great, as every database i know has some implementation of it. Having this without using native types should be possible right? It seems like a core feature of databases to me.

**Comment by Jolg42** [comment]
@PhilippMolitor the length limitation is not implemented in SQLite ([for example a VARCHAR(30) is in fact a TEXT](https://www.sqlite.org/datatype3.html)) so a generic limitation attribute would not work for SQLite.

The Native Types feature will ensure that the feature works on the specified database.

The universal solution could be to do it during runtime with Prisma Client when creating / updating data.

**Comment by michiomochi** [comment]
@Jolg42 
Thank you for your reply!
I understand the progress of this feature 👍 
Looking forward to the release 🤗

**Comment by dan003400** [comment]
I would love to be able to use prisma migrate reset when running integration tests, but at the moment this requires a confirmation prompt which kills the ability to use this in automated testing. Can we add a --force flag to this command please. This command is PERFECT for the start of integration tests, it drops all the previously creates data, runs migrations, then we generate the client artifacts. Only thing stopping us from using it is the prompt.

**Comment by Jolg42** [comment]
Thanks @dan003400 for your feedback I think it would be great too, I'll pass the word to my colleagues to discuss 😃

**Comment by adaddeo** [comment]
Fairly minor but ran into a corner case where I wanted to run a migration created with `--create-only` but not have it automatically generate and apply another migration for another changeset.

**Comment by albertoperdomo** [comment]
Interesting @adaddeo - is there anything you can share in terms of context? Why did you want to run a previously generate migration but not generate new migrations? In this case, would you say it would be ok to git stash the changes in your schema, or do you the need for a flag to skip the new changes?

**Comment by albertoperdomo** [comment]
@dan003400 `prisma migrate reset --force` is now live in 2.15.0

**Comment by pantharshit00** [comment]
Natives Types support is also live in 2.15 :)

**Comment by adaddeo** [comment]
@albertoperdomo I had done a create-only migration to rename a column. I altered the migration to just be one line which renamed the column. When I went to re-run the migration I was being prompted to name a second migration and was confused as to what else had changed. It turns out the index names are also being synced with the schema (which is very nice IMO) and since my migration only changed the column name the second was changing the index. So all in all it actually made sense once I figured out what was going on but it seemed strange in the moment I wasn't able to "apply" that pending migration without creating another one.

One thing that wasn't immediately clear, even after looking through the docs (though the concept is definitely [outlined here](https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-flows#development-environments)) is how `prisma migrate reset` is useful in development for modifying an uncommitted migration (say I want to add a column but have a clean PR with one migration). It works great once I figured it out but took me a minute to pick up on as I was thinking more in terms of rolling back as you would in other systems.

**Comment by tadejstanic** [comment]
In one of my projects, we started using Prisma because we wanted to speed up the development compared to some previous stacks that used either knex or TypeORM. And boy, what a different DX, of course in a better way. But in that project, we couldn't use Prisma Migrate because it was not production-ready yet. So we decided to use [graphile-migrate](https://github.com/graphile/migrate) migration tool and I must say that if you like writing DB schema changes in a raw SQL, that combo (prisma & graphile-migrate) worked very well (by using `prisma introspect & prisma generate`). 

But I had constantly in mind, that the right way for handling migrations when Prisma is involved is to treat `schema.prisma` as a single source of truth especially when you need to alter the schema manually. If you're using `prisma.introspect`, I think you are more or less out of options to do any kind of manual changes in the `schema.prisma`, unless you don't want to constantly check what was left in the schema after you did the introspection. Therefore I was eager to see when Prisma Migrate will near to GA. 

Today, I made a few tests with Prisma migrate and I'd decided to share my experiences. I like how it is integrated with the Prisma.Client, however, what I miss is a better `draft` mode. I found that generating multiple migrations files during the development just to apply all the changes that are sometimes kind of `roll-backs` is quite cumbersome. What I was expecting was something that I discovered in `graphile-migrate`, where you have a so-called `current.sql` that represents a migration in a `draft` mode, and whenever there is a change, it runs against the shadow and finally the development db. But the main trick here is, how the SQL statements should be written. They have to be [idempotent](https://github.com/graphile/migrate#idempotency). And this requirement opens the door for altering the schema without having roll-back statements or additional steps (i.e. manual change of the migration file) like we have in the current version of `Prisma Migrate`. 

So I imagine applying this kind of approach to Prisma Migrate would be something like this:
1. Change in `schema.prisma` occurs;
2. Prisma generates draft migration file which has idempotent SQL statements and executes against shadow and dev DB;
3. When a developer is done with changes, he would run smth like `prisma migrate commit`, which would delete the draft file and generate a migration file that would be versioned in the VSC.

I'm aware that I'm biased in favor of `graphile-migrate`, but I thought it might be useful to share my thoughts if that would help with further Prisma Migrate development.

**Comment by albertoperdomo** [comment]
@tadejstanic Thanks for taking the time to write such comprehensive thoughtful feedback.

I'm with the product team at Prisma, currently focusing on Prisma Migrate.
I'm not familiar with graphile-migrate but now that you've mentioned it I will look into it.

We have thought a bit about that drafting workflow. With the current product shape, this is possible by using `prisma db push` during prototype. This updates the database schema from the Prisma schema file without creating any migration files. Once you are ready, you can create a new migration with migrate dev, and as part of the process the database will be reset and the new migration applied.

This has some limitations: you would not be able to customize SQL during this iteration process.

We have also considered alternative ways of achieving similar workflows:

* a draft mode, where we keep re-writing on the same migration until it is "committed". This has the potential problem of opening up for the user to customize the SQL, only for it to be overwritten again.
* squashing migrations after they have been created (has a similar problem to the above, unless we just concatenate the files, which might have questionable value).

What do you think of the workflow using `prisma db push` until you are ready to create the migration? And what are your thoughts on customizing the SQL scripts and having these files been overwritten when using this draft functionality?

Bonus: if you have some time I'd love to setup a 30 min call with you to chat more in depth. You can book some time with me using this link - https://calendly.com/alberto-prisma/30-min-zoom-call

**Comment by joshmanders** [comment]
Outside of whats been said here, something that confuses me is why a single `migration.sql` file is being written to a migration folder, instead of doing like `migrations/20210101000000_initial_schema/migration.sql` can we get `migrations/20210101000000_initial_schema.sql` makes it easier to maintain when it's not a directory of directories with a single migration file. Unless I'm missing something and there's going to be or is more that goes in there than the single `migration.sql` file.

**Comment by nksaraf** [comment]
I was testing the `nativeTypes` feature with postgres, and not sure if this a bug,
but I used
`	updatedAt @updatedAt @db.Timestamptz`

to get a timestamp with timezone. Even though the initial migration is applied with the timestamp with timezone.
```
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
```

every time I run `prisma migrate dev --preview..`, there are new migrations created that have this:

```sql
-- AlterTable
ALTER TABLE "notification_preferences" ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;
```

Is this a bug, or expected?

**Comment by tadejstanic** [comment]
@albertoperdomo 
> What do you think of the workflow using prisma db push until you are ready to create the migration? And what are your thoughts on customizing the SQL scripts and having these files been overwritten when using this draft functionality?

I have mixed feelings about `prisma db push`. I went through the [docs](https://www.prisma.io/docs/reference/api-reference/command-reference#db-push) and they are quite complicated to reason, especially if you don't have a lot of experiences with the db migrations (therefore I'm a bit concerned for junior devs for instance). If we take the limitation regarding column renaming, it forces you to use a different command `prisma migrate dev --create-only` and manually edit the SQL script which I found somehow contradictory with the idea of making db schema changes through a single source of truth - `schema.prisma`. This leads to my answer about customizing the SQL scripts. My personal feeling is having two ways for changing db schema (SQL scripts and `scehma.prisma`) seems like a good decision but on the other hand, I'm afraid it just adds another layer to keep in sync which you've already implicitly mentioned.

I'm quite confident, that the idea of generating `idempotent` SQL statements during the `draft` mode would also solve the problems that you've exposed while presenting alternative ways (`re-writing on the same migration until it is "committed" `AND `squashing migrations`). From my experiences, when you have `idempotent` SQL statements, you are actually just appending them to the `draft` file until you achieve the desired state. Another benefit of this approach would also be, that you wouldn't need to `reset` the db because if there are some conflicts with the schema or existing data, the execution of the last appended SQL statement would just fail.

**Comment by nickreynke** [comment]
@joshmanders 

> something that confuses me is why a single `migration.sql` file is being written to a migration folder

I think this is due to the `migration.sql` file currently acting as a script that **does** something to the database instead of **reverting** what has been done by the `migration.sql`. My idea is that the reason for the extra migration folders might be that there could be a `migration_up.sql` and a `migration_down.sql` in future releases, allowing you to control what happens when the migration should be run and what should happen when this should be reverted.

Is this assumption correct? And if yes, is this planned?

**Comment by tomhoule** [comment]
@nksaraf thanks for reporting the timestamptz issue — working on a fix right now.

**Comment by joshmanders** [comment]
@nickreynke
> @joshmanders
> 
> > something that confuses me is why a single `migration.sql` file is being written to a migration folder
> 
> I think this is due to the `migration.sql` file currently acting as a script that **does** something to the database instead of **reverting** what has been done by the `migration.sql`. My idea is that the reason for the extra migration folders might be that there could be a `migration_up.sql` and a `migration_down.sql` in future releases, allowing you to control what happens when the migration should be run and what should happen when this should be reverted.
> 
> Is this assumption correct? And if yes, is this planned?

From my understanding the Prisma Migrate command will be Forward Only migrations. https://sbg.technology/2016/02/02/how-we-release-so-frequently/

**Comment by adaddeo** [comment]
Proposal: `--skip-seed` flag for `prisma migrate reset`

Our tests are setup to run against a clean database and this would let us use this command for quickly resetting between tests.

**Comment by albertoperdomo** [comment]
@adaddeo I added a GH issue for this: https://github.com/prisma/prisma/issues/5317

**Comment by adaddeo** [comment]
@albertoperdomo  awesome!

Another approach: `--seeds ./prisma/testSeeds.ts`, giving the ability to have one stable seeds file for test environments versus one that might be changing more freely to meet developers needs for local development

**Comment by codeslayer1** [comment]
Can someone please have a look into these issues - #5282 & #5244 . It's becoming really difficult to use Prisma migrate since it resets the db every time and is now also dropping & recreating foreign keys after upgrade to v2.16.

**Comment by albertoperdomo** [comment]
@codeslayer1 We are going to look into both issues very soon.

**Comment by albertoperdomo** [comment]
@adaddeo `--skip-seed` is now live in 2.16.0

**Comment by albertoperdomo** [comment]
## Update: 2.15.0 release

In 2.15.0 we added support for native types in Prisma Migrate via the `nativeTypes` preview feature.
Using the native type syntax for PSL, Prisma Migrate will generate the corresponding DDL statements in the migrations.

We also added support for seeding. You can find the guide [here](https://www.prisma.io/docs/guides/prisma-guides/seed-database) and the reference docs [here](https://www.prisma.io/docs/reference/api-reference/command-reference#db-seed-preview). Feedback for the seeding functionality can be shared [here](https://github.com/prisma/prisma/issues/5161).
 
Prisma Migrate will automatically trigger seeding when the database is reset.

More info in the [release notes for 2.15.0](https://github.com/prisma/prisma/releases/tag/2.15.0).

## Update: 2.16.0 release

As you may have noticed most of our team effort in the last two weeks has been spent on native types and improving its compatibility with Prisma Migrate.

We've now added `Unsupported(String)` and `dbgenerated(String)`, which makes it possible to use Prisma Migrate to manage columns of types that are not yet supported by Prisma.

Example:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int                            @id @default(autoincrement())
  email String                         @unique
  name  String?
  bio   Unsupported("multilinestring") @unique @default(dbgenerated("''"))
}
```

Prisma Migrate generates the following migration:

```sql
CREATE TABLE `User` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191),
  `multilinestringField` multilinestring NOT NULL DEFAULT '',

  UNIQUE INDEX `User.email_unique`(`email`),
  UNIQUE INDEX `User.bio_unique`(`bio`),
  PRIMARY KEY (`id`)
);
```

`dbgenerated(String)` can also be used with supported native types. Here is an example of how to leverage this to use database-generated UUIDs as default for a UUID column:

```prisma
model User {
  id   String  @id @db.Uuid @default(dbgenerated("gen_random_uuid()"))
  name String?
}
```

Prisma Migrate generates the following migration:

```sql
CREATE TABLE "User" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT,

    PRIMARY KEY ("id")
);
```

There is a new option --skip-seeding for `prisma migrate reset` and `prisma migrate dev`.
 
More info in the [release notes for 2.16.0](https://github.com/prisma/prisma/releases/tag/2.16.0).

**Comment by kripod** [comment]
Hello,

Thank you for working on an awesome migration experience! Today I’ve just encountered an error while trying to add a new one-to-one relationship and I’m not sure how to proceed:

```
Step 0 Added the required column `[redacted]` to the `[redacted]` table without a default value. There are [n] rows in this table, it is not possible to execute this migration.
```

While this error totally makes sense, I would like to create and then connect a new model to each record of the `[redacted]` table. While modifying the migration file might work out somehow, I’m not sure how CUIDs should be generated as the primary key of each model I plan to generate.

I’m curious if there’s a chance to support programmatic migration files, e.g. JavaScript/TypeScript executed besides an SQL file. If that isn’t planned, how should I solve the one-to-one relationship problem introduced by adding a new mandatory attribute tied to another, not-yet-created model?

**Comment by tomhoule** [comment]
Hi @kripod — a typescript migrations DSL is definitely something that is on the table, but since it would be a lot of design and implementation work, the tradeoffs and priorities have to be weighed. To answer to your specific case, as in many other scenarios, the flexible and scalable way to do this migration would be in multiple steps:

- In a first migration, add the new field, but nullable
- Deploy that migration, fill in the data (cuid is trickier, as you noted, because afaik you can't fill that in directly in SQL)
- Once the data is there, make the field required in a second migration

One alley that we considered as well would be giving guidance for these kinds of scenarios directly in migrate. There's a lot of possibilities.

**Comment by kripod** [comment]
Thanks for your detailed answer, @tomhoule!

I would love to see a way to add `migration_before.{js,ts}` and `migration_after.{js,ts}` files inside each step’s directory and execute them in the same transaction as `migration.sql`. Thus, data fixes could occur alongside schema modifications without any records left in an inconsistent state by accident.

To let programmatic migration steps be applied as a transaction, I think that `migration_{before,after}` files should have a format similar to:

```ts
export default async (prisma) => {
  const prevData = await prisma.model1.find(…);
  return [
    prisma.model1.updateMany(…),
    prisma.model2.create(…),
  ];
}
```

**Comment by nickreynke** [comment]
The `--create-only` flag does not seem to work correctly. Create an issue here: https://github.com/prisma/prisma/issues/5553

**Comment by miller-productions** [comment]
Liking Prisma Migrate so far.

Early days in terms of my experience with it but so far it has been excellent. 

I very much appreciate the code-first approach that Prisma Migrate is taking. It makes consistent, repeatable database development, testing and deployment quite easy.

I have questioned to myself why the decision was made to introduce a layer of abstraction, i.e. `prisma.schema`, with it's own Prisma Schema Language, rather than just working with SQL in the first place? But I suppose I'll probably understand that a bit more the further I get into the Prisma docs.

Was able to get up and running and comfortably familiar with Prisma Migrate in a short time after reading through the docs and trying things out in my dev environment a few times. I've so far been exploring the development/non-production aspects. Looking forward to playing around with non-development/production oriented features next, i.e. `migrate deploy` etc.

**Comment by jasonkuhrt** [comment]
https://github.com/prisma/prisma/issues/5714

**Comment by jasonkuhrt** [comment]
https://github.com/prisma/prisma/issues/5716

**Comment by MohannadBahaa** [comment]
when Prisma Migrate it will be GA / production-ready  ?

**Comment by 2color** [comment]
@MohannadBahaa Stay tuned. We'll have news very soon.

**Comment by albertoperdomo** [comment]
Hello! Prisma Migrate was released in General Availability today in version 2.19.0!

The announcement blog post can be found [here](https://www.prisma.io/blog/prisma-migrate-ga-b5eno5g08d0b).
Documentation can be found [here](https://www.prisma.io/docs/concepts/components/prisma-migrate).

We are still listening to your feedback through the usual channels (GH issue, #product-feedback on Public Slack).

**Comment by MohannadBahaa** [comment]
> @MohannadBahaa Stay tuned. We'll have news very soon.

awesome
