### ISSUE TITLE
Support for more patterns to model self-relations (e.g. nested sets and closure tables)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4657]
## Problem

Prisma currently only seems to offer the [adjacency list](https://schinckel.net/2014/09/13/long-live-adjacency-lists/) pattern for self-relations. 

Other ORMs like TypeORM offer a bit more flexibility with different patterns, such as [nested sets](https://typeorm.io/#/tree-entities/nested-set) and [closure tables](https://typeorm.io/#/tree-entities/closure-table).

## Suggested solution

I think it would be interesting to think about how these patterns could be modeled in the Prisma schema and be picked up by Prisma Migrate to model self-relations in different ways in the underlying DB .

## Additional context

This topic has been originally brought up in this [Reddit thread.](https://www.reddit.com/r/node/comments/kdjhcb/migrating_a_large_production_app_from_typeorm_to/gg0cork/?utm_source=reddit&utm_medium=web2x&context=3)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
