### ISSUE TITLE
Make Prisma GO client to return slice of pointers

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#4667]
When using gqlgen the library now generates resolvers that require the return type to be a slice of pointers. This has changed in release [v0.9.0](https://github.com/99designs/gqlgen/releases/tag/v0.9.0). Because Prisma is NOT returning pointers but rather slices of structs, it requires an unnecessary code in every resolver returning multiple values, just to retype the slice. That can be seen [here](https://github.com/99designs/gqlgen/issues/738).

As Prisma now returns struct pointers when returning a single value I think it would be great for consistency to also return pointers to values when returning a slice. What do you think?

**Comment by steebchen** [comment]
I would like to know why Prisma should implement this and why this is considered a bug. I don't even understand why gqlgen returns a slice of pointers and not structs, and I didn't get an answer on the [original thread](https://github.com/99designs/gqlgen/issues/375#issuecomment-507701988) yet. It makes sense to return a pointer for single values because it can be nil, but with list of items it doesn't make sense for me as Prisma will never return a nil item in a slice.

**Comment by steebchen** [comment]
gqlgen has released an update to configure this. Can I close this issue @malekjaroslav?
