### ISSUE TITLE
`Failure during a migration command: ... The value provided for column Some("text") is too long.` - Report id `8248`

### ISSUE THREAD

**Issue by chanlito** [prisma/prisma#4683]
<img width="1034" alt="Screen Shot 2020-06-29 at 2 18 27 PM" src="https://user-images.githubusercontent.com/15667259/85984452-68959580-ba13-11ea-8595-0217f80de3dd.png">

**Comment by tomhoule** [comment]
This is an old issue and the error is already clear enough, we're just going to close it.

**Comment by chanlito** [comment]
But has the issue been addressed?

**Comment by tomhoule** [comment]
The issue is that a string in the migration (probably a default) is too long for the column — we could provide our own error for that, but it wouldn't be any clearer than the database error. Also note that this type of errors is much more visible with recent versions of migrate, since you actually commit and hopefully review the SQL migration directly.
