### ISSUE TITLE
Support data conversion

### ISSUE THREAD

**Issue by siberian-man** [prisma/prisma#4993]
I need to save an instance of Big (big.js, a library for working with decimals) to db and then restore it. But I don't want to perform conversion manually all the time. It would be great if I would be able to define a Decimal scalar along with a logic on how to parse and serialise values to allow such a conversion to be done automatically by Prisma2.

As @matthewmueller said, something like this in prisma's schema file could work:

`amount Int @js.big`

**Comment by pantharshit00** [comment]
We have decimal support in the schema via native types and client uses Decimal.js library for that: https://www.prisma.io/docs/concepts/components/preview-features/native-types#additional-prisma-types

Not sure this issue is valid anymore and I think I can close this in favor of https://github.com/prisma/prisma/issues/4002
