### ISSUE TITLE
[Discussion] Prisma Client as inter-service communcation between microservices

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma#5000]
We are facing a major refactoring phase on our team to break our monolith into microservices. We'll be using Apollo Federation to federate each GraphQL microservice, and will be using Photon as our DB client for several services. 

In this context, we're evaluating how we want to facilitate communication between our services, apart from our Pub/Sub systems or events. 

REST or gRPC seems to be the way for many to go at the moment. REST has well known limitations and advantages. gRPC is promising, but the tooling for it outside of Go (or at least in Typescript, which we are avid users of) is lackluster and young. 

It occurred to me that perhaps Photon could act as an auto-generated, inter-service communication SDK for GraphQL microservices. It could auto-generate based on an introspection query, thus providing static typing and compile-time request validation between the services as each service evolves. Furthermore, existing tools such as Apollo's Graph Manager could help map out the communication relationships between the services as they grow, as each would act as a "client" for the other. 

Does this make sense to anyone else than me? Perhaps it's already planned, and I just can't find the info 🙈

**Comment by janpio** [comment]
In the years since this discussion was started, it became clear that _Prisma ORM_ for now is mainly that - an ORM to manage your database schema and talk to your database. Anything beyond that can be built _with_ Prisma, for example using [custom generators](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#community-generators) or expanding Prisma Client itself with [Client Extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions).
