### ISSUE TITLE
Support Order by Relations

### ISSUE THREAD

**Issue by cimchd** [prisma/prisma#5008]
I want to order a table by a nested attribute. I tried something like this:

```js
const result = await prisma.posts.findMany({orderBy: { author: { name : 'desc' } } }) ;
console.log(results);
```
But I got an error: 
`Unknown arg ' user' in orderBy.user for type CustomerAccountOrderByInput.` 

When I checked the type PostOrderByInput there were only the scalar attributes of the post model available, the related models are missing.

Is it possible to extend the orderBy types to include the related models?

I detected this issue using nexus-prisma, @Weakky proposed to make it a prisma/photon issue: https://github.com/prisma-labs/nexus-prisma/issues/458

**Comment by matthewmueller** [comment]
Hey folks, we started working on this and are ready to share our proposal, please have a read and let us know if we're missing anything.

If interested, I'd love to jump on a short call with you to chat about this proposal or any problems you face with the Prisma Client: calendly.com/matthewmueller/prisma. This is a great opportunity to influence what we build!

---

# Proposal

## Databases

- Postgres
- MySQL
- SQLite
- SQL Server

## Operations

- findMany
- findFirst
- groupBy (maybe)

## Order Properties

- ascending (asc)
- descending (desc)

## Relations

Ordering by relations is supported on both one-to-one and one-to-many relations. In both cases, you can traverse the relation on the side of the relation that "has one". Let's look at some examples

### One-to-One

For one-to-one relationships, you can order by the relation from either side:

✅ Order users by their budget if they're a customer

✅ Order customers by by their budget if they're a customer

```groovy
model User {
  id Int @id
  name String
  customer Customer?
}

model Customer {
  id Int @id
  budget Int
  user User
}
```

```tsx
prisma.user.findMany({
  orderBy: {
    customer: {
      budget: 'desc'
    }
  }
})
```

### One-to-Many

For one-to-many relationships, you can order by the relation from one side:

✅ Order posts by their author's name

⛔️ Order authors by their post's titles

```groovy
model Author {
  id Int @id
  name String
  posts Post[]
}

model Post {
  id Int @id
  title String
  author Author
}
```

```tsx
prisma.post.findMany({
  orderBy: {
    author: {
      name: 'asc'
    }
  }
})
```

# FAQ

## Can you order by multiple fields inside a relation?

Yes! Just like with ordering by multiple scalars, you can also order by multiple relation scalars. 

```tsx
prisma.post.findMany({
	select: {
		author: {
			firstName: true // will issue a 2nd, unnecessary SELECT query
		} 
	}
  orderBy: [{
    author: {
      firstName: 'asc'
		},
		author: {
			lastName: 'desc'
		}
  }]
})
```

This somewhat clumsy syntax is necessary because the order matters for fields in an `orderBy`.

## Can you order by a deeply nested relation?

Surprisingly, yes. You can also order by a deeply nested relation. Given the following schema:

```tsx
model Author {
  id Int @id
  name String
  posts Post[]
  address Address
}

model Post {
  id Int @id
  title String
  author Author
}

model Address {
  id Int @id
  title String
  author Author
}
```

```tsx
prisma.post.findMany({
  orderBy: {
    author: {
      firstName: 'asc'
			address: {
				zip: 'desc'
			}
		}
  }
})
```

## Can you order by a foreign key?

Yep. 

```tsx
await prisma.post.findMany({
  orderBy: {
    author: {
      addressId: 'asc'
		}
  }
})
```

## How do you handle NULLs?

Just like with ordering by scalars, how NULLs are ordered in a column is database-specific. We don't impose any additional ordering on top of what the database already does:

```tsx
await prisma.post.findMany({
  orderBy: {
    author: {
      name: 'asc' // handling NULL names is database-specific
		},
  }
})
```

# Limitations

## Unnecessary SELECT while doing a nested select

The following will issue a JOIN and a SELECT when the JOIN has the record's information already

```tsx
prisma.post.findMany({
	select: {
		author: {
			firstName: true // will issue a 2nd, unnecessary SELECT query
		} 
	}
  orderBy: {
    author: {
      firstName: 'asc'
		}
  }
})
```

We'll address this later when we focus on query optimization.

**Comment by rostislav-simonik** [comment]
@matthewmueller in this example which one is taking the precedence ? 

```
prisma.post.findMany({
  orderBy: [{
    author: {
      firstName: 'asc',
      address: {
        zip: 'desc'
      }
    }
  }]
})
```

**Comment by rostislav-simonik** [comment]
probably it's a typo and you meant

```
prisma.post.findMany({
    orderBy: [{
        author: {
            firstName: 'asc',
        }     
    }, {
        author: {
            address: {
                zip: 'desc'
            }
        }
    }]
})
```
> @matthewmueller in this example which one is taking the precedence ?
> 
> ```
> prisma.post.findMany({
>   orderBy: [{
>     author: {
>       firstName: 'asc',
>       address: {
>         zip: 'desc'
>       }
>     }
>   }]
> })
> ```

**Comment by maartenraes** [comment]
@matthewmueller is this still a candidate feature for the 2.16.0 release? 
I've bumped into this problem once again and hovering between implementing a work around or waiting for this to be released.

**Comment by matthewmueller** [comment]
Yep! This will be available in the `2.16.x` release!

**Comment by Karl-EdwardFPJeanMehu** [comment]
Will ordering on 1:n relations from the one side also be available in v.2.16.x?

**Comment by dpetrick** [comment]
You can only traverse *to* a to-one side, coming from a many or one side (m -> 1, 1 -> 1). If you have specific requirements and use case where you'd need to order over a many side, we'd certainly like to hear about it (in a separate feature request issue).

**Comment by d3r3nic** [comment]
I have a m-n explicit relationship and Im trying to sort the result in this nested query. any suggestions?

```
model Institution {
    id                    Int         @default(autoincrement()) @id
    username              String      @unique
    institutionName       String
    email                 String      @unique
    activated             Boolean     @default(false)
    phoneNumber           Int?
    createdAt             DateTime    @default(now())
    updatedAt             DateTime    @updatedAt
    members               MembersInstitutions[]
}

model MembersInstitutions {
    institution          Institution @relation(fields: [institutionId], references: [id])
    institutionId        Int
    member               Member      @relation(fields: [memberId], references: [id])
    memberId             Int
    status               Status?
    startDate            DateTime    @default(now())
    endDate              DateTime?
    createdAt            DateTime    @default(now())
    updatedAt            DateTime    @updatedAt
    @@id([institutionId, memberId])
}

model Member {
    id                   Int         @default(autoincrement()) @id
    username             String      @unique
    email                String      @unique
    firstName            String
    lastName             String
    activated            Boolean     @default(false)
    createdAt            DateTime    @default(now())
    updatedAt            DateTime    @updatedAt
    institutions         MembersInstitutions[]
}

let query = {
    where: {id: decodedInstId},
    select: {
        members: {
            where: {
                status: 'requested'
            },
            select: {
                member: {
                     ------------------// how to achieve this?
                    // orderBy: {
                    //     firstName: 'asc',
                    // },
                   ------------------
                    select:{
                        firstName: true,
                        lastName: true,
                        // activated: true,
                        id: true
                    }
                }
            }
        }
    }
};

```

**Comment by janpio** [comment]
Open a new issue please instead of posting in this old, closed one. We ware happy to answer these questions, but not when it pings >30 people that are subscribed to an issue. Thanks.
