### ISSUE TITLE
Provide a Prisma datasource package for Apollo Server

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma#5017]
Hi. This is in relation to using Prisma Client with Apollo server, specifically this: https://www.apollographql.com/docs/tutorial/data-source/

There are existing implementations available for:
REST API: https://www.npmjs.com/package/apollo-datasource-rest
Mongo: https://www.npmjs.com/package/apollo-datasource-mongo

You can have an implementation for Prisma Client as well: apollo-datasource-prisma

I am currently building my own as a fallback. if I am successful, I will share the details with you guys so that you can have a look.

This can help people in seamlessly integrating Prisma Client with graphql.

**Comment by m1pl** [comment]
Our company started implementing a data source for Apollo Server. Right now it's tied to our code, but we could easily make a standalone package out of it. It should provide a default dataloader and CRUD operations, so any class extending the `PrismaDataSource` base class would just need to provide functions for more complex use-cases, without duplicating the basic stuff over and over again. We have to implement quite a lot of "magic", as the generated Prisma types have no common base. Is it possible to change the code generation, so that there are base interfaces for all delegates, input types, e.t.c.?

This is what a generic `findById` would look like in the data source:
```
export abstract class PrismaDataSource extends DataSource<TContext = any> {
  context!: TContext;

  delegate!: PrismaDelegate;

  initialize(config: DataSourceConfig<TContext>): void | Promise<void> {
    this.context = config.context;
  }

  findById(id: number) {
    return this.context.prisma[this.delegate].findUnique({
      where: {
        id,
      },
    });
  }
}
```

The generated types (`*Delegate`, `*FindUniqueArgs`, ... ) extending some common base types would make this easy. Is there any way of doing this?

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
