### ISSUE TITLE
Casing for Prisma Client model and field names

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5035]
Similar to https://github.com/prisma/prisma2/issues/1851, but Client level

> Upper case models produce Prisma client call with a weird casing:
> 
> ```prisma
> model ATOMS {
>   ATOM_TYPE                   Int?
>   CHARGE                      Float?
>   ELEMENT                     String?
>   ID                          Int         @default(0) @id
>   DRUG_ID                     DRUGS?
>   bONDS_ATOMSToBONDS_ATOM1_ID BONDS[]     @relation("ATOMSToBONDS_ATOM1_ID")
>   bONDS_ATOMSToBONDS_ATOM2_ID BONDS[]     @relation("ATOMSToBONDS_ATOM2_ID")
>   rING_ATOM                   RING_ATOM[]
> 
>   @@index([DRUG_ID], name: "ATOMS_DRUG_ID")
> }
> ```
> 
> Casing in generated client:
> 
> ![image](https://user-images.githubusercontent.com/746482/75041435-dd345280-54bc-11ea-8239-59bcb7c76581.png)
> 
> Same applies for field names like `bONDS_ATOMSToBONDS_ATOM1_ID`.

Right now this exists: https://github.com/prisma/prisma-client-js/blob/ffa2f18bd5dc9390380f01d3f68a9c81adeb1086/packages/photon/src/runtime/getPrismaClient.ts#L349

This should be removed, and everything that is similar: The schema is the source of truth for capitalization of model and field names.

**Comment by timsuchanek** [comment]
Until we have more reportings about this, we will close this.

**Comment by m4nuC** [comment]
This actually breaks camel case naming convention when acronyms should be capitalized, eg. we have an NFT model, it becomes `nFT`.

**Comment by pantharshit00** [comment]
We lowercase the first letter now. I don't think we can change that now, that will break things for existing users.

**Comment by pantharshit00** [comment]
You can try using a map:

```prisma
model nft {
 // fields ..
 // ..
 @@map("NFT")
}
```

**Comment by m4nuC** [comment]
@pantharshit00 thanks, I will try this.

**Comment by kukaki** [comment]
> This actually breaks camel case naming convention when acronyms should be capitalized, eg. we have an NFT model, it becomes `nFT`.

Yeah. In our case, one of the models name is **MEPAction** (as per the naming conventions it should be **MEPAction**, not **MepAction**).

but the prisma code generated is **prisma.mEPAction**, it actually should be **prisma.mepAction**.

Just because Prisma is generating this wierd code, we need to flout the naming conventions and use **MepAction** instead of **MEPAction**.



> You can try using a map:
> 
> ```prisma
> model nft {
>  // fields ..
>  // ..
>  @@map("NFT")
> }
> ```
> 
> This will provide `prisma.nft` in the client and database table will be called `NFT`

@pantharshit00 This names the database table name as **nft**. But the prisma code generated is still **prisma.nFT**

**Comment by pantharshit00** [comment]
As I already told here we can't change it. Here is the lowercase function we use: 
https://github.com/prisma/prisma/blob/ba74c81fdbc9e6405946fdc6f9d42d103d008dc2/packages/react-prisma/src/index.ts#L62-L64

It is very simple and just lowercase the first letter. It is designed so that generally convention of using Capitalized Case in Prisma schema reflects fine in the client. When you use existing database models we recommend using `@map` if your model doesn't follow the capitalize case.
