### ISSUE TITLE
Improve error message: `permission denied for table User`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5076]
```
PrismaClientUnknownRequestError: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42501"), message: "permission denied for table User", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3489), routine: Some("aclcheck_error") }) }) })
    at PrismaClientFetcher.request (/var/task/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

via https://prisma.slack.com/archives/CA491RJH0/p1599953612394700?thread_ts=1599953586.394600&cid=CA491RJH0

(Turned out to be cause by full disk in that case...)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
