### ISSUE TITLE
findFirst with `undefined` value shouldn't return data

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5149]
## Bug description

Calling `findFirst` with an `undefined` in where filter still returns data. This is not intuitive. 

## How to reproduce

1. Deploy this schema with `yarn prisma db push --preview-feature`

```prisma
datasource ds {
    provider = "sqlite"
    url      = "file:./dev.db"
}

generator pc {
    provider = "prisma-client-js"
}

model User {
    id   String @id
    name String
}
```

2. Ensure it has some rows
3. Run the following script

```ts
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
async function main() {
  const data = await prisma.user.findFirst({
    where: {
      id: null
    },
  })
  console.log({ data })
}

main()
```

4. It returns

```
{ data: { id: '1', name: 'Alice' } }
```

5. The where ID doesn't match anything, it shouldn't return

## Expected behaviour

IMO, this should be a runtime error. 

## Prisma information

```
(base) divyendusingh [p2-ff]$ yarn prisma --version                                                                                                                                  130 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-ff/node_modules/.bin/prisma --version
@prisma/cli          : 2.15.0-dev.57
@prisma/client       : 2.15.0-dev.57
Current platform     : darwin
Query Engine         : query-engine 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.333.0
```

**Comment by timsuchanek** [comment]
This behaves as intended. However, we can update our JSDoc.

**Comment by timsuchanek** [comment]
This is the solution:
![image](https://user-images.githubusercontent.com/1094804/107204613-27c81b00-69fd-11eb-8a0e-4ee1d1604a7b.png)
It'll be available in a bit.

**Comment by bartoszhernas** [comment]
This would be good to include in big red text in Sequelize migration tips&tricks. We have just released Prisma to production, where we replaced thousands of lines of code from Sequelize. All in all Prisma is awesome, but this one thing introduced nasty bug. Of course due to our fault, but as the issue mentioned, this is not intuitive.

 Can there be a flag where you can control the behaviour? The case is that it happens a lot in auth code etc where you do
 ```
    const device = await prisma.deviceModel.findFirst({ where: { deviceId } });
```
If by accident you pass undefined here, the random model is returned which is really dangerous in some cases.

**Comment by michaeldever** [comment]
Agreed, we've just done a big migration from typeorm to prisma, and this is something that we're going to have to check all occurences of finds for across code/tests.

**Comment by davnicwil** [comment]
Have just come across this and I was pretty surprised by it.

I would also describe it as dangerous, mostly because I'd guess that most people would not assume this behaviour, and will instead rely on error handling code after the query to check if nothing was found when and `undefined` id is passed, for example.

I think it would be great to introduce as a feature the ability to configure this behaviour off globally.

I can see an argument that typescript can eliminate this bug too. The reason I came across it was admittedly due to a lazy workaround on my part -- I was asserting a query param was present in TS with the `!`, then the query param name changed, resulting in it being `undefined`. Really I should have used a zod-like runtime type guard. But, even in the case of using TS, examples like this of things not being quite perfect and `undefined`s sneaking in at runtime abound. I really think it's better to have the additional failsafe here.

**Comment by dctanner** [comment]
This has the be one of the worse design decisions. We also just found a bug where findFirst returns another user’s record. The problem is it does this silently.

**Comment by taco-chen** [comment]
Totally agree with this is a bad and dangerous design.

**Comment by taco-chen** [comment]
For anyone who is currently struggling with this issue. The following workaround could use [prisma middleware](https://www.prisma.io/docs/concepts/components/prisma-client/middleware) to prevent any `undefined` appears in `where`. For me, this is handy that I could prevent to make mistakes which will let the `undefined` to sneaked in.

Write a custom `prismaClient` instance which include the middleware. The middleware will check the `params.args.where` and throw an Error if any `undefined` has been included. 
```ts
import { PrismaClient } from '.prisma/client';

const prisma = new PrismaClient();
prisma.$use(async (params, next) => {
  if (hasUndefinedValue(params.args?.where))
    throw new Error(
      `Invalid where: ${JSON.stringify(params.args.where)}`
    );
  return await next(params);
});

export default prisma;

function hasUndefinedValue<T>(obj: T): boolean {
  if (typeof obj !== 'object' || obj === null) return false;
  for (const key in obj) {
    if (!Object.prototype.hasOwnProperty.call(obj, key)) continue;
    const value = obj[key];
    if (value === undefined) return true;
    if (typeof value === 'object' && !Array.isArray(value))
      if (hasUndefinedValue(value)) return true;
  }
  return false;
}
```

This you could export and use the `prismaClient` instance as usual. It will also be better to have the test case to verify the middleware is working fine:

```ts
describe('with undefined', () => {
  it('should throw InvalidParameterError', async () => {
    const error = new Error('Invalid where: {}');
    await expect(
      prisma.user.findUnique({ where: { email: undefined } })
    ).rejects.toThrow(error);
  });
});
```

Hope this help somebody!

**Comment by Scalahansolo** [comment]
How is this even possible....

**Comment by omeha2** [comment]
It's a nightmare. 
You need to add a huge red banner with an explanation to the documentation!
I can only imagine how many bugs appear because of this "smart" design

**Comment by sarzixon** [comment]
Cmon guys this can't stay in that way, first thing to repair that mess should be big red warning in docs as mentioned above.

**Comment by divyenduz** [comment]
Hi everyone, I don't think that Prisma team (I don't work at Prisma anymore) monitors closed issues (someone from the team, please correct me if I am wrong?). 

I do see that this issue is getting a lot of attention. To make progress, please create a new ticket, link it back to this one and show that a lot of community members want this changed 🙏🏼 

Thank you.

**Comment by Scalahansolo** [comment]
@janpio Does it sound like this issue should be reopened? Kinda feels like it due to recent comments?

**Comment by janpio** [comment]
No. Someone made this design decision a long time ago, we can only change it with a breaking change, and we are not eager to do that right now. We are aware it is a problem and are taken comments like these into account. There also a lot of other issues about this, for example https://github.com/prisma/prisma/issues/11021 or https://github.com/prisma/prisma/issues/20169. You can leave you upvotes on these.

**Comment by Scalahansolo** [comment]
Appreciate the response. I figured that was the case and while not the ideal people in this thread want, I understand, because yeah.... this would be a massive breaking change. Appreciate ya chiming in here so that way in the future people at least know the current state on this from Prisma's perspective!

**Comment by bartoszhernas** [comment]
I still believe this is such a dangerous design: once again just imagine writing auth function that looks up user by email and hash and by accident it comes up empty. The first user is usually the admin… 

It would be worth it to change it with breaking change and add configuration option to opt in to the old behavior. 

It’s just dangerous and not only bad design. For now the big red alert anywhere near filters documentation should be posted.

**Comment by hkiame** [comment]
Totally dangerous. They should listen to users' feedback and change the design.

**Comment by fnfdelivery** [comment]
I think the idea of findfirst would theoretically find the first item it could find if your filter was undefined. Since with no parameters find first literally means finds the first item? Checking if your filter arguments are valid beforehand I think is good practice
