### ISSUE TITLE
@map not carried over to `makeEnum`

### ISSUE THREAD

**Issue by pandaniell** [prisma/prisma#5383]
Given the following enum in `schema.prisma`
```
enum Role {
  ADMIN     @map("admin")

  @@map("role")
}
```
The generated JavaScript contains
```js
exports.Role = makeEnum({
  ADMIN: 'ADMIN',
});
```
The value should be the same as inside the map

**Comment by Jolg42** [comment]
Hi!

Could you check which version of @prisma/cli and @prisma/client you are using here?

**Comment by pandaniell** [comment]
Yes sorry! I am using `^2.15.0` for both, to add: Whenever I reference one of the enum values inside a query, it does insert in lowercase into my database properly, maybe this is done on database level? (Postgres), the problem is you cannot compare against values you get from the database since they will be in lowercase

**Comment by pantharshit00** [comment]
I can reproduce this with `2.16.0-dev.67`. We should definitely export the correct value. 

It works when you insert data as we use postgres/mysql enums under the hood.

**Comment by Weakky** [comment]
Hey folks,

I think this issue stems from a misunderstanding of how `@map` works.

`@map` gives metadata to the Query Engine so that it knows the name of the model/enum field name stored in the database. `@map` never leaks into the client, it's the field name that's used in the client. eg:

Given this datamodel 👇,

```prisma
model User {
  id Int @id @map("user_id")
  role Role  @map("user_role")
}

enum Role {
  ADMIN @map("admin")
}
```

The client should expose:

```
type User = {
  id: number
  role: Role
}

type Role = {
  ADMIN: 'ADMIN'
}
```

It's only internally that the Query Engine will use these `@map` annotations to do the mappings. These `@map` values aren't expected to be sent over the wire. They're roughly used, for instance, to:

- Select the proper columns. eg: `SELECT user_id AS id, user_role AS role FROM ...`
- Compare against the actual enum values stored in the DB. eg: `SELECT ... FROM ... WHERE user_role = "admin"` 👈 `"admin"`, not `"ADMIN"` here.

Hope that makes sense, I'm closing now. Feel free to ask further questions/re-open if you still think that's wrong.

**Comment by danielweil** [comment]
How should we define enums with special characters if map doesn't work? By using @map, we save correctly in the database, but when I fetch using the library, it brings me the other value which is different.

**Comment by seansu4you87** [comment]
Yes I'm running into the same problem as @daniellwdb:

When we fetch the model using the prisma client, and try to compare the value of the enum, we cannot do a direct comparison:
```typescript
const user = await prisma.user.findUnique({ where { id: id} });
// user.role will be 'admin' because that's what's mapped to the database
// UserRole.ADMIN will be 'ADMIN'
// The comparison will always fail.  We need prisma to generate a value of 'admin' somewhere, so we can do a comparison without typing out the string value ourselves
if (user.role === UserRole.ADMIN) {
  // do something
}
```

**Comment by Jolg42** [comment]
@seansu4you87 Could you create a new issue? It would help, as we would need to have the information necessary for a reproduction first with a recent version.
