### ISSUE TITLE
Preview feature feedback: Efficiently `createMany` records at once.

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#5437]
Please share your feedback about the `createMany` functionality that was released in [v2.16.0](https://github.com/prisma/prisma/releases/tag/2.16.0) in this issue.

Documentation is [here](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview).

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-client`](https://prisma.slack.com/archives/CCWDULGUW) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by ricardoalmeida** [comment]
Very nice feature, thanks!

I see we can use the `skipDuplicates` that performs "ON CONFLICT ... DO NOTHING", but it will be nice to have the other possibilities the Postgres provides, for example: "ON CONFLICT (did) DO UPDATE..." or "ON CONFLICT ON CONSTRAINT my_custom_pkey DO UPDATE...". It would allow us a sort of "upsert" for the "bulk create".

Questions/suggestions:

1. Is there a plan to allow INSERTs as a raw query in case we want to specify the "ON CONFLICT"?
2. The "returning" for bulk create would be nice as well.
3. To better simulate the Postgres "ON CONFLICT", instead of `skipDuplicates`, I would provide the option `onConflict` and the values for this key: "raise", "replaceAll", "replaceAllExceptFields", "nothing".

**Comment by some-user123** [comment]
I can only second @ricardoalmeida

I'd really like to have an `upsertMany` as we already have `findMany`, `deleteMany` and now `createMany`. This could be achieved using `ON CONFLICT ... DO UPDATE ...` .

Should I open a separate issue/feature request for that?

**Comment by sakulstra** [comment]
the feature is well working for me :+1:

That said at most places in my code I cannot use it as like the others above already mentioned i'd rather need a `create or update` than a `create or skip`

**Comment by MattGson** [comment]
@ricardoalmeida  agreed. Probably a separate `upsertMany` function would fit better with the current API. 

I would look at the knex conflict/merge API for inspiration. Should be able to achieve across Pg, MySQL and SQLite with native `on conflict do` and `on duplicate update`:

- Create many rows and ignore key conflicts
- Create many rows and set specific fields on a conflicting row
- Create many rows and choose fields to merge on conflict (i.e. update parts the existing row to match the conflicting row being inserted)


API could look something like:
```js

interface Person {
   id: string;
   first_name: string;
   last_name: string;
}

person.upsertMany({

  data: PersonCreateInput[],
  merge: {
     id: boolean;
     first_name: boolean;
     last_name: boolean;
  },
  update: Person;
})

```

Although I personally think the update block is not needed and have never found a use for it in the current API (always just merge the fields). In the case that both `merge` and `update` reference the same field, some precedent would need to be set.

**Comment by matthewmueller** [comment]
This one will be stabilized in `2.20.0`. Thanks for the comments everyone! We'll continue in separate issues.

**Comment by pantharshit00** [comment]
Closing as this is stable now.
