### ISSUE TITLE
Horizontally scale (load balance) prisma

### ISSUE THREAD

**Issue by clayrisser** [prisma/prisma#5517]
Is it safe to run multiple instances of prisma and load balance them? If not, are there plans to add support for that? Maybe having a leader prisma node with standby nodes running for writes, and just round Robin reads. Currently it’s a big problem that prisma could be a single point of failure.

**Comment by Sytten** [comment]
Prisma 2 is not prisma 1, you are supposed to just run the binary beside your application. At some point they will switch to direct calls with the rust NAPI binding instead of a network call. I could see the return of a separate gateway at some point for serverless applications but that doesn't seem to be on the short term planning.

**Comment by thebiglabasky** [comment]
Hi, as @Sytten said Prisma 2 comes as a regular library so this issue is not applicable to it. 
If you're using Prisma 1, you can consider upgrading to Prisma 2, following our tutorial: https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/how-to-upgrade
I'll close this issue, but am happy to chat further if you want to share more insights!
