### ISSUE TITLE
User ID type instead of int to enable database transparency

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#5601]
## Problem

```
    Invalid `prisma.user.findFirst()` invocation:

    {
      where: {
        OR: [
          {
            username: 'ericThread1'
          },
          {
            id: 'ericThread1'
                ~~~~~~~~~~~~~
          }
        ]
      }
    }

    Argument id: Got invalid value 'ericThread1' on prisma.findFirstuser. Provided String, expected IntFilter or Int.
    type IntFilter {
      equals?: Int
      in?: List<Int>
      notIn?: List<Int>
      lt?: Int
      lte?: Int
      gt?: Int
      gte?: Int
      not?: Int | NestedIntFilter
    }

```

## Suggested solution

user type id,
for some databases will use string as id.

**Comment by matthewmueller** [comment]
Hey @calidion, thanks for the suggestion, but a database's type system is quite a bit different than the GraphQL type system. The typescript's types map directly to database types.

Since the database won't accept a string in an integer column, the Prisma Client should prevent this from happening too. 

You can still use an ID type in GraphQL and then convert it to either a string or integer in your resolver before passing it to the Prisma Client. 

Hope this helps!
