### ISSUE TITLE
Internal: Publish untested CLI at canary Npm dist tag

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5619]
- We want to publish the CLI as quickly as possible, skipping any testing or other processes.
- Npm dist tag: `cli-canary` or similar
- Version numbers: `2.17.0-cli-canary.44` or similar
- Running as GH Actions pipeline (vs Buildkite)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
