### ISSUE TITLE
'Not' filter doesn't seems to make a comparison to a null variable.

### ISSUE THREAD

**Issue by Bligoubloups** [prisma/prisma#5634]
Hi !
I have a problem when using a `updateMany` query with a `not` filter. When the `nbLinks` field is null in the database, the not filter doesn't seem to be applied. For instance, if `args.data.nbLinks` is equal to `9` and I have a task with `nbLinks` equals to `null` in my database, the `chatUser` won't be updated.
```ts
await ctx.prisma.chatUser.updateMany({
        data: {
          isBan: true,
        },
        where: {
          Task: {
            nbLinks: {
              not: args.data.nbLinks,
            },
          },
        },
      });
```
I can fix this with an 'OR' filter:
```ts
await ctx.prisma.chatUser.updateMany({
        data: {
          isBan: true,
        },
        where: {
          Task: {
              OR: [
                {
                  nbLinks: {
                    not: args.data.nbLinks,
                  },
                },
                {
                  nbLinks: null,
                },
              ],
          },
        },
      });
```
But this seems to be a dirty hack.

Thanks for your help !

**Comment by ryands17** [comment]
@Bligoubloups 👋 

Is your User-Task relationship a 1-1 or a 1-many?

**Comment by Bligoubloups** [comment]
Hello @ryands17!

It's a user can have many task :)

**Comment by ryands17** [comment]
I could check this and the only way to do this right now would be an `OR` condition. The reason is that in SQL, `null` records are disregarded when checking for a value. So "not of value x"  in the sql sense is all records with a value that are not x. Which is why Prisma adds a condition for checking the value as well as if it's not null.

You can view the queries generated by adding the `query` option to the `PrismaClient` constructor as shown [here](https://www.prisma.io/docs/support/creating-bug-reports#include-logging-and-debugging-output).

Let me know if that helps :)

**Comment by Bligoubloups** [comment]
Thank u a lot for the explanation!
