### ISSUE TITLE
when quering, passing string to DateTime field results runtime error

### ISSUE THREAD

**Issue by umlx5h** [prisma/prisma#5682]
## Bug description
We can not pass string value to DateTime field even it allows passing string in type declaration.
So, type check is not working, and when executing it results following runtime error.

```
Argument <DateTime field>: Got invalid value '2021-01-01' on prisma.aggregatePost. Provided String, expected DateTimeFilter or DateTime.
```

I want to just pass string to datetime field in where clause and filtering and get the result.
It allows to pass string values to datetime field, and If we pass the string values, we get the runtime error. 
I think it is a bug, If string type is not possible, it must be removed from type definition.

## How to reproduce
prisma.schema
```
model Book {
  id          Int      @id @default(autoincrement())
  title       String
  publishedAt DateTime
}
```

main.ts
```
  // no type checking error
  // runtime error
  // Argument publishedAt: Got invalid value '2021-01-01' on prisma.createOneBook. Provided String, expected DateTime.
  await prisma.book.create({
    data: {
      title: "book",
      publishedAt: "2021-01-01",
    },
  });

  // no type checking error
  // runtime error
  // Argument publishedAt: Got invalid value '2021-01-01' on prisma.findManyBook. Provided String, expected DateTimeFilter or DateTime.
  await prisma.book.findMany({
    where: {
      publishedAt: "2021-01-01",
    },
  });

  // no type checking error
  // runtime error
  // Argument publishedAt: Got invalid value '2021-01-01' on prisma.deleteManyBook. Provided String, expected DateTimeFilter or DateTime.
  await prisma.book.deleteMany({
    where: {
      publishedAt: "2021-01-01",
    },
  });
```

## Expected behavior
It should be simply allowed passing string values to DateTime field. because normal sql can do as follows.
```
INSERT INTO "Book"("title", "publishedAt") VALUES ('book', '2021-01-01');
SELECT * FROM WHERE publishedAt = '2021-01-01';
````
I don't want to convert string to date anything like that because it is not necessary in normal sql world.
and I don't want to convert and think about timezone.
It's like taking away the freedom of the user. so simply allowing any string or date object are appropriate I think.

## Prisma information
Generated types  allow passing string  as follows.

index.d.ts
<details>
<summary>generated types</summary>
  export type BookWhereInput = {
    AND?: Enumerable<BookWhereInput>
    OR?: Enumerable<BookWhereInput>
    NOT?: Enumerable<BookWhereInput>
    id?: IntFilter | number
    title?: StringFilter | string
    publishedAt?: DateTimeFilter | Date | string
  }

  export type BookCreateInput = {
    title: string
    publishedAt: Date | string
  }

  export type BookUncheckedCreateInput = {
    id?: number
    title: string
    publishedAt: Date | string
  }

  export type BookUpdateInput = {
    title?: StringFieldUpdateOperationsInput | string
    publishedAt?: DateTimeFieldUpdateOperationsInput | Date | string
  }

  export type BookUncheckedUpdateInput = {
    id?: IntFieldUpdateOperationsInput | number
    title?: StringFieldUpdateOperationsInput | string
    publishedAt?: DateTimeFieldUpdateOperationsInput | Date | string
  }

  export type BookUpdateManyMutationInput = {
    title?: StringFieldUpdateOperationsInput | string
    publishedAt?: DateTimeFieldUpdateOperationsInput | Date | string
  }

  export type BookUncheckedUpdateManyInput = {
    id?: IntFieldUpdateOperationsInput | number
    title?: StringFieldUpdateOperationsInput | string
    publishedAt?: DateTimeFieldUpdateOperationsInput | Date | string
  }

</details>

## Environment & setup
- OS: WSL Ubuntu
- Database: only tested in MySQL and PostgreSQL
- Node.js version: v15.5.0
- Prisma version: 2.16.1

**Comment by matthewmueller** [comment]
Hey there, we want to be a bit more strict about date formats than SQL.You can also use the native Javascript date and have access to more date formats.

I think this should work:

```ts
await prisma.book.deleteMany({
    where: {
      publishedAt: new Date("2021-01-01"),
    },
  });
```

**Comment by umlx5h** [comment]
@matthewmueller 
> we want to be a bit more strict about date formats than SQL. 

If it is a specification, then string type should be removed from type definition i think.
By doing so, runtime error can be avoidable in compile time.

**Comment by Ezard** [comment]
@matthewmueller I had a similar thing when using Postgres `TIME` fields, using Prisma's new support for native types (i.e. via `@db.Time`)

As @umlx5h mentioned above, the Typescript types allow for a string to be passed, but the query engine doesn't; whilst using a JS `Date` object makes the query work for me, it does seem a bit weird having to pass `new Date('1970-01-01 ${time}')` instead of just '12:34'.

Your mentioned wanting to be strictness (which I 100% agree with), so maybe you could do something like this, to force the string that's passed to be a valid time?

```typescript
type SingleDigit = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
type Hour = `0${SingleDigit}` | '11' | '12';
type Minute = `0${SingleDigit}` | `1${SingleDigit}` | `2${SingleDigit}` | `3${SingleDigit}` | `4${SingleDigit}` | `5${SingleDigit}`;
type Second = `0${SingleDigit}` | `1${SingleDigit}` | `2${SingleDigit}` | `3${SingleDigit}` | `4${SingleDigit}` | `5${SingleDigit}`;
type Time = `${Hour}:${Minute}` | `${Hour}:${Minute}:${Second}`;

const validTime: Time = '12:34:56';
const invalidTime: Time = '43:21';
```

Obviously it'd be a lot of work on the part of the team at Prisma to maintain typings for all of the various combinations of date formats/time formats that various DBs support, so supporting just the "simple" formats like the one above seems like a reasonable tradeoff - for anything more complex, users always have the option to use the native JS `Date` object.

**Comment by matthewmueller** [comment]
> If it is a specification, then string type should be removed from type definition i think.

I think I agree with this, but it's too late to make a breaking change like this now. Strings are also convenient when you're passing dates between services, as long as the services all use ISOString. 

> Your mentioned wanting to be strictness (which I 100% agree with), so maybe you could do something like this, to force the string that's passed to be a valid time?

Definitely an interesting idea. It would still be a breaking change and it wouldn't really improve the common case of the Prisma Client (handling HTTP requests), but it would be a nice improvement for scripts when you know the date upfront.

Closing since this works as expected.
