### ISSUE TITLE
Unable to run a `db pull`

### ISSUE THREAD

**Issue by SebastienElet** [prisma/prisma#6010]
Hi Prisma Team!

We ran a migration of our prisma1 datamodel to prisma2 last week.
The migration of the schema was fine with the initial `db pull` then `npx prisma-upgrade` (with a lot of manual fixes but it was expected).

However now prisma1 & prisma2 are working but we are not able to run `db pull` command

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.15.1           | 
| Prisma CLI  | 2.18.0             | 
| Binary      | da6fafb57b24e0b61ca20960c64e2d41f9e8cff1| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:160:14] We assume an internally valid datamodel before mutating.
```

**Comment by SebastienElet** [comment]
I sent the schema by email (it's large and i would like to keep it private).

**Comment by do4gr** [comment]
Hey, thanks for reporting this. 

Unfortunately we were not collecting the information in our error reporting in a format that allows us to exactly replay the bug. That has changed with 2.19 which should be out next Tuesday. Can you please try again then? This should allow us to exactly pinpoint the issue. 

We fixed one issue that was showing the same symptoms, so I'm closing this one now because we cannot act on it (due to our, not your fault). Please just open a new issue once you retried with 2.19 and still get an error.

**Comment by Jolg42** [comment]
@SebastienElet Note: it's also available in our dev version `2.19.0-dev.27` if you want to try it before the official 2.19 release

**Comment by SebastienElet** [comment]
Hello, thanks a lot for the feedback

I tried and now i have a ` Could not find relation field …` with the wrong relation, i will try to fix my relations.

Thanks again 👍

**Comment by SebastienElet** [comment]
I fixed my relations and it works 🤩

**Comment by Jolg42** [comment]
Great news! 😍
