### ISSUE TITLE
Option to disable Decimal.js Generation?

### ISSUE THREAD

**Issue by tarazena** [prisma/prisma#6049]
## Problem

I have few columns in my db that have Decimal values, my GraphQL Server usually returns whatever responses that Prisma returns (using Float in GraphQL for Decimals).

Recently I upgraded to the latest version of Prisma (2.18.0, was on 2.15.0), Since Prisma generates Decimal for Decimal types of columns, All my GraphQL schema was broken (Now its returning Decimal.js Objects instead of numbers), and i was forced to revert back to my original version.

Is there a way to disable using Decimal.js?

## Suggested solution

Allow users to cast the Decimal.js values in Prisma Client like
```ts
const db = new PrismaClient({
  typeOverride: {
    ['Decimal']: (data: Decimal) => data.toNumber()
  }
});
``` 
or maybe in the schema by adding `@cast(Float)` ?

## Alternatives

Reverted to an earlier version of Prisma

**Comment by Thibault2ss** [comment]
We have the exact same issue, and would like to have a way to offer prisma1 retro-compatibility on those float fields. Our graphql server + frontend expect numbers instead of Decimal.js class.

Being a large scale project, changing everything to work with this class, or creating all the resolvers to override this, would be way too much work at once.

It creates some friction for a smooth migration towards prisma v2.

Such a proposed api would be a good solution to us.

Thank you for your help, well done on prisma 2, keep up the good work ! ❣️

**Comment by alexandrduduka** [comment]
### ISSUE
We have a similar issue, running the PostgreSQL database and trying to update from 2.16 to 2.18. We have a table like this:
```
model Report {
  id              String   @id @default(cuid())
  date         DateTime
  mix           Float
  avg_total Float
}
```

Reports are calculated with a SQL script, using `prisma.$raw`, then processed and inserted into the database. Now, if we keep it as `Float`, the values returned have the issue with the precision, as described here https://github.com/prisma/prisma/issues/2903, and if we switch to Decimal, we do not receive a number anymore.


### MORE CONTEXT
SQL script looks this way:
```
	select
		uuid_generate_v4() as "id",
		date_trunc('day', t."start", '${FACILITY_TZ}') as "date",
		round(avg(some_float_column)::numeric, 2) as "avg_total",
                round(avg(another_float_column)::numeric, 2) as "mix",
       from ...
```

When running it directly against the DB, we receive the following values:
```
avg_total: 4.80
mix: 1.40
```

When running it with `prisma.$raw`, we get:
```
avg_total: 4.8
mix: 1.400000001
```

After inserting the reports in the database and retrieving them with `prisma.findMany`, we get:
```
avg_total: 4.800000001
mix: 1.4
```

In the database, both values have `.000000001` part.

**Comment by tom-richter** [comment]
I have also came across this problem recently. In my Postgres database I store measured values in a Decimal field. It is important that all digits are preserved during inserting and querrying. This is especially important for trailing zeros. The number of digits indicates how accurate the measurement was. So it makes a difference if I store 0.0 or 0.00 in the database. [Decimal.js unfortunately removes all trailing zeros.](https://mikemcl.github.io/decimal.js/#zero-nan-infinity) For inserting there is this workaround using `executeRaw` eg. `$executeRaw('INSERT INTO "Nutrient" ("amount") VALUES (${nutrient.amount});')`. For queries, however, even `$queryRaw<Nutrient[]>('SELECT amount FROM "Nutrient";')` doesn't work anymore. The decimal values get converted into floats and I loose the precision. I think I found the piece of code that does the string conversion. In this [file](https://github.com/prisma/prisma/blob/master/src/packages/client/src/runtime/query.ts) in line 1877 the postgres Decimal gets converted to a Decimal.js decimal which strips away trailing zeros:
`Decimal: (value) => {return new Decimal(value)}`. It would help me a lot if I could deactivate Decimal.js and instead just return the value as a string, like node-postgres does. So, unfortunately, at the moment I have to store measured values as strings.

**Comment by Thibault2ss** [comment]
BTW @tarazena @tom-richter @alexandrduduka, here is how I handle this as a temporary dirty fix, if it can help:

On our ApolloServer (or any graphql server you use) I added a middleware `decimalCastMiddleWare` that will find any DecimalType in the response and convert them to number:

<ins>index.ts :</ins>
```ts
import { ApolloServer, makeExecutableSchema } from 'apollo-server-express'
import { applyMiddleware } from 'graphql-middleware'

const middlewares = [decimalCastMiddleWare]
const schema = applyMiddleware(makeExecutableSchema({ typeDefs, resolvers }), ...middlewares)

const server = new ApolloServer({
  schema,
  etc...
})
``` 

<ins>decimalCastMiddleware.ts :</ins>

```ts
import { Decimal } from '@prisma/client/runtime'

// recursive function looping deeply throug an object to find Decimals
const transformDecimalsToNumbers = (obj: any) => {
  if (!obj) {
    return
  }

  for (const key of Object.keys(obj)) {
    if (Decimal.isDecimal(obj[key])) {
      obj[key] = obj[key].toNumber()
    } else if (typeof obj[key] === 'object') {
      transformDecimalsToNumbers(obj[key])
    }
  }
}

export const decimalCastMiddleWare = async (resolve, root, args, context, info) => {
  const result = await resolve(root, args, context, info)
  transformDecimalsToNumbers(result)
  return result
}

```

- [see more on graphql middlewares with apollo](https://dev.to/notrab/using-graphql-middleware-with-apollo-server-39af)

**Comment by tarazena** [comment]
@Thibault2ss You can also use a custom directive to cast them as well!

**Comment by millsp** [comment]
Have you tried manually changing the `Decimal` to `Float`?

Before:
```prisma
model B {
  id       String  @id @default(cuid())
  float    Float   @db.Real
  dFloat   Float   @db.DoublePrecision
  decFloat Decimal @db.Decimal(2, 1)
  numFloat Decimal @db.Decimal(10, 6)
}
```

After:
```prisma
model B {
  id       String  @id @default(cuid())
  float    Float   @db.Real
  dFloat   Float   @db.DoublePrecision
  decFloat Float   @db.Decimal(2, 1)
  numFloat Float   @db.Decimal(10, 6)
}
```

**Comment by alan345** [comment]
@millsp yes it works, but if you run introspect, the schema will be changed again. And you will have to manually change to float again..

Similar issue: https://github.com/prisma/prisma/discussions/6421

**Comment by janpio** [comment]
@alexandrduduka, the linked issue https://github.com/prisma/prisma/issues/2903 is now closed as fixed. Is it valid to hide your comment here as outdated then?

**Comment by alexandrduduka** [comment]
Hi @janpio, I assume it was fixed in `2.20.1`, am I correct? We have to wait until `nexus-prisma-plugin` supports it in order to be able to check for our case.

**Comment by janpio** [comment]
No, the issue you linked to was closed last year. If you have a current problem with floating point precision, please open a separate issue with all required information so we can take a look at this. If we do not know about problems, we can not fix them unfortunately.

**Comment by matthewmueller** [comment]
There's quite a few different problems resulting from this one change. I think I understand the issue so to unpack them for latecomers like myself. 

If you have an existing database with the following schema:

```sql
create table Product (
  id serial primary key,
  name text,
  cost decimal(10, 2)
)
```

Previously, if you introspected, you'd get the following prisma schema:

```prisma
model Product {
  id Int @id @default(autoincrement())
  name String
  cost Float
}
```

We used to map decimals in the database to float values in the Prisma schema, which ultimately mapped to numbers in the Prisma client. Going the other way, I _think_ migrate also used to map Float to Decimal. 

Decimals and floats are very different beasts. Converting between the two can lead to rounding errors. Decimals also take more bits and are a lot slower to operate on than floats. The flip-side is they can store numbers with arbitrary precision. People typically use the decimal type for storing money and scientific computing.

When we introduced native types, we wanted to clean this up. Decimals map to decimals, floats map to floats.

If you introspected in a later version you got:

```
model Product {
  id Int @id @default(autoincrement())
  name String
  cost Decimal @db.Decimal(10, 2)
}
```

Since Javascript doesn't have a decimal type, we introduced decimal.js to fill in this missing data type.

This created the problem because we were no longer returning a number for the cost field, we were returning an instance of Decimal.

We're sorry about this unexpected breaking change. 

My first reaction to your suggestion is that you don't really want to disable decimal though, it's the proper return type for the job. 

Instead, I would suggest adding a Decimal scalar to your GraphQL schema and do the conversion there. Is there a reason why you don't want to or can't make this adjustment?

**Comment by tarazena** [comment]
@matthewmueller Thank you for your response.
The reason that I don't think its viable is because if I introduced a Decimal Scalar, It means that every GraphQL Consumer needs to be updated as well. I also thought of adding a Decorator/Middleware to convert those, this will cause a performance impact to the GraphQL Server.

I understand the nature of numbers in JavaScript and how it's a huge difference between JS numbers and SQL in general, I still think adding `@cast(Float)` flag in the prisma would make more sense, its optional, so any prisma consumer can use it. I think with proper documentation we can outline the risks of precision loss.

**Comment by alan345** [comment]
Thanks @matthewmueller for the clarification. I also understand the issue with decimal in javascript. 

But I agree also with @tarazena, let the prisma user decides how decimal should be interpreted. A flag could be the solution. 

From my personal experience, I'm form prisma1, the MySQL database was created with decimal. My codbase use float. Changing my codbase for decimal is a lot of work.

**Comment by matthewmueller** [comment]
> The reason that I don't think its viable is because if I introduced a Decimal Scalar, It means that every GraphQL Consumer needs to be updated as well.

Do you mind clarifying this point? My GraphQL is a bit rusty, but I don't see why the GraphQL consumers would need to change. 

I created a small example in this gist to demonstrate what I mean: https://gist.github.com/matthewmueller/b3ed598f0a9ed8a81dacc969a625dc29. In this example, the `amount` would be the decimal field before and `balance` is the decimal field after we changed it. Both return numbers back to GraphQL consumers.

Regardless of the configuration, I can definitely see us abstracting Decimal.js away and providing an interface for you to bring your own Decimal, but this doesn't seem to solve the OP's main issue.

**Comment by tarazena** [comment]
@matthewmueller Thank you for your response.
Your gist works well when you have few fields that needs to be casted, however in large apps where there are plenty of fields that will need to be casted, you will see a performance impact since its going to cast every individual field. you can also use a middleware to cast things too as well, but again the server is doing more work to cast things that Prisma should do in the first place

**Comment by matthewmueller** [comment]
Hey @tarazena I don't really see how performance would matter in this case. The task of casting must happen somewhere, since we're receiving back a decimal type from the database and our application is expecting a float (e.g. number in JS). Prisma isn't going to be able to cast a decimal to a number faster than your application can.

If arbitrary precision doesn't matter for your application, I'd suggest adjusting the data type in your database to be a Float or an Int, then when you regenerate the Prisma Client, your client will return numbers.

I know Prisma added to this confusion in the past when we conflated the 2 types (float and decimal), but we took steps to separate them and I'd prefer we don't offer ways to merge them back together again because then we'll see more precision issues. See: https://github.com/prisma/prisma/issues/6902 for more details.

**Comment by omar-dulaimi** [comment]
> BTW @tarazena @tom-richter @alexandrduduka, here is how I handle this as a temporary dirty fix, if it can help:
> 
> On our ApolloServer (or any graphql server you use) I added a middleware `decimalCastMiddleWare` that will find any DecimalType in the response and convert them to number:
> 
> index.ts :
> 
> ```ts
> import { ApolloServer, makeExecutableSchema } from 'apollo-server-express'
> import { applyMiddleware } from 'graphql-middleware'
> 
> const middlewares = [decimalCastMiddleWare]
> const schema = applyMiddleware(makeExecutableSchema({ typeDefs, resolvers }), ...middlewares)
> 
> const server = new ApolloServer({
>   schema,
>   etc...
> })
> ```
> 
> decimalCastMiddleware.ts :
> 
> ```ts
> import { Decimal } from '@prisma/client/runtime'
> 
> // recursive function looping deeply throug an object to find Decimals
> const transformDecimalsToNumbers = (obj: any) => {
>   if (!obj) {
>     return
>   }
> 
>   for (const key of Object.keys(obj)) {
>     if (Decimal.isDecimal(obj[key])) {
>       obj[key] = obj[key].toNumber()
>     } else if (typeof obj[key] === 'object') {
>       transformDecimalsToNumbers(obj[key])
>     }
>   }
> }
> 
> export const decimalCastMiddleWare = async (resolve, root, args, context, info) => {
>   const result = await resolve(root, args, context, info)
>   transformDecimalsToNumbers(result)
>   return result
> }
> ```
> 
> * [see more on graphql middlewares with apollo](https://dev.to/notrab/using-graphql-middleware-with-apollo-server-39af)

Hey @Thibault2ss 
I tried your code with TypeGraphQL, but didn't work for me unfortunately. So wondering if anybody here managed to get it to work before I force myself to cast all FLOAT to DOUBLE.

**Comment by tarazena** [comment]
@omar-dulaimi read [TypeGraphQL middleware docs](https://typegraphql.com/docs/middlewares.htmlhttps://typegraphql.com/docs/middlewares.html) Middleware implementations are little different.

**Comment by omar-dulaimi** [comment]
@tarazena The implementation isn't the problem, I have already done that here https://github.com/MichalLytek/typegraphql-prisma/discussions/103

The problem i'm facing is related TypeGraphQL. I was hoping somebody did this already and working for them.

**Comment by omar-dulaimi** [comment]
@matthewmueller 

> Prisma isn't going to be able to cast a decimal to a number faster than your application can.

Please correct me if I'm wrong. Wasn't the switch to Rust for gains in type-safety and performance?
I'm not sure if casting is faster in rust than javascript, but I suspect it. If it was faster, then it makes much more sense to do that process within prisma code.

**Comment by matthewmueller** [comment]
> Please correct me if I'm wrong. Wasn't the switch to Rust for gains in type-safety and performance?

The primary reason was for the ability to embed the Rust Query Engine in different languages via WASM. We're just starting to  see this with efforts like NAPI. You can expect more language support from us as WASM and WASI become more widespread. Type-safety and performance is a nice side-effect, but for these types of optimizations, we'd rather

---

Since this issue has veered a bit, and we've already discussed [our concerns with offering a way to disable Decimal.js](https://github.com/prisma/prisma/issues/6049#issuecomment-824728007) and [how to make this work in GraphQL](https://github.com/prisma/prisma/issues/6049#issuecomment-841279607), I'm going to close this issue. 

One thing that fell out of this discussion was the desire to bring your own Decimal.js solution. With this solution, you may be able to achieve the same thing as disabling it. I've created a follow-up issue to bring your own Decimal.js implementation: https://github.com/prisma/prisma/issues/7158.

**Comment by fdjones** [comment]
Hi, can this issue be re-opened? I'm not sure it's fixed. I'm a new user of Prisma and this is causing me a lot of problems. The issue I have is this:

I have a PostgreSQL db with columns having type decimal.
I created my Prisma models using Prisma introspect and it has types those columns as `Decimal`.
When I'm writing the GraphQL type for this column, I have either Int or Float, so I pick float.
This `float` type is converted to `number` in native JS, and these graphql types are autogenerated on any change of a graphql file so trying to update them is pointless, everything has to be done via the graphql files.
When I try to type anything using this column, I get `Type 'Decimal' is not assignable to type 'number' because the type that was inferred from using `Float` was `number` but the type that Prisma has is `Decimal`. 

Really not sure how to proceed with this other than using ts-ignore, which defeats one of the main points of using Prisma in the first place.

**Comment by matthewmueller** [comment]
Hey @fdjones, I'd recommend creating a [custom scalar](https://graphql.org/learn/schema/#scalar-types) for Decimal.

**Comment by jalik** [comment]
@matthewmueller I think you guys are too much focusing on GraphQL, I have the same problem but not using GraphQL, so what's would be the solution ? converting each decimal values before returning data in JSON responses on server side ? or do I handle that on the client side (values are received as string) ?

I understand the fact that a float is not a decimal, but in some cases it's fine, and we should be able to **opt-in** for that solution, which is way easier to handle for developers.

In fact today I saw that I had to change some fields from integer to decimal just to handle decimals in the future, but that small change which is done in seconds in the database, is clearly not the same compared to what I have to do in all my code (moving from number to string or number to class instance), it even seems impossible to do the transition without introducing bugs...

**Comment by alvik48** [comment]
If you need to change the behavior with conversion of Decimal objects when calling `JSON.stringify()`, you can use the next trick:

```
const prisma = require('@prisma/client');
prisma.Decimal.prototype.toJSON = function() {
  return this.toNumber();
}
```

**Comment by gustperz** [comment]
How can I get my **index.d.ts** file to be generated with the `number` type instead of `Prism.Decimal`?

**Comment by cazjck** [comment]
> If you need to change the behavior with conversion of Decimal objects when calling `JSON.stringify()`, you can use the next trick:
> 
> ```js
> const prisma = require('@prisma/client');
> prisma.Decimal.prototype.toJSON = function() {
>   return this.toNumber();
> }
> ```

this one work for me. thank a lot

**Comment by paulwer** [comment]
this wont work when using class-transformer or simmilar

**Comment by millsp** [comment]
To everyone: If you have a suggestion, please open a fearture request or request or a bug report. Thanks.

**Comment by pastukhvladyslav** [comment]
We have a lot of nested structures with decimal data type. The best we came up with is based on @Thibault2ss solution. Helper which converts all nested decimal fields to number.

```
import { Prisma } from '@prisma/client'
import { cloneDeep, keys, isArray, isObject } from 'lodash'

type SwapDecimalWithNumber<T> = {
  [k in keyof T]: T[k] extends Prisma.DecimalJsLike ? number : T[k] extends object ? SwapDecimalWithNumber<T[k]> : T[k]
}

export const decimalsToNumber = <T extends object>(obj: T): SwapDecimalWithNumber<T> => {
  obj = cloneDeep(obj)

  keys(obj).forEach((key) => {
    if (Prisma.Decimal.isDecimal(obj[key])) {
      obj[key] = obj[key].toNumber()
    } else if (isArray(obj[key])) {
      obj[key] = obj[key].map((el) => (isObject(el) ? decimalsToNumber(el) : el))
    } else if (isObject(obj[key])) {
      obj[key] = decimalsToNumber(obj[key])
    }
  })

  return obj
}
```

We wrap objects every time we get data from prisma like this:
```
decimalsToNumber(obj)
```

**Comment by BatuhanSevgil** [comment]
> If you need to change the behavior with conversion of Decimal objects when calling `JSON.stringify()`, you can use the next trick:
> 
> ```js
> const prisma = require('@prisma/client');
> prisma.Decimal.prototype.toJSON = function() {
>   return this.toNumber();
> }
> ```

thanks :) it fix my problem

**Comment by kamilwezgowiec** [comment]
> How can I get my **index.d.ts** file to be generated with the `number` type instead of `Prism.Decimal`?

I have run into a similar issue. Using [alvik48](https://github.com/alvik48)'s solution I was able to fix the TypeScript type as follows:
```ts
import { Decimal } from '@prisma/client/runtime/library';

declare module '@prisma/client/runtime/library' {
  interface Decimal {
    toJSON(): number;
  }
}

Decimal.prototype.toJSON = function () {
  return this.toNumber() as any;
};
```

Then here, `typeof json` is `number`:
```ts
const dec = new Decimal(5);

const json = dec.toJSON();
```

**Comment by ivosabev** [comment]
Here is a quick utility the replaces the Decimal type with simple number type

```typescript
type ReplaceDecimal<T> = {
  [K in keyof T]: T[K] extends Decimal 
    ? number 
    : T[K] extends object 
      ? ReplaceDecimal<T[K]> 
      : T[K];
};

type Wallets = ReplaceDecimal<PrismaWallets>;
```
