### ISSUE TITLE
Oops, an unexpected error occured!

### ISSUE THREAD

**Issue by comeriven** [prisma/prisma#6138]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.16.0           | 
| Prisma CLI  | 2.17.0             | 
| Binary      | 3c463ebd78b1d21d8fdacdd27899e280cf686223| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:166:14] We assume an internally valid datamodel before mutating.
```

**Comment by Jolg42** [comment]
Thanks for reporting this.

Unfortunately, we were not collecting the information in our error reporting in a format that allows us to replay the bug. That has changed with 2.19.0. Can you please try again with this version? This should allow us to exactly pinpoint the issue.

I'm closing this one now because we cannot act on it.
Please just open a new issue once you retried with 2.19.0 and still get an error.
