### ISSUE TITLE
prisma migrate deploy: The database server at DATABASE URL was reached but timed out

### ISSUE THREAD

**Issue by bardsol** [prisma/prisma#6224]
## Bug description
"prisma migrate deploy" sometimes crashes in production with the error message:
The database server at `MY.DATABASE.ondigitalocean.com`:`25061` was reached but timed out.
22:46:12.233  	Please try again.
22:46:12.233  	Please make sure your database server is running at MY.DATABASE.ondigitalocean.com`:`25061`

Database is Postgres database with PGBouncer pooling hosted on DigitalOcean. App is NextJS hosted on Vercel. The bug happens before building on vercel. Build command: prisma migrate deploy && npm run build

## How to reproduce
Hard to reproduce, it seemingly happens randomly. There wasn't even any migrations that was needed.
1. prisma migrate deploy

## Expected behavior
Migration should succeed or cancel if there are no pending migrations.

## Prisma information
I'd rather not share the database schema publicly, if it is needed I can share it privately to a Prisma dev.

## Environment & setup

Database is Postgres database with connection pooling hosted on DigitalOcean. App is NextJS hosted on Vercel. The bug happens before building on vercel. Build command: prisma migrate deploy && npm run build.

The Database URL environment variable has the pgbouncer=true flag

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 14.x
- Prisma version: ^2.19.0

**Comment by Jolg42** [comment]
Like [posted in public Slack](https://prisma.slack.com/archives/CKQTGR6T0/p1616580030365400?thread_ts=1616536218.356300&cid=CKQTGR6T0)

You could pass a longer timeout in the address
https://www.prisma.io/docs/concepts/database-connectors/postgresql#arguments
```
postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=myschema&connect_timeout=15
```
To set the connection timeout to 15 seconds instead of 5s by default.

The issue could be that the database in the same geographic zone as the CLI trying to connect to it.

**Comment by janpio** [comment]
Duplicate at: https://github.com/prisma/prisma/issues/6224
