### ISSUE TITLE
Separate integration tests by database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6272]
When introducing a new database like Vitess (which is a MySQL variant) it would be super helpful to be able to run just the integration tests that use MySQL. To achieve that, we would need to separate the integrations tests by database and make them filterable.

This then would enable us to do things like that: https://github.com/janpio/vitess-framework-testing/pull/3/files or https://github.com/janpio/vitess-framework-testing/pull/6/files

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
