### ISSUE TITLE
Expose `user._count()` chaining api

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#6330]
When we [introduced count on relations](https://github.com/prisma/prisma/releases/tag/2.20.0), we make it possible to write a query like so:

```ts
const users = await prisma.user.findFirst({
  include: {
    _count: {
      select: { posts: true },
    },
  },
})
```

What is not possible yet, but we could totally make it happen:
```ts
const postCount = await prisma.user.findFirst()._count().posts
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
