### ISSUE TITLE
Prisma migrate fails on M1 Mac

### ISSUE THREAD

**Issue by djru** [prisma/prisma#6397]
## Bug description

`npx prisma migrate dev` fails with the below error:

```
% npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Error: Command failed with Unknown system error -86: .../node_modules/@prisma/engines/query-engine-darwin cli get-config
spawn Unknown system error -86
```

This is on an M1 macbook air. When I try to run that executable which prisma was complaining about, it gives an error about the cpu type.

```
zsh: bad CPU type in executable: ../node_modules/@prisma/engines/query-engine-darwin
```

**Is this simply a matter of prisma not supporting arm macs as a target yet?**

## How to reproduce

1. Clone [graphql prisma sample code](https://github.com/howtographql/graphql-js/blob/master/src/index.js)
2. run `npx prisma migrate dev`

## Expected behavior

Should generate migration without error

## Prisma information

Schema
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  text      String
  link      String
}
```

## Environment & setup

OS: macOS 11.2.1
Database: sqlite 3.32.3
Node: 15.12.0
prisma: 2.20.0

**Comment by tomhoule** [comment]
Relevant existing issue: https://github.com/prisma/prisma/issues/5245

M1 CPUs are unfortunately not supported yet.

**Comment by pantharshit00** [comment]
Prisma should still work via Rosetta on M1. Please make sure that rosetta is enabled in your machine.

**Comment by uncvrd** [comment]
@pantharshit00 hey! would you be able to clarify how to run prisma using rosetta emulation? I currently have the following Dockerfile but it fails to generate artifacts with the `npm install` prisma postinstall script. `prisma` is within my `package.json` which is installed upon build.

```
# ------------> Base Image
FROM node:14-alpine AS base

WORKDIR /workspace

# ------------> Development Image
FROM base AS development

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
```

Running this same `Dockerfile` on an intel mac works fine, but doesn't work on my new M1 device

**Comment by DanielOberlechner** [comment]
I can't work as well not with Prisma because of the following error:
`
Error: Generator at prisma-client-py could not start:

Traceback (most recent call last):
  File "/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/bin/prisma-client-py", line 5, in <module>
    from prisma.cli import main
  File "/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/prisma/__init__.py", line 9, in <module>
    from .utils import setup_logging
  File "/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/prisma/utils.py", line 10, in <module>
    from ._types import FuncType, CoroType
  File "/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/prisma/_types.py", line 4, in <module>
    from pydantic import BaseModel
ImportError: dlopen(/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so, 0x0002): tried: '/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (no such file), '/Users/danieloberlechner/.local/share/virtualenvs/YT-TitleCollector-fIAu2flS/lib/python3.9/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
`

Is there a chance for a solution out there? Would like to keep progressing with my project..
