### ISSUE TITLE
How to migrate without getting: 'We need to reset the PostgreSQL database'

### ISSUE THREAD

**Issue by shwethashyam1** [prisma/prisma#6403]
## Bug description

I added a new table to my database and tried to run 'npx prisma migrate dev --create-only'. But it says '✔ Drift detected: Your database schema is not in sync with your migration history. We need to reset the PostgreSQL database.' 

As an alternative, I have also archived all my old prisma migrations into a different folder and deleted the prisma_migrations table from the postgres database. After this, I ran prisma introspect to get the updated schema, added the new table and tried the migrate dev command. Unfortunately, I still keep getting asked to reset the database which would cause all user info to get deleted.

## Expected behavior

create new migration.sql file without resetting the database
## Environment & setup

- OS:  MacOS
- Database:  Postgres
- Node.js version:  Node 12
- Prisma version:

```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
```

**Comment by albertoperdomo** [comment]
Hello @shwethashyam1,

If I understood correctly, I think this is the expected behavior, since you caused drift by adding a table directly to the database.

Here are a few options for how to deal with this...

Option A: Add the table to the schema file, use Prisma Migrate dev to create a migration to add the table and add the table to the database schema
Option B: Add the table to the database (causing drift), introspect the database to update the schema file, use Prisma Migrate dev to create a migration to add the table and update the database schema, accepting that this will trigger a database reset.

Data loss during database resets in development can be offset by using the seeding functionality. Seeding will be triggered automatically after a DB reset.

I don't get why you removed all migrations. This will of course trigger a DB reset since the migration history diverges (Prisma Migrate will see migrations in the DB that were applied that no longer exist locally).

Alternatively, if you don't care at all about migrations, you could use `prisma db push` and `prisma db pull` (prisma introspect is being renamed), which allow syncing the schema file in both directions without using migration files.

I hope this helps. Let me know if you have any follow up questions or comments.
