### ISSUE TITLE
`generate` shows me TS snippet although clearly in JS project

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6409]
I get this output on `npx prisma generate`:

````
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (2.20.1) to .\node_modules\@prisma\client in 115ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
````

Although I am clearly in a JS project:
- No tsconfig
- Only source code file is an index.js

It would be nice if Prisma Client could do some minimal detection of the project type and output the appropriate code snippet.

**Comment by petradonka** [comment]
@quest-bot stash 50

**Comment by fiznool** [comment]
This is valid JS code if you are using ES modules. Is the suggestion to show a CommonJS snippet if you are in a JS project? If so, I would question if this is the correct move, given the way that the node ecosystem is moving (away from CJS, to ES).

**Comment by fiznool** [comment]
@quest-bot embark

**Comment by janpio** [comment]
Do you have a suggestion on how to specify a more useful variant of what the issue is asking for? The goal should be that the snippet works by just copy-pasting it into the project the CLI is being run on. Currently that is not the case for a simple CJS project, which there are still many (even if we all wish that was not the case any more).

**Comment by fiznool** [comment]
I can see from the docs that the JavaScript instructions still use CommonJS syntax too. So to maintain consistency I think the suggestion to provide a different snippet is reasonable after all.

Would a message such as this be acceptable?

---

You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

If you are using TypeScript or JavaScript with ES modules, use the following snippet to get started:

```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

Otherwise, copy and paste this to get going:

```
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()
```

**Comment by jharrell** [comment]
That looks great to me @fiznool. Thanks!

Yes, you are correct. We would like JS instructions to use CJS syntax while TS uses ESM.

**Comment by janpio** [comment]
The original idea in the issue would be to detect the needed code and show the correct one, that can be copy/pasted directly. Not sure if that is possible.

**Comment by fiznool** [comment]
@janpio thats what I ended up doing in the linked PR.

**Comment by jaysaadana19** [comment]
@quest-bot embark

**Comment by jaysaadana19** [comment]
@quest-bot loot #6409

**Comment by jaysaadana19** [comment]
@quest-bot embark

**Comment by jiashengguo** [comment]
Quine asked me to look into this issue. Based on my understanding, @fiznool has made the correct fix but was unable to add the corresponding test case, right?

I attempted to add a test case for simulating a JavaScript environment, as per @millsp's comments. However, it seems that some modifications are needed for the existing test infra either way.

- For the CLI tests, since the actual running code is in the `cli/build/index.js` of the current repo, it definitely could find the Typescript environment.  Even if I copy all the build output to the temp directory and run it there, it’s still the case because the build output has the Typescript dependency.
- For The e2e test suite, it relies on the Typescript environment to execute the `_step.ts`.

If it's true, I believe that this kind of change would be better executed by the internal team. Please correct me if I am wrong. 

On the other hand, I can't think of any reason why people would use Prisma in a non-Typescript environment. Are there any actual users who have ever complained about it? Even in the rare case that people do use Prisma without Typescript, I assume they wouldn't be confused by the existing console output.

So, to be honest, based on the cost-benefit analysis, if I were the PM of Prisma, I probably would either mark it as "won't fix" or simply accept the fix provided by @fiznool if our engineers are okay with it.  😄

**Comment by janpio** [comment]
I think I found a way: I created a new branch `context-aware-generate-output` from current `main`, reopened the PR of @fiznool, then pointed the PR to the new `context-aware-generate-output` branch. We should now be able to clean up the PR to be able to merge into that branch - which I think should close the Quine quest properly. When done I can create a new PR from that branch to `main` that we can finish on our side by adding the needed tests, and reopen this issue here to mark that it is not actually merged yet and might not make the next release if we are not quick enough.

Does that work?

**Comment by janpio** [comment]
@jiashengguo I don't have to create a `tsconfig` file manually but can just run a simple `script.js` when testing stuff quickly.

@fiznool Do you agree that merging your PR to that temporary branch is a good idea?

**Comment by fiznool** [comment]
@janpio sounds good to me 👍

**Comment by janpio** [comment]
https://github.com/prisma/prisma/pull/21140 is merged.
https://github.com/prisma/prisma/pull/21620 now exists.

**Comment by petradonka** [comment]
@quest-bot reward @fiznool

**Comment by petradonka** [comment]
Thanks for the contribution & working this one out with us @fiznool!

**Comment by jkomyno** [comment]
Closing this issue as fixed already.
