### ISSUE TITLE
Way to check connection string without generating client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6410]
## Problem

I can not generate a client with an empty database, so I can not call `$connect()` to check if my connection string is valid.

## Suggested solution

One of the following:

- A status command: `npx prisma status` or `npx prisma db status` that confirms that a connection to the database could successfully be created
- `npx prisma generate` could let me create a client without a model, so I can call `$connect()` manually in my code

## Alternatives

One of the following:

- Run `npx prisma db pull` or `npx prisma introspect`
- Add fake model to schema file, then run `npx prisma generate` and use `$connect()`

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
