### ISSUE TITLE
Netlify Functions deploy fails with Prisma because of size problems, Prisma deploys with 2 QE binaries

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6503]
In a minimal Prisma project (no `binaryTargets` in schema, super simple function code that only requires `@prisma/client`) deployed to Netlify the deployment to AWS Lambda includes two different Prisma Query Engine binaries, `query-engine-debian-openssl-1.0.x` and `query-engine-rhel-openssl-1.0.x`. Only the `rhel-openssl-1.0.x` one is required on that platform.

This is a problem, as that also means both these binaries have to be uploaded in the archive to Lambda where a limit of 50MB applies. This leaves less space for user project code.

### Probable explanation

Netlify builds on Debian, so Prisma Client by default adds that binary to the project. Additionally we have special code in Prisma (https://github.com/prisma/prisma/blob/d3e28bf2ec47e645591f743f0b58749b4572811f/src/packages/sdk/src/getGenerators.ts#L390-L395) that makes sure the `rhel-openssl-1.0.x` binaryTarget is added when running on Netlify. Result: 2 binaries.

### Reproduction

- Repository: https://github.com/janpio/prisma-binary-repro
- Schema: https://github.com/janpio/prisma-binary-repro/blob/main/prisma/schema.prisma
- Function: https://github.com/janpio/prisma-binary-repro/blob/main/netlify/functions/index.js
- Deployed Function: https://prisma-binary-repro.netlify.app/.netlify/functions/index
- To reproduce fork this repository and connect it to a new Netlify project via Git. Automatic deploy should give you a function that can reproduce this

### Workaround 1

- Setting `binaryTargets = ["rhel-openssl-1.0.x"]` in the `generator` block of the `schema.prisma` tells Prisma to only download that binary:
  - https://github.com/janpio/prisma-binary-repro/pull/1/files
  - https://deploy-preview-1--prisma-binary-repro.netlify.app/.netlify/functions/index
- Note that this makes local development in your project also a bit harder, you have to modify your binaryTargets again for local development and replace that line or set it to `native`
- This of course only works if build process on Netlify does not want to use Prisma Client (e.g. to seed a database or similar, which Redwood for example support). Without the Debian binary Prisma Client will fail during the build process.
- If you want to use this: Make sure to use the "Clear cache and deploy site" button on Netlify, otherwise you will probably see a cached function and spend a lot of time being confused.

### Workaround 2

You can also build your project locally and then upload the full bundle with the Netlify CLI with `netlify deploy`, without a Netlify CI build step: We have an end to end example for this that you can build on: https://github.com/prisma/e2e-tests/tree/dev/platforms/netlify-cli (Note that it uses `output` on the generator in the schema.) (You probably have to add a step that removes your local platform binary or use Workaround 1 additionally.)
  
### Thoughts about solution
- Removing the Debian QE binary or not downloading it in the first place on Netlify is the obvious approach. The problem of that is described in the Workaround section above as well - one might want to use the Debian binary during the Netlify build to run Prisma Client.
- Possibly we can influence the archive creation somehow to make sure only the correct binary is included.
- Maybe there is also a way to get a different binary for the build process than for the function (in theory the `node_modules` for both could potentially look different or could be manipulated during the build process.

**Comment by millsp** [comment]
https://github.com/prisma/prisma/pull/6527

**Comment by pedrosousa13** [comment]
Hi @Jolg42 !

I'm trying to deploy a nextjs project and keep getting that error even after updating to 2.21.2, and clearing the cache in the build process.

Build step `prisma generate && next build` using yarn.

`PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")

Searched Locations:

  /.prisma/client
  /opt/build/repo/node_modules/@prisma/client
  /
  /var/task/node_modules/.prisma/client
  /var/task
  /tmp/prisma-engines
  /var/task/node_modules/.prisma/client

You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at cb (/var/task/src/nextPage/index.js:40268:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.21.2',
  errorCode: undefined
}`
