### ISSUE TITLE
Misleading validation error on MongoDB connection strings

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6539]
```
C:\Users\Jan\Documents\throwaway\mongoQA>node index.js
PrismaClientInitializationError2 [PrismaClientInitializationError]: 
Invalid `prisma.user.findMany()` invocation:


  error: Error validating datasource `db`: The URL for datasource `db` must start with either the protocol `mongodb://` or `mongodb+srv://`.
  -->  schema.prisma:6
   |
 5 |   provider = "mongodb"
 6 |   url      = env("DATABASE_URL")
   |
```

when `DATABASE_URL` is set to `mongodb://`

**Comment by dpetrick** [comment]
Can't reproduce the message in any context:
- `mongodb://` in the datamodel file as plain string.
- `mongodb://` in `DATABASE_URL` and `env("DATABASE_URL")`  in the datamodel file.

Possibly got fixed by some changes made by the migration team in between (as they're working on the parser at the moment)?

**Comment by pantharshit00** [comment]
I can also no longer reproduce after updating. I guess we can close this.
