### ISSUE TITLE
Lots of "SELECT 1" queries overloading Database

### ISSUE THREAD

**Issue by eduhenke** [prisma/prisma#6668]
Is this timer configurable? I am currently facing a problem that the prisma client was sending a lot of those "SELECT 1" requests, which overload the database(64k SELECT 1 requests in 1 hour):
![image](https://user-images.githubusercontent.com/8304447/115418578-f96e7500-a1cf-11eb-8f37-70c4c51a32a5.png)

I have 2 pods each with connection limit set to 200, and this overloads our DB(2vCPU 7.5GB Cloud SQL Postgres).

I think that if I could tweak around this parameter I could reduce the number of the "SELECT 1" queries, and reduce the load on our DB.

_Originally posted by @eduhenke in https://github.com/prisma/prisma/discussions/5604#discussioncomment-635772_

**Comment by eduhenke** [comment]
![image](https://user-images.githubusercontent.com/8304447/115436825-ca60ff00-a1e1-11eb-8026-ab1a067f12f9.png)

As you can see the DB with 2 vCPU gets completely overloaded by the "SELECT 1" Query

**Comment by janpio** [comment]
> As you can see the DB with 2 vCPU gets completely overloaded by the "SELECT 1" Query

That is super weird, as `SELECT 1` is one of the fastest and lightest queries one can run on the database.

Are you also monitoring the open connections on the database during that time?
How and where is your application running? 
What kind of queries it is executing?

**Comment by eduhenke** [comment]
I think that the other issue that I opened(https://github.com/prisma/prisma/issues/6664) and this one are related.
While trying to solve both issues I found this issue: https://github.com/prisma/prisma/issues/6329#issuecomment-815008831

And that is my exact setup: I am running Google Cloud SQL with Query Insights.

I've updated the prisma version to the latest(v2.21.2), and since then(1 hour ago) the number of active connections seemed to be lower(~270 at 02:06, and ~100 now):
![image](https://user-images.githubusercontent.com/8304447/115442846-e2884c80-a1e8-11eb-9558-681deca21971.png)

And so did the DB load:
![image](https://user-images.githubusercontent.com/8304447/115442914-f16eff00-a1e8-11eb-8941-70d592694248.png)

However, this "SELECT 1" queries overloading the DB, happen occasionally, they are not fully reproducible(they go up, when the traffic goes up and/or the number of active connections goes up). 
Until now it seems that only updating the prisma version and decreasing the connection pool of the pods has helped, I will report back after running the system a bit longer.

**Comment by janpio** [comment]
Thanks for the feedback, that makes a bit more sense now.

The issue #6329 you found was exactly why I asked you to update, and I am happy that this helped. We are still watching these deployments trying to understand what exactly is going on and why - so any further feedback from your would be very welcome.



> However, this "SELECT 1" queries overloading the DB, happen occasionally, they are not fully reproducible(they go up, when the traffic goes up and/or the number of active connections goes up).

My _theory_, and this is not based in any proof yet, is that Google Cloud SQL is misreporting the load generated by the query here in the screenshot you posted. It might look like the total time is mostly used by this query, but in reality something else is causing load on the server (some other bad query, the number of open connections, or something similar). Again, just a rough theory.

If it turns out this query is indeed a problem, we might totally add a knob to turn that retry number up a bit. We are also generally looking into how to get rid of this query by doing keep alive in our connection pool completely different, but that is a bigger project for that I have no timeline.

**Comment by eduhenke** [comment]
Just reporting back, I've upscaled to about 20 replicas each with a connection pool of 16, because of our load.
And it still reports the "SELECT 1" query as the highest load, is it normal that it is called 144000 times in a hour? That's 40 times a second.

We do have another query(the second one) that is indeed heavy, it returns on average 20k rows, but it is only called once every 6 seconds:

![image](https://user-images.githubusercontent.com/8304447/115453715-4f561380-a1f6-11eb-80b9-0f406e50f2dc.png)

**Comment by janpio** [comment]
The query is run every 15 seconds per idle connection in the connection pool of the Prisma Query Engine. One `PrismaClient` instance has 1 Prisma Query Engine, with a default connection_limit/pool size of `2*cpu_core+1`. 

If I understood correctly you have 20 app servers running, each with a connection_limit of 16. If those connections are all active in the pool (meaning they were used at least once) that would mean 20*16*4*60 = 76800 expected queries. Not your number, but close enough that this _kinda_ makes sense.

Important questions:
- Do you have graph for the connections in use on the database side?
- Can you maybe filter this load graph by query?
- As I do not know the graph above very well, what exactly does the "green" area in the graph show - is that indeed "CPU and CPU wait", meaning you are using too much CPU for the machine size of your database?

And some more:
- Are you getting any application errors with database errors thrown by Prisma?
- Do you have some retry logic in your application that keeps reytring queries if they fail on the database side?
- Can you roughly explain what you application is doing?

We have some experimental parameters we might be able to try out here. They would effectively make sure the connection are closed earlier - but we need to understand what is going on first better before we try those.

**Comment by eduhenke** [comment]
Hmm, I see. I've contacted Google Cloud Support to help me in this as well, as it doesn't seem to be a specific problem with Prisma.

# Data

Graph of active connections of the last 6 hours(it sometimes stabilizes in 100, because I've scaled 10 servers with 10 connections in the pool):
![image](https://user-images.githubusercontent.com/8304447/115466555-a368f400-a206-11eb-8031-69bc3173074a.png)
Graph of Database load(A measure of the work (in CPU-seconds) that all executed queries in your selected database perform over time: https://cloud.google.com/sql/docs/postgres/using-insights#using-db-load-graph)
![image](https://user-images.githubusercontent.com/8304447/115466712-d3b09280-a206-11eb-8fcc-ed1b91b996c3.png)

Graph of Database load filtered by the "SELECT 1" query:
![image](https://user-images.githubusercontent.com/8304447/115466939-22f6c300-a207-11eb-9522-94faca579fdc.png)

# Errors
In the last 3 hours it throwed:
- 33x P1017 error
- 3x Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 16.
- 1x This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic: the database system is in recovery mode. Which happens probably because of the Query Insights enabled as linked in the other issue.
- 43x "Server has closed the connection."

# Retry Logic
I have no retry logic in my application

# Application
My application serves a GraphQL server, that connects to this database. It queries various tables, most tables contains less than 1000 rows, and one specific table has 2.5 million rows(it has some indexes to speed up some queries).

**Comment by janpio** [comment]
How many connection can the database server handle at a time per Google Cloud's recommendation?
Can you upgrade or scale up the database server easily to see if that changes the situation?
Have you tried disabling Query Insights if that improves the situation?

What I am currently reading from these graphs and error messages (and that includes a lot of guessing) is that the database server becomes unresponsive or otherwise restarts from time to time when many connections are open. That is also when the `SELECT 1` queries are executing for a lot longer than usual, causing to to "eat time" and making the top of your list.

**Comment by janpio** [comment]
Based in that previous reading of the possible situation:
Do you have enough traffic on your API that it makes sense that you are maxing out the possible number of connections per server? (Are there indeed 10 database queries happening per server at the same time usually?)

One thing you could try is to _lower_ the `connection_limit` per server to make the queries run in sequence instead of in parallel, waiting in the queue a bit. This might lead to slower response times, but less connection  - and if this is the problem it might help already. (If you start seeing a lot more "Timed out fetching a new connection from the pool" errors, you can increase the `pool_timeout` parameter from its default of 10 to 30 or even 0, for infinite)

**Comment by janpio** [comment]
Any update here @eduhenke? I am still interested in figuring out what is happening here.

**Comment by eduhenke** [comment]
Hello @janpio it's been a while since I've touched this issue, but if I recall correctly, there were a few points:

- there were indeed a lot of SELECT 1 queries, however it seemed like it was more of a Cloud SQL Query Insights problem
- In production I've set the params to `connection_limit=20&pool_timeout=30`, and that seems to be OK
- I was/am doing a lot of quick polling(1-2s) on the frontends, and they sometimes consume analytic data(that sums, aggregates, on the spot), now I've put a layer of cache(https://www.npmjs.com/package/prisma-lrucache-middleware) between my DB and server, and that seemed to help

Overall, it just seemed like a Cloud SQL Query Insight, diagnosing that the problem was with the SELECT 1 queries, but it was with how(and how much) I was querying the data.

We sometimes have performance problems, but it is a lot more manageable now. Thanks for the previous help!

**Comment by janpio** [comment]
Thanks a lot for the update, that sounds very reasonable. We'll still try to get better here in the future of course.

**Comment by kevinsimper** [comment]
@eduhenke Are you sure it is `SELECT 1` as your screenshots says `SELECT $1` which could indicate prepared statements. I am also using Google Cloud and have seen the same, but I assumed it was the Query Insights which was not great at the prepared statements sent.
