### ISSUE TITLE
Un-generated Client error message could point out that using `output` might require different import

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6672]
## Problem

It could happen that you set an `output` in your `generator`, but you still `import { PrismaClient } from '@prisma/client';` in your project. 

Under certain circumstances (e.g. when you run `npm install` in a project that has `prisma` as devdependency and `@prisma/client` as dependency, see `package.json example below) it can happen that the uninitialized Client is put into the default location in `node_modules/.prisma/client`, where the default import will look for a generated Client.

This will lead to an error like this:

> @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

![image](https://user-images.githubusercontent.com/80341254/115387819-d64dc080-a1e3-11eb-98bd-e6be03881a3f.png)

Right now the error message is not super helpful in connecting these dots and might send a user to hunt a problem (Prisma Client was not generated) that does not even really exist.

Example: https://github.com/prisma/prisma/issues/6644

## Suggested solution

1. The error message could get a second line that points out that if you are using `output` in generator, you might have forgotten to import your Prisma Client from there and should do that instead.
2. Optionally it could even read check for an `output` value and see if this matches the current, own import. If not it could give some helpful output.

## Alternatives

Do not forget that you are using an `output` in your `generator`

## Additional information

package.json:
```json
{
    "name": "test",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "devDependencies": {
        "prisma": "^2.20.1"
    },
    "dependencies": {
        "@prisma/client": "^2.20.1"
    }
}

```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
