### ISSUE TITLE
Error when Prisma try to fit an old MongoDB record in a model with a new field.

### ISSUE THREAD

**Issue by matheusfenolio** [prisma/prisma#6688]
Those are two existing records in my MongoDB collection. I inserted them using a version of Post model without author field.

![image](https://user-images.githubusercontent.com/37229507/115592523-b385df80-a2a9-11eb-8b87-155606abe5df.png)

Then I added author field as a String in Post model.

![image](https://user-images.githubusercontent.com/37229507/115592591-ca2c3680-a2a9-11eb-8955-765c2c7dc5e2.png)

When I tried to recover those records, I got an error. 

![image](https://user-images.githubusercontent.com/37229507/115592655-dca67000-a2a9-11eb-9829-a760841a5860.png)

**Comment by matthewmueller** [comment]
Looking at this again, I'm not totally sure it's a bug, because the schema defines the shape of your data and the previous items in the collection don't have that shape. 

Without migrate or introspect though, I can see how easy it is to run into this and I'll talk to the team to see what we can do. 

Two workarounds that should work:

- Make the author optional (String?)
- Backfill the previous records to have an author.

**Comment by matheusfenolio** [comment]
Awesome! It's working now. It is something to pay attention, maybe an advise would help.

![image](https://user-images.githubusercontent.com/37229507/115593424-de246800-a2aa-11eb-990f-578e10e5f166.png)

**Comment by janpio** [comment]
As this might be much more common with Mongo, we could possible invest in giving a better error message here that tells the user what is going on @matthewmueller, something along "Data returned included and `author` with value `null` which is not compatible with your current schema."

**Comment by matthewmueller** [comment]
Glad to hear that worked for you @matheusfenolio. Re-opening as a discussion because this is a super easy trap to fall into in the current state.

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/prisma/issues/6715
