### ISSUE TITLE
Can not run "npx prisma init" command: binary download error `getaddrinfo ENOTFOUND`

### ISSUE THREAD

**Issue by codebdy** [prisma/prisma#7106]
### Bug description

I can not run "npx prisma init" under windows system, plea help me.
![image](https://user-images.githubusercontent.com/18096128/118445380-f14b1c00-b720-11eb-8526-8fff0f2f5a2e.png)

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by rxwater** [comment]
I think maybe china firewall cause this problem,but I can not solve it with VPN. Is any way to solve this problem? this problem will block many China programers

**Comment by janpio** [comment]
You are right unfortunately, at least this website agrees:
![image](https://user-images.githubusercontent.com/183673/118716080-b6321100-b824-11eb-8611-ac097d171068.png)
http://www.chinafirewalltest.com/?siteurl=https%3A%2F%2Fbinaries.prisma.sh%2F

Are there common ways how to fix/avoid this? Our knowledge here is limited, but of course we are super interested in fixing this.

**Comment by AGDholo** [comment]
@janpio If only one XML page, Maybe consider adding another server which not banned in China.

I use the Vercel to my server, but it has been banned in China recently, they have a method to solve it: https://www.vercel-status.com/incidents/r758bhbklgfd

It might work.

If I make a project with Prisma to China programmer, VPN cannot to solve it perfect, because not everyone uses VPN.

**Comment by janpio** [comment]
Thanks @AGDholo - unfortunately it is _much_ more than 1 XML page. That domain is hosting thousands of binaries we build for different platforms and operating systems - and that for each version of Prisma we release (production and development).

But we are looking into this now. We definitely want to find a solution that works for Chinese developers, optimally out of the box without any custom configuration.

Are there best practices how other tools handle this? Do they do so automatically, or via some documentation? Do they have good error message that tell you how to work around it?

Right now we are looking into AWS Cloudfront's chinese footprint. Maybe we can just use that to make the data being served from working servers for you.

**Comment by AGDholo** [comment]
@janpio 

In China, there are companies that specialize in mirror proxy acceleration services for common package managers, for example 

npm mirrors: https://npm.taobao.org/mirrors/
ubuntu mirrors: https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

This is the only solution in China besides using good quality servers (CN2 lines, not banned etc.), which are used by many institutions or schools.

For the disabled in China issue: If a domain name or server is disabled, then you need to change the domain name and server IP to resolve the issue.

In addition, the general server line is very bad and the download speed is extremely slow, so it is basically the same as being disabled, which is limited by the bandwidth of the Chinese export network.

**Comment by janpio** [comment]
Do you by chance know if when we uploaded our binaries to the the [Alibaba Cloud Object Storage Service](https://www.alibabacloud.com/product/oss), this would work behind the firewall?

**Comment by rxwater** [comment]
The firewall dose not distinguish Alibaba and others, except the server locate in China.If you want to use the server that locate in China, you must request permission from government.
Not all servers are block by firewall, but we don't know the rules

**Comment by pantharshit00** [comment]
Electron uses taobao for china distribution, I think that is the best bet here. https://www.electronjs.org/docs/tutorial/installation#custom-mirrors-and-caches

**Comment by pantharshit00** [comment]
If you are blocked by this, try building the engines yourself for now while we figure this out: https://github.com/prisma/prisma-engines#building-prisma-engines


https://www.prisma.io/docs/concepts/components/prisma-engines#using-custom-engine-binaries

**Comment by AGDholo** [comment]
@janpio If the prisma download file could upload to the npm, the taobao mirrors could auto-async these file form https://cdn.npm.taobao.org/dist/xxxx

If the open source project is very popular, it might be possible to contact the Chinese IDC vendor and ask them to provide free acceleration services as a support to the open source community (might work).

Also, alibabacloud global's server line quality varies and needs to be tested to know, so if you want to use alibabachina then it's not realistic because you have to provide ICP qualifications to the Chinese government for review.

The line quality needs to be tested several times to know, maybe you can contact alibabacloud support directly to ask, as far as I know vercel switched from aws to gcp after the line quality is much better, also can be included in the test list.

---

As a relatively large open source project, I think there is a good chance of getting the IDC provider to offer free services.

**Comment by janpio** [comment]
> If the prisma download file could upload to the npm, the taobao mirrors could auto-async these file form cdn.npm.taobao.org/dist/xxxx

Hmmm, unfortunately we chose not to use Npm for our binary distribution in the past. That would now come in _really_ handy indeed. And adding that is also not trivial, as our whole download logic depends on our current AWS S3 based architecture.

But maybe this gives us an idea to make it work anyway.

> if you want to use alibabachina then it's not realistic because you have to provide ICP qualifications to the Chinese government for review.

Thank you for this clarification! I was under the impression that using Alibabacloud would give us a server inside China, but seems it does indeed not matter at all - the IDC requirement is the same as it would be on AWS China.

Until then please indeed see what Harshit wrote above: https://github.com/prisma/prisma/issues/7106#issuecomment-845111692

**Comment by janpio** [comment]
This has not been a problem for a while, so I think we can close this.
