### ISSUE TITLE
Extend Prisma Client

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7161]
## Problem

Right now we don't provide guidance on how use the Prisma Client within a higher-level model or domain.

## Use cases

**1. Adding a computed field:** The canonical example is getting a full name from a first and last name. We also have some use cases in: https://github.com/prisma/prisma/issues/3394 and https://github.com/prisma/prisma/issues/5998

**2. Multi-step actions**: Right now people put all their Prisma Client calls inside their GraphQL resolvers or RESTful controllers. This leads to "fat controllers" that are hard to test and lead to code duplication across controllers. The reason is because the Prisma client is often lower-level than your business domain and expressing your business logic requires multiple steps. 

   Some Examples:
   - _team.signup_: signing up for Slack requires you to create a user and a team at the same time
   - _document.update_: when you update a document, you also update its search index and fire off an email to subscribers
  
   From a top-level view of your application, you'd consider these to be a single action (e.g. team.signup and document.update), but they break down into multiple steps. We should have a way to turn multiple steps into single actions without limiting the rich capabilities of the Prisma Client API. https://github.com/prisma/prisma/issues/5258 https://github.com/prisma/prisma/issues/5258

**3. Custom Validation**: Validate fields before they hit the database. Using the example above, for a `team.signup(team_name, owner_email)` action, you can validate that the owner's email address is valid and the team name doesn't have any special characters before you go to the database. Lots more use cases in: https://github.com/prisma/prisma/issues/3528

## Existing Solutions

- **Middleware:** Is one way to solve the multi-step actions triggering other actions, but you wouldn't really want to trigger other Prisma Client actions within this middleware. It's also global configuration for the entire instance of the client. Models can be more flexible. 
- **Doing it in your resolver or controller**: This works fine for simple applications. When you start sharing this logic, you need a way to abstract shared business logic into a model.

## Prior Art

In Rails you have a difference between [Active Record](https://guides.rubyonrails.org/active_record_basics.html) and the [Active Record Query Interface](https://guides.rubyonrails.org/active_record_querying.html). Prisma Client is an awesome Active Record Query Interface but Active Record is currently DIY. We should also have a story for some of the Active Record use cases described above.

## Suggested Next Steps

- [ ] Create an example script with the Prisma Client we have today demonstrating the use cases above. E.g. A model with computed fields, multi-step actions and custom validation.
- [ ] Do we lose the rich querying capabilities of the Client? What can we do about that? Can we have both? If so, how could we have both?
- [ ] How easy was this script to write with our existing generated type definitions? Anything we can do to improve this common workflow?
- [ ] Document how to do currently this so we can point users to this documentation whenever they ask about it. Create new issues for larger future improvements.

*What I'd like to avoid:* Going too deep into implementing a solution before understanding how one would do this with today's Prisma Client in a hacky way perhaps.

## Related

- Extend the Prisma Client: https://github.com/prisma/prisma/issues/5222
- Virtual Fields: https://github.com/prisma/prisma/issues/3394
- CRUD Wrapper Service: https://github.com/prisma/prisma/issues/5273
- Document how to use Prisma in a Wrapper Function: https://github.com/prisma/prisma/issues/5258
- Convert the Models from Types to Classes: https://github.com/prisma/prisma/issues/5998

**Comment by tobiasdiez** [comment]
Computed fields are also related to https://github.com/prisma/prisma/issues/5998, which would provide a very easy and flexible way to implement them.

**Comment by matthewmueller** [comment]
@tobiasdiez that's a good one. Added that to the Related list. Thanks!

**Comment by josh-hemphill** [comment]
This might also be related: #6759 
Or more generally, orchestrating your app's initialization/setup as it relates to the database.

**Comment by matthewmueller** [comment]
Might be! I could see two Prisma Client in one higher-level model. One with read access, one with right access.

**Comment by yasaichi** [comment]
It seems to me that [prisma/ent](https://github.com/prisma/ent) could deal with the usecase 1 and 2. Why don't you re-start from it?

**Comment by Newbie012** [comment]
Related - https://github.com/prisma/prisma/issues/6349

**Comment by ysfaran** [comment]
Are there already plans to implement this soon?

**Comment by smolattack** [comment]
It would be useful to be able to add your own opaque types/smart constructors.

An example of how that might work has been suggested in https://github.com/prisma/prisma/issues/6349#issuecomment-866367713

**Comment by tobiasdiez** [comment]
@matthewmueller can we as a community help with the examples explaining the status quo. If yes, in which form do you prefer these, e.g comments here or as a external repository?

**Comment by matthewmueller** [comment]
Yes, that would be great! The way I'm thinking about this is a realistic, yet minimal example. Perhaps a signin form where you need to take multiple actions or responding to a github comment that sends out emails.

Just looking to put together some patterns of higher-level models to see where we fall short and provide ideas on how to improve the Client to support these use cases.

**Comment by matthewmueller** [comment]
Hey folks, so I compiled a list of patterns that you can use to extend the Prisma Client. This is a first draft. Please let me know how helpful you find this and if there's anything I should add, change, clarify, etc.

- [Preview URL](https://deploy-preview-2602--prisma2-docs.netlify.app/docs/concepts/components/prisma-client/extend-client)
- [Pull Request](https://github.com/prisma/docs/pull/2602)

**Comment by irvinebroque** [comment]
@matthewmueller - coming from ActiveRecord, I've found myself wrapping prisma in a model that represents the instance of a record. The docs have a good bit on how to wrap the prisma client delegates into a class that gets you some reusable static methods, but might benefit from an example using instances.

Maybe I'm the crazy one, but here's the gist of the pattern I find myself using with Prisma and classes:

``` typescript
import type { Admin as AdminRecord } from "@prisma/client";

import prisma from "../prismaClient";

import Customer from "./Customer";

export default class Admin {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  email: string;
  private customerId: string;

  constructor(record: AdminRecord) {
    this.id = record.id;
    this.createdAt = record.createdAt;
    this.updatedAt = record.updatedAt;
    this.email = record.email;
    this.customerId = record.customerId;
  }

  adminRecord() {
    return prisma.admin.findUnique({ where: { id: this.id } });
  }

  async customer() {
    const response = await prisma.customer.findUnique({
      rejectOnNotFound: true,
      where: { id: this.customerId },
    });
    return new Customer(response);
  }

}
```

``` typescript
import type { Customer as CustomerRecord } from "@prisma/client";

import prisma from "../prismaClient";

import Admin from "./Admin";


export default class Customer {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;

  constructor(record: CustomerRecord) {
    this.id = record.id;
    this.createdAt = record.createdAt;
    this.updatedAt = record.updatedAt;
    this.name = record.name;
  }

  customerRecord() {
    return prisma.customer.findUnique({ where: { id: this.id } });
  }

  async admins() {
    const response = await this.customerRecord().admins();
    return response.map((admin) => new Admin(admin));
  }

  static create(params: {
    name: string;
    email: string;
  }) {
    const { name, email } = params;
    const data = {
      name,
      admins: {
        create: [
          {
            email,
          },
        ],
      },
    };
    return prisma.customer.create({ data });
  }
}
```

There's more boilerplate here than would be ideal (setting many properties in the constructor), challenges optimizing queries that span multiple tables and therefore multiple models, lack of lazy relations, etc. But for now this makes it easy to work with data from the prisma client outside of models. Ex:

``` typescript
// let's say that context is set elsewhere, and it's our starting point for a request:
const admin = context.admin;
const customer = await admin.customer();
const allAdmins = await customer.admins();
```

...which with lazy relations could end up looking very much like ActiveRecord:

``` typescript
const allAdmins = context.admin.customer.admins();
```

(I know this last part on lazy relations is out of scope for this issue, and others have mentioned it in https://github.com/prisma/prisma/issues/1984, https://github.com/prisma/prisma/discussions/3899 and https://github.com/prisma/docs/issues/327, but I think fundamentally an API like this is what people coming from ActiveRecord and similar ORMs are looking for)

**Comment by mmahalwy** [comment]
There's a library called https://github.com/stephenh/joist-ts that I think does a great job of code-generating files and types, similar to Prisma, but has a data mapper / active record feel. cc @stephenh

**Comment by tobiasdiez** [comment]
@matthewmueller what is now the plan given that your PR https://github.com/prisma/docs/pull/2602 has been merged? While the added guides are definitely helpful some of the existing solutions (especially for computed fields) are somewhat suboptimal and don't really scale to more complex examples.

**Comment by mmahalwy** [comment]
Here's a good example or idea:
```ts
const mockUser = {
  firstName: 'John',
  lastName: 'Doe',
  email: 'joe@abc.com',
}

class DbClient {
  schemas: any;

  constructor(schemas) {
    this.schemas = schemas;
  }

  get users() {
    const schemas = this.schemas;
    return {
      findAll() {
        return [mockUser].map(u => Object.assign(schemas.users, u))
      }
    }
  }
}

const userSchema = {
  get fullName() {
    return this.firstName + ' ' + this.lastName
  }
}

const dbClient = new DbClient({
  users: userSchema
})


const users = dbClient.users.findAll()

console.log(users, users[0].fullName)
```

**Comment by matthewmueller** [comment]
@tobiasdiez, would love to learn more about why some of these solutions (especially computed fields) are suboptimal. Do you mind sharing a bit more?

**Comment by matthewmueller** [comment]
We added some new documentation on how to build some of these use cases yourself:

- Custom Validation: https://www.prisma.io/docs/concepts/components/prisma-client/custom-validation
- Computed Fields: https://www.prisma.io/docs/concepts/components/prisma-client/computed-fields
- Excluding Fields: https://www.prisma.io/docs/concepts/components/prisma-client/excluding-fields
- Custom Models: https://www.prisma.io/docs/concepts/components/prisma-client/custom-models

We do plan to implement these features into the Prisma Client eventually, but this is meant to help you along in the meantime. If you'd like to chat about any of these topics or have any questions, feel free [to book some time with me](https://calendly.com/matthewmueller/prisma-extend-client).

**Comment by puchm** [comment]
I have been following this discussion for some time and I would like to contribute my thoughts.

I've been trying to build a Prisma Middleware (using `prisma.$use`) that basically tracks changes to the database. While that is a rather complex topic by itself I found that possibly the hardest thing to do was to handle all of the cases how Prisma could possibly modify something. The possibility of nesting queries introduces a lot of cases that (considering you'd want to do it properly) you all need to cover. While it's probably very much debatable if the project I tried to pull off is in the correct spot in the Prisma Middleware (would probably be better doing this at a lower level). I still think it showed me what Prisma really needs (in my opinion).

What I would love to see would be hooks based on models and operations **that would also get called if the operation is nested**.

E.g. it would be cool if you could do
```ts
prisma.$foo.user.onCreate((data, select, include, next) => {
    // Do something, perhaps modify the data

    const result = next(data, select, include);

    // Possibly modify the result, e.g. adding computed fields
    // select or include could also be used to check if a computed field needs to be computed

    return result
})
```

As with the Prisma Middleware you could perform changes to the data that gets inserted, modify the result or you could even make additional calls to Prisma in the Middleware. The only difference is that you don't need to worry about covering every possible case of the query structure. Additionally, the typings for these hooks could be part of the Prisma client so it would be a lot more type safe than todays `prisma.$use`.

Some other things that would generally help would be:
- custom directives for both models and fields
- finding a good way for hooking into the client generation and migration. There should be a possibility of doing both separately so that you could
    - add custom columns into the database (hidden from the client) that help you compute computed fields
    - add computed fields that don't have an actual column in the database
    - possibly add models

Regarding the second point there should probably also be some predefined directives that make a field either client-only or database-only but I do think it would be best if you could also do this programmatically. This would also allow you to add fields to either all models programmatically or only some of them, e.g. based on the model directives I mentioned before.

I have no idea if any of this is feasible at all. To my understanding, much of the Prisma client is not actually written in Typescript so this could potentially come at a performance cost. Also this is obviously something that would require major work so for now it will remain a fantasy for me.

**Comment by adaddeo** [comment]
My team has been using Prisma for a year now. Our use case is complex and involves many of the use cases mentioned here and then some.

In the JS/TS ecosystem there are multiple strong opinionated ORMs with plugins for just about everything. We specifically use Prisma for its simple API and strong types which lends it well to a functional paradigm.

Documentation on how to compose the Prisma client with other specialized libraries for things such as validation is a great direction. There are some things that could improve the composability of the client. Outside that I'd prefer the core team to keep delivering features specific to managing and interacting with the database than make an ActiveModel style ORM that tries to do it all.

**Comment by tobiasdiez** [comment]
> @tobiasdiez, would love to learn more about why some of these solutions (especially computed fields) are suboptimal. Do you mind sharing a bit more?

Adding helper methods that compute additional fields works well to add one or two fields. But in a more complex project, you end up with a lot of helper methods, that devs have to remember, import separately, etc. It would be nice if one could create a custom model class and then say "Prisma please use this class as the model for users". Something like the following rewrite of the example from https://www.prisma.io/docs/concepts/components/prisma-client/computed-fields:
```ts
import User as PrismaUser from prisma

// Somewhere add a config that prisma automatically wraps all methods normally returning `User` with this class 
class User extends PrismaUser {
    constructor(private user: PrismaUser) {
         // So that methods/properties defined on `PrismaUser` work
         super(user)
   }

    function computeFullName(): string {
         return this.user.firstName + ' ' + this.user.lastName,
    }
}

async function main() {
  const user = await prisma.user.findUnique({ where: 1 })
  user.computeFullName() // This now works, because `findUnique` returns a `User` and not a `PrismaUser`
  user.firstName // Still works
}
```
Currently one can achieve something like this using `Objects.assign` and manually wrapping return values of prisma functions. But this becomes tiresome and complicated.

Alternatively, if prisma would return a class `User` (instead of an object with type `User`), then one could use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to get
```ts

import { User } from "prisma"
declare module "prisma" {
  interface User {
    computeFullName(): string
  }
}
User.prototype.computeFullName = function () {
  return this.user.firstName + ' ' + this.user.lastName,
};

async function main() {
  const user = await prisma.user.findUnique({ where: 1 })
  user.computeFullName() // This now works, because we extended `User` 
  user.firstName // Still works
}
```

**Comment by yasaichi** [comment]
@tobiasdiez 
Your idea is just what I needed before, however, I found out that class-based ORM introduces another problem: type safety.
In an example of [this document](https://www.prisma.io/docs/concepts/components/prisma-client/computed-fields), if you fetch users that don't have `firstName` or `lastName` using the `select` option, you'll get an unexpected result from `computeFullName`. Unfortunately, you can't notice that before running the code.
That's why now I don't think introducing class into Prisma is best to deal with the use cases above.
By the way, if you just want to use the syntax `object.method`, [Bind-this operator](https://github.com/tc39/proposal-bind-this) (currently Stage-1 Proposal) could help you.

```typescript
import { User } from "prisma"

function computeFullName(this: User) {
  return this.firstName + ' ' + this.lastName,
};

async function main() {
  const user = await prisma.user.findUnique({ where: 1 })
  user::computeFullName()
}
```

**Comment by tarazena** [comment]
I'm thinking we should use something like Firebase does when fetching data from their store. In Firsbase we use `withConverter` to cast the result to different instances e.g.
```ts
class Post {
  constructor(readonly title: string, readonly author: string) {}

  toString(): string {
    return this.title + ', by ' + this.author;
  }
}

const postConverter = {
  toFirestore(post: Post): firebase.firestore.DocumentData {
    return {title: post.title, author: post.author};
  },
  fromFirestore(
    snapshot: firebase.firestore.QueryDocumentSnapshot,
    options: firebase.firestore.SnapshotOptions
  ): Post {
    const data = snapshot.data(options)!;
    return new Post(data.title, data.author);
  }
};

const postSnap = await firebase.firestore()
  .collection('posts')
  .withConverter(postConverter)
  .doc().get();
const post = postSnap.data();
if (post !== undefined) {
  post.title; // string
  post.toString(); // Should be defined
  post.someNonExistentProperty; // TS error
}
```

One thing i found out difficult to build is dynamic typing, if we started including different entities in queries, we need a way to use the types more easily rather than building them out manually e.g.
```ts
 const uses = await prisma.user.findUnique({where : { id }, include: { posts: true, comments: true }});
/* 
Prisma here knows that the user type is going to be User & { posts: Post[]; comments: Comment[] } but there is not an exported type by default so we have to build those/
*/

type UserWithCommentsAndPosts = User & { posts: Post[]; comments: Comment[] };

const findPostWithComment (user: UserWithCommentsAndPosts) => ....

```

doc for [FirebaseDataConverter](https://firebase.google.com/docs/reference/node/firebase.firestore.FirestoreDataConverter)

**Comment by mattrabe** [comment]
I'm using the [custom model](https://www.prisma.io/docs/concepts/components/prisma-client/custom-models) approach to add "computed fields" to my prisma models.

In a nutshell I'm "extending" the find & create methods that prisma provides, in order to inject my computed fields. This works, but my biggest complaint is that I was unable to reuse the method names - so I'm not actually *extending* `findUnique()` - I'm providing a *new* method named `find()` that uses `findUnique()` under the hood. Using prisma's `findUnique()` inside of my `findUnique()` appears to create an infinite loop... There's also more boilerplate than I'd love.

I think it would be great if custom classes/methods could be passed to `new PrismaClient()`. That would provide maximum flexibility, while still defaulting to all of the existing prisma functionality if nothing is passed. I do not think prescribing this stuff in the schema file would be a good approach. This could be something like:

```typescript
export default new PrismaClient({
  user: {
    findUnique: (user: User): User => doWhateverToUser(user)
  }
})
```

or:

```typescript
export default new PrismaClient({
  user: {
    beforeFindUnique: (args: Prisma.UserFindUniqueArgs): Prisma.UserFindUniqueArgs => doWhateverToArgs(args)
    afterFindUnique: (user: User): User => doWhateverToUser(user)
  }
})
```

or if just for computed fields:

```typescript
export default new PrismaClient({
  user: {
    computedFields: (user: User): User => applyComputedFieldsToUser(user)
  }
})
```

## Current Use Example:

Currently using this setup in a monorepo.

### `packages/orm`:

`schema.prisma`:

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = [ "native", "rhel-openssl-1.0.x" ]
}

datasource db {
  provider = "mysql"
  url = env("DATABASE_URL")
}

model User {
  id                String          @id @default(uuid())
  email             String          @unique
  password          String?
  firstName         String
  lastName          String
  createdAt         DateTime        @default(now())
  updatedAt         DateTime?       @updatedAt
  deletedAt         DateTime?
}
```

`models/user/types.ts`:

```typescript
import { User as PrismaUser } from '@prisma/client'

export interface User extends PrismaUser {
  name: string,
}
```

`models/user/index.ts`:

```typescript
import {
  Prisma,
  PrismaClient,
  User as PrismaUser,
} from '@prisma/client'

import { User } from './types'

const userModel = (model: PrismaClient['user']) => ({
  add: async (args: Prisma.UserCreateArgs): Promise<User> => {
    const user = await model.create(args)

    return applyComputedFields(model)(user)
  },

  find: async (args: Prisma.UserFindUniqueArgs): Promise<User|undefined> => {
    const user = await model.findUnique({
      ...args,
      include: {
        teams: { include: { team: true } },
        ...args.include,
      },
    })

    if (!user) {
      return undefined
    }

    return applyComputedFields(model)(user)
  },

  get: async (args: Prisma.UserFindManyArgs = {}): Promise<User[]> => {
    const users = await model.findMany({
      ...args,
      include: {
        teams: { include: { team: true } },
        ...args?.include,
      },
    })

    return Promise.all(users.map(applyComputedFields(model)))
  },

  name: (user: PrismaUser): string => `${user.firstName}${(user.firstName && user.lastName && ' ') || ''}${user.lastName}`,
})

const applyComputedFields = (model: PrismaClient['user']) => async (user: PrismaUser): Promise<User> => {
  const self = userModel(model)

  return {
    ...user,
    name: self.name(user),
  }
}

export default (model: PrismaClient['user']) => Object.assign(model, userModel(model))

export * from './types'
```

`index.ts`:

```typescript
import { PrismaClient } from '@prisma/client'

import userModel, { User } from './models/user'

const prisma = new PrismaClient()

const models = {
  user: userModel(prisma.user),
  // ...more models...
}

export default Object.assign(prisma, models)

export const {
  user,
  // ...more models...
} = models

export type {
  User,
  // ...more model types...
}
```

### `packages/app`:

```typescript
import orm, { User } from '@monorepo/orm'

const user: User|undefined = await orm.user.find({ where: { email: 'test@example.com' } })
```

**Comment by ShanonJackson** [comment]
This functionality already exists:
ES6 "Proxy" contains two traps for get/apply, these traps can be combined and wrapped around PrismaClient; Now whenever .findMany etc are called you can compose your own pre and post logic in an easy way.

Agree that maybe it might be better to have this as part of PrismaClient but if it is it should just use ES6 Proxy because then it can be fully implemented without touching the internals.

```
const proxyify = <T extends object>(value: T, table?: string, operation?: string): T => {
	return new Proxy(value, {
		apply: function trap(obj, props, args) {
			if (typeof obj !== 'function') return;
			if (operation) {
				console.log(args, table, operation);
				// pre logic.
			}
			const returned = obj(...args);
			if (returned instanceof Promise) {
				/* post logic feel free to use finally */
				return returned;
			}
			// post logic.
			return proxyify(obj(...args));
		},
		get: function trap<K extends keyof T & string>(obj: T, key: K) {
			const operations = [
				'findMany',
				'findUnique',
				'update',
				'count',
				'upsert',
				'aggregate',
				'aggregateRaw',
				'deleteMany',
				'createMany',
				'create',
				/* ...etc or you can generate this list yourself through various ways. */
			];
			const isOperation = operations.includes(key);
			return proxyify(obj[key] as any, table || key, isOperation ? key : undefined);
		},
	});
};
const client: PrismaClient = proxyify(new PrismaClient());
```
This is a simple example in our internal use we have an API we're written to easily allow pre/post logic by adding another parameter to proxify I.E
```
proxify(new PrismaClient(), {
    user: {pre: () => {/* do something*}, post: () => {/* do something */}},
}
```

**Comment by matthewmueller** [comment]
@ShanonJackson I haven't used ES6 Proxies yet. Is that also type-safe?

**Comment by omar-dulaimi** [comment]
Hey all,

I've built a new Prisma Generator to emit custom models based on Prisma recommendations(as mentioned in the docs).
Currently, you could either `WRAP` or `EXTEND`. More grouping behaviors will be added soon.

Feel free to try it here: https://github.com/omar-dulaimi/prisma-custom-models-generator

**Comment by floelhoeffel** [comment]
Everyone passionate about extending Prisma, please check our new proposal in #15074 by @millsp

**Comment by random42** [comment]
Hi,

My opinion is that extending specific models is not that important, since business specific tasks should be handled one layer above Prisma. But you added it so hurray.

However, extending the base functionality of the client with generic functions is of primary importance to me, for example to have a `findByPrimaryKey` or `findPaginated` functionality. The real problem is that generated types are not extending one generic `Delegate` interface, but every model has its own.

See my [question](https://stackoverflow.com/questions/73714902/prisma-typescript-how-to-extend-client) on StackOverflow that explains the problem.

**Comment by JuanGalilea** [comment]
has someone had any issues with $-methods while using ES6 proxies or even tried them?

I'm getting errors like:
`proxyOfPrismaClient.$disconnect() // $disconnect is not a function`
Even when using very simple or even transparent proxies.

I can't find any info on why this might happen.

**Comment by millsp** [comment]
@random42 we will soon publish and expansion of our guide to show how to do that with client extensions.

@JuanGalilea It is possible that we have a bug there, please create a new issue and provide us with a repro.

Thanks.

**Comment by millsp** [comment]
We're closing this issue as the points from the OP have been implemented in Client Extensions. If something is still missing for you, please open a feature request, a bug report, or a discussion. Thanks.
