### ISSUE TITLE
Support MySQL Prefix Index ("Partial Index", string index with length)

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/prisma#7263]
### Bug description

Hello,

I have noticed that unique constraints don't get introspected, and if manually added, they vanish at consecutive re-introspections.

### How to reproduce

Have a MySQL table that looks like this:

```

CREATE TABLE Item {
  `categoryId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   UNIQUE KEY `categoryId_UNIQUE` (`categoryId`(191)),
}
```

run introspection.

### Expected behavior

It should introspect the unique constraints normally. It should not remove them once introspection is run again.

### Prisma information

```
model Item {
 categoryId    String?    @db.VarChar(255);
}
```

### Environment & setup

- OS: Ubuntu v18.04
- Database: MySQL 5.7
- Node.js version: v14.15.1

### Prisma Version

```
prisma               : 2.19.0
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.358.0

```

**Comment by pantharshit00** [comment]
Looks like we don't support unique keys right now with introspect and only unique indexes. I am going to mark this as a bug for now for team to decide if this was a miss or this is a bug.

**Comment by janpio** [comment]
This is a "prefix index" (string field with length) in MySQL (Documentation at https://dev.mysql.com/doc/refman/8.0/en/create-index.html, headline "Column Prefix Key Parts
" or https://www.mysqltutorial.org/mysql-index/mysql-prefix-index/) that we unfortunately do not support in Introspection and Migration yet.

From the documentation it seems that you could in theory update your database to _not_ have that length on the unique index any more, then Prisma should just pick that up. Can you try that maybe?

Otherwise unfortunately the only workaround is to add the `@unique` to the field manually right now and make sure it stays after each future Introspection.

**Comment by do4gr** [comment]
We've just released a proposal to add support for this in the PSL. Please chime in here: https://github.com/prisma/prisma/issues/9577

**Comment by do4gr** [comment]
Since 3.5 we now offer the ability to introspect and migrate length limited indexes using the `extendedIndexes` preview flag. Can you please try it out?

**Comment by janpio** [comment]
(If you are looking for partial or filtered or conditional unique indexes or constraints, this is the right issue: https://github.com/prisma/prisma/issues/6974)
