### ISSUE TITLE
@calculated attribute feature request

### ISSUE THREAD

**Issue by Tismas** [prisma/prisma#729]
I couldn't find an elegant solution to this problem so:

It would nice to have an attribute that makes field change value every time some other fields are changed. For example:
```
model Post {
    reviews: Review[]
    rating: Number @average(reviews.rating, 0)
}
```
or
```
model Post {
    reviews: Review[]
    rating: Number @calculated(reviews.rating / reviews.length, 0)
}
```

Where 0 is the default value.

**Comment by pantharshit00** [comment]
Hi, 

I would use an aggregation here to calculate the rating. 

If you rather want to your database to manage the value rather than your application this, SQL views should solve your problems: https://github.com/prisma/specs/pull/248


cc @matthewmueller thoughts?

Introduction of this directive would not work for every case and databases already solve this custom computation via aggregations so I think implementing such directive will not be feasible. Here is the spec for photon aggregations: https://github.com/prisma/specs/tree/master/photonjs#aggregations

Bear in mind that many of the features I am talking about are yet to be implemented.

**Comment by Tismas** [comment]
I rather thought about the use case for huge data sets that are additionally often read and hardly ever modified. Correct me if I'm wrong but in this case aggregation or SQL views are not ideal. Instead, it'd nice to have a cached field that is modified every time some other field changes. Something like `@AfterUpdate` in typeORM but "sweeter".

**Comment by matthewmueller** [comment]
Thanks for reaching out! That's a super interesting use case. 

Echoing @pantharshit00, I also think this makes more sense on a photon level, because while `@calculated(reviews.rating / reviews.length, 0)` looks nice, it can get a lot more complicated than that 😅

We've also thought about these lifecycle hooks like `@AfterUpdate`. Nothing concrete yet, but definitely on our radar.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/3394
