### ISSUE TITLE
JSON connector 

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#731]
For simple apps and demos a JSON file can serve as a great database with the big benefit of being **transparent** (aka you can simply edit the file via your editor).

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
