### ISSUE TITLE
The Query Engine will choke the Node.js event loop with logs, if having lots of traffic.

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#7318]
### Bug description

The Node.js event loop is one thread, and the Query Engine is as many threads as you have logical cores. This means if we run lots of parallel queries, and we also log all of them, the 32 threads you have in Query Engine will spam the single-threaded JavaScript event loop.

This leads to:

- Using all the memory.
- Preventing the JavaScript event loop from serving any requests.

We can fix this by not logging in the client at all. The client should tell the Query Engine what needs to be logged, and how the logs should be formatted. We then just utilize the facilities of Tracing, directly writing to stdout/stderr.

### How to reproduce

- Get a fast server/workstation
- Enable query logging
- Execute a single query as fast as you can
- Observe results in RSS growth and event loop getting slower.

### Expected behavior

Logging should not have any effect on RSS or system perfomance.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
