### ISSUE TITLE
Database version setting to the PSL

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#7432]
Database versions have different features which we sometimes cannot support for backwards compatibility. For example, PostgreSQL 10 has `IDENTITY`, which is a recommended way to implement auto-incremented columns. To be compatible with PostgreSQL 9, we use the older `SERIAL` even if the user never uses that version anywhere.

We could define in our datasource a new version column:

```prisma
datasource pg {
  provider = "postgres"
  url = "postgres://..."
  minimumVersion = "10"
}
```

This would then give an error if trying to migrate a version older than the minimum version.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
