### ISSUE TITLE
Improve logging around env var loading / dotenv in CLI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7438]
From a user logfile:

```
Running Prisma CLI:
yarn prisma migrate reset --force --schema "/home/.../Projects/.../api/db/schema.prisma" 
2021-06-01T17:56:00.450Z prisma:loadEnv project root found at /home/tharshan/Projects/uservitals/api/package.json
2021-06-01T17:56:00.462Z prisma:tryLoadEnv Environment variables not found at null
2021-06-01T17:56:00.463Z prisma:tryLoadEnv Environment variables not found at undefined
2021-06-01T17:56:00.463Z prisma:tryLoadEnv No Environment variables loaded
```

Context: https://github.com/prisma/prisma/blob/caca0e71233c895ef60aa9ce1bc7598a36537f87/src/packages/sdk/src/utils/tryLoadEnvs.ts#L31
Internal Discussion: https://prisma-company.slack.com/archives/CSP5ZBE0Y/p1622570299011000

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
