### ISSUE TITLE
Connection parameters 'sslaccept=accept_invalid_cert' is not working

### ISSUE THREAD

**Issue by devalnor** [prisma/prisma#7479]
### Bug description

Hi,

Digital Ocean databases use unsigned SSL certificate with SSL required only.
The connection parameters 'sslaccept=accept_invalid_cert' is not working 

```
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

### How to reproduce

Create a Digital Ocean postgress database

### Prisma information

N/C

### Environment & setup

- OS: OSX 10.13.6
- Database: PostgreSQL
- Node.js version: 

### Prisma Version

```
"@prisma/client": "^2.24.1",
"prisma": "^2.24.1",
```

**Comment by devalnor** [comment]
Same issue with another heroku PostgreSql on public network "?sslmode=require&sslaccept=accept_invalid_certs" did nothing

**Comment by pantharshit00** [comment]
Hello, 
I am unable to reproduce this. Also, can you make sure these error are coming from Prisma not something else that you use in your app. 

I am asking because we do the TLS communication in Rust in Prisma while the stacktrace suggest a javascript TLS library is being used. 

Also, try again with the latest Prisma version once.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
