### ISSUE TITLE
Better overview page for cluster root route

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#752]
When running a development cluster, the root route (e.g. `http://localhost:60000/`) should have a good overview page containing the following information:

* Link to docs
* Cluster health information
* Spinner if system is loading
* Cluster version
* List of deployed services including API endpoints
* If no services deployed, print command how to deploy first service

**Comment by sorenbs** [comment]
Is this page protected by the masterToken?

**Comment by schickling** [comment]
Good question. My suggestion is, since this page is just intended for the development cluster it doesn't need be. It should however just be accessible via `localhost` and not via `0.0.0.0`.

Any other thoughts on this?

**Comment by kbrandwijk** [comment]
Please do not implement that last part (localhost only). A lot of people work with cloud IDE's nowadays, and having a 'localhost' restriction seriously impacts this. Other question: if this development docker already available?

**Comment by sorenbs** [comment]
@kbrandwijk Is it possible to run a docker container inside cloud9?

**Comment by kbrandwijk** [comment]
@sorenbs That depends on the configuration. With a hosted workspace, you can't. With a SSH workspace, you can. Also, Cloud9 is not the only virtualization solution. You can also use VM's locally, run your own development environment in Docker locally, use a SSH workspace locally, etc. The point is that people use all kinds of configurations, and any software that restricts access to localhost only doesn't play well with it.

**Comment by marktani** [comment]
I created a separate proposal/feature request: https://github.com/graphcool/graphcool/issues/787 please chime in there about the port bindings.

**Comment by rwatts3** [comment]
@schickling 
also restricting to localhost completely breaks the service when using Docker Toolbox. On my work pc we have windows 7  docker for mac or docker for windows is not available to windows 7 , therefore having to use docker toolbox which uses virtualbox under the hood is my current workflow at work. 

I have tested the @next tag in docker for mac and things work flawlessly. However the behavior and workflow is not the same in fact I have yet to deploy to my local cluster on my windows 7 machine due to the localhost issue. 

Two things to note, I noticed with the last push the 0.7.0 version of the cli handles the port issue within the docker setup, however the application itself is still looking at localhost. So that solves one of the problems, but since the application is looking at localhost, the authentication process is just a loop and never actually deploy your local files to the local cluster.
