### ISSUE TITLE
Better indent migrate warnings and errors

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#7594]
## Problem

Migrate warnings and errors formatted in lists have no indentation after the first line.

![unexecutable_migrations_alignment](https://user-images.githubusercontent.com/13155277/121642193-79a6ad80-ca90-11eb-87ec-856cca548be2.png)

## Suggested solution

Format these messages with indentation after the first line:

```
- Lorem ipsum dolor sit amet consectetur adipiscing elit, urna consequat felis
  vehicula class ultricies mollis dictumst, aenean non a in donec nulla.
- Phasellus ante pellentesque erat cum risus consequat imperdiet aliquam,
  integer placerat et turpis mi eros nec lobortis taciti, vehicula nisl litora tellus
  ligula porttitor metus. 
```

The wrap width would need to be based on the terminal width.

## Alternatives

Leave things as they are.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
