### ISSUE TITLE
Snapshot tests for log output of app using Prisma

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7605]
The Node-API work introduces some fundamental changes how Prisma works under the hood. For the users of course this should not change _any_ behavior if possible. One of the way to measure and confirm that, would be to snapshot the log output of a small application using Prisma Client and snapshot that (after sanitizing variable values like time measurements (`52ms`), timestamps and so on).

We should add a test to our test suite that does this. Then we can run it for the current binary, and the Node-API library and see the differences and make sure they are minimal (or learn we have a problem).

**Comment by janpio** [comment]
Unblocked by https://github.com/prisma/prisma/issues/9039

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
