### ISSUE TITLE
Run (most) tests on all operating system

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7725]
We should enable the `prisma/prisma` tests for all operating systems. Currently this is not possible, as the tests use databases that are started via Docker: https://github.com/prisma/prisma/pull/7721 (GH Actions can not run Linux containers on Windows, and the MacOS runners do not have Docker installed by default).

A possible solution could be to use `services` in our GH Actions setup again: https://docs.github.com/en/actions/guides/creating-postgresql-service-containers

**Comment by janpio** [comment]
3 phases:

1. Build a CI pipeline that can run on Windows and MacOS
2. Learn and understand what tests are failing
3. Fix the failing tests

**Comment by matthewmueller** [comment]
So do prisma/prisma CI tests only run on linux right now?

**Comment by janpio** [comment]
Yes, both on Buildkite and GH Actions.

**Comment by Jolg42** [comment]
We have some e2e tests running on Windows, macOS and Linux like https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml#L328-L334 but indeed the full test suite of prisma/prisma is only running on Linux mainly because of  Docker only being available for Linux and it's needed to setup our databases in a short amount of time.

**Comment by aqrln** [comment]
Adding some links for later (will add more if I come across anything useful)

* https://github.com/Homebrew/actions
* https://github.com/MinoruSekine/setup-scoop
* https://github.com/prisma/prisma-engines/blob/13f3d226498ac5671ef0f3ad466a9529a64778e6/.github/workflows/migration-engine.yml#L224-L229
