### ISSUE TITLE
Add `Prisma` namespace to ungenerated Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7844]
Right now we only export `PrismaClient` from the ungenerated Client, but we added the `Prisma` namespace that some people import as well - and that is now missing:

![image](https://user-images.githubusercontent.com/183673/123278767-82bf6200-d507-11eb-8179-b771ddb8b981.png)

TODO:
- Add `Prisma` export to `index.js` and `index.d.ts`
- Add JSDoc to that
- Also see if we can throw an error if you try to use this

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
