### ISSUE TITLE
Custom generators: Clean up `version` 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7862]
As we discovered during some code review, there is some really old code in the generator logic that uses the `version` from `onManifest` in a way that can not work - for a long time.

At the same time this `version` is used for useful things by custom generators:
https://github.com/maoosi/prisma-appsync/pull/19#issuecomment-868122251

So we should clean that up.

Context:
- https://github.com/prisma/prisma/blob/master/src/packages/sdk/src/versions.ts
- https://github.com/prisma/prisma/blob/808707bc3dcc3248ef37d670066aae80e7778840/src/packages/sdk/src/getGenerators.ts#L731-L733
(Possibly these 3 lines can just be removed and then it is clean enough.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
