### ISSUE TITLE
Warn when 2 generators write to the same location

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7867]
This schema leads to the generators overwriting each other:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

generator clientNodeApi {
  provider        = "prisma-client-js"
  previewFeatures = ["nApi"]
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

like this:

````
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (2.26.0-dev.38) to .\node_modules\@prisma\client in 95ms

✔ Generated Prisma Client (2.26.0-dev.38) to .\node_modules\@prisma\client in 107ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
````

We should warn that the user should use `output` on one or both of the generators, or possibly even fail the `generate` call.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
