### ISSUE TITLE
`The PrismaClient you are running does not reflect your current 'schema.prisma' file`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7971]
On of the worst experiences is when you change your schema, e.g. modifying a model, changing the datasource `url`  or adding a preview feature flag, then running your script again and nothing changes. Which is logical, as you forgot to `npx prisma generate` in between to actually regenerate your Client!

It would be amazing if we could detect these cases and output an error message like this:
```
The PrismaClient you are running does not reflect your current 'schema.prisma' file.
```

Potential solutions that come to mind would be to check if the schema file is newer than the schema file in the generated Client, if the file content (via checksum) has changed vs. the generated Client or similar.

If you are running the Prisma VSCode extension that could also track modifications to `schema.prisma` and know if you ran `prisma generate` since then (by also watching the file or file content).

Difficult is how to figure out a way to do this without influencing and impacting production usage of Prisma Client where there _is_ no project schema file that could be changed but just the generated Client, or a static schema file in the `prisma` folder.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
