### ISSUE TITLE
Test snapshot files have very very long indentation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8031]
https://github.com/prisma/prisma/blob/30773b7ca34f104b2dc50581cf5e1046cbd27bf1/src/packages/migrate/src/__tests__/DbSeed.test.ts#L78-L79
https://github.com/prisma/prisma/blob/30773b7ca34f104b2dc50581cf5e1046cbd27bf1/src/packages/migrate/src/__tests__/DbSeed.test.ts#L95-L96

Something is wrong there.

**Comment by Jolg42** [comment]
We could check the source code of Jest to get an idea of what's happening.

It's nothing blocking though. A bit annoying to have to scroll.

**Comment by janpio** [comment]
This is also happening in other snapshots: https://github.com/prisma/prisma/pull/13190/files/6b0a6925ef9dfd79467f7446c2a550f81b1de6bf#r865887332

**Comment by Jolg42** [comment]
I tried to find out more about jest inline snapshots diff being always updated while I needed to work on `db pull` tests.

Current behavior: inline snapshots get indented to the right unexpectedly when running with `-u`

After testing, it looks like it only happens when we use `packages/get-platform/src/test-utils/jestSnapshotSerializer.js`
When running jest with `-u` the expected value by Jest and returned value from the serializer don't match, which triggers an update.
If nothing changed then the indentation stays the same.
But if a snapshot was added / modified all the rest gets indented.

Note: this only affects multi-line text inline snapshots

One thing we can do for now for limiting this issue is splitting the massive test file in smaller ones: https://github.com/prisma/prisma/pull/19205
And second, only use `jestSnapshotSerializer` when needed with https://jestjs.io/docs/expect#expectaddsnapshotserializerserializer
```
import serializer from 'my-serializer-module';
expect.addSnapshotSerializer(serializer);
```

**Comment by Jolg42** [comment]
Note: this a regex that I used on VS Code at some point to replace all multi-line snapshots `(toMatchInlineSnapshot\(`)\n([\s\S\n]+?)(`\))$` and replace with `toMatchInlineSnapshot()` so I could try recreating them all from scratch.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
