### ISSUE TITLE
Select column using an alias for output prisma orm

### ISSUE THREAD

**Issue by FluxusGaming** [prisma/prisma#8104]
## Problem

Select column using an alias for output prisma orm

**Comment by pantharshit00** [comment]
Can you please give an example of what you are trying to describe?

**Comment by NU11B0T** [comment]
How can we define an alias in a select query?
`SELECT column_name AS alias_name FROM table_name;`

**Comment by pantharshit00** [comment]
You can alias your result in your code:
```ts
  const { column_name: alias_name } = await prisma.test.findMany();
```

Can you please tell me why you need SQL level aliasing in Prisma?

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/8151

**Comment by TalbertH** [comment]
**For my case, we have an a lot of relations on one "item" table.** 

<img width="1503" alt="Screen Shot 2022-07-13 at 2 53 46 PM (2)" src="https://user-images.githubusercontent.com/104466295/178843423-ad607b1a-0e26-46d4-b5ef-c3b31000e374.png">

For example colorFinish, paintType, sheenType these tables all have [id , name , createdAt, updatedAt]columns . In the Item table these are related by an id. 

So instead of get the ids I want the name to return in one call just the name of these types instead of the id, let alone the full Object. 

**In knex I did something like this:**

  _let filterItems = knex.queryBuilder().from("items")
            .select([
                "items.*",
                "sheenTypes.name AS sheenType",
                "paintTypes.name AS paintType",
                "materialTypes.name AS materialType",
                "carpetTypes.name AS carpetType",
                "colorFinishes.name AS colorFinish",
                "speciesTypes.name AS speciesType",
                "constructionTypes.name AS constructionType",
                "vinylFloorTypes.name AS vinylFloorType"
            ])
            .leftOuterJoin('sheenTypes', 'items.sheenTypeId', '=', 'sheenTypes.id')
            .leftOuterJoin('paintTypes', 'items.paintTypeId', '=', 'paintTypes.id')
            .leftOuterJoin('materialTypes', 'items.materialTypeId', '=', 'materialTypes.id')
            .leftOuterJoin('carpetTypes', 'items.carpetTypeId', '=', 'carpetTypes.id')
            .leftOuterJoin('colorFinishes', 'items.colorFinishId', '=', 'colorFinishes.id')
            .leftOuterJoin('speciesTypes', 'items.speciesTypeId', '=', 'speciesTypes.id')
            .leftOuterJoin('constructionTypes', 'items.constructionTypeId', '=', 'constructionTypes.id')
            .leftOuterJoin('vinylFloorTypes', 'items.vinylFloorTypeId', '=', 'vinylFloorTypes.id')
            .then((res) => {
                console.log(res)
                return res
            }).catch(e => { console._log(e) })

So on the leftOuterJoin I only return the name of the types so when returned I get a more organized call.

Is this possible to do in prisma?

**Comment by janpio** [comment]
Please turn that into a GitHub discussion, here in a closed issue no one should reply to such a question. Thanks.
