### ISSUE TITLE
Improve error messages in schema validation on unknown argument

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#8120]
## Problem

When you write an attribute in the prisma schema and add an argument that isn't known to prisma, the error is just "No such argument".

## Suggested solution

A better error message with more context, and maybe a list of accepted arguments.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
