### ISSUE TITLE
`deleteMany` optimisation

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#8239]
## Problem

Currently `deleteMany` fetches the rows to be deleted and then deletes the rows that results in two queries. Probably this was implemented due to cascade deletes not working.

## Suggested solution

`deleteMany` should use only a single query that deletes the specified items.

## Additional context

Related discussion: https://github.com/prisma/prisma/discussions/8211

**Comment by ecker00** [comment]
Any updates on this? Notice that it's rather slow to end up running a raw query instead.

**Comment by baptisteArno** [comment]
Is there already someone working on this? I'd be willing to contribute! Or would it be too complicated?

**Comment by tbell511** [comment]
Are there any updates on this?

**Comment by Jacse** [comment]
This is a crazy way to implement a delete with a filter. If I want to delete a lot of rows, it will run out of memory and crash. Why would the client want to fetch all that data to only pick the ids and run a query that could as easily have been run directly with the where clauses?

**Comment by njpearman** [comment]
+1 on the Prisma team addressing this ASAP. Our app had OOMs and timeouts for very large batch deletes because Prisma hauls back all of the rows that need to be deleted to then use in an `IN` clause when it just needs a filtered `DELETE` command. I have to say the current approach is a bonkers bad way of doing a filtered `DELETE` for any large amount of data. In the mean time, we're using `prisma.$executeRaw`.

**Comment by Jolg42** [comment]
The optimization is now available since `5.4.0`, for more details check out the bottom part of the release notes:
https://github.com/prisma/prisma/releases/tag/5.4.0
<img width="948" alt="Screenshot 2023-10-09 at 10 33 07" src="https://github.com/prisma/prisma/assets/1328733/15e56e79-c9fc-4aec-a3a2-adf107ad561c">
