### ISSUE TITLE
Improve error message "`"Error validating: Many to many relations must always reference the id field of the  related model. Change the argument `references` to use the id field of the related model  `BanHistory`. But it is referencing the following fields that are not the id: uuid"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8267]
In this issue an error message popped up:

> Error: Schema parsing
> error: Error validating: Many to many relations must always reference the id field of the
 related model. Change the argument `references` to use the id field of the related model
 `BanHistory`. But it is referencing the following fields that are not the id: uuid

https://github.com/prisma/prisma/issues/8243#issuecomment-879223806

I think the use of "id field" in the error message might be a bit misleading, especially if the user data model actually has a field `id`.

Does this refer to the `@id` field / primary key? Do we have this in more places?

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
