### ISSUE TITLE
Enable raw query support in MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8270]
## Problem

Currently we offer a subset of the query functionality available to MongoDB users. 

This would give us an escape hatch for users that want to use more advanced features like [$lookup in the aggregation pipeline](https://github.com/prisma/prisma/issues/6712).

## Suggested solution

We offer the [$queryRaw](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access) API for SQL users. I think we could extend that interface for MongoDB.

The generated API would need to change slightly since MongoDB works with JSON objects, not strings. Perhaps something like:

```diff
- prisma.$queryRaw(`...`)
+ prisma.$queryRaw({ ... })
```

## References

- [Internal Discussion](https://prisma-company.slack.com/archives/C0239SYUZV1/p1627481856003300?thread_ts=1627480443.003200&cid=C0239SYUZV1)

**Comment by sakulstra** [comment]
Would it be possible to just expose access to the underlying  mongoClient, `prisma.nativeClient` so i got access & typing for `distinct`, `aggregate` and so on as an escape hatch? `$queryRaw` might be a little limiting in case you want to o other things then query right?

Currently working around this by initializing an additional client on startup.

**Comment by janpio** [comment]
Such a "underlying mongoClient" does technically not exist as Prisma Client sends its queries to a Prisma Query Engine, that executes the queries generated by Prisma Client (or the "raw query"). The Query Engine does not live in JavaScript/TS land with the typings you might expect.

**Comment by jzzfs** [comment]
@sakulstra I agree that exposing the `nativeClient` would help. As [discussed here](https://github.com/prisma/prisma/discussions/8452#discussion-3478531), I was struggling with [`Json` filters](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#json-filters) queries (TL;DR they're not supported for mongodb atm. The only option is to init another, non-prisma, mongodb client).

@janpio my 2 cents, if I may -- I reckon exposing the `nativeClient` would kill two birds with one stone:

- **it'd add support for various db-client-specific operations** (e.g. aggs in SQL and NoSQL DBs are not that easily generalizable and so every eager user would be allowed to handle those on their own)
- and, more importantly, **it'd help prisma users go around the not-yet-implemented features / feature requests** without having to resort to a supplementary DB client and dealing with connection pool handling etc.

**Comment by janpio** [comment]
The problem is that there _is_ nothing like a `nativeClient` in Javascript world in Prisma Client. So this is unfortunately just not possible with Prisma's architecture.

Your request is still welcome of course, and we will take into consideration how we can improve this situation. Raw query support for MongoDB is definitely interesting and will be considered when we have the capacity.

**Comment by dannysofftie** [comment]
The idea of exposing the `nativeClient` as suggested by @sakulstra sounds great, but since there is nothing like a `nativeClient` in Javascript world in Prisma Client, I think this where TypeScript can come in handy.

The `$queryRaw` would have type definitions for all operations the underlying Prisma engine can handle, creating a native and raw feeling without exposing any `nativeClient` as there is none.
