### ISSUE TITLE
NestJS: Generator for DTOs

### ISSUE THREAD

**Issue by KevinDennyII** [prisma/prisma#8334]
> Can Prisma generate types for swagger with swagger attribute for each field?

We are experiencing the same issue.

Prisma generated the following for us:
```
export type PersonSocialMediaUncheckedCreateInput = {
    person_social_media_id?: string
    person_id: string
    social_media_name?: string | null
    social_media_type_id: string
    is_active?: boolean
    data_source_id: string
    created_date?: Date | string
    updated_date?: Date | string
    created_by_user_id: string
    updated_by_user_id: string
    org_id: string
  }
```

Our controller looks like this:
```
import { Body, Controller, Param, Post, Request } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import { CreatePersonSocialMediaDto } from '../dto/create-person-social-media.dto';
import { PersonSocialMediaServicePrisma } from '../services/person-social-media-prisma.service';

@ApiTags('people/{personId}/social-media-prisma')
@Controller('people')
export class PersonSocialMediaControllerPrisma {
  constructor(private readonly personSocialMediaService: PersonSocialMediaServicePrisma) {}

  @Post(':personId/social-media-prisma')
  @ApiOperation({ summary: 'Adds a new social media record' })
  createSocialMedia(
    @Request() req,
    @Param('personId') personId: string,
    @Body() createPersonSocialMediaDto: CreatePersonSocialMediaDto
  ) {
    return this.personSocialMediaService.createSocialMedia(personId, req.body, req.user.authDetails);
  }

 
}
```

Our service looks like this:
```
import { AuthDetails } from '@civitech/shared/util-models';
import { Injectable, Logger } from '@nestjs/common';
import { PersonSocialMedia } from '@prisma/client';
import { PrismaService } from '../../../../../prisma.service';

const logger = new Logger();

@Injectable()
export class PersonSocialMediaServicePrisma {
  constructor(
    private prisma: PrismaService
  ) {}

  async createSocialMedia(
    personId: string,
    personSocialMediaRequest,
    authDetails: AuthDetails
  ): Promise<PersonSocialMedia> {
    personSocialMediaRequest.person_id = personId;
    const { userId, orgId, dataSourceId } = authDetails;
    const details = {
      org_id: orgId,
      data_source_id: dataSourceId,
      created_by_user_id: userId,
      updated_by_user_id: userId,
    };

    const data = { ...personSocialMediaRequest, ...details };
    try {
      return await this.prisma.personSocialMedia.create({ data });
    } catch (error) {
      logger.error(`Unable to create person social media record`);
      throw error;
    }
  }

}
```

We are using NestJS.  In reading that the generated files should replace the additional DTO files you would created with TypeORM, Swagger does not seems to recognize the Prisma generated type as it would the additional DTO files.

Definitely an issues that needs to be looked at here

_Originally posted by @KevinDennyII in https://github.com/prisma/prisma/discussions/4651#discussioncomment-1017147_

**Comment by KevinDennyII** [comment]
But the documentation set forth in NestJS says that this should be sufficient in replacing our dto files

"Notice how you're using Prisma Client's generated types to ensure that the methods that are exposed by your service are properly typed. You therefore save the boilerplate of typing your models and creating additional interface or DTO files."
Reference: https://docs.nestjs.com/recipes/prisma#use-prisma-client-in-your-nestjs-services

**Comment by pantharshit00** [comment]
Can you share a minimal reproduction? The information provided has missing parts like the service code so please share a minimal reproduction in a small git repository so that we can have a proper look here.

**Comment by Saeid-Za** [comment]
Correct me if i'm wrong but for swagger generation to work properly, we should decorate each field of our Model Class with `@ApiProperty`.
But the problem here is that there is no class generated by prisma, only typescript `types` which as you know, exist at compile time only.
The quote you mentioned is indicating that you wouldn't need any interfaces to type your services, but if you need any validation (by using `class-validator` decorators for example) or code generation (swagger or grapghql decorators) you'll need to define your own dto claases.

**Comment by pantharshit00** [comment]
I don't have any experience with swagger + nestjs but @KevinDennyII should be able to verify.

**Comment by KevinDennyII** [comment]
@Saeid-Za that is correct, we have this decorator at the top of our controller.

**Comment by KevinDennyII** [comment]
> Can you share a minimal reproduction? The information provided has missing parts like the service code so please share a minimal reproduction in a small git repository so that we can have a proper look here.

@pantharshit00 I did not put our code in a git repository but I did update my original comment with all the code involved.  Will this suffice?

**Comment by ahmednawaz10p** [comment]
looking for a solution to same problem https://stackoverflow.com/questions/68773041/use-prisma-generated-types-with-swagger-nestjs

**Comment by kompetenzlandkarte** [comment]
As of it now nestjs just provides types but no classes. If you use `select` you potentionally modify the reponse type. So I create my types manually and use the `implements` keyword.

**Comment by g-thinh** [comment]
I believe you can generate classes using this [package](https://www.npmjs.com/package/@vegardit/prisma-generator-nestjs-dto), the resulting classes can then be used with the decorator.

**Comment by DaichiShirakawa** [comment]
I really want feature that prisma models to generate NestJS DTOs.
`@nestjs/swagger` requires DTOs for export correct swagger...

**Comment by pingustar** [comment]
+1

**Comment by janpio** [comment]
We are still missing a minimal reproduction to be able to look into this deeper: https://github.com/prisma/prisma/issues/8334#issuecomment-882106109

**Comment by omidh28** [comment]
+1

**Comment by omidh28** [comment]
> I believe you can generate classes using this [package](https://www.npmjs.com/package/@vegardit/prisma-generator-nestjs-dto), the resulting classes can then be used with the decorator.

Does not fix return type declaration

**Comment by Saeid-Za** [comment]
Returning to this issue after serveral months, I think generating `classes` instead of Compile-Time only `types`, is not in scope of prisma.
- why generate a bunch of runtime classes when prisma itself is not taking advantage of, so i humbly think that this is a userlan feature.
- furthermore, if Prisma would generate classes, there is no way of applying per field validators like `@IsEmail` or even more common ones like `@IsOptional`, so it would be pointless for prisma to generate classes that we, as developers can't decorate.
- As a final reason, following 3-layer architecture, data layer interfaces (types that prisma generates), should be seperated from Controller level types (DTOs in nestjs context), not only to follow conventions, but reach better flexebility in your code. I, have worked in several backend projects that utilize nestjs with prisma, in most cases, there are seperated types/classes for each layer (controller, service and data). I can share the baseline If that would help.

You can always use the mentioned library, to generate your base classes, then customize it yourself to your needs, in conclusion I think this issue could be closed.

**Comment by janpio** [comment]
We at Prisma honestly still do not really understand the underlying problem here. We do not know much about Nestjs, we have 2 custom community generators listed at https://www.prisma.io/docs/concepts/components/prisma-schema/generators#community-generators (https://github.com/vegardit/prisma-generator-nestjs-dto and https://github.com/unlight/prisma-nestjs-graphql) but it seems those might not be solving the original request here? 

Please help us out understand!

**Comment by jonasschultheiss** [comment]
the vegardit generator is honestly not usable. you validate user input in nestjs with class-validator decorators, which this generator doesn't support. you also can't add them yourself, as the generation just overwrites these files.
i can't speak about the graphql one, as i haven't used graphql yet.

My current task in my company is to move all entities and dto's to an npm package, which made me come in contact with these "missing features" again.

If I have time this weekend and don't forget it, i'll create a minimal reproduction.

**Comment by janpio** [comment]
These are community generators, so they might just wait for someone to raise these issues with them and/or optimally send a Pull Request with the functionality.

**Comment by jonasschultheiss** [comment]
please look at this. the company that maintains this package has moved on from prisma and it doesn't look like the're going to add this.

https://github.com/vegardit/prisma-generator-nestjs-dto/issues/23

**Comment by janpio** [comment]
Then someone should take ownership of it by doing a fork and working on it themselves. As @Saeid-Za said, this is far outside of what Prisma can offer you right now. We have more than enough work improving Prisma itself. We can only offer you the tools to build something like this for yourself, which the community generator system achieves.

**Comment by jonasschultheiss** [comment]
yeah, i thought i'd be too much to ask from prisma.
i'm quite happy with the way we've achieved it in our package. can i help by providing nest exclusive documentation?

**Comment by janpio** [comment]
Absolutely! Maybe start by writing a long comment here, and if others agree this can totally be turned into official documentation over time.

**Comment by mubaidr** [comment]
Is there any possibility to make sure the custom classes are always matching with `Prisma` types?

1. Add model-A to `Prisma` schema
2. Generate types for Model-A (`prisma generate`)
3. Add classes (Class Model-A) to projects (that would be same properties as type `Model-A`)
4. Update prisma schema to add/remove properties to Model-A
5. Class added in step will be wrong typed or better say obsolete related to Prisma types, there is no way to find that out. Project will compile fine. 

This defies the concept that Prisma being the single source of truth for all data/ types in the project. 

Can we have something like interface for the types in Prisma client:

```ts
Class ModelA implements interface Prisma.ModelAInterface{
 **// this implementation will make sure that class has all properties that of ModelAInterface**
}

```

Currently we can do:
```ts
Class ModelA implements Prisma.ModelA{
 **// this implementation does not guarantee anything**
}
```

**Comment by amrtgaber** [comment]
@janpio I pushed up an example that hopeully can help you understand the issue. Here is a link to the specific line of code that is affected.

https://github.com/amrtgaber/nestjs-api-tutorial/blob/main/src/bookmark/bookmark.controller.ts#L26

Swagger's decorator @ApiCreatedResponse accepts a type but its looking for something that exists at runtime (like a class) so the prisma types don't work because they only exist at compiletime. If you clone the project and check the line linked above you'll see this error `'Bookmark' only refers to a type, but is being used as a value here.`.

It might be out of scope but if prisma had a feature to turn on classes instead of types, or to generate class files that match the types, that would be super helpful. I'll also go check if swagger could potentially work on a solution as well.

Thanks for taking a look.

**Comment by amrtgaber** [comment]
Also, for what it's worth and for anyone else looking for best practices, I found an approach in the prisma docs for how to solve this problem. It requires creating an entity that copies from the type. This is ok but would be nice if there was an option for the entity to be created automatically.

https://www.prisma.io/blog/nestjs-prisma-rest-api-7D056s1BmOL0#update-swagger-response-types

**Comment by linxiaowu66** [comment]
is it possible the prisma type file can generate to the swagger dto file ?

**Comment by jd4u** [comment]
> 

If the prisma-client-js generator provide a switch to the swagger notations, it will be reliable compared to any community generator.

**Comment by moh1434** [comment]
You can use [tsoa](https://www.npmjs.com/package/tsoa) with nest to generate swagger from prisma results.
See this example [https://github.com/moh1434/nest-tsoa-exampe](https://github.com/moh1434/nest-tsoa-exampe)

**Comment by axuu** [comment]
As its 2023, you can use generators from the community to generate classes that can be used for Swagger. For example `[prisma-generator-nestjs-dto](https://github.com/vegardit/prisma-generator-nestjs-dto)` or `[prisma-class-generator](https://github.com/kimjbstar/prisma-class-generator)`

Reference: https://www.prisma.io/docs/concepts/components/prisma-schema/generators

**Comment by jd4u** [comment]
using plugins is mostly creates issues of dependencies...
like in case of [prisma-generator-nestjs-dto](https://github.com/vegardit/prisma-generator-nestjs-dto), the application is using very old uuid dependency and causes warning while install for 6 vulnerabilities (3 low, 3 high)..

Having the OpenAPI standard generation with a switch within Prisma generator will provide reliability to all users.

**Comment by axuu** [comment]
> Using plugins many times creates issues of dependencies...
> 
> Like in case of [prisma-generator-nestjs-dto](https://github.com/vegardit/prisma-generator-nestjs-dto), the application is using very old uuid dependency and causes warning while install for 6 vulnerabilities (3 low, 3 high)... (I had tasted before 2 months and did again today)
> 
> Having the OpenAPI standard generation with a switch within Prisma generator will provide reliability to all users.

thx and I will notice the issues about it.

**Comment by win0113** [comment]
use typia  https://typia.io/docs/utilization/prisma/   https://typia.io/docs/json/schema/

**Comment by Med5KDB** [comment]
> * As a final reason, following 3-layer architecture, data layer interfaces (types that prisma generates), should be seperated from Controller level types (DTOs in nestjs context), not only to follow conventions, but to reach better flexebility in your code. I, have worked in several backend projects that utilize nestjs with prisma, in most cases, there are seperated types/classes for each layer (controller, service and data). I can share the baseline If that would help.
> 
Hey @Saeid-Za, would you mind to help have a better understanding by explaining why we should not use the same prisma generated types in both services and controllers? What are the downsides?
If I well understand, you used to define `DTOs` for controllers, right? 
Thanks in advance!

**Comment by Saeid-Za** [comment]
Hello There @Med5KDB !
Sure, I'll try to explain my point of view, I'll assume that we are talking in context of NestJs.

## 1. How to validate inputs from API consumer?
Nest heavily deepens on decorators to provide a way for the developer to implement the data transformation, validation, defining a package (aka `Modules`), services, endpoints and more.
Decorators are a runtime function that would modify a class or it's members and requires a class to be attached on.

Prisma generates Typescript types (not classes) that could not be decorated, because types are stripped when you build your project (transpiling/building the TS into JS), in simpler terms, types have no `runtime` effect.

You could not reuse your typescript types as a DTO, which is mostly used for data validation in NestJS, as you couldn't decorate it.
Even if prisma would generate classes instead of types, you wouldn't be controlling the classes (you don't own the class definition and could not modify the internals of it) and again, you couldn't reuse these imaginary prisma classes as DTO classes for validation.

You would need to own the DTO classes for them to be decorated. these generators recommended by folks here would do such thing.

## 2. Separation of Concerns
A 3-layer architecture is a software design pattern that separates an application into three main layers:
1. Presentation Layer (Controller): Responsible for handling user input and rendering output,  this layer is typically the API layer that receives requests and sends responses.
2. Business Logic Layer (Service): Contains the core functionality and rules of the application. It encapsulates the application's logic and processes data.
3. Data Access Layer (Repository): Handles data storage and retrieval, abstracting the data source (e.g., database) from the rest of the application.

In the context of using Prisma with NestJs, out data layer, is indeed the `Prisma` itself, business layer is the `Service` and the presentation layer is the `Controller` 

We could imagine what are the input of each layer,
1. Input: Data From the User
2. Input: Sufficient Data Needed to execute some logic (related to the app context and it's requirements)
3. Input: DB Operation and variables to do create a DB query and execute in the form of SQL

You could imagine that coupling the controller layer (where we define the API and what do we expose) to Data layer types (which are based on the schema of database) in limiting the structure of your APIs to your database schema.
If we need to restructure our database, we might also have to rewrite the API interface,

Interfaces play a crucial role in determining the maintainability and adaptability of your software.

In a perfect world you would define separate interfaces for the Controller (Using DTOs), Services (which could make them reusable) and data layer (which already is separated by prisma itself).
But in a more practical sense, I'll try to stick by these rules:
1. Controllers: Define Specialized DTOs for every Controller and do not depend on Prisma types.
2. Services: If your service is going to be a reusable one, define separate interfaces and do no depend on the DTOs, otherwise feel free to use DTO types in the service interface.

I hope this clarifies my point !

**Comment by Med5KDB** [comment]
I got your point. Thanks a lot!

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. This kind of feature is too framework-specific (it's for NestJS only), and shouldn't live within Prisma's codebase. We encourage you to draw inspiration by third-party solutions that were posted above by fellow Prisma users, like https://github.com/vegardit/prisma-generator-nestjs-dto/issues/23.
Moreover, if you need to validate inputs from API consumers, I'd recommend to check https://github.com/chrishoermann/zod-prisma-types, and https://github.com/omar-dulaimi/prisma-zod-generator out.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
