### ISSUE TITLE
Out-of-range error when working with unsigned bigint

### ISSUE THREAD

**Issue by PaulSchwarz3000** [prisma/prisma#8431]
Working with MySQL / MariaDB and the bigint package on a table with an unsigned bigint field as the primary key produces an out-of-bounds error when going past the max value of a signed bigint.

table/field model:
`model pg_pages {
  PG_iID      BigInt        @id @db.UnsignedBigInt
 .... }`

query: 
`const foundpg = await prisma.pg_pages.findUnique({
                  where: {
                              PG_iID: 9540952483316114396n
                            }
        });`

produces the following error:

> 
> Invalid `prisma.pg_pages.findUnique()` invocation:
> 
>   Error parsing GraphQL query: query parse error: Parse error at 3:13
> number too large to fit in target type

Note this number is out of range for a signed bigint, but wouldn't be for an unsigned one.
Is there any way to work with the full unsigned range without altering the database?

**Comment by 18124772589** [comment]
我这里也出现了同样的问题

**Comment by pantharshit00** [comment]
I will consider this as a bug in our engines parser.

**Comment by dpetrick** [comment]
It's not an engine bug: BigInt is a stringified value for the engine by default. Ints _can_ be written at the moment, but the engine doesn't guarantee that it can be processed for BigInt (in this case, the GraphQL parser errors out).

The TS client should just always write BigInts as string. I suspect it's simply an oversight somewhere there.

**Comment by SevInf** [comment]
After investigating it does seem like the engine bug to me: engine [parses bigints as i64](https://github.com/prisma/prisma-engines/blob/main/query-engine/core/src/query_document/parser.rs#L302), which is not enough to fit the values between 2^63 and 2^64 - 1, acceptable for unsigned types.
Unless I've misunderstood the suggestion or things changed since then, serializing `bigint` as a string does not help: engine validator will just reject as an incorrect value for the type. Without validation, it fails with the same parsing error.

**Comment by dpetrick** [comment]
Prisma only supports the full range on signed integers. Closing this issue in favor of a feature request: https://github.com/prisma/prisma/issues/13617

Please note that the error message will be better in 3.15 as well.
