### ISSUE TITLE
Typechecking types generated by prisma causes `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by dansworkaccount** [prisma/prisma#8535]
### Bug description

When typechecking the types that are generated by prisma cause an error `RangeError: Maximum call stack size exceeded`. This error occurs with typechecking with ts-node, or tsc. 

### How to reproduce

1. Run `prisma generate`
2. Run `tsc --noEmit ` 

### Expected behavior

`tsc` is able to complete without a stack error

### Prisma information

The schema has about ~115 models and ~40 enums. 

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.5.0
This the environment of my local machine but the error is occurring on other machines and cicd pipeline

### Prisma Version

```
2.19.0
```
We are currently working on upgrading to the newest version and moving away from the nexus-plugin-prisma

**Comment by janpio** [comment]
Can you share the schema maybe? That would be best for a reproduction on our side so we can just start debugging vs. first trying to find a reproduciton.

**Comment by pantharshit00** [comment]
Also, please try again with latest version. 2.19 is bit old now.

**Comment by rs-payres** [comment]
@janpio I was able to put together a private repository with a minimal reproduction using our schema.  Is it possible for me to share this with someone on the Prisma team to review?  I believe I have narrowed the bug down to an excessively deep type instantiation stack caused by the custom XOR type on a schema of sufficient size, more specifically, with a model with a sufficient number of relationships.

**Comment by janpio** [comment]
@pantharshit00 can take a look for sure.

Are you sure this is caused by Prisma and not by Nexus by the way?

**Comment by rs-payres** [comment]
thank you @janpio. Yes I am sure it is Prisma. My reproduction uses the quick start from prisma docs as the frame. It is Prisma 2.28, with my organization's schema and a single function.

@pantharshit00 I have provided access to the repository for you. Please let me know if you have any issues working with it.

To provide some more information, I can share some of the research I have done.

The reason I believe it is related to the XOR type is from debugging tsc and watching the stack grow until blowing with a ton of XOR frames. I looked at the code for that type which references a stack overflow post, which references [issue 14094](https://github.com/Microsoft/TypeScript/issues/14094) in the Typescript repository. That led me to [issue 23777](https://github.com/microsoft/TypeScript/issues/23777) in the Typescript repository which sounds very similar.

Let me know if you have any other questions about it.

**Comment by LarryYarianTraction** [comment]
For what it's worth, we've recently started to encounter this issue also.  We are using Prisma 2.21 and do not use Nexus.  We use introspection to build our schema from a Postgres DB.  The schema has 124 models with many relationships and 15 enum types.

We thought it might be a Node.js compatibility issue so we downgraded to Node 14.4 and that seemed to help for a little while.  But we recently added a few more models, with relationships, to our schema and are experiencing this issue with Node 14.4 now, too.

I can share the schema, if needed, but it needs to be treated as sensitive information and made available only to those who have a need to see it.

**Comment by rs-payres** [comment]
@janpio @pantharshit00  Has anyone at Prisma been able to look into this issue yet? Our schema has grown enough to reach our initial increased stack limit.

**Comment by millsp** [comment]
Which version of TypeScript are you currently using? Does this works with other versions?

**Comment by dansworkaccount** [comment]
We are currently using TypeScript version 4.2.4. We have tested the most recent version 4.4.3 and the error is still present

**Comment by Jolg42** [comment]
This comment from TypeScript repo could help debug what's happening here maybe
https://github.com/microsoft/TypeScript/issues/31538#issuecomment-495281656

**Comment by rs-payres** [comment]
Yes, I have looked at a number of TypeScript issues, that one included, to find debugging steps, which is how I came to the conclusion that this particular issue is caused by the XOR implementation. I have a private repo with minimal reproduction and debugging instructions that I invited @pantharshit00 to. I can invite others from the Prisma team as well if that would be helpful, it is using my company's schema so I cannot share it publicly, unfortunately. I would also be happy to share more information on the research I have already done, I have tried to keep the information I have included so far as closely relevant as possible so as not to spam...

**Comment by pantharshit00** [comment]
Hello @rs-payres 

Sorry for the late reply here. I had to take some time off last week and I wasn't able to get back here on time to accept the repository invitation. Can you please send that again 🙏 ?

**Comment by Jolg42** [comment]
Note: would be interesting to reproduce with TypeScript version v4.5-beta: https://github.com/microsoft/TypeScript/releases/tag/v4.5-beta and see is result is the same.

**Comment by rs-payres** [comment]
@Jolg42 I tested my reproduction repo last night on the 4.5 beta and it has the same issue. I looked at the PR for tail-recursion type check ejection before and, while it looks related, it doesn't cover this specific scenario because it is not caught by their previous safety measures.

**Comment by millsp** [comment]
Hey @rs-payres, can you please invite me to your repro?

**Comment by Bjoernstjerne** [comment]
Can you please contact me for an NDA? We use the same prisma schema for two backends. The smaller ones tsc compiles fine with prisma up to 3.5 but for the larger backend no version higher than 3.1.1 compiles.

**Comment by Jolg42** [comment]
Hi @Bjoernstjerne could contact us at schemas@prisma.io so we can handle this privately?

**Comment by Nayir** [comment]
Hi there, we are experiencing the same issue with typescript 4.4.3 and prisma 3.4.0 when running a `seed.ts` with ts-node. So we found a little workaround, building the typescript file into `seed.js` and running it instead of the .ts file. This way we avoid the RangeError: Maximum call stack size exceeded.  @Jolg42  Be free to contact me in private for more informations. My schema is private too I can't share it here.

**Comment by ile** [comment]
This may be a different issue, but I'm getting `RangeError: Maximum call stack size exceeded` with this model:

```
type Address {
	address			String
	name			String
	group			Address[]
}
```

Actually I created that model with a kind of an accident, and it looks very error-prone. Something that would cause an infinite loop. And it did.

**Comment by pimmee** [comment]
I'm having the same issue. It also seems to be related to the generic `Without` / `XOR` types. It's quite hard to debug which type is the culprit as adding breakpoints in the `typescript.js` file breaks the debugger, but I've at least managed to add try / catch in the `typescript.js` file with prints to see it was due to `Without / XOR`.
 
 
![202967976-434924fa-b12e-4592-97fb-9d157f95446f](https://user-images.githubusercontent.com/33460567/202989962-74bee1e8-5f17-4fd0-be9d-4d013b4b6ae1.png)

The generated prisma types in my project is currently ~162000 LOC, and I suspect the following self referential model is the breaking point, as the generated types is very complex and creates an infinite loop:

```ts
model Folder {
  id             String   @id @default(cuid())
  createdAt      DateTime @default(now()) @map("created_at")
  updatedAt      DateTime @updatedAt @map("updated_at")
  path           String
  homeId         String   @map("home_id")
  authorId       String?  @map("author_id")
  files          File[]
  home           Home     @relation(fields: [homeId], references: [id], onDelete: Cascade)
  author         User?    @relation(fields: [authorId], references: [id])
  subFolders     Folder[] @relation("FolderToFolder")
  parentFolder   Folder?  @relation("FolderToFolder", fields: [parentFolderId], references: [id], onDelete: Cascade)
  parentFolderId String?  @map("parent_folder_id")

  @@unique([homeId, path])
  @@map("folders")
}
```

See for example:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/33460567/202990976-db50b06e-b6c7-4bb9-b79d-4f2cb4b5d3a9.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/33460567/202991538-549fb000-d09c-4928-b003-39fab1f2119d.png">


I've emailed the full `schema.prisma` file to schemas@prisma.io.

Is there any workaround for this?

**Comment by demipixel** [comment]
I'm experiencing this as well. Was causing silent errors in `ts-jest` which was sadly many hours of debugging :c

I only have 14 models and experience the same issue. Did some debugging of this issue last night and also found that it seems to occur with an XOR, although unclear if that's the actual issue. Increasing stack size does not seem like a long-term solution, and I assume it's slowing down type checking in the meantime.

**Comment by millsp** [comment]
Hey @demipixel can you please share a reproduction with us?

**Comment by demipixel** [comment]
I'll see what I can do. I tried extracting just the schema alone and can't seem to replicate, so must be due to how I'm using the types.

**Comment by KevNik** [comment]
@Jolg42 yes, the problem still reproducible, i'm currently using this version and still get the error

**Comment by millsp** [comment]
@KevNik could you please share a reproduction with us?

**Comment by SevInf** [comment]
Hey @KevNik  ,

Did you get a chance to have a look at @millsp  comment? It'd be helpful for us to move your issue forward.

Thank you 🙏

**Comment by KevNik** [comment]
Sorry, i'm not using TypeScript.

`import axios from 'axios';
try {
    await axios.get('http://192.168.40.215/dummy-endpoint')
} catch (e) {
    // this line is returning 1753 to be stored
    console.log(JSON.stringify(e).length)
}`

**Comment by millsp** [comment]
@KevNik since your issue is at runtime and not about types, could you please create a separate issue?

**Comment by millsp** [comment]
Since we haven't received a reproduction and given the age of this issue (reported for `2.19.0`), we are closing it. But of course, happy to re-open it if you can provide us with a reproduction or more information to dig into. Thanks for your understanding!
