### ISSUE TITLE
Prisma Unable to connect with google cloud sql

### ISSUE THREAD

**Issue by Nijinsha** [prisma/prisma#8638]
### Bug description

Hey, I am trying to connect to the cloud SQL database from app engine standard env. Getting this error.

`PrismaClientInitializationError2 [PrismaClientInitializationError]: Can't reach database server at 'hiddenIP':'3306'`

```
app.yaml 
DATABASE_URL: mysql://user:password@localhost/dbname?host=/cloudsql/project-id:us-central1:dbname

beta_settings:
  cloud_sql_instances:project-id:us-central1:dbname
```

### Environment & setup

- OS: GCP app engine
- Database:  google cloud sql (MySQL)
- Node.js version: 

### Prisma Version

```
^2.27.0
```

**Comment by j-Kode** [comment]
I know this thread is old but I was having issues with this and couldn't really find an answer. I got this working on my App Engine to Postgres connection using the following tutorial [here](https://cloud.google.com/sql/docs/postgres/connect-app-engine-flexible#public-ip-default).

I followed the the TCP Port & Public IP Address for Postgres. 

My Prisma Connection string is as follows: `'postgres://<user>:<password>@172.17.0.1:<PortYouSpecify>/<DatabaseName>'`

In your `App.yaml` file for your app you need to specify the port and cloud sql instance as follows.

`beta_settings:
  cloud_sql_instances: [CLOUD_SQL_INSTANCE_NAME]=tcp:<PortYouSpecify>`

This worked for me, hope this helps.

**Comment by jharrell** [comment]
@Nijinsha 

Hi! Following up: are you still seeing this? We're happy to jump on this with more information (schema, query, and a reproduction repo if possible).

Thanks!

**Comment by Nijinsha** [comment]
Hey this was some URL issue if i remember correctly. It was solved.

**Comment by alist** [comment]
_Since this issue was one of a limited number of hints I found on the internet for my issue connecting google app engine standard environment to my cloud sql using prisma, I wanted to summarize my findings after figuring it out._

For GCP App Engine **Standard Environment** with a Cloud SQL instance in the same project, I could **only** get Unix Sockets to work. 

I tried both public and private IPs for the SQL instance, following [the (**flexible** instance) instructions][1] for specifying `cloud_sql_instances` in the app.yaml. The Cloud SQL connector worked from my laptop, but I did not try it on the cloud, because there didn't seem an easy way to use with Prisma.

The only way I could get a connection to work was via the Unix Socket method. I kept the following flexible instance `beta_setting` in my `app.yaml`:

```
beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME
```

And then I could connect using the unix socket per [prisma docs][2] with this format for the `DATABASE_URL` (with a final trailing slash hint from [stack overflow][3]):


```
postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost/$POSTGRES_DB_NAME?host=/cloudsql/$INSTANCE_CONNECTION_NAME/
```

Unfortunately, while the [App Engine standard env docs][4] mention connecting to SQL via public or private IPs, in practice it just didn't work for me. Maybe it's because I would have needed to specify the outgoing Private Interface IP to access a private IP on a VPC like [google does in their mysql example app][5], but I don't think Prisma supports that?

Choosing the outgoing interface IP might be the only thing I'd ask about from the Prisma perspective, not sure if there's already a feature request for that. Thanks to those who contributed here before me.

OH, and if you create a database user e.g. `prisma` for migrating prod SQL from your laptop or CI/CD, your app user e.g. `server` wont have permissions to access that. You'll need to bless it from the `prisma` user. This is apparently just a `postgresql` thing but it caught me.

Really hope this saves someone else the time I lost..

  [1]: https://cloud.google.com/sql/docs/postgres/connect-app-engine-flexible#configure
  [2]: https://www.prisma.io/docs/orm/overview/databases/postgresql#connecting-via-sockets
  [3]: https://stackoverflow.com/a/77984589/1433553
  [4]: https://cloud.google.com/sql/docs/postgres/connect-app-engine-standard#configure
  [5]: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/c401daf710653257790a4149be7480e58b213c2f/cloud-sql/mysql/mysql2/connect-connector-auto-iam-authn.js#L23
