### ISSUE TITLE
Keep comments in datasource block during re-introspection

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#8647]
In the absence of another env management approach I'd like to be able to use comments in the datasource block. But re-introspecting removes them. 

<img width="253" alt="Screen Shot 2021-08-09 at 09 46 29" src="https://user-images.githubusercontent.com/16278407/128674271-f379dcc5-e2de-4096-bcbd-bf9cf78b153c.png">

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
