### ISSUE TITLE
Remove or document `sdlSchema()` type in NodeAPILibraryTypes.ts

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#8689]
When reviewing code I found this `sdlSchema()` method exposed without any documentation and not used anywhere.

https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/engine-core/src/library/types/Library.ts#L23

[After checking with Rust team](https://prisma-company.slack.com/archives/C016KUHB1R6/p1628683029025800) I found out that:
- It's implemented in Query Engine Node-API here https://github.com/prisma/prisma-engines/blob/master/query-engine/query-engine-node-api/src/engine.rs#L357-L362
- It's implemented in Query Engine binary here https://github.com/prisma/prisma-engines/blob/master/query-engine/query-engine/src/server/mod.rs#L155
- It's used in Query Engine Binary for the "Playground" (and also for Node-API?)
```
/// Handler for the playground to work with the SDL-rendered query schema.
/// Serves a raw SDL string created from the query schema.
``` 

We could: 
- document it in the TS code (but it's not used anywhere)
- or preferred: remove the type from TS code, so keeping it only for engine internals

It's a really small task but I don't want to make the decision in place of the team here.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
