### ISSUE TITLE
Add test for invalid env var with overrides

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#8692]
https://prisma-company.slack.com/archives/G01BS87JKD4/p1628684601018100

**Comment by matthewmueller** [comment]
This is relevant when we remove the Scala tests

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
