### ISSUE TITLE
Clarify naming of `generateInFolder` and `getTestClient`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8845]
This is about:
https://github.com/prisma/prisma/blob/main/packages/client/src/utils/generateInFolder.ts
https://github.com/prisma/prisma/blob/main/packages/client/src/utils/getTestClient.ts

Previous context: https://github.com/prisma/prisma/issues/7873
Conclusion there was:
> Both are just for tests
> Let’s make that clear in file and method names and we can close this.

In conversations we were not super sure about this - so we should check again and then choose more descriptive and certain names for these.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
