### ISSUE TITLE
Our GitHub Actions should always include a "failure" mechanism with an alert system

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#8862]
In some but not all our GitHub Actions workflows we have a failure mechanism which posts to Slack.

We should list where it's not yet implemented and implement where it makes sense.

Why? So we don't miss a failure that blocks a workflow for many days 😅

- https://github.com/prisma/introspection-ci/blob/main/.github/workflows/upgrade.yml and analyse.yml
- https://github.com/prisma/migrations-ci/blob/main/.github/workflows/upgrade.yml and analyse.yml
- Probably more

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
