### ISSUE TITLE
`LibraryEngine`: Handling of binaryTargets in error messages missing

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8898]
`BinaryEngine` has this whole concept of `incorrectlyPinnedBinaryTarget`, which is used to output a "helpful" error message:

https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/engine-core/src/binary/BinaryEngine.ts#L398-L402
https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/engine-core/src/binary/BinaryEngine.ts#L474-L484

For `LibraryEngine` the same error message is used without the actual check if it is incorrectly pinned via binary target, leading to even more misleading error messages: https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/engine-core/src/library/LibraryEngine.ts#L585-L590 (it will tell you you pinned wrong just because the file is missing)

This whole concept seems untested as well.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
