### ISSUE TITLE
Rename `binaryTargets`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8901]
The `binaryTargets` configuration naming is confusing (vs. engine, binary, library) and totally not self explanatory. What it actually does, is to define the platforms of the engines (formerly known as binaries) that should be downloaded and made available to Prisma Client. 

A name like `platforms`, `enginePlatformTargets`, `enginePlatforms` or similar would probably be able to reflect that better. 

(This can be a backwards compatible change.)

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
