### ISSUE TITLE
Generate .d.ts file inside project, not node_modules

### ISSUE THREAD

**Issue by sdegutis** [prisma/prisma#8997]
## Problem

It looks like prisma generates `node_modules/.prisma/client/index.d.ts` with my project's types. This isn't kept in git history, and it seems to break the natural separation where node_modules has static external types only. Plus it seems strange and unintuitive and convention-breaking to have *my project's types* imported from `@prisma/client`, which confused me at first. These only apply to first-time users or people examining Prisma to see if its suitable for their needs, if they're like me who first skim over a project's docs to see if they understand everything about how it works.

## Suggested solution

Why not just put this generated file somewhere in ./ instead? Then I can keep it in git history, examine it, and other team members don't need to regenerate it.

## Alternatives

I would assume that the idea of not having to regenerate it is probably considered moot because the database itself needs to be updated at the same time anyway, so might as well do both at the same time, hence the current setup. But I still think the other reasons for having it outside node_modules are worthy of consideration.

## Additional context

I'd assume this has already been discussed, and searched for "type definition files" and ".d.ts" and similar, and can't find previous discussion.

**Comment by geromegrignon** [comment]
You can find the explanation in the [docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#keeping-the-query-engine-binary-out-of-version-control-by-default) :

> Keeping the query engine binary out of version control by default
Prisma Client is based on a query engine that's running as a sidecar process alongside your application. This query engine binary is downloaded when prisma generate is invoked and stored in the output path.
By generating Prisma Client into node_modules, the query engine is kept out of version control by default (since node_modules is typically ignored for version control). If it was not generated into node_modules, then you would need to explicitly ignore it, e.g. for Git you'd need to add the output path to your .gitignore file.

**Comment by sdegutis** [comment]
This doesn't explain to me why it *should* be ignored though.

**Comment by janpio** [comment]
> Why not just put this generated file somewhere in ./ instead? Then I can keep it in git history, examine it, and other team members don't need to regenerate it.

You can totally do that if you prefer: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path

**Comment by pantharshit00** [comment]
You can provide a path to where you want to generate the client as Jan mentioned. We give you that option.
