### ISSUE TITLE
Add different representations of fields depending on the field type

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#91]
For example, it would be useful to have a query argument `display` of type Enum for `DateTime` fields that would allow the time to be returned as a UNIX timestamp:

```graphql
query {
  allPosts {
    createdAt # will print '2017-02-07T10:03:11.123Z'
    unixCreated: createdAt(display: UNIX) # returns '1486461799'
  }
}
```

Further use cases for the `display` query argument will be collected here. This is different to #56 because here, `display` would be a fixed part of the schema and not customizable.

**Comment by migueloller** [comment]
Another way this could be implemented is with directives:

```graphql
query {
  allPosts {
    createdAt # will print '2017-02-07T10:03:11.123Z'
    unixCreated: createdAt @format(display: UNIX) # returns '1486461799'
  }
}
```

The reason why directives might be more compelling is because you wouldn't have to overload (add the `display` argument) to every single field that returns a `DateTime`. You can simply use a directive when you want that format and you're good to go.

It could also even look like this:

```graphql
query {
  allPosts {
    createdAt # will print '2017-02-07T10:03:11.123Z'
    unixCreated: createdAt @unix # returns '1486461799'
  }
}
```

The directive would be constructed in such a way that it would only apply in fields that return a `DateTime`. Should be fairly simple to implement.

Thoughts?

**Comment by marktani** [comment]
Is this part of the schema as such that autocomplete in GraphiQL is aware that `@unix` can only be passed in front of `DateTime` fields? I don't think that's the case.

Using a query argument means that we can at least rely on the type safety and autocompletion when constructing queries.

It's still an interesting suggestion, I think we should try to collect more use cases for different representations depending on type. There might be none though.

**Comment by migueloller** [comment]
@marktani, GraphiQL will only be aware that `@unix` can be passed for fields (not specifically `DateTime` fields). Nevertheless the directive implementation could be made to ignore non-`DateTime` fields so that there's no error if you use it.

This lack of safety at the type level is a downside of using directives though. Good catch!
