### ISSUE TITLE
Only accept known properties for `generator` with `provider = "prisma-client-js"`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9119]
Right now you can add _any_ key-value combination to a `generator` with `provider="prisma-client-js"`, although we know exactly which properties are valid and which are not. 

This schema is happily accepted:

```
generator client {
  provider = "prisma-client-js"
  foo      = "bar"
}
```
That is unfortunate, as `foo` is definitely not supported for ` provider        = "prisma-client-js"`. 

We should only allow the known properties ones and fail on the others.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
