### ISSUE TITLE
Introspection warnings about validation errors of created schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9185]
An introspected schema should ideally always be valid, because it represents an actual live database. But there are scenarios that don't make sense in a Prisma schema.

For example: two foreign keys that are exactly the same. Technically, we should put both foreign keys in the schema, so migrate can handle them properly. But we can't even represent that in the schema.

We should warn about these scenarios.

**Comment by tomhoule** [comment]
Putting this in the "Gaps" column because that makes some real existing databases not usable with Prisma.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
