### ISSUE TITLE
Avoid using magic string values for JsonNull/DbNull

### ISSUE THREAD

**Issue by matthijscollabai** [prisma/prisma#9243]
## Problem

Since Prisma 3.0, the input for filtering and updating nullable JSON fields no longer accepts `null`, but instead the `Prisma.JsonNull` and `Prisma.DbNull` values to better distinguish between the two types of nulls.

I can see that this solves a real problem, but the current implementation has a significant drawback: `JsonNull` and `DbNull` are implemented as magic string values. This means their types overlap with regular string data that can be stored in a JSON field. Some problems this could cause:
- Filtering/storing `Prisma.DbNull` on a non-nullable JSON field will type-check, but produce a JSON string value of `"DbNull"` instead of an actual `NULL`, which may lead to confusing bugs
- User-provided strings that get stored as a top-level value in a JSON field need to be sanitized to make sure they're not `"JsonNull"` or `"DbNull"`, or users might be able to inject either kind of null value and cause an unexpected state

## Suggested solution

A possible alternative approach would be making JsonNull and DbNull `Symbol`s or some kind of class instance, so that they don't overlap with the `JsonValue` type

**Comment by aqrln** [comment]
This issue is now fixed, and the change will be released in Prisma 4.0.0.

`DbNull`, `JsonNull` and `AnyNull` will now be singleton instances of their eponymous classes. We eventually settled on this design after making them symbols first because it allows for better type errors, and thus better DX (but you may still see "symbols" being referenced in some public GitHub issues used for planning and orchestrating this change).
