### ISSUE TITLE
After upgrading to 3.0.2, can't create or update records when json field is null

### ISSUE THREAD

**Issue by chemicalkosek** [prisma/prisma#9264]
I'm having a similar error to https://github.com/prisma/prisma/issues/9199 after upgrading to Prisma 3.0.2 (from 2.x)

I have also ran `prisma migrate` with no changes in order to cohere with Upgrade Path for referential actions and named constraints

datamodel in particualar:
```
model Room {
  id        String    @id @default(cuid()) @db.VarChar(30)
  name      String
  updatedAt DateTime  @updatedAt
  createdAt DateTime  @default(now())
  accountId String    @map("account") @db.VarChar(30)
  bgColor   Json?
  account   Account   @relation(fields: [accountId], references: [id])
  bookings  Booking[]

  @@index([accountId])
}
```
Mutation from Nexus:
```
    t.field('createRoom', {
      type: 'Room',
      args: {
        name: nonNull(stringArg()),
        accountId: nonNull(idArg()),
        bgColor: arg({type: "Json"}),
      },
      resolve: (_parent, args, ctx) => ctx.prisma.room.create({
        data: {
          ...args
        }
      })
    });
```

Error when bgColor is null (the same thing when creating or updating):
```
Invalid `prisma.room.create()` invocation: { data: { name: 'Test Room', accountId: 'ckm7v6zpi00130huil8hbwvlk', bgColor: null ~~~~ } } Argument bgColor for data.bgColor must not be null. Please use undefined instead.```
```

_Originally posted by @chemicalkosek in https://github.com/prisma/prisma/issues/9199#issuecomment-919430264_

**Comment by janpio** [comment]
Thanks @chemicalkosek for the great issue. With the model and query included in it, we should be able to reproduce the behavior in 2.x and 3.x and see if we also get the same difference you are describing.

**Comment by pantharshit00** [comment]
I think this is expected as this is listed as a breaking change in 3.x

https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3#json-null-equality

**Comment by chemicalkosek** [comment]
I don't think it is, we've been through it already the linked issue.
I'm not doing any filtering by Json. It's creating or updating a record with a null Json field value.

**Comment by robmurtagh** [comment]
Hi, I'm also running into the same issue. I'm doing:

```ts
prisma.foo.update({ where: { ... }, data: { someJsonColumn: null }});
```

And am receiving the error message:

```
Argument someJsonColumn for data.someJsonColumn must not be null. Please use undefined instead.
```

However, if I understood things correctly, I'm not sure that this can be quite right:
 * By using `null`, I want to set a MySQL `NULL` value, regardless of what was there before
 * If I used `undefined`, I think that would let the value unchanged from whatever it was before

Is that a correct understanding? If so I think this is a genuine bug, and not an expected change?

**Comment by amitozalvo** [comment]
I can't modify JSON fields to null anymore since 3.0...
Any workarounds?

**Comment by matthewmueller** [comment]
Hey everyone, sorry for the confusion here. 

This is expected, but we missed this in our documentation.

We stopped allowing nulls for JSON field inputs because:

```
prisma.foo.update({ where: { ... }, data: { someJsonColumn: null }});
```

The above code is ambiguous:

- Did you mean setting someJsonField to the value null?
- Or did you mean setting someJsonField to the database NULL?

The solution is to use `DbNull` and `JsonNull` ([documentation](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values))

To insert a `null` value into a Json field, you would write:

```ts
import { Prisma } from '@prisma/client'

prisma.log.create({
  data: {
    meta: Prisma.JsonNull,
  },
})
```

And to insert a database `NULL` into a Json field, you would write:

```ts
import { Prisma } from '@prisma/client'

prisma.log.create({
  data: {
    meta: Prisma.DbNull,
  },
})
```

We're going to improve [this error message](https://github.com/prisma/prisma/issues/9344) and also [fix up our documentation](https://github.com/prisma/docs/pull/2348).

**Comment by chemicalkosek** [comment]
That would mean rewriting even the simplest resolvers such as
```
 resolve: (_parent, args, ctx) => ctx.prisma.room.create({
        data: {
          ...args
        }
      })
```

to check for json null values.
Can we make a default that will transform the null value to the previous behaviour? Or such thing will not be possible?

**Comment by saimonmoore** [comment]
Just ran into this issue. We uncovered the issue while doing the following:

```
const record = repository.find() // does a `prisma.find()` underneath the hood;
record.foo = "bla";
repository.createOrUpdate(record) (does a `prisma.upsert({where: ..., create: record, update: record})` under the hood;
```
I'm having a hard time understanding why we now need to go through all of records attributes and convert any nulls into `Prisma.JsonNull`. And since we've abstracted prisma under our Repository abstraction, we're either going to have to couple prisma code (`Prisma.JsonNull`) in the caller (we wrote the repository to abstract the orm) or do some very tricky code in the repository because we have no way of knowing if the null was due to an explicit (makes this null in the db) or don't bother since it was already null in the db and I just looked it up.

Maybe I'm missing something?

**Comment by saimonmoore** [comment]
Erm ok hold on. We're on prisma v3.0.2 and we don't even have Prisma.JsonNull but we're seeing this error message: https://github.com/prisma/prisma/issues/9344 so now I'm really stumped. :(

**Comment by gbkwiatt** [comment]
Not only this is bit weird not allowing to insert real null, but also jusing Prisma.JsonNull it inserts `null` string rather than db NULL 
e.g. from postgres 
![image](https://user-images.githubusercontent.com/62710468/151666251-a3b7826c-4af5-4e1f-9dc7-5eb70e236ade.png)
and that's on latest Prisma 3.8.1

**Comment by schulzf** [comment]
here is a handy function to convert all `null` to `DbNull` if that can help

```
import { Prisma } from '@prisma/client';

export const replaceNullWithDbNull = (obj: Record<string, any>) => {
	for (const key in obj) {
		if (obj[key] === null) {
			obj[key] = Prisma.DbNull;
		} else if (typeof obj[key] === `object`) {
			replaceNullWithDbNull(obj[key]);
		}
	}

	return obj;
};
```

**Comment by baptisteArno** [comment]
Would be nice to have a simple option that converts nulls to DbNulls automatically.

**Comment by mkramek** [comment]
Hello!
Can it be mentioned somewhere in the docs? I've stumbled upon this, since I've been looking for:
```
where: {
    field: {
        not: null
    }
}
```
on a Json type field, and Prisma was giving me errors.
The solution was:
```
where: {
    field: {
        not: Prisma.DbNull
    }
}
```
Not sure if it's mentioned, since my Googling didn't show anything of the sort.
Thanks in advance!

**Comment by janpio** [comment]
Let us know if you stumbled over some places where we could or should have linked that information. Always important to surface such separate content in the right spots.

**Comment by mkramek** [comment]
I'd say that a good spot would be in "Null and undefined" section, as an explanation that e.g. "for data consistency purposes, Prisma utilises helper types, such as DbNull or JsonNull". That'd explain, why `not: null` is misbehaving with Json type fields. 
Of course now that I've localised the exact explanation as mentioned, I can't say it's nonexistent - nevertheless, it would be of great help to put Json type `null`-ish values near the null-related topic.

**Comment by janpio** [comment]
I created a docs issue so someone can think about this in the future: https://github.com/prisma/docs/issues/5012 Thanks for the feedback!
