### ISSUE TITLE
no such file or directory, open '/path/schema.prisma' since 3.1.1

### ISSUE THREAD

**Issue by s97712** [prisma/prisma#9435]
### Bug description

When I call ` new PrismaClient()`, I get the error 
```bash
(node:12802) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/mnt/d/workspace/path/packages/api/src/schema.prisma'
```
That just happen on 3.1.1

### How to reproduce

1. Upgrade prisma to 3.1.1
2. Execute `prisma db push` command
3. Call ` new PrismaClient()`

### Environment & setup

- OS: Windows(wsl)
- Database: SQLite
- Node.js version: v14.17.4

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at ../../.yarn/unplugged/@prisma-engines-npm-3.1.0-24.c22652b7e418506fab23052d569b85d3aec4883f-4e2ba773cc/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```

**Comment by henry-young** [comment]
I can also confirm a similar error occurs when you import prisma from a yarn workspace package. 
It seems to attempt to look and error in the first directory of the importing package.
`Error: ENOENT: no such file or directory, open '/Users/henryyoung/projects/project-monorepo/packages/server/.adirectory/schema.prisma'`

**Comment by janpio** [comment]
@s97712 Are you also getting this in context of a Yarn Workspace Package?

**Comment by henry-young** [comment]
I forgot to mention, I'm seeing this using yarn v1. I haven't confirmed
this with V2.

**Comment by danielmahon** [comment]
I am also getting a similar error after upgrading to `3.1.1`. Seems to "stop" at the first folder in the workspace. I am currently outputting the prisma client as a sibling workspace package and importing it accordingly. `3.0.2` works fine.

`Error: ENOENT: no such file or directory, open '/usr/src/app/packages/server/.vscode/schema.prisma'`

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
@danielmahon Also Yarn workspaces?

**Comment by henry-young** [comment]
Based on the folder structure I would imagine so

**Comment by danielmahon** [comment]
> @danielmahon Also Yarn workspaces?

Yup, but I'm also using the traditional node_modules workflow, not pnp. (For the time being)

**Comment by elie222** [comment]
I'm using npm workspaces and seeing this issue with Next.js.

**Comment by coolcalcacol** [comment]
Using Yarn v3 with PnP getting the error 
`Error: ENOENT: no such file or directory, open '/6mans/.yarn/unplugged/@prisma-client-virtual-1facac348b/schema.prisma'`
Not using any workspaces.

**Comment by s97712** [comment]
> @s97712 Are you also getting this in context of a Yarn Workspace Package?

Yup

**Comment by elie222** [comment]
Facing the same issue on 3.0.2 btw.

I have the monorepo setup working with a regular Node.js app but facing this issue when trying to use it with Next.js.

**Comment by janpio** [comment]
Everyone else has this working in 3.0.x but it only broke in 3.1.1 @s97712 @henry-young @coolcalcacol @danielmahon? 

I suggest everyone for whom it did not only break with 3.1.1 please open a separate issue so we can investigate this properly. Thanks. The original poster here explicitly mentions that this happens after the update to 3.1.1, so let's only investigate these cases here. Might have very different root causes.

**Comment by revmischa** [comment]
I'm using 3.1.1 -
It’s not running properly in my lambda function/layer setup. I get the error `ENOENT: no such file or directory, open '/var/task/schema.prisma'`
Can I at least tell it what path my schema.prisma file is at somehow? I couldn’t find anything in the docs. I have the file in a lambda layer (/opt/nodejs/prisma)

<img width="349" alt="Screenshot 2021-09-29 at 18 53 50" src="https://user-images.githubusercontent.com/245131/135304752-f8bc1070-7a37-47c8-947f-2e2f27e34429.png">


Additionally, it seems like in Prisma 3 it now is trying to find the schema.prisma file when I import the file that constructs my prisma client (`new PrismaClient()`), whereas before it didn’t do that. This is a problem for me because some of my lambda functions are set up to use prisma (with secrets, layer, network access to the DB, etc) and some aren’t but still import files which import the prisma client. So now I can’t start the functions that don’t have anything to do with prisma because it explodes saying it can't find `schema.prisma` even though I have no intention of using it in that function.

**Comment by janpio** [comment]
Is this a new problem with 3.1.1 @revmischa? If not, please open a new issue as this one is about a change between Prisma 3.0.x and 3.1.1.

**Comment by s97712** [comment]
> Can you please help us out and create a minimal reproduction of your setup that shows the problem occurring? Please put it in a Github repository and post the link here. Thanks.

I cannot reproduce in the new project, I will try to find out the real reason

**Comment by revmischa** [comment]
> Is this a new problem with 3.1.1 @revmischa? If not, please open a new issue as this one is about a change between Prisma 3.0.x and 3.1.1.

I was testing upgrading from 2.x right now. I just tried 3.0.2 and got the same missing schema error.

**Comment by s97712** [comment]
> Can you please help us out and create a minimal reproduction of your setup that shows the problem occurring? Please put it in a Github repository and post the link here. Thanks.

https://github.com/s97712/prisma-workspace

**Comment by coolcalcacol** [comment]
> Can you please help us out and create a minimal reproduction of your setup that shows the problem occurring? Please put it in a Github repository and post the link here. Thanks.

https://github.com/coolcalcacol/prisma-issue

**Comment by henry-young** [comment]
> Everyone else has this working in 3.0.x but it only broke in 3.1.1 @s97712 @henry-young @coolcalcacol @danielmahon?

This is correct.

I am currently using 3.0.2 with no issues. Issue only happens after upgrade.

**Comment by pantharshit00** [comment]
I can reproduce with https://github.com/s97712/prisma-workspace and https://github.com/coolcalcacol/prisma-issue. 

We don't officially support Yarn 2/3 but still going to mark this as confirmed bug for now.

**Comment by coolcalcacol** [comment]
> We don't officially support Yarn 2/3

Is this expected to happen?

**Comment by pantharshit00** [comment]
@coolcalcacol Follow https://github.com/prisma/prisma/issues/1439. No timeline yet.

**Comment by internalfx** [comment]
I can confirm the same bug. Works fine with `3.0.2`

**Comment by henry-young** [comment]
Just reporting that this is still an issue in the latest release `3.2.0`. `3.0.2` is the latest version that doesn't have this issue.

**Comment by rathax** [comment]
still broken on 3.2.0
npm: 7.19.1
node 16.5.0

**Comment by tobilen** [comment]
Same problem here. @henry-young helped me work around the issue.

`findSync` is very eager to find a match for the generated output and one needs to work around the current implementation in order to trick it to fall back to `__dirname`.

First of all, having a path with only one segment will make the second passed matcher to `findSync` be an empty string, which matches everthing. So my first fix was to move around my setup so that the output path had 2 segments, i.e.

```
generator client {
  provider = "prisma-client-js"
  output = "./generated/client"
}
```

Next thing i did was make sure that my path would not be accidentally matched by any filename in the yarn cache, since prisma will recurse through that(!). Picking an output path like `./prisma/client` will match for the first segment and break.

I ended up choosing `./generated/client`, which works for my case. It sure would be nice to pass the dirname in the config, next to the output 😁

**Comment by dimaip** [comment]
I can confirm. Setting it to `"./generated/output"` from `"../prisma-client"` fixes it for me.

**Comment by henry-young** [comment]
Confirming that the above works. Thanks for that @tobilen.

As @tobilen mentioned, it's important that the path starts with `./` and has two segments (I also chose `generated/output`).

It is nice to have a workaround, although my preference would still be to add the quotes back into the string as per `<= v3.0.2`.

**Comment by henry-young** [comment]
Also, for anyone wondering my folder structure is as follows:
```
node_modules/
prisma/
├─ generated/
│  ├─ output/
│  │  ├─ ...generated files here...
├─ migrations/
├─ schema.prisma
.gitignore
package.json
tsconfig.json
```

I was unable to have my schema file (and my generated output) in the root of the package. Nesting everything under `/prisma` works well for me. 

Also here is a snippet from my `package.json` just incase anyone was needing help with yarn workspaces.
```
{
  "name": "@db/client",
  "private": true,
  "main": "prisma/generated/output/index.js",
  "types": "prisma/generated/output/index.d.ts",
...
}
```

So I can access prisma using `import { PrismaClient } from '@db/client';` from another package in the workspace.

**Comment by andyjy** [comment]
Hit this using NPM workspaces for a monorepo (with Next.js).

I couldn't get @henry-young's `./generated/output` fix to work for me - but figured another way that's working:

1. prisma folder nested within monorepo workspace package e.g. `<monorepo root>/packages/mydbpackage/prisma/schema.prisma`
2. generator `output=` directly into `<root>/node_modules/` (similar to the default when `output` isn't specified)
3. .. *and* use the `@` prefix to scope the generated client node_module package name
4. Finally, be sure import the client using the `@`prefix-scoped module pathname

Works for me importing into a separate monorepo Next.JS package: 

`prisma.schema`:
```
generator = "../../../node_modules/@~internal/prisma-myschema/client"
```

then:
```
import { PrismaClient } from "@~internal/prisma-myschema/client
```
(No dependencies required in the calling module package.json - node will automatically look in the root `node_modules`)

This is now working for me with multiple prisma schemas, managed separately from within one package within my monorepo, and generated separately into different top-level node_modules folders. 

Using the @-scope prefix seems to force the client to be treated as an external dependency to be loaded from node_modules and not anywhere else. The client is then found correctly, not transpiled by Next.JS (as encountered in #10171), and the import treated successfully as CommonJS rather than hitting an error when the generated client attempts to require('./runtime..') which I encountered due to my monorepo being configured with `type="module"`.

_(Thanks for the shares above, directed me to figure this out after digging around in the zaniness of the `findSync() / __dirname` logic - which appears to be attempting more magic than some might consider healthy 😬 )_

**Comment by elie222** [comment]
@andyjy are you able to share a sample project that includes the different pieces?

I have this in a `db` package:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  generator = "../../../node_modules/@~internal/prisma-myschema/client"
}
```

And when I import the following into my `web` package (a Next.js project). I get the following error:

```ts
import { PrismaClient } from "@~internal/prisma-myschema/client"
```

![image](https://user-images.githubusercontent.com/3090527/142733335-e054680a-d979-46a9-be04-e830d2dbcc43.png)

Or in Next:

```
Module not found: Can't resolve '@~internal/prisma-myschema/client'
```

**Comment by andyjy** [comment]
> @andyjy are you able to share a sample project that includes the different pieces?

Sure! <https://github.com/andyjy/prisma-multiple-schemas-monorepo-demo>

**Comment by Luke-zhang-04** [comment]
I've been facing a similar issue where the path points to `.git`

`Error: ENOENT: no such file or directory, open '/home/opc/Documents/project/.git/schema.prisma'`

And I think it has something to do with this code at the beginning of `runtime/index.js`

```js
const dirname = findSync(process.cwd(), [
    ".prisma",
    "",
], ['d'], ['d'], 1)[0] || __dirname
```

After some investigating, `findSync` was matching all the directories in `process.cwd()` and just listing them out and then picking the first one. I fixed it by removing the empty string in the array, and it works now. Not sure if this helps at all but the issue seems similar, and only happened after I upgraded from ~3.0.0

```js
const dirname = findSync(process.cwd(), [
    ".prisma",
], ['d'], ['d'], 1)[0] || __dirname
```

**Comment by arthurfiorette** [comment]
Appearently, is this function here:

https://github.com/prisma/prisma/blob/62b91fd9bd32da983f457857411edef6daeecda1/packages/client/src/generation/utils/buildDirname.ts#L31

It fails to generate the correct directory to the generated code. For me, if i change it to only __dirname it works seamlessly

Located at the generated code `index.js`
![image](https://user-images.githubusercontent.com/47537704/146848323-c751a332-cc2e-4412-bf1e-8aceb2aba5dd.png)

**Comment by Luke-zhang-04** [comment]
Looks like https://github.com/prisma/prisma/pull/9295 caused this by removing the quotes

**Comment by FizzBuzz791** [comment]
Still seem to be hitting this issue in 3.8.0, any chance of a fix any time soon? I'd rather not write a script to modify a generated file and languishing on 3.0.2 prevents me from getting bug fixes, vulnerability fixes, etc.

**Comment by Luke-zhang-04** [comment]
In the same boat here. The fix is there, I just can't figure out why the test won't run. Ideally this is done before the 3.9 milestone

**Comment by dev-marinho** [comment]
Same, prisma@3.8.2

**Comment by marmik18** [comment]
Facing same issue on [3.9.1](https://github.com/prisma/prisma/releases/tag/3.9.1)

**Comment by millsp** [comment]
Hey everyone, we have a fix that is ready. Could you please give it a try?
https://www.npmjs.com/package/@prisma/client/v/3.11.0-integration-fix-empty-path.1

**Comment by aertmann** [comment]
Hey @millsp, can confirm your version mentioned in [above](https://github.com/prisma/prisma/issues/9435#issuecomment-1049780015) works for solving this issue. Thanks for taking care! cc @Jolg42 @janpio

**Comment by dev-marinho** [comment]
@millsp, 3.11.0-integration-fix-empty-path.1 version resolved the issue, thanks.

**Comment by Faithfinder** [comment]
Willing to bet reproduction is the same as #10512

**Comment by xygengcn** [comment]
Same, prisma@3.10.0。。。next version time？

**Comment by jensmeindertsma** [comment]
@millsp I just tried your fix but it doesn't seem to solve the issue that when I build my app into `./build/index.js` in a workspace, Prisma then tries to find the schema file at `./build/schema.prisma` instead of `./prisma/schema.prisma`.

Is this a different issue than the one you fixed?

**Comment by FC5570** [comment]
Getting the same issue with yarn v3.1.1 `.yarn\unplugged\@prisma-client-virtual-841eea369e\node_modules\.prisma\client\schema.prisma`

**Comment by gualopezb** [comment]
Managed to resolve this issue by symlinking the schema.prisma and engine files. Check out this [comment](https://github.com/prisma/prisma/issues/10433#issuecomment-1290739826) for the details.

**Comment by thegeeko** [comment]
if you are using next u can also try [#10433](https://github.com/prisma/prisma/issues/10433#issuecomment-1304673679)
