### ISSUE TITLE
Getting a string '(array)' in the generator config instead of the expected value when array is used

### ISSUE THREAD

**Issue by capaj** [prisma/prisma#9511]
### Discussed in https://github.com/prisma/prisma/discussions/9510

<div type='discussions-op-text'>

<sup>Originally posted by **capaj** September 29, 2021</sup>
in my prisma.schema file I have a generator like this:
```
generator typegraphql {
    provider = "typegraphql-prisma"
    output   = "../generated/typegraphql-prisma"
    emitOnly = ["enums", "models"]
}
```

problem is when I run it, I am getting this:
```
  generator: {
    name: 'typegraphql',
    provider: { fromEnvVar: null, value: 'typegraphql-prisma' },
    output: {
      value: '/home/capaj/work-repos/authier-repos/authier/backend/generated/typegraphql-prisma',
      fromEnvVar: null
    },
    config: { emitOnly: '(array)' }, // I am expecting ["enums", "models"] here, instead I am getting a string here 
    binaryTargets: [],
    previewFeatures: [],
    isCustomOutput: true
  },
```

I am expecting ["enums", "models"] here, instead I am getting a string in the config. Why? 
</div>

Tested with prisma 3.1.1

**Comment by janpio** [comment]
Thanks for opening an issue @capaj, for completeness I will repeat my answer from the discussion as well:

This might very well be a not yet supported feature.
The generator API in general is pretty much experimental, so I would not be surprised if this is the case.

We will investigate this as a bug first, but if it turns out the implementation is not supposed to "parse" arrays yet, this could become a feature request.

**Comment by MichalLytek** [comment]
@janpio I think it's a bug since `previewFeatures` and `binaryTargets` are properly handled as array of strings.

It doesn't sound like a complex change on the prisma schema parser but would really help the library creators in handling generator options, which makes Prisma DX better for end users.

**Comment by janpio** [comment]
My guess (!) would be that these known properties have special handling in our parsing, where we transform them into an array instead of a string. If that is true, implementing this would mean we have to look at the string value in general and decide if it actually represents an array. (That you _actually_ get `(array)` contradicts this guess a bit, so someone will have to investigate and look at the details)

**Comment by MichalLytek** [comment]
@janpio I believe it might be hardcoded but if we parse `schema.prisma`, we get `[` token which informs that "here starts an array" so that you could move parsing the array level up into the root options' parser, instead of the dedicated for Prisma Client 😉

**Comment by zackdotcomputer** [comment]
+1 for a fix to this issue - it's still present a year later on Prisma 4.7.x.
@janpio if you're still interested in taking a look at this, the coercion happens here: https://github.com/prisma/prisma-engines/blob/dcee72a29a5d6ce9d5d5617064e1f8cf63baccd1/psl/psl-core/src/validate/generator_loader.rs#L102

Rust is told to explicitly coerce arrays to this string. Ideally, it would instead recurse and apply the validation/sanitization to each element in the array (and each element in any sub-arrays and so on) and then provide us the resulting array of strings in the generator's config.

Sadly I know Rust only just barely enough to provide the trace to where this was happening, not enough to tackle the PR myself.

**Comment by janpio** [comment]
Thanks for digging! 

That also explains why `binaryTargets` and `previewFeatures` already work: 
https://github.com/prisma/prisma-engines/blob/dcee72a29a5d6ce9d5d5617064e1f8cf63baccd1/psl/psl-core/src/validate/generator_loader.rs#L79-L89 
https://github.com/prisma/prisma-engines/blob/dcee72a29a5d6ce9d5d5617064e1f8cf63baccd1/psl/psl-core/src/validate/generator_loader.rs#L92-L95
https://github.com/prisma/prisma-engines/blob/dcee72a29a5d6ce9d5d5617064e1f8cf63baccd1/psl/psl-core/src/validate/generator_loader.rs#L22-L28
These "first class properties" have their own code, and are skipped here.

So the fix for you @zackdotcomputer and @MichalLytek would be to instead return `["enums", "models"]` instead of `'(array)'` (note that the second one is directly a string with quote, and the first one an actual real array)?
