### ISSUE TITLE
Can not spawn Query Engine when using Electron

### ISSUE THREAD

**Issue by TasinIshmam** [prisma/prisma#9619]
## Problem

The [ASAR file format](https://github.com/electron/asar) is an archive used to package the source code and dependencies of an application in Electron. However in order to ```spawn``` the Query Engine binary, it has to be outside the ASAR archive, since ASAR archives are read-only and cannot ```spawn``` a separate process. 

As a solution [electron-builder](https://github.com/electron-userland/electron-builder) provides a way to unpack or "move" these binaries out of the ASAR archive and into a different location. 

However, this leads to a new problem. As the location of the  ```Query Engine``` binary has changed to a different location,  ```PrismaClient``` can no longer automatically detect the binary. In such cases, the path for the ```Query Engine``` binary needs to be manually passed to the ```PrismaClient``` during initialization in this way: 

```typescript
let prisma = new PrismaClient({
   __internal: {
    engine: {
      binaryPath: "/path/to/binary"
    }
  }
})

```

_However, this API is currently not public and undocumented_, making it difficult for usage by people outside of Prisma. 

## Suggested solution

Either of the following seem like acceptable solutions: 

1. This API needs to be made public and documented. 
**OR** 
2. Some provision needs to be added so that the ```PrismaClient``` can automatically locate the path to the unpacked ```Query Engine``` binary.

**Existing Workaround**: Use the private API for the moment.

**Related Issues/Discussions**: 
- #9613
- #5200

**Comment by janpio** [comment]
> Yes the problem also applies here, as the Node-API also needs to be `spawn'd`.

There is now `spawn`ing happening for Node-API, only `require`: https://github.com/prisma/prisma/blob/main/packages/engine-core/src/library/LibraryEngine.ts (vs. https://github.com/prisma/prisma/blob/main/packages/engine-core/src/binary/BinaryEngine.ts)

**Comment by awohletz** [comment]
Electron-builder detects the binaries and leaves them unpacked on Windows and Mac. On linux, I have to explicitly add the prisma engines dir to my electron-builder settings. Here are the relevant settings:
```yaml
win:
  asarUnpack:
    - prisma
linux:
  asarUnpack:
    - prisma
    - node_modules/@prisma/engines
mac:
  asarUnpack:
    - prisma
```
The `prisma` directory in asarUnpack is so that Prisma can read the `prisma.schema` and migrations. If it's not unpacked, Prisma can't access those in the asar at runtime and throws an error. 

These settings create this directory in the packed Electron app: `resources\app.asar.unpacked\node_modules\@prisma\engines`. This directory contains, for example on Windows, `introspection-engine-windows.exe`, `migration-engine-windows.exe`, `prisma-fmt-windows.exe`, `query_engine-windows.dll.node` and a few other files. 

**With these settings, I am able to instantiate Prisma Client normally without passing any engine and without setting any environment variables.**

It also leads to a large Electron app size. The large majority of the size of my app is taken by the Prisma binaries, which are duplicated in both places: Here `resources\app.asar\node_modules\@prisma\engines` and `resources\app.asar.unpacked\node_modules\@prisma\engines`. And the query_engine-windows.dll.node again in `resources\app.asar\dist\generated\client` (I am using a custom Prisma client generation directory so that I can copy that generated client into my Electron app bundle on pack).

The size of `resources\app.asar.unpacked\node_modules\@prisma\engines` is 70MB on Windows.

**Comment by TasinIshmam** [comment]
Keeping the Prisma libraries binaries out of the `ASAR` archive using the `extraResources` configuration option that electron-builder provides seems to work fine. One possible drawback to this is the extra bundle size of the final applicaiton. 

Notably, this works for both the new Node-API and the older rust binary. A while ago, I created a small [example repo](https://github.com/TasinIshmam/prisma-electron-test)demonstrating how to do the above, I think it might be relevant to anyone facing this issue.  

@madebysid  @janpio  sorry for the delay following up. Please feel free to take a look!

**Comment by TasinIshmam** [comment]
Closing this, because the `extraResources` option provides a very easy solution to keep any binaries outside the ASAR archive, with little configuration needed.
