### ISSUE TITLE
Working tree not clean after running the `@prisma/client` tests

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#9729]
Working tree is not clean after running the integration tests due to files with SQLite databases being changed.

```
 M ../packages/client/src/__tests__/integration/happy/float-napi/dev.db
 M ../packages/client/src/__tests__/integration/happy/interactive-transactions/dev.db
 M ../packages/client/src/__tests__/integration/happy/middlewares-transaction/dev.db
 M ../packages/client/src/__tests__/integration/happy/middlewares/dev.db
```

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
