### ISSUE TITLE
Support Prisma in Next.js middleware without using the Data Proxy

### ISSUE THREAD

**Issue by patryk-smc** [prisma/prisma#9928]
## Problem

Related to #85 #9841

Next.js is working on [middleware support](https://github.com/vercel/next.js/discussions/29750) which runs in V8 environment. Currently, it is not possible to run Prisma there. 

## Suggested solution

Since Prisma 3.3.0 we have Early Access support for Cloudflare Workers (which run in V8 environment too), it would be nice to extend that functionality to support Next.js middleware as well.

**Comment by matthewmueller** [comment]
We discussed this one more in depth. It's unfortunately a hard problem because Next.js essentially has added another type of Javascript environment depending on the file you're in. We've handled browser vs. server environments with the package.json, but this is a new environment specific to the Next.js file layout, so no generic way to know. 

For server-side rendering (SSR) it continues to make sense to use the default Node-API implementation of the Prisma Client. But the Node-API implementation wouldn't work inside the Next.js middleware, so to pull this off right now you'd need two Prisma Clients, one built for SSR, one built for Edge Functions.

Longer-term, I could see us always generating one package for each environment, that you could switch out depending on the context:

```ts
import { PrismaClient } from "@prisma/client" // used in pages/index.js
import { PrismaClient } from "@prisma/edge" // used in _middleware.js
```
