### ISSUE TITLE
Pagination should not effect the `distinct` behaviour of `findMany` fetches

### ISSUE THREAD

**Issue by lskuper** [prisma/prisma#9974]
### Bug description

Hi there 👋 

the _distinct_ keyword combined with _cursor-pagination_ within one query leads to distinctness _within_ one pagination page, but unfortunately not _beyond_ pagination pages.
This leads to two problems when paginating a distinct query:
1) elements that shouldn't be fetched due to distinctness are being fetched on subsequent fetches.
2) unpredictable fetching behaviour: varying the page size (with _take_) leads to different items being obtained although the underlying data in the database is the same.

### How to reproduce

schema:
```
model Comments {
  id       String  @id @default(uuid())
  authorId String
  cursorId String  @unique
}
```
Filled with data
```
{ cursorId: "0001", authorId: "user1" },
{ cursorId: "0002", authorId: "user2" },
{ cursorId: "0003", authorId: "user1" },
{ cursorId: "0004", authorId: "user3" },
{ cursorId: "0005", authorId: "user1" },
```
Executing findMany fetches of the following shape each with 
1) _distinct on userId_ 
2) _cursor-pagination_ and 
3) different values for page_size
```
const res = await prismaClient.comments.findMany({
  distinct: ["userId"],
  orderBy: { cursorId: "asc" },
  cursor: { cursorId: lastFetchedElement?.cursorId },
  take: page_size,
  skip: firstPage ? undefined : 1,
  select: { cursorId: true },
});
```
result without pagination:
```
[{ scoreId: "0001" }, { scoreId: "0002" }, { scoreId: "0004" }]
```
result with page_size = 3:
```
page_1: [{ scoreId: "0001" }, { scoreId: "0002" }, { scoreId: "0004" }]
page_2: [{ scoreId: "0005" }]
--> concatenated:   [{ scoreId: "0001" }, { scoreId: "0002" }, { scoreId: "0004" }, { scoreId: "0005" }]
```
result with page_size = 2:
```
page_1: [{ scoreId: "0001" }, { scoreId: "0002" }]
page_2: [{ scoreId: "0003" }, { scoreId: "0004" }]
page_3: [{ scoreId: "0005" }]
--> concatenated:   [{ scoreId: "0001" }, { scoreId: "0002" }, { scoreId: "0003" }, { scoreId: "0004" }, { scoreId: "0005" }]
```

### Expected behavior

Different pagination page sizes should not affect the final data obtained. Concatinating pages client side should always lead to the same final data.
The error seems to be in the behaviour, that the scope of distinct currently is a page, but rather should be the whole (filtered) table, regardless of which page is being fetched.

Each of the example queries should lead to a concatenated result of:
```[{ scoreId: "0001" }, { scoreId: "0002" }, { scoreId: "0004" }]```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.13.0

### Prisma Version

```
3.1.1
```

**Comment by SevInf** [comment]
I think current behavior is not a bug, but intended behaviour, which needs to be documented.
Each page request is stateless and independent and does not know anything about what happened during previous fetches. Moreover, previous fetch might not even exist: in your example, fetch with `cursorId: '002'` could easily be the first page fethced, not preceded by anything. 

I understand that current behaviour might be confusing, but there is hardly a way to achieve what you ask for in any sort of performant way. Any sort of stateful pagination would involve acquiring DB connection for the whole duration of the pagination, which would be unacceptable for most of the applications.

**Comment by BoscoDomingo** [comment]
I can confirm this has also happened to me. It leads to weird behaviours since different `take`s lead to different results from the same query.

It would be nice if you gave us an option to treat queries with a `distinct` and `cursor` differently, since `distinct` should apply to the entire table, not just the subset you're operating in. If Prisma does find a violation of the distinct within the `take` limit, it searches for more records until it can return exactly the `limit` or it reaches the end of the table, so maybe there's a possibility to look into that?

My example:
Query:
```typescript
return await prisma.someTable.findMany({
      distinct: ['username', 'productId'],
      where: {
        username: criteria.username,
        productId: criteria.productId,
      },
      orderBy: {
        id: 'desc',
      },
      cursor: pagination.cursor
        ? {
            id: pagination.cursor,
          }
        : undefined,
      skip: pagination.cursor && !pagination.includeCursor ? 1 : 0,
      take: take,
    })
```

Data:
```
id: 1 username: a productId: XYZ (...plus some other data)
id: 2 username: b productId: XYZ (...)
id: 3 username: c productId: XYZ (...)
id: 4 username: b productId: XYZ (...)
...
```
If I pick a `take=3` then the first result returns the first 3 items, but on the second query, with `cursor=3` and `take=3` the item with `id=4` is returned, when it shouldn't be

This is extremely counterintuitive, and should 100% be mentioned in the docs.

**Comment by miguelff** [comment]
Hi @Iskuper, @BoscoDomingo

For your expected behaviour to exist, the generated queries for the different pages would require consistent ordering on the cursor. This is not the case for your queries because the cursor is unique, and the query is selecting distinct on fields that are not unique -- obviously, I know, because otherwise, why `distinct`, right? --.

Anyways, this is to say that in your scenarios, there are many potential cursors for each distinctly selected item, and that is the root cause of the behaviour you are seeing. 

In this [fiddle](https://www.db-fiddle.com/f/8793BAvHWXWQukhARnK6ti/5), there is an example how to implement the behavior you expected in SQL.

The database state would be:

```sql
CREATE TABLE test (
  id SERIAL PRIMARY KEY,
  fruit TEXT
);

INSERT INTO test (fruit) VALUES ('Apple'),('Orange'),('Pear'),('Banana'),('Apple'),('Orange'),('Pear'),('Banana'),('Tangerine');
```

And a query for a second page of results would be:

```
SELECT id, fruit FROM (
  SELECT min(id) as id, fruit FROM test GROUP BY fruit ORDER BY id ASC
) as tmp 
WHERE id > 2 LIMIT 2
```

However there's a problem with this approach. Fetching each page would require for the inner select to traverse the whole table in order to do the grouping and ordering (or to intersect the cursor and distinct field indexes if the db is smart enough and the table has an index on the distinct fields). This would unfortunately lead to both very poor UX, and to risk availability of the database server if the cardinality of the distinct fields is very high, and that is the main reason why we haven't found a proper way to implement this in prisma (even optionally)

Unless there is a better, scalable way of generating a consistent cursor for each distinct field (we would be very pleased to receive proposals!) I don’t think we are going to implement this as part of prisma API, given the tradeoffs. Sorry.

However, we reckon that you hit a case in which the behaviour might be unexpected (despite correct in terms of specification) and we will discuss internally whether this should be documented further.

**Comment by BoscoDomingo** [comment]
Thank you for the follow-up. This is no longer a concern for me (I don't even work at the company I had this issue in), but is definitely not the intuitive behaviour.

One would expect the `distinct` keyword to be applied to the entire table (just as with raw SQL) and this could likely be cached by Prisma somehow to avoid running such an intensive query more than once. I would expect an index for this in any case.

Again, I'm no longer a user of Prisma, for reference and I believe we solved this issue by either running raw SQL or performing a different query altogether. I can't recall.

Hope you can look into this further!
